### ISSUE TITLE
rename the project 

### ISSUE THREAD

**Issue by jmtd** [chocolate-doom/chocolate-doom#1014]
There are several good reasons why we should rename the project:

 • chocolate is almost always produced with milk products. It’s not clear that people with lactose or milk protein allergies are welcome to use our project
 • “Chocolate” implies we are in the pocket of Big Sugar
 • have you ever tried to talk about chocolate doom in the real world? Immediate stumbling block as you have to explain why “chocolate”, followed by strange looks afterwards
 • there’s some ambiguity as to whether all our contributions are fair trade

Since the twitter account is @cocoademon, I propose “Cocoa Doom” which avoids most of the pitfalls identified above. 

I’ve laid the groundwork to make a rename easy already with the docs changes from a few months back.

**Comment by fabiangreffrath** [comment]
"Cocoa" is also too ambiguous. I am all for "Vegan gluten-free decaffeinated fat-reduced soy-milk Chocolate Doom". Maybe add "from Hell" as a friendly belittlement.

**Comment by fragglet** [comment]
For me there's a personal aspect to this question too. Many of you probably don't know, but I have a sweet tooth, which may have been part of the reason why the name "Chocolate Doom" seemed so attractive when I started the project back in 2005. But I'm older now and in recent years though I've been making a conscious effort to cut back on consuming sugary foods. But with this project named the way it is, it's a continual temptation and reminder of the chocolate I'm trying not to eat. I know that you folks are trying to do good opening all these bugs and sending pull requests, but the fact is that every one of them takes a small toll on my health. The irony is that if we don't do something soon it may well spell my own chocolate doom.

**Comment by JNechaevsky** [comment]
No, no, and again no. Despite of project's conservative aim, we must follow modern trends which are dictating:

- Names must be short, so I'm suggesting to short name to "Chocolate".
- However, to avoid some possible copyright infringement, we can play on word and rename it to "Chocolatte".

Now about logo re-branding. Again, following modern trends, logo must be simplified, and of course, some legal info must be presented. Thus, I belive, it must be something like this:

![](http://priscree.ru/img/b458ba16be16a2.png)

P.S. Maybe we also should include some epilepsy warnings?

**Comment by linguica** [comment]
Maybe we should leverage the existing name so people can figure out the heritage instead of having to remember a different name. "Chocolate" is problematic for the reasons stated above, and "Doom" really isn't great since it's a trademarked name and the project will forever have a legal sword of damocles above it. I suggest shortening the name to "Choom". The developers could perhaps be known as the "Choom Gang."

**Comment by AXDOOMER** [comment]
![screenshot at 2018-04-01 23-02-43](https://user-images.githubusercontent.com/6194072/38181466-fc0e39f0-3600-11e8-9f8d-4baee2ceb605.png)
It's not fake news. Believe me!

**Comment by fragglet** [comment]
Okay folks, some great ideas in this thread. I'll give this some thought and let you know what I decide.
