### ISSUE TITLE
Digital music not working

### ISSUE THREAD

**Issue by blacksparrow123** [chocolate-doom/chocolate-doom#1017]
### Background

Version of Chocolate Doom: 3.0.0

Operating System and version: Manjaro 64bit

Game: Doom

### Bug description
The digital music is not working.
Error loading midi: Unrecognized audio format.

I'm using flac pack from there.
http://sc55.duke4.net/games.php#doom

Same happens with hexen.
But i'm using pack from this your wiki page.
https://www.chocolate-doom.org/wiki/index.php/Digital_music_packs

What am i doing wrong?

**Comment by fragglet** [comment]
Manjaro is a variant of Arch? Looks like the Arch SDL_mixer package doesn't have FLAC support compiled in (FLAC isn't listed as a dependency [here](https://www.archlinux.org/packages/extra/x86_64/sdl_mixer/)). 

Side note, please make sure you use either the Ogg or FLAC version; MP3 is not supported.

**Comment by chungy** [comment]
The correct package for Choco v3 is https://www.archlinux.org/packages/extra/x86_64/sdl2_mixer/

I run Arch though (and maintain the Choco AUR package), don't have an issue with FLAC myself. Interesting.

**Comment by fragglet** [comment]
Sorry - I was looking at the wrong SDL_mixer package (should have been SDL2_mixer). Looks like it should work then, but I don't know if Manjaro does something different with its package.

But I discovered the error message from the OP is actually the message you get when failing to load a .mid file:

https://github.com/chocolate-doom/chocolate-doom/blob/master/src/i_sdlmusic.c#L1258

So this may not be an error message related to the music packs functionality at all.

**Comment by blacksparrow123** [comment]
Well. That probably my issue.

MIXER:Got different values from SDL: freq 44100, blocksize 512
ALSA:Can't subscribe to MIDI port (65:0) nor (17:0)
MIDI:Opened device:none

That i got, when tried to run doom from gog via wine.
Thanks anyway. :)

**Comment by fragglet** [comment]
My gues is you probably don't have any Timidity patches installed.

I suggest you install [EAWPATS](https://www.doomworld.com/idgames/sounds/eawpats) and configure "Timidity configuration file" to point at the `timidity.cfg` file from that .zip.
