### ISSUE TITLE
Doom 2: I saved the game, now I'm stuck into a wall

### ISSUE THREAD

**Issue by adolfintel** [chocolate-doom/chocolate-doom#1025]
### Background

Version of Chocolate Doom: 3.0.0

Operating System and version: Windows 10 1709

Game: Doom 2

Any loaded WADs and mods (please include full command line): chocolate-doom.exe -iwad DOOM2.WAD -savedir DOOM2-savedir

WAD file hash:
![image](https://user-images.githubusercontent.com/16307689/39010767-dd85e90c-440f-11e8-8c4c-72dff7a8e6d2.png)

### Bug description
I quicksaved on a platform before entering a teleporter, and when I reloaded the game I was stuck into a wall. 
The level is MAP03 of Doom 2, but I suspect it may happen in other maps as well, including Doom 1.  
I've attached the saved game.
[doomsav0.zip](https://github.com/chocolate-doom/chocolate-doom/files/1929318/doomsav0.zip)

Observed behavior:
* Quicksave the game in a certain location
* Die
* Reload
* Sometimes I'm slightly off the location where I saved. Usually it's not even noticeable but in this case it got me stuck into a wall. 

Expected behavior:
To be in the same location as where I saved.

### Disclaimer
I know chocolate doom aims for the vanilla experience. If this bug was present in vanilla, it's fine.

**Comment by JNechaevsky** [comment]
Sadly yes, it's a vanilla bug (or better say - _behavior_), caused by this code, invoked after game loading: https://github.com/chocolate-doom/chocolate-doom/blob/master/src/doom/p_saveg.c#L1657

**Comment by adolfintel** [comment]
Thanks for the quick reply 👍 
I'll close the issue then, who am I to question vanilla doom? 😂

**Comment by fabiangreffrath** [comment]
It's even possible to "salvage" the savegame if you restore it in a Choco build with these two lines commented out (or in Crispy Doom).

**Comment by fabiangreffrath** [comment]
Please see here:
https://github.com/fabiangreffrath/crispy-doom/commit/1fd1cc765164e4f00ff1e671e698052f85ed1845

**Comment by adolfintel** [comment]
Great explaination, thanks for the insight
