### ISSUE TITLE
Heretic - Coop spy in demos dont know player 2's status.

### ISSUE THREAD

**Issue by Proluiz** [chocolate-doom/chocolate-doom#1028]
Game: Heretic

When you coop spy any player but player 1 in multiplayer demoplayback the game dont update to his information and status bar keep showing player 1 data (Hp/ammo/item/armor) so it's impossible to see players 2 3 and 4 current status.

**Comment by fragglet** [comment]
Thanks for the report. I believe this is vanilla Heretic behavior, so it won't be fixed in Chocolate Heretic.
