### ISSUE TITLE
Heretic - Sound souce in demoplayback is aways player 1.

### ISSUE THREAD

**Issue by Proluiz** [chocolate-doom/chocolate-doom#1029]
Game: Heretic

Using coopspy to see any other player in multiplayer demos, the sound source dont follow the spyed player and you can still hear player 1 sound source making other player coopspy whitout sounds.

Edit: Doom coopspy has the same behavior but unlike heretic, doom can record demo in player 2 view point so playbacking him alone is a work perfectly, but heretic aways record demo has player 1 no matter who's recording, so there's no way to playback them correct.

**Comment by fragglet** [comment]
As with #1028, I believe this is vanilla Heretic behavior, so it won't be fixed in Chocolate Heretic.

You can also make an argument that this is desirable behavior, otherwise a monster can sneak up on you and kill you while you're spying without you realising it.
