### ISSUE TITLE
Heretic - Possible post-1.2 demo recording option for recording demos?

### ISSUE THREAD

**Issue by Proluiz** [chocolate-doom/chocolate-doom#1030]
Game: Heretic

Having lack of heretic ports that can run heretic demos I have to suggest it here, it's possible to add a option that force engine to record demos exactly as doom1.3 does? (ex: -doomdemo or -demospecial) I know that's something that goes off choco heretic target but I can get very in hand for speedrunning playback in multiplayer, to later record it to yourtube or something else, also make the engine crash when trying to playback it whitout the command (ex: This demo was recorded in other version. Try using -Doomdemo).

Note: If this is not possible can you guys move this suggestion to crispy heretic?
Extra info in doom demo handling in: https://doomwiki.org/wiki/Demo
Possible regressions: Demos recorded with this command make it not work in original heretic. Because it I suggested recording via command line.
Similar to: #1029 #1028 #1027

**Comment by fragglet** [comment]
Thanks for the suggestion, but this sounds out of scope for the project, since vanilla Heretic doesn't support any such format. I suggest filing a Crispy Heretic feature request.
