### ISSUE TITLE
New warning with GCC 8.1

### ISSUE THREAD

**Issue by turol** [chocolate-doom/chocolate-doom#1031]
### Background

Version of Chocolate Doom: git master

Operating System and version: Linux with GCC 8.1

New and shiny compiler, new and shiny warning:
```
src/w_merge.c: In function ‘FindSpriteFrame’:
src/w_merge.c:219:5: error: ‘strncpy’ specified bound 4 equals destination size [-Werror=stringop-truncation]
     strncpy(result->sprname, name, 4);
```
https://github.com/chocolate-doom/chocolate-doom/blob/00311e89f5bc707c333c38b5f1850d2f2a35e076/src/w_merge.c#L219

There are several ways to fix this:
1. Detect the new compiler and disable the warning. Not recommended because this warning might catch some real bugs in the future.
2. Ask the GCC folks if there's some way to tweak the code to make the compiler shut up. Not recommended because it's fragile and might break again in the future.
3. Bump the size of `sprname` to 5. This fixes the warning and based on quick testing doesn't break anything.

Which do we want?

**Comment by fabiangreffrath** [comment]
> Bump the size of sprname to 5.

This seems to be the only reasonable solution.

**Comment by fabiangreffrath** [comment]
Also, we could use `memcpy()` instead of `strncpy()`.

**Comment by AXDOOMER** [comment]
`memcpy` is the function to use if you want to copy the string and don't care about the NULL terminator.

**Comment by chungy** [comment]
We can also replace it with `M_StringCopy`.

**Comment by turol** [comment]
Replacing `strncpy` with `M_StringCopy` is not correct in this case. It always makes sure there's a NUL terminator but here all 4 characters are important. Copying 4-character string with `M_StringCopy` would lose the last one.

**Comment by AXDOOMER** [comment]
If we look at the code, the only time this string will be accessed again is here: https://github.com/chocolate-doom/chocolate-doom/blob/98b86be284c0d4a1a18f8b3aa9f652b779e441ea/src/w_merge.c#L193

Let's say we would use `memcpy`, then if `name` is smaller than 4, the rest of the string will not be padded with `\0`, but `strncpy` pads the remaining space with `\0`. Then we can't use that. 

The third parameter of `strncasecmp` is `4`, so if the size of the string happens to be smaller than 4 and doesn't have a `\0` at the end, the code will not behave correctly. 

The code assumes that a sprite lump always starts with 4 characters, this is how sprites are named in Doom. There is no bug, the code does exactly what we want. 

> Bump the size of sprname to 5.

For the sake of shutting up the compiler warning, this seems like the best solution. It would always make sure there is enough space for the `\0` and the code would still behave exactly the same.

**Comment by fabiangreffrath** [comment]
If we choose to use `memcpy()` then we don't need to increase the buffer size.

**Comment by AXDOOMER** [comment]
> If we choose to use memcpy() then we don't need to increase the buffer size.

I was trying to find a case were there could be a new bug because of a missing NULL terminator since `memcpy()` copies the string "as is" and doesn't add a NULL terminator if the source string is shorter than the length specified. After thinking about it again, it wouldn't add any bug that wouldn't happen elsewhere if someone loads a WAD file which has a sprite lump with a name shorter than 4 characters.
