### ISSUE TITLE
HACKING: missing rule for casts

### ISSUE THREAD

**Issue by fabiangreffrath** [chocolate-doom/chocolate-doom#1032]
The HACKING document is currently missing a rule for casts, e.g.

```
char a;
int b;

a = (char) b;
```

Do we want a space before the `(` or one after the `)` or none or both?

**Comment by JNechaevsky** [comment]
So, proper style will be like this?
```
long val = (long)(intptr_t) ptr;
```

This will be a fix for compiler warning on x64 build, please take a look: https://github.com/JNechaevsky/russian-doom/commit/7a202471d6a9cd350befab9193aca9db53680fff. But before make a PR, we want to be sure that everything is styled well for HACKING document.

**Comment by fabiangreffrath** [comment]
@fragglet Could you please comment on intermediate casts? Do we require a space between `)` and `(` or not?

**Comment by fragglet** [comment]
I would say not. @JNechaevsky's example looks good to me.
