### ISSUE TITLE
Savegame quietly refusing to load because of a gameversion mismatch

### ISSUE THREAD

**Issue by Zodomaniac** [chocolate-doom/chocolate-doom#1036]
This prevents Crispy Doom from throwing a warning with the name of the map-containing WAD if it's not loaded but needed to restore a savegame (see screenshot how it should normally happen) in case the loaded IWAD and the savegame IWAD are Doom 2 IWADs of different versions (e.g. 1.666 and 1.9): https://github.com/fabiangreffrath/crispy-doom/issues/314
![filename mismatch warning](https://user-images.githubusercontent.com/15119473/39928397-e8a73b4e-553d-11e8-8bdd-dbb78a41ebc5.png)

**Comment by fabiangreffrath** [comment]
Thanks @Zodomaniac ! I think I found a more elegant solution for Crispy in https://github.com/fabiangreffrath/crispy-doom/commit/290844cd8a2aac84b00c5ccfdcfe5756a27bc501 anyway. Choco is supposed to do whatever Vanilla did in this situation, which  - to be honest - I don't know.
