### ISSUE TITLE
Suspicious code in strife p_switch.c

### ISSUE THREAD

**Issue by turol** [chocolate-doom/chocolate-doom#1039]
https://github.com/chocolate-doom/chocolate-doom/blob/5c28b4cd722fa8ebad86005c32c4618020fdee41/src/strife/p_switch.c#L1017

This code uses both DEH_snprintf and DEH_String. It's redundant and violates the coding style and so is probably wrong.

**Comment by fragglet** [comment]
Yes, the `DEH_String()` call there is redundant.

**Comment by jmtd** [comment]
> Will someone else fix this or should I send a PR?

I'm sure a PR is welcome :+1:

**Comment by chungy** [comment]
Has anyone verified whether the DeHackEd code should even remain in Strife? I suspect it's just left over from when the files were copied from Doom and the game was reverse engineered...

Mind, that there is a real project to support patches of vanilla Strife: https://www.doomworld.com/sehacked/

I'm not aware of any mods in the wild that uses it, but maybe it'll be nice to verify it's compatible.

**Comment by chungy** [comment]
I've done some basic text string replacement tests via DOSBox

Chocolate Strife won't load any *.seh file as-is, but I can delete lines unrelated to what I want to test (eg, keeping only text replacement lines). It only loads a subset of changed lines (eg, "Name your character" and not "empty slot"). I think it's safe to say that the DeHackEd code in Choco Strife is just vestigial from Doom and not really compatible with SeHackEd.
