### ISSUE TITLE
Only 2 players are able to enter a co-op lobby

### ISSUE THREAD

**Issue by bradc6** [chocolate-doom/chocolate-doom#1046]
### Background

Version of Chocolate Doom: 3.0.0

Operating System and version: Mac OSX 10.13.5

Game: (Doom/Heretic/Hexen/Strife/other) Ultimate Doom

Any loaded WADs and mods (please include full command line):

### Bug description

Observed behavior: Attempting to connect more then 2 players into a co-op match causes the 3rd joining player to be stuck at "Waiting for game to start" with no one in the lobby.

Expected behavior:
It should allow more then two players to enter the lobby and start the game.

**Comment by fabiangreffrath** [comment]
Stupid question, but does the map have more than 2 multiplayer start points?

**Comment by JNechaevsky** [comment]
Just tested this case in one PC. On a first try something went wrong with fourth local client:
- Lobby: http://priscree.ru/img/447d5f659ec1b6.png

On second try everything becomes fine, though. All four player are get connected and game was started normally.

- Lobby: http://priscree.ru/img/848ef56e2f58d6.png
- In game: http://priscree.ru/img/1b6171dccd220b.png

Not sure is first try is related to this case somehow, but...

**Comment by fabiangreffrath** [comment]
> with 3 players on a map with only two multiplayer start points and got a segfault.

This probably shouldn't happen!

**Comment by mfrancis95** [comment]
What if that's vanilla behaviour? Would anyone be able to test that?

**Comment by bradc6** [comment]
I figured it out, you can play 4 player co-op. The problem is that everyone needs to connect into the lobby within a few seconds otherwise any one who did not join immediately will timeout and fail. This is probably true with any # of players.

**Comment by bradc6** [comment]
Sorry, forgot to mention that I'm playing the Ultimate Doom (vanilla - no custom maps/mods)
