### ISSUE TITLE
Music pack configuration is convoluted, needs improvement

### ISSUE THREAD

**Issue by fragglet** [chocolate-doom/chocolate-doom#1051]
I think the current setup for installing [music packs](https://www.chocolate-doom.org/wiki/index.php/Digital_music_packs) is too convoluted and needs to be improved. These are my current thoughts:

* The content-based replacement system (based on SHA hashes) is the right approach, but forcing the user to download a .cfg file from Github is clearly an unnecessary step. The config files [cause confusion among users](https://www.doomworld.com/forum/topic/86366-chocolate-doom/?do=findComment&comment=1880659).

* Configuration requires setting a path inside the setup tool, which is complicated, especially on Windows where the textscreen native file selector is broken.

* The original idea was to get authors of music packs to include a config file but we can't do that for every possible music pack, especially if people just rip soundtracks off CDs (Hexen install CD for example)

* The current system only checks for certain hard-coded filenames (some discussion in #993).

My idea is that the current system should change as follows:

* We auto-configure and create a standard directory for music packs (overridable from config file if desired). We search for and load any .cfg files found in this directory.

* Setup tool should have a button to open this directory in the file manager, so the user can dump files in there.

* Contents of the [music packs](https://github.com/chocolate-doom/music-packs) repository get "bundled"; if you put a file in the music directory named "d_e1m1.flac" then it auto-configures for the appropriate SHA1 hash.

**Comment by jmtd** [comment]
It would be nice to handle the user optionally using a MP3 or ogg pack rather than only the flac one.

**Comment by chungy** [comment]
Ogg Vorbis is already supported.

MP3's patents expired nearly a year ago, it's probably harmless but I'm not sure about the value.

**Comment by jmtd** [comment]
You misunderstand; I don’t mean Ogg support in chocolate. As they stand the configuration files in the external repo only define mapping’s to .flac files.

**Comment by fragglet** [comment]
Majority of this is now implemented. The main thing that isn't implemented yet is autoloading all config files named `*.cfg`. Also need to add auto-configuration of the substitute music directory.

**Comment by fragglet** [comment]
Auto-configuration of substitute music directory is now done, and the setup tool is updated accordingly.

Remaining things now:

* Autoloading all `*.cfg` config files (#993).
* Configuration is hard to discover in the setup tool. Music packs only work when using Native MIDI mode for music (#528), and the option is invisible until you set it to that mode. I think it's time to fix this.

**Comment by fragglet** [comment]
All done!
