### ISSUE TITLE
WAD file auto-loading

### ISSUE THREAD

**Issue by fragglet** [chocolate-doom/chocolate-doom#1052]
The [gameplay enhancements](https://www.chocolate-doom.org/wiki/index.php/Gameplay_enhancements) page lists a number of mods, some of which are nice to just load every time you start the game. There's also [gusgonna.wad](https://www.doomworld.com/idgames/sounds/gusgonna) and I'm also working on my own vanilla-compatible smooth weapons patch. Currently you have to specify all of these on the command line every time you run the game.

Other ports like PrBoom+ already have features to auto-load WAD files on startup every time. It would be nice to have something similar.

**Comment by fragglet** [comment]
My idea for how to do this is to have an "autoload" directory we automatically configure and create (similar to the music pack one described in #1051). Any .wad files put in this directory get autoloaded like they would with `-merge`, along with any .deh patches. There should be a `-noautoload` command line argument that will disable the functionality.

Some mods (like the minor sprite fixing project) have specific WAD files which need to be loaded for specific IWADs. So there should be different autoload directories for different games, like what we already do for savegames.

**Comment by fabiangreffrath** [comment]
NB: I have this in Crispy:
https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/d_main.c#L1741

**Comment by fabiangreffrath** [comment]
It should be possible to set the order in which the files are loaded, preferably by anything different than their file names.

**Comment by Kroc** [comment]
An ini/cfg file for autoloading, that has sections for "[global]", "[doom.wad]", "[doom2.wad]" etc.? This would keep things to a single config file, and you wouldn't technically need folders for each IWAD, as ultimately, the WAD files you want to autoload may be mixed-and-matched across IWADs.

**Comment by JNechaevsky** [comment]
I agree, using this ZDoom-like approach could be familiar for everyone and more user-friendly.

**Comment by fragglet** [comment]
I'd really like to make this not require explicit configuration files if possible. Just copying files into a directory is a lot simpler; the simplest configuration is no configuration.

Fabian brings up ordering. Are there examples of WADs people would want to load in a particular order? All the ones I have can be loaded in any order.

Copying PWADs is annoying but maybe it's not a big concern. The largest autoload WAD is maybe 20MiB, modern hard drives are >2TiB. Outside Windows you can use symbolic links if it's a big concern. We could also have a 'global' subdirectory of WADs which get loaded in every game.

**Comment by Kroc** [comment]
Requiring physical-layout goes entirely against being able to script the setup. In PortaDOOM, for example, I don't want to have to duplicate files but more so the player will have the option to play with multiple choices of mod loadout (when we consider a cross-section of /idgames) and this can't be done if physical-layout automatically determines loadout rather than a having different configuration files that can be selected via command line.

**Comment by fragglet** [comment]
Note that I'm not proposing a more general system like "different play setups / configurations" - this is purely solving a single problem: "how do I make these WADs load every time I run the game?". 

If you want something more general that supports explicit ordering and multiple configurations then arguably that already exists in the form of response files. Writing one is the same amount of work as writing a .ini file (it's just a text file).

**Comment by jmtd** [comment]
Is portadoom a launcher? Most launchers would probably want to pass -noautoload and build a command line for loading themselves

**Comment by Kroc** [comment]
Yes, PortaDOOM scripts everything; this is the 2'100 line batch file that does the bulk of the work: https://github.com/Kroc/PortaDOOM/blob/master/PortaDOOM/files/doom.bat -- getting dozens of DOOM engines to work as one is very difficult!

**Comment by fabiangreffrath** [comment]
@fragglet Can this get closed now?

**Comment by fragglet** [comment]
Yes! I thought I already closed it..
