### ISSUE TITLE
I can't join the server

### ISSUE THREAD

**Issue by YuGiOhJCJ** [chocolate-doom/chocolate-doom#1060]
### Background

Version of Chocolate Doom: 3.0.0

Operating System and version: Slackware64 14.2

Game: Doom II

Any loaded WADs and mods (please include full command line): none

### Bug description

Observed behavior: I can't join the server.

Expected behavior: I can join the server.

Hello, I have recently upgraded from 2.3.0 to 3.0.0.
Now, on 3.0.0 I am unable to join the server.

Here is what happens on 2.3.0:
- I start the server:
```
$ chocolate-server 
Chocolate Doom standalone dedicated server
zone memory: Using native C allocator.
Registered with master server at master.chocolate-doom.org:2342
```
- I start the client setup:
```
$ chocolate-doom-setup
```
- I configure the client: Join a network game > Find server on local network... > Enter > F10
- I see "Waiting for game start..." and the list of players
- When I press the Space bar, the game starts

Here is what happens on 3.0.0:
- I start the server:
```
$ chocolate-server 
Chocolate Doom standalone dedicated server
zone memory: Using native C allocator.
Registered with master server at master.chocolate-doom.org:2342
```
- I start the client setup:
```
$ chocolate-doom-setup
```
- I configure the client: Join a network game > Find server on local network... > Enter > F10
- I see "Waiting for game start..." but I do not see the player list (I see "Please wait...")
- After about 1 minute, the client crashes and I get:
```
D_InitNetGame: Connected to 192.168.0.2
Disconnected from server.
Lost connection to server
```
- On the server side, I see:
```
Client 'YuGiOhJCJ' timed out and disconnected
```

As you can see the behavior is not the same on 3.0.0 than on 2.3.0.
Why I can't join the server please?

Thank you.
Best regards.

**Comment by fragglet** [comment]
Thanks for the report. This is a known bug in v3.0 (#1046) and has already been fixed. The next release will include the fix.

You may be able to avoid the bug by not using the separate `chocolate-server` binary. There's no need to use it - just run `chocolate-doom -server` (or use "start a network game" from inside the setup tool).

**Comment by YuGiOhJCJ** [comment]
Running `chocolate-doom -server` is not a solution for me. Indeed, I run the server program on a machine in a startup script, in a text-only terminal, without a graphical user interface and with a user that does not have a home directory. It means that I need to run the chocolate doom server as a dedicated server. I tried `chocolate-doom -dedicated` but I get the same problem than with `chocolate-server`. I think that I will downgrade to 2.3.0 while I am waiting for the next release. However, I will try the current version to check that it works like I expect.

**Comment by fabiangreffrath** [comment]
> This is a known bug in v3.0 (#1046) and has already been fixed

Maybe it's time for a 3.0.1 release now. There was also the Hexen ACS script issue which has been fixed.

**Comment by fragglet** [comment]
> Running chocolate-doom -server is not a solution for me. Indeed, I run the server program on a machine in a startup script, in a text-only terminal, without a graphical user interface and with a user that does not have a home directory

Presumably the clients that are playing the game are not headless though. Why can't one of those  act as the server, and why do you think you need to run a server on another machine?

Just curious; I'd like to understand your use case better.

**Comment by chungy** [comment]
> Maybe it's time for a 3.0.1 release now.

I think I would rather see a full 3.1.0, there have been quite enough changes. Though that's @fragglet's prerogative :)

**Comment by ChilePepp3r** [comment]
I am experiencing the same issue on some Raspberry Pis  with version 3.0.1 of Chocolate DOOM
