### ISSUE TITLE
Can't see any enemy

### ISSUE THREAD

**Issue by faffa42** [chocolate-doom/chocolate-doom#1064]
### Background

Version of Chocolate Doom: 0.11.3-1

Operating System and version: Ubuntu 18.04

Game: (Doom/Heretic/Hexen/Strife/other) Doom

Any loaded WADs and mods (please include full command line):

### Bug description

Observed behavior: Empty levels and no enemies at all

Expected behavior: A hell full  of enemies?

**Comment by fabiangreffrath** [comment]
Judging from the version number, I guess you were running FreeDoom. And judging from the lack of enemies, I guess you were running the FreeDM deathmatch variant.

**Comment by faffa42** [comment]
The actual version is 3.0.0-4 - sorry I read just the splashscreen in which is indicated the wrong version number. I installed it from repo on Ubuntu 18.04 from terminal, following the guide. Do you have any idea?

**Comment by fabiangreffrath** [comment]
Probably install the doom-wad-shareware package to get some "real" Doom taste.

**Comment by fabiangreffrath** [comment]
Apart from this, the freedoom Debian package should install a desktop entry for each campagn, also the single player ones.

**Comment by fragglet** [comment]
Try `zless /usr/share/doc/chocolate-doom/INSTALL.doom.gz` for some more detailed install instructions on how to find an IWAD.
