### ISSUE TITLE
Embedded netgame demos prevent loading games in singleplayer

### ISSUE THREAD

**Issue by carburet0r** [chocolate-doom/chocolate-doom#1068]
- Chocolate Doom 3.0.0, Windows 10
- Doom 2 with Alien Vendetta (-iwad doom2.wad -file av.wad)

Attempting to load a game during Alien Vendetta's first demo results in the message: "You can't do load while in a netgame! Press a key."

**Comment by fabiangreffrath** [comment]
Does the same happen with DOOM.EXE?

**Comment by linguica** [comment]
Yes, you can start a new game during AV DEMO1 in vanilla.

**Comment by fragglet** [comment]
Closing as vanilla behavior. Thanks for the report.
