### ISSUE TITLE
Quickload message truncated on saved game names over 20 characters long

### ISSUE THREAD

**Issue by carburet0r** [chocolate-doom/chocolate-doom#1069]
- Chocolate Doom 3.0.0 (20 characters)
- Crispy Doom 5.2 (16 characters)

The query "Do you want to quickload the game named '_x_'? Press Y or N." has characters cut off at the end if a saved game name is over 20 characters long in Chocolate Doom, or 16 characters long in Crispy Doom.

**Comment by fabiangreffrath** [comment]
Just checked and Vanilla shows all 23 characters:
![bildschirmfoto vom 2018-07-09 16-27-51](https://user-images.githubusercontent.com/6449237/42456421-2a73673e-8395-11e8-9095-4ad9ac7186b9.png)

**Comment by fabiangreffrath** [comment]
Sorry, QLPROMPT string is 47 chars long.

**Comment by chungy** [comment]
The message actually in [`d_english.h`](https://github.com/chocolate-doom/chocolate-doom/blob/54a2c31efc2242d130aecae0b79922e4a92d4a08/src/doom/d_englsh.h#L44) is 46 characters, plus the implicit \0 terminator. `80-47-13 = 20`

**Comment by fabiangreffrath** [comment]
There are also 4 newline chars in the string which take up one byte each.

**Comment by Zodomaniac** [comment]
@fabiangreffrath aha, I see, 43 visible characters+4 newlines=47.

**Comment by fragglet** [comment]
Fixed, thanks!
