### ISSUE TITLE
Revenant idle sound plays at max volume regardless of sound fx settings

### ISSUE THREAD

**Issue by ReakutheCrate** [chocolate-doom/chocolate-doom#1080]
### Background

Version of Chocolate Doom: 3.0.0

Operating System and version: Windows 7

Game: Plutonia Experiment, map08

### Bug description

I've been keeping game volumes down lately when playing almost anything, mostly to listen to other things in the mean time, however, in map08 of Plutonia, I can hear the Revenants rummaging around in the background in full force, even when all sound is set to 0 (not disabled), making them louder, and unbearable to listen too.
Distance from the groups hardly make a difference in the intensity either.

**Comment by fabiangreffrath** [comment]
This is a well-known bug in Vanilla Doom:
https://doomwiki.org/wiki/Sound_effects_behave_differently_on_level_8
