### ISSUE TITLE
autogen error

### ISSUE THREAD

**Issue by kenken64** [chocolate-doom/chocolate-doom#1082]
### Background

Version of Chocolate Doom:
checkout sdl2 branch
Operating System and version:
Windows 10
Game: (Doom/Heretic/Hexen/Strife/other)
Doom
Any loaded WADs and mods (please include full command line):
Nope
### Bug description
checking for sdl2 >= 2.0.1... no
configure: error: Package requirements (sdl2 >= 2.0.1) were not met:

No package 'sdl2' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables SDL_CFLAGS
and SDL_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

Observed behavior:
checking for sdl2 >= 2.0.1... no
configure: error: Package requirements (sdl2 >= 2.0.1) were not met:

No package 'sdl2' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables SDL_CFLAGS
and SDL_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

Expected behavior:
Success build

**Comment by fabiangreffrath** [comment]
So, do you have pkg-config installed? What does `pkg-config sdl2 --libs` print?

**Comment by chungy** [comment]
Can you review the wiki page [Building Chocolate Doom on Windows](https://www.chocolate-doom.org/wiki/index.php/Building_Chocolate_Doom_on_Windows) and be sure that all the steps are followed?

**Comment by fragglet** [comment]
Please install the sdl2 (and sdl2_mixer and sdl2_net) libraries before attempting to build. Chocolate Doom cannot be built without them. You'll probably find the instructions @chungy has linked useful.
