### ISSUE TITLE
SetConfigDir segfault

### ISSUE THREAD

**Issue by Pickle** [chocolate-doom/chocolate-doom#1083]
### Background

Version of Chocolate Doom:
sdl2-branch

Operating System and version:
Linux arm

Game: (Doom/Heretic/Hexen/Strife/other)
Doom

Any loaded WADs and mods (please include full command line):
Doom2.wad
### Bug description

Observed behavior:
SetConfigDir has the potential to receive a null string from GetDefaultConfigDir (line 2198)

Then when the null string is used in strcmp the segfault occurs.

Expected behavior:

Set the string to a default string if null is returned.

```
void M_SetConfigDir(const char *dir)
{
    // Use the directory that was passed, or find the default.

    if (dir != NULL)
    {
        configdir = dir;
    }
    else
    {
        configdir = GetDefaultConfigDir();
    }

    **// new code
    if (configdir == NULL)
    {
        configdir = "./";
    }
    // new code end** 

    if (strcmp(configdir, "") != 0)
    {
        printf("Using %s for configuration and saves\n", configdir);
    }
```

Some error checking might be helpful in GetDefaultConfigDir too.

**Comment by fabiangreffrath** [comment]
I'd rather not let `GetDefaultConfigDir()` return `NULL` if this is what it gets from `SDL_GetPrefPath()`. There is already a second code path that doesn't use that function.
