### ISSUE TITLE
Chocolate-doom on Ubuntu 18.04.1 LTS in WSL

### ISSUE THREAD

**Issue by CarbonPaste** [chocolate-doom/chocolate-doom#1088]
### Background

Version of Chocolate Doom: 
chocolate-doom (2.3.0-3)

Operating System and version: 
Ubuntu 18.04.1 LTS on Windows 10 x86_64

Game: (Doom/Heretic/Hexen/Strife/other) 
Doom

Any loaded WADs and mods (please include full command line): 
Doom.wad

### Bug description

Observed behavior: 
When running the program; "Segmentation fault (core dumped)".
When running the program in debug mode; 
Program received signal SIGSEGV, Segmentation fault.
0x0000000008028480 in ?? ()
(gdb) bt
#0  0x0000000008028480 in ?? ()
#1  0x000000000803887b in ?? ()
#2  0x000000000801a5db in main ()
(gdb)

Expected behavior: chocolate-doom launching

**Comment by chungy** [comment]
The version in the 18.04 repositories seems to be 3.0: https://packages.ubuntu.com/bionic/chocolate-doom Might want to run an apt update/upgrade...

Also you won't get a display if you don't have an X server running (Cygwin can provide one), and no audio if you don't run PulseAudio on Windows. This is a fairly odd use case, honestly.

**Comment by CarbonPaste** [comment]
I want to run the game in ASCII art.

**Comment by chungy** [comment]
Hmm, 2.3 may be the correct version to use, since aalib support is only in [SDL 1.2](https://wiki.libsdl.org/FAQUsingSDL).  Still, how did you install the package? It's pretty unusual for you to have 2.3 on Ubuntu 18.04.

**Comment by fragglet** [comment]
> I want to run the game in ASCII art.

Some friendly advice: this is an important detail that would have been really helpful to have included in the original report.

**Comment by AXDOOMER** [comment]
Doom in ASCII art is [unplayable](https://youtu.be/5zP7yS_2ojw?t=11s).

**Comment by chungy** [comment]
All this being said, we still need more details to figure out why it's segfaulting, but it honestly might be a bug that doesn't even exist in the current version. The issue tracker isn't necessarily the best place to do something as abstract and unusual as this.

**Comment by chungy** [comment]
It's been over a week since the report, shy on details and in a very unusual mode to run (Windows' Linux compatibility layer, rather than as a regular Windows binary). I'm going to close this, but it can be reopened if new details emerge.
