### ISSUE TITLE
Add Support for Strife: Veteran Edition?

### ISSUE THREAD

**Issue by MasterO2** [chocolate-doom/chocolate-doom#1095]
Can Strife: Veteran Edition support be added to Chocolate Doom?  Or would that be outside the scope of Chocolate Doom?  

(If you guys need their source code, you can find it at https://github.com/svkaiser/strife-ve) (Also, as far as I can tell, both Chocolate Doom and Strife-Veteran Edition are GPL 2.0, so there should not be any license issues).

**Comment by fragglet** [comment]
Indeed, Strife: VE is derived from Chocolate Strife and was developed by the same authors ([see the wiki](https://www.chocolate-doom.org/wiki/index.php/Strife:_Veteran_Edition)).

As far as adding support for it, I'm not sure what you're asking for. This project is only ever going to support the DOS versions, but there is IWAD autodetection already in place that will detect `strife1.wad` automatically if you have Strife: VE installed. If you're asking about incorporating some of the new features that were added for Strife: VE, most of them are going to be out of scope for the project.

**Comment by fragglet** [comment]
I'm going to go ahead and declare this out of scope - unless @haleyjd thinks there are things in sve.wad which are worth including. Should it be autoloaded?

**Comment by MasterO2** [comment]
> It's kind of hairy. I think SVE includes some modified scripts to prevent unwinnable game scenarios and maybe a few other map fixes. Even if we might be able to load some of SVE's changes, we'll never really be a replacement for SVE itself, and certainly should never be loaded by default.
> 
> Despite having played through both versions of the game multiple times, I'm really not sure what the major differences are, if any. Perhaps we can be enlightened either by Quasar or @MasterO2

The one major difference happens to be the addition of Capture the Chalice in Strife: Veteran Edition, which was not in the original Strife.  

Outside of that, per GOG's site, the others are:

Completion of missing and unfinished options in the original game, such as: the planned "Capture the Chalice” multi-player mode, marking of current objectives on the auto-map, and special HUD for the Torpedo weapon

Support for high resolutions, with proper aspect ratio

OpenGL for video backend to provide portability and support for vertical sync

Dynamic lighting and bloom

Widescreen support

Ability to freely rebind all keyboard, mouse, and gamepad inputs

Achievements

---

Most of the above you have probably already done, except for Capture the Chalice.  I leave it up to you what is outside the scope of Chocolate Doom, though.

**Comment by chungy** [comment]
This'll sound disappointing, but if that was the goal, to bring in all those engine features from Veteran Edition, it's a non-starter. Chocolate Strife is strictly conformant to the original vanilla engine released in 1996 and pretty much none of what you listed would be in line with that goal.

Being that Strife Veteran Editon's engine is open source, there isn't really any reason to use anything but that if you want the whole kit and caboodle.

**Comment by fragglet** [comment]
I'll echo what @chungy said - most of the features you've listed involve way more than just loading a WAD file and are out of scope for the project. Sorry to disappoint.
