### ISSUE TITLE
Heretic: HHE map renaming is not fully accurate

### ISSUE THREAD

**Issue by ETTiNGRiNDER** [chocolate-doom/chocolate-doom#1106]
### Background

Version of Chocolate Doom: v3.0.0

Operating System and version: Linux (Peppermint 9 64-bit)

Game: Heretic

Any loaded WADs and mods (please include full command line): ./chocolate-heretic -deh NAME.HHE -hhever 1.3

### Bug description

Observed behavior:

The patch changes the automap title but not the intermission map title.

Expected behavior:

When vanilla Heretic is patched with this HHE, both the automap and intermission titles are changed.

[NAME.HHE.zip](https://github.com/chocolate-doom/chocolate-doom/files/2590831/NAME.HHE.zip)

**Comment by ETTiNGRiNDER** [comment]
Essentially, vanilla has a single string for each map title.  The full string is used for the automap, while the intermission string discards the first seven characters.  That's the "ExMx:  " label by default but the EXE doesn't really care what's there, it just chops the first seven off regardless.

**Comment by fragglet** [comment]
Fixed, thank you!
