### ISSUE TITLE
README could do with some basic build information

### ISSUE THREAD

**Issue by zx64** [chocolate-doom/chocolate-doom#1111]
I noticed that https://www.chocolate-doom.org/wiki/index.php/Building_Chocolate_Doom_on_Windows etc. appears to be the canonical source of information on how to build, but hasn't yet been updated for CMake.
I think it'd be useful to have a few lines in the README (or a README.Windows etc.)

---

For more details, see https://www.chocolate-doom.org/wiki/index.php/Building_Chocolate_Doom_on_Windows

This project uses CMake to build and depends on SDL2, SDL2_mixer, SDL2_net as well as optional dependencies like libpng and libsamplerate.
For Windows/MSVC, you'll need to download and extract the SDL2 development packages:
* SDL2 (https://www.libsdl.org/release/SDL2-devel-2.0.9-VC.zip)
* SDL2_mixer (https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-2.0.4-VC.zip) 
* SDL2_net (https://www.libsdl.org/projects/SDL_net/release/SDL2_net-devel-2.0.1-VC.zip) 

You'll then need to set the following environment variables
* `SDL2_DIR` - Path to the unpacked development package for SDL
* `SDL2_MIXER_DIR` - Same but for SDL2_mixer
* `SDL2_NET_DIR` - Same but for SDL2_net

Alternatively, you can pass them on the command line, e.g. assuming you've extracted all three development packages into C:\SDL2:

```
git clone https://github.com/chocolate-doom/chocolate-doom/
cd chocolate-doom
mkdir build
cd build
cmake .. -G "Visual Studio 15 2017 Win64" -DSDL2_DIR=C:\SDL2\SDL2-2.0.9 -DSDL2_MIXER_DIR=C:\SDL2\SDL2_mixer-2.0.4 -DSDL2_NET_DIR=C:\SDL2\SDL2_net-2.0.1
```
You should now be able to open the generated `Chocolate Doom.sln`.

---

That's just off the top of my head - the key things for me were the env vars to find SDL. 

Simplify/elaborate as appropriate e.g. if you think it's worth having more info about CMake or where to get the optional dependencies (it's not something I've yet to bother with so don't have the details to hand).

Probably worth omitting the wiki link for now until that's up to date as that might confuse things.

One other thing related to SDL/CMake/MSVC that probably won't affect many people is that its default CMake project doesn't produce an install with the same directory layout as the devel packages, so I wasted a bunch of time trying to figure out why my local build of SDL wasn't being detected at the same time as getting my head around CMake's syntax etc.

**Comment by remyabel** [comment]
Sounds like you'd really benefit from [vcpkg](https://github.com/Microsoft/vcpkg). i.e, this isn't really a Chocolate Doom problem.

**Comment by zx64** [comment]
Quite possibly, but where is that mentioned?

**Comment by fragglet** [comment]
I think this is covered already in the INSTALL file that gets shipped with the source tarballs - it already gives instructions on how to use autotools to build. The cmake build can be documented via the wiki, along with any system-specific instructions.

**Comment by chungy** [comment]
> I noticed that https://www.chocolate-doom.org/wiki/index.php/Building_Chocolate_Doom_on_Windows etc. appears to be the canonical source of information on how to build, but hasn't yet been updated for CMake.

Mind that CMake is still not the official way to build Chocolate Doom and instructions for using it belong on the [alternative build](https://www.chocolate-doom.org/wiki/index.php/Building_Chocolate_Doom_on_Windows_%28alternative_build%29) page, which does note its out-of-date status as of present. It needs a Windows developer using MSVC and CMake to write the instructions to make it all work.
