### ISSUE TITLE
Strife: When the -iwad parameter is used, VOICES.WAD won't be found (only voices.wad)

### ISSUE THREAD

**Issue by mfrancis95** [chocolate-doom/chocolate-doom#1120]
### Background

Version of Chocolate Doom: 2b20ce64a869e112be68217f1d44ca2c870d0d0e

Operating System and version: Ubuntu 18.04

Game: Strife

### Bug description

Observed behavior: Run `chocolate-strife -iwad somepath/STRIFE1.WAD`, assuming VOICES.WAD is located in somepath. VOICES.WAD does not get loaded. However, it does if you rename it to voices.wad.

Expected behavior: Finding VOICES.WAD should be case insensitive, like how it is if you run `chocolate-strife` without the `-iwad` parameter.

**Comment by fabiangreffrath** [comment]
Looks like we should set
```
voiceswad = NULL;
```
in
https://github.com/chocolate-doom/chocolate-doom/blob/master/src/strife/d_main.c#L859

**Comment by fabiangreffrath** [comment]
He, no, sorry, I am still sleeping...

**Comment by fabiangreffrath** [comment]
I guess this makes more sense (cannot test myself, I am currently at work...)
```
--- a/src/strife/d_main.c
+++ b/src/strife/d_main.c
@@ -855,10 +855,8 @@ void D_IdentifyVersion(void)
             voiceswad = M_SafeFilePath(iwadpath, "voices.wad");
             Z_Free(iwadpath);

-            if(!M_FileExists(voiceswad))
-                Z_Free(voiceswad);
-            else
-                name = voiceswad; // STRIFE-FIXME: memory leak!!
+            name = M_FileCaseExists(voiceswad);
+            Z_Free(voiceswad);
         }

         // not found? try global search paths
@@ -877,6 +875,7 @@ void D_IdentifyVersion(void)
         {
             // add it.
             D_AddFile(name);
+            free(name);
         }
     }
 }
```
