### ISSUE TITLE
Make 'double click acts as Use' mouse setting disabled by default

### ISSUE THREAD

**Issue by Zodomaniac** [chocolate-doom/chocolate-doom#1131]
This setting may be confusing to players when enabled by default, e.g. in the mods like STRAIN where the pistol firing rate is faster than in original Doom: if the player fires by fast-click then one may fail to fire two shots in succession because of this 'double click acting as Use'. It's non-Vanilla either IIRC.
![choco_setup](https://user-images.githubusercontent.com/15119473/51676758-a1dd0100-1fe8-11e9-9f69-17d4535ee985.png)

**Comment by fabiangreffrath** [comment]
The critical point is if this is Vanilla behaviour or not.

**Comment by Zodomaniac** [comment]
I'd like to add that maybe saving screenshots in PNG should be enabled by default, as PCX format is obsolete.

**Comment by fabiangreffrath** [comment]
> I'd like to add that maybe saving screenshots in PNG should be enabled by default, as PCX format is obsolete.

At least if PNG support (still optional!) is compiled in. But that's a different topic, please open a separate issue for it.

**Comment by chungy** [comment]
Indeed, it only seems to work with the right mouse button.

**Comment by AXDOOMER** [comment]
Double-click to use works with the middle and right mouse button. This is vanilla behavior.

**Comment by sneakernets** [comment]
Makes sense, as some mice swapped 2 and 3, so that covers both types.

**Comment by Zodomaniac** [comment]
OK, I'm closing this) let it stay as is.
