### ISSUE TITLE
Const correctness and other problems in GetGameName

### ISSUE THREAD

**Issue by turol** [chocolate-doom/chocolate-doom#1138]
src/doom/d_main.c:849:43: error: passing argument 1 of ‘GetGameName’ discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]

```
             gamedescription = GetGameName("Freedoom: Phase 1");
```

`GetGameName` is here:

https://github.com/chocolate-doom/chocolate-doom/blob/493194672320732fd03e28f489672d76f4a9d58d/src/doom/d_main.c#L676

I can't just make `gamename` `const` since it's also used for building the dehacked description.

Since the function sometimes returns an allocated string and sometimes the original constant the caller can't free it if necessary. This causes a memory leak, although a bounded one.

What's the best way to fix these issues?

The string returned from `DEH_String` is used as a format string without verification. This can cause problems, even security issues. Do we care about malicious DEHs?

Also the return value of `GetGameName` is stored in `gamedescription` which is declared `extern` in `doomstat.h` and defined in `doomstat.c`. However it doesn't appear to be used outside `d_main.c`. Heretic and Hexen have it in their respective `*_main.c` and declared `static`. Can I move it and remove the `extern` definition?'

This code has been copy-pasted into Strife so it should be fixed there too.

**Comment by fragglet** [comment]
Change `GetGameName()` to always return an allocated string? ie. if it's a const string then strdup() it. Then it's always safe to free. If you want to move things around to make them static then go right ahead.

Re: dehacked replacements of format strings, yes we do care about this. Check out `DEH_printf` and variant functions.

**Comment by turol** [comment]
Ok, will do. However `strdup` (or `M_StringDuplicate`) is not correct here since the dehacked path uses `Z_Malloc`. There doesn't appear to be a `Z_StringDuplicate`. Should I write one or just use `Z_Malloc` here? Or just change this function to use `M_StringDuplicate`?

Can I fix whitespace issues and reduce scope of `deh_sub` variable while I'm at it?
