### ISSUE TITLE
player_name: A privacy concern

### ISSUE THREAD

**Issue by PorscheMonty** [chocolate-doom/chocolate-doom#1141]
CD automatically fills in this field with the computer's name (at least on WinXP and Win7) and uses it without the user's acknowledgment, which's about the last thing you want if you named your computer after yourself (or used something equally as personal) and are genuinely concern about such sensitive information being made available to third parties before joining a multiplayer game.

My recommendation would be to rather greet a first-time-user with a screen where he may change a generic, default pseudonym for something more to his liking.

Best regards and sorry for the inconveniences.

**Comment by jmtd** [comment]
Maybe we should use an approach similar to [petname](https://godoc.org/github.com/dustinkirkland/golang-petname) but with a doom flavour. E.g. "Cheeky cacodemon".

**Comment by AXDOOMER** [comment]
If Chocolate-Doom uses the computer name for `player_name` on Windows, then it should be changed so it uses the username of the user like it does on Linux.

**Comment by chungy** [comment]
@AXDOOMER highlights the underlying issue in this report: it should be based on user name and not computer name by default.

**Comment by AXDOOMER** [comment]
By default, Chocolate-Setup reads the `USER` and `USERNAME` environment variables when it tries to set the default player name. 

https://github.com/chocolate-doom/chocolate-doom/blob/4127fabfb33035fba382afdd1f608db099af0835/src/setup/multiplayer.c#L1095

There is code in Chocolate-Doom that does the same:

https://github.com/chocolate-doom/chocolate-doom/blob/25ae4973fab0cfffe47fbc8373dae8a8715786d7/src/net_client.c#L1209

**Comment by PorscheMonty** [comment]
> 
> 
> @AXDOOMER highlights the underlying issue in this report: it should be based on user name and not computer name by default.

Well, I'd rather say it should not be based on anything that reveals any personal information no matter what part of the OS it is gathered from.

**Comment by jmtd** [comment]
> Well, I'd rather say it should not be based on anything that reveals any personal information no matter what part of the OS it is gathered from.

Quite; I can see that USER/USERNAME could also contain thought-to-be-private information.
