### ISSUE TITLE
Doom Scythe crashes when I try to save in the final map

### ISSUE THREAD

**Issue by chiffon-rouge** [chocolate-doom/chocolate-doom#1146]
### Background

Version of Chocolate Doom: 3.0.0

Operating System and version: macOS 10.14.3

Game: Doom 2 (Scythe)

Any loaded WADs and mods (please include full command line):
-file "/Users/[username]/etc/WAD/SCYTHE.WAD"

### Bug description

Observed behavior:
Whenever I try to save in the final map of Scythe (Fire & Ice) the game crashes by closing the application. No save game is created in the process.

I guess this is the relevant part of Apple's crash notification by I could be wrong. I'm happy to provide more informations if needed.

```
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00000000000003c0
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [1120]
```

Expected behavior:
Saving the game by creating a save game.

**Comment by chiffon-rouge** [comment]
I'm sorry, I guess this was premature ... I changed "vanilla_savegame_limit" to "0" in the chocolate-doom.cfg file. Now everything works as intended. The problem was related to #2 I guess.

**Comment by AXDOOMER** [comment]
If Chocolate-Doom doesn't exit cleanly, then it should be made so it exists cleanly. It's a bug if it simply crashes, because users don't have a clear explanation of why it happened. 

Usually, if the game exists when the savegame was too big, Chocolate-Doom still creates a backup somewhere. The location of this backup file is OS specific I think.
