### ISSUE TITLE
On updating SDL_mixer to 2.0.4 chocolate-midiproc.exe doesn't do its job anymore on Windows

### ISSUE THREAD

**Issue by Zodomaniac** [chocolate-doom/chocolate-doom#1147]
### Background

Version of Chocolate Doom: Git build March 6, 2019

Operating System and version: Windows 7

Game: (Doom/Heretic/Hexen/Strife/other) Doom 2

Any loaded WADs and mods (please include full command line):

### Bug description

Observed behavior: The SFX volume is (SFX setting*Music volume/15) like before introducing chocolate-midiproc.exe. Clicking interruptions of sound occur every half a second if the music output is different from Native MIDI (e.g. OPL or MP3/OGG/FLAC in Crispy fork)

Expected behavior: SFX and music volumes should be independent.

**Comment by chungy** [comment]
When you say updating, did you manually download a DLL from somewhere, or did you compile with 2.0.7?

**Comment by fabiangreffrath** [comment]
Our daily builds have been upgraded to 2.0.7 recently.

**Comment by fragglet** [comment]
It was actually SDL_mixer that got updated to 2.0.4. @Altazimuth thinks that updating SDL to 2.0.9 might fix the problem

**Comment by AlexMax** [comment]
It's been a while, but it's my recollection that `midiproc` only concerns itself with playing MIDI files, and OPL2 and friends are still played by the parent process.

**Comment by fabiangreffrath** [comment]
> It was actually SDL_mixer that got updated to 2.0.4. 

And in the course of this SDL was updated to 2.0.7 or not?

> @Altazimuth thinks that updating SDL to 2.0.9 might fix the problem

Well, then...

**Comment by fragglet** [comment]
Build server is now building with v2.0.9 - @Zodomaniac can you give the latest build a try and see if it solves your problem?

**Comment by Zodomaniac** [comment]
@fragglet No, SFX volume still depends on MIDI volume.

**Comment by fragglet** [comment]
And the clicking sounds?

**Comment by Zodomaniac** [comment]
The clicking sounds are gone, luckily.

**Comment by fragglet** [comment]
Great. I think it's reasonable to conclude that the clicking and the SFX volume problems were separate bugs, albeit maybe both triggered by the update to SDL_mixer 2.0.4. At least we've fixed one.

**Comment by fragglet** [comment]
@AlexMax - it looks like if midiproc fails to start up, we fall back to the old, non-midiproc behavior. This would explain the bug - is there any way we can confirm this hypothesis? (log files, stderr, etc.)

**Comment by Zodomaniac** [comment]
@fragglet 
> it looks like if midiproc fails to start up, we fall back to the old, non-midiproc behavior

Yes, it's exactly what happens, I checked the task manager. With older SDL_mixer the midiproc runs but with newer one it fails to start.

**Comment by fragglet** [comment]
Apparently Alex may have found a potential crash that he's looking into.

**Comment by AlexMax** [comment]
The crash I was talking about was unrelated to midiproc.

However, I think I know what's going on.  When I compile the program with SDL 2.0.5 and SDL_Mixer 2.0.1, I get six enumerated music decoders, one of which is `NATIVEMIDI`.  However, with SDL 2.0.9 and SDL_Mixer 2.0.4, I get a single enumerated music decoder, which isn't `NATIVEMIDI`.  Because Chocolate Doom cannot enumerate native midi support, it decides not to spawn midiproc.

Yuck.  Not quite sure what to do here.

**Comment by chungy** [comment]
Is it an SDL limitation?

**Comment by fabiangreffrath** [comment]
Maybe this is because we don't even call `Mix_Init()` in the sound code?

**Comment by fabiangreffrath** [comment]
Please try this:
```
diff --git a/src/i_sound.c b/src/i_sound.c
index 468b2da7..bdb414a8 100644
--- a/src/i_sound.c
+++ b/src/i_sound.c
@@ -253,6 +253,7 @@ void I_InitSound(boolean use_sfx_prefix)

         if (!nomusic)
         {
+            Mix_Init(MIX_INIT_FLAC | MIX_INIT_MP3 | MIX_INIT_OGG | MIX_INIT_MID);
             InitMusicModule();
             active_music_module = music_module;
         }

```

**Comment by fragglet** [comment]
Interesting! Glad that we've found the apparent cause. I suggest that we add the `Mix_Init()` call, albeit not in `i_sound.c`. It looks like the function is reentrant and can be called multiple times. So we'll need:

* `Mix_Init(MIX_INIT_FLAC | MIX_INIT_OGG | MIX_INIT_MP3);` inside `i_musicpack.c`
* `Mix_Init(MIX_INIT_MID);` inside `i_sdlmusic.c`

**Comment by Zodomaniac** [comment]
@fragglet it should be made the way that will allow Crispy fork to play a WAD with all possible audio formats inside.

**Comment by fragglet** [comment]
Crispy needs `Mix_Init(MIX_INIT_FLAC | MIX_INIT_MP3 | MIX_INIT_OGG | MIX_INIT_MID);` inside `i_sdlmusic.c` (ie. just a few more flags)

In other words Fabian's solution is correct but in the inappropriate file.

**Comment by fabiangreffrath** [comment]
I'll take care of the right flags in Crispy, thanks. :wink:

**Comment by fabiangreffrath** [comment]
Where exactly do we inset the calls? Apparently, `SDLIsInitialized()` returns false positive in each case.

**Comment by AlexMax** [comment]
Just to test, I shoved a `Mix_Init(MIX_INIT_FLAC | MIX_INIT_MP3 | MIX_INIT_OGG | MIX_INIT_MID);` call before enumerating music decoders, and that did indeed seem to fix the problem.  Now I get 7 codecs enumerated instead of one.

**Comment by Zodomaniac** [comment]
I'm sorry to say that midiproc still doesn't spawn.

**Comment by fabiangreffrath** [comment]
Oh, crap! It seems that enumerated names are not defined in the CPP-sense. I didn't know that.
```
$ cat test.c
#include <stdio.h>

enum {DEF};

int main (void)
{
#ifdef DEF
puts("def");
#else
puts("not def");
#endif
}

$ make test
cc     test.c   -o test

$ ./test
not def

```

**Comment by Zodomaniac** [comment]
Fixed, finally! :1st_place_medal:
