### ISSUE TITLE
Apply Romero's 'funky blue' to netgame start screen

### ISSUE THREAD

**Issue by Zodomaniac** [chocolate-doom/chocolate-doom#1151]
It would be logical to apply Romero's funky blue to chocolate-doom.exe's netgame start screen as you did to setup tool
![Romero's blue](https://user-images.githubusercontent.com/15119473/54450048-7c56b300-4760-11e9-97ad-527dcfd7a789.png)

**Comment by fragglet** [comment]
I'm going to say no on this one. Setup tool only. If the waiting screen is analogous to the popup boxes shown by `sersetup`/`ipxsetup` under DOS, those don't actually set Romero Blue.

**Comment by nukeykt** [comment]
A bit offtopic, but was "Romero's funky blue" actually coded by Romero? Raptor's setup utility uses exactly the same color and most likely Doom's one inherit it from there, not vice-versa. Raptor's setup was most likely programmed by Scott Host and Paul Radek.

**Comment by Zodomaniac** [comment]
Maybe then the new color should be discarded? For me the bright blue window of waiting for netgame start after dark blue one of Setup is just sharp to the eyes and feels like a bug.

**Comment by AXDOOMER** [comment]
It's color inconsistency. Even though one window comes from the setup tool and the other from the main engine executable, both are text windows and should use the same color theme for consistency in the eyes of the users.

**Comment by JNechaevsky** [comment]
As an idea - apply bright blue color in netgame window only when the game is actually ready to start, i.e. when there is two or more players ready.

**Comment by fabiangreffrath** [comment]
Let's rather not switch colors back and forth.

**Comment by Zodomaniac** [comment]
Posted another issue, more appropriate for the direction that the discussion has taken
https://github.com/chocolate-doom/chocolate-doom/issues/1153

**Comment by fragglet** [comment]
Please send a pull request to fix the netgame wait screen if the inconsistency really bugs you.
