### ISSUE TITLE
chocolate-setup can only bind actions to enter key, and cannot remap to anything else

### ISSUE THREAD

**Issue by poikilos** [chocolate-doom/chocolate-doom#1157]
### Background

Version of Chocolate Doom: 2.3.0

Operating System and version: Fedora 29 (updated 2 days ago approx)

Game: any

Any loaded WADs and mods (please include full command line):
chocolate-doom-setup

### Bug description

Observed behavior: When trying to change keys (such as "up"), can press enter, and key changes to enter, but pressing any other key afterward does not change the key (though on-screen says Enter is to select things). Pressing enter on a different field changes that to "Enter" and the previous to "(none)" 

Expected behavior: Press enter on an action's field, then press a different key to bind the action to that key.

**Comment by fragglet** [comment]
So basically whenever you try to change a key binding, it always gets set to "enter" and doesn't allow you to actually press the key you wanted to bind? Is that correct?

**Comment by poikilos** [comment]
Yes

**Comment by jmtd** [comment]
I presume you are using GNOME/Wayland in Fedora 29? Do you get the same results if you use "GNOME on Xorg" session?

**Comment by poikilos** [comment]
Hmm...On my Antergos computer updated today, I don't get the issue in GNOME in either Wayland or xorg (GNOME 3.32.2), but it is chocolate-doom-setup 3.0.0. I still get the issue with the computer in the original issue with 2.3.0 even in x.org mode.

**Comment by fabiangreffrath** [comment]
So, this is probably a pre-SDL2 issue.

**Comment by poikilos** [comment]
Thanks--understood. Close if appropriate.
