### ISSUE TITLE
load PWADs by dragging the file onto the executable

### ISSUE THREAD

**Issue by fabiangreffrath** [chocolate-doom/chocolate-doom#1161]
Short story: It should be possible to load PWADs by simply dragging them onto the executable icon.

**Comment by chungy** [comment]
In the Windows world, it works just by appending the file name(s) as a program argument.

PrBoom and GZDoom both already have support for loading *.wad and *.deh files without another parameter first, and it probably isn't terribly hard to support this feature by checking the extension.

**Comment by fabiangreffrath** [comment]
I'd suggest we only apply the extension checking logic if we detect there is no other "regular" parameter (i.e. one starting with a dash) on the command line. Else it might turn out a bit tricky to find out which parameter is just a loose filename and which one belongs to a former regular parameter.

**Comment by fabiangreffrath** [comment]
Things to consider:

 - Files passed on the comand line without a preceeding regular parameter should only be allowed if they are the *first* parameters after the excutable name, e.g. `chocolate-doom mypwad.wad`. Else, calls like e.g. `chocolate-doom -deh mypatch.deh mypwad.wad` would be ambigious. Granted, calls like `chocolate-doom -fullscreen mypwad.wad` would not, but where to draw the line?

 - Should PWADs given on the command line without a regular parameter get `-file`d or `-merge`d? This is not a trivial question, as it determines where to add the logic to the code (PWADs given to `-merge` get merged before the ones given to `-file` get added, because the former are supposed to be modified IWADs).

**Comment by fabiangreffrath** [comment]
Next question: Do we consider `*.lmp` files passed without a preceeding parameter to be demos that want to be played back or lumps that want to get added as if they were PWADs?

**Comment by fabiangreffrath** [comment]
Bonus question: Are we going to detect and identify IWADs by their file name and load them as if they were passed over to the `-iwad` parameter?

**Comment by fragglet** [comment]
.LMP files are lumps (let's not guess about them being demos) and yes, we should definitely detect IWADs. I suggest adding a function to `d_iwad.c` to query if a filename matches an IWAD filename.
