### ISSUE TITLE
autogen no package sdl2 found

### ISSUE THREAD

**Issue by igdegoo** [chocolate-doom/chocolate-doom#1167]
### Background

Version of Chocolate Doom: 3.0

Operating System and version: windows 10

Game: (Doom/Heretic/Hexen/Strife/other) the game of compiling things

Any loaded WADs and mods (please include full command line): well im trying to compile it so there arent going to be any loaded mods

### Bug description

Observed behavior: autogen errors with No package 'sdl2' found

Expected behavior: autogen doesnt error and works

theres another issue on this saying to follow the page  at https://www.chocolate-doom.org/wiki/index.php/Building_Chocolate_Doom_on_Windows correctly, but i have. (yes ive done the Installing build dependencies chapter)

i tried installing sdl2 with pacman -S SDL2 but it says "error: target not found: sdl2"

and pkg-config sdl2 --libs results in

Package sdl2 was not found in the pkg-config search path.
Perhaps you should add the directory containing `sdl2.pc'
to the PKG_CONFIG_PATH environment variable
No package 'sdl2' found

it could be because i have devkitpro installed which includes msys (but i did a new install in a differnet folder)

**Comment by fragglet** [comment]
Please type the command exactly as it appears on the wiki page:
```sh
pacman -S base-devel msys2-devel \
       mingw-w64-i686-{toolchain,SDL2{,_net,_mixer},libsamplerate,libpng} \
       python zip git
```
The package is named `mingw-w64-SDL2`, not `sdl2`.

**Comment by igdegoo** [comment]
> The package is named `mingw-w64-SDL2`, not `sdl2`.
when i try installing that with pacman -S it says target not found as well

**Comment by chungy** [comment]
It is possible the wiki instructions have gone out of date (has happened before). I'll try to get on a Windows system later today to check it.

**Comment by chungy** [comment]
Just verified that it all works, but as the one that wrote most of the text on the wiki, I will appreciate feedback if it is unclear.

I can think of two possible points of confusion at the moment:
* Did you complete the first steps of running `pacman -Syu` once, then again?
* Did you run a terminal appropriate for the target compiler? Eg, if you installed the i686 toolchain, you should use the _32-bit_ shortcut, not the 64-bit or generic ones.

**Comment by igdegoo** [comment]
> 
> 
> Just verified that it all works, but as the one that wrote most of the text on the wiki, I will appreciate feedback if it is unclear.
> 
> I can think of two possible points of confusion at the moment:
> 
>     * Did you complete the first steps of running `pacman -Syu` once, then again?
> 

yes i did

>     * Did you run a terminal appropriate for the target compiler? Eg, if you installed the i686 toolchain, you should use the _32-bit_ shortcut, not the 64-bit or generic ones.

i did not think it said that inthe wiki. ill try using msys32.exe

**Comment by igdegoo** [comment]
thanks a lot chungy. it detected sdl2 and is compiling rn

**Comment by igdegoo** [comment]
compiled
