### ISSUE TITLE
Hall of mirror

### ISSUE THREAD

**Issue by chocolate-import** [chocolate-doom/chocolate-doom#117]
> The following bug was [originally reported](https://sourceforge.net/p/chocolate-doom/bugs/117/) on Sourceforge by [axdoom](https://sourceforge.net/u/axdoom/profile/), 2010-12-31 21:37:57:

The hall of mirror effect in Chocolate-Doom is different from the one in the original Doom.

**Comment by jmtd** [comment]
Closed in favour of duplicate #676 (which has current discussion and code)
