### ISSUE TITLE
Chocolate doom freezing randomly in win10

### ISSUE THREAD

**Issue by barrel-of-pasta** [chocolate-doom/chocolate-doom#1171]
I'm using the latest git build of chocolate doom with the ultimate doom and well it's not working correctly in windows 10 1903. I dumped SDL2 2.0.8 into the folder which seemed to fix the issue. I got more curious and I found this while looking through their bug tracker.. I'm not sure if this is the issue though

https://bugzilla.libsdl.org/show_bug.cgi?id=4391

**Comment by fabiangreffrath** [comment]
But we do already call `SDL_Init(SDL_INIT_JOYSTICK)` in `I_InitJoystick()`. Maybe it is too late, though? Could this also be the cause for https://github.com/chocolate-doom/chocolate-doom/issues/1169 ?

**Comment by barrel-of-pasta** [comment]
Well it was just a guess and I've not looked at the code since well I don't know how to code. I could go the extra mile and try to see what's happening while the application is running. What's the best way to do something like that? I can use the command prompt and I've compiled applications before

**Comment by fragglet** [comment]
The latest SDL releases really seem to be a mess. I think we should probably roll back to 2.0.8 but as I recall that had some major bugs as well.
