### ISSUE TITLE
[Feature request] Add support to Sigil

### ISSUE THREAD

**Issue by e-minguez** [chocolate-doom/chocolate-doom#1173]
### Background

Version of Chocolate Doom: v3.0.0 (baef4832)

Operating System and version: PS Vita

Game: (Doom/Heretic/Hexen/Strife/other): Sigil

Any loaded WADs and mods (please include full command line): nope

### Bug description

Observed behavior: After copying the sigil wad into ux0:/data/chocolate/iwads/SIGIL.wad, SIGIL doesn't show 'sigil' game in the game selection.

Expected behavior: Sigil is supported

**Comment by fabiangreffrath** [comment]
Sigil is explicitely *not* Vanilla compatible.

**Comment by shirkdog** [comment]
Before reopening this issue or adding another, there is the SIGIL_COMPAT.wad with the goal of being supported by "Vanilla DOOM".

Will this not be supported by chocolate-doom?

**Comment by chungy** [comment]
Chocolate Doom only loads vanilla-compatible IWADs/PWADs. If SIGIL_COMPAT works in vanilla and doesn't in Chocolate Doom, file a new report for that.

**Comment by shirkdog** [comment]
And for now, I would leave this closed, I validated I received the same exact error in Vanilla DOOM on DosBox, which is a testament to Chocolate Doom being authenticate to Vanilla.

**Comment by Zodomaniac** [comment]
With Crispy Doom fork of Choco https://github.com/fabiangreffrath/crispy-doom you can play Sigil even with Buckethead's MP3 soundtrack already with the daily build available at http://latest.chocolate-doom.org/
