### ISSUE TITLE
W_GetNumForName errror on start

### ISSUE THREAD

**Issue by AGuyCalledGerald** [chocolate-doom/chocolate-doom#1175]
Version of Chocolate Doom: 3.0.0

Operating System and version:

Windows 10 64 bit

Game: Doom2

Any loaded WADs and mods (please include full command line):

doom2.wad

### Bug description

Downloaded chocolate doom for windows.
Placed doom2.wad in the same directory.
Started chocolate doom.

Error message: 

W_GetNumForName: genmidi not found!

I disabled all sound effects & music in setup. Error changes to

W_GetNumForName: PNAMES not found!

**Comment by fabiangreffrath** [comment]
Your IWAD is cleary corrupted.

**Comment by fragglet** [comment]
I concur. Something's wrong with your IWAD file- please feel free to reopen if you can get it to work using any other source port.
