### ISSUE TITLE
Mention TNT and Plutonia in savegame auto-naming

### ISSUE THREAD

**Issue by Zodomaniac** [chocolate-doom/chocolate-doom#1180]
### Background

Version of Chocolate Doom: Latest git

Operating System and version: Win 7

Game: Plutonia, TNT

### Bug description

Observed behavior: the automatically filled in save name is just 'MAPxx' for Plutonia and TNT 

Expected behavior: It would be better to print 'Plutonia MAPxx' and 'TNT MAPxx' respectively.

**Comment by fabiangreffrath** [comment]
Savegames are stored in separate directories per IWAD, so there is no risk of mixing up Plutonia or TNT savegames with regular Doom 2 ones. Thus, if you run Chocolate Doom with Plutonia as the IWAD, you will only be presented Plutonia savegames, so adding "Plutonia" to savegame descriptions would be pretty redundant.

Please re-open if I missed anything.

**Comment by Zodomaniac** [comment]
No, under Windows all savegames are stored in the same folder, so if I save from MAP01 of HoE, PLT and TNT, I get the following:
![DOOM00](https://user-images.githubusercontent.com/15119473/60000187-5cdafa80-966c-11e9-9f9c-e00a979b2314.png)

**Comment by fabiangreffrath** [comment]
Oh, indeed! We don't have `configdir` on Windows, so we don't have `savegamedir` either.
