### ISSUE TITLE
Random Freezes During Coop Play Over Internet

### ISSUE THREAD

**Issue by ssardiko** [chocolate-doom/chocolate-doom#1190]
### Background

Version of Chocolate Doom:
3.0.0
Operating System and version:
Windows 10 Build 17763
Game: (Doom/Heretic/Hexen/Strife/other)
Doom 2
Any loaded WADs and mods (please include full command line):

### Bug description

Observed behavior:
Game will freeze for an indefinite amount of time when playing coop over the internet with another person. Players will either have to wait until the game unfreezes or until one of the players leaves the game.
Expected behavior:
Game does not freeze in coop.

**Comment by fragglet** [comment]
Thanks for the report - I believe this is already fixed in daily builds.

Please switch to playing with a build from http://latest.chocolate-doom.org and if you encounter the problem again, don't hesitate to reopen this bug.
