### ISSUE TITLE
Keyboard input is ignored while a new demo is loaded on menu screen.

### ISSUE THREAD

**Issue by crocket** [chocolate-doom/chocolate-doom#1192]
### Background

Version of Chocolate Doom: https://github.com/chocolate-doom/chocolate-doom/commit/b9d4c04c840321f5ec70787d8afb1256766aaa01

Operating System and version: Gentoo Linux

Game: Doom

Any loaded WADs and mods (please include full command line):

* chocolate-doom -iwad the-ultimate-doom -window

### Bug description

Observed behavior:

While a new demo is loaded, keyboard input is ignored on menu screen.

![2019-08-24_Sat_13:25:34](https://user-images.githubusercontent.com/748856/63638128-2e56bb80-c6bf-11e9-9761-1e223c62eaee.png)

Expected behavior:

Keyboard input should not be ignored on menu screen while a new demo is loaded.

**Comment by fragglet** [comment]
Thanks for the report. This is vanilla behavior whenever a screen melt occurs.
