### ISSUE TITLE
Old midiproc-related bug: when running Choco after removing midiproc, the MIDI volume isn't applied

### ISSUE THREAD

**Issue by Zodomaniac** [chocolate-doom/chocolate-doom#1193]
### Background

Version of Chocolate Doom: https://github.com/chocolate-doom/chocolate-doom/commit/b9d4c04c840321f5ec70787d8afb1256766aaa01

Operating System and version: Win 7 Professional 64-bit

Game: Doom (2)

Any loaded WADs and mods (please include full command line):

### Bug description

Pre-condition: run Choco, set music volume to 1 (near minimum). Then quit Choco.

Observed behavior: if you remove midiproc.exe from the folder and run Choco again, the MIDI volume will be maximum, though it is near minimum in sound volume settings.

Expected behavior: the MIDI volume value should be read from config correctly regardless of midiproc's presence, the SFX volume as well (before MIDI volume is fixed, I cannot test the SFX volume for sure if it's applied correctly).

**Comment by fabiangreffrath** [comment]
@AlexMax May this be due to this line?
https://github.com/chocolate-doom/chocolate-doom/blob/master/midiproc/main.c#L144

**Comment by Zodomaniac** [comment]
>To work around this bug, we set the volume to itself after the MIDI has started playing.
This looks wrong, The volume should be set to the value read from config, not to 'itself', because it can be wrong initially.

**Comment by Zodomaniac** [comment]
Closing this as there is no more need to remove midiproc from the folder after resolving #963 :)
