### ISSUE TITLE
Midiproc cannot run with older DLLs (SDL2 2.0.5, mixer 2.0.1) when using fluidsynth

### ISSUE THREAD

**Issue by Zodomaniac** [chocolate-doom/chocolate-doom#1199]
### Background

Version of Chocolate Doom: Built on 27.09.2019 SDL2 2.0.5 and SDL2_mixer 2.0.1 with fluidsynth support

Operating System and version: Win 7 Professional x64

Game: Doom (2)

Any loaded WADs and mods (please include full command line):

```
@echo off
set SDL_SOUNDFONTS=TimGM6mb.sf2
start chocolate-doom
exit
```

### Bug description

Observed behavior: `chocolate-midiproc.exe` doesn't launch

Expected behavior: `chocolate-midiproc.exe` should launch

**Comment by chungy** [comment]
You're supposed to use the DLLs shipped with Chocolate Doom. Mixing in other versions from other sources is not supported.
