### ISSUE TITLE
fragglet, why is the problem not resolved in 2 years?

### ISSUE THREAD

**Issue by PepsimanRUS** [chocolate-doom/chocolate-doom#1200]
fragglet, why is the problem not resolved in 2 years? link https://github.com/chocolate-doom/chocolate-doom/issues/971

**Comment by fragglet** [comment]
Because I'm not your slave.

**Comment by 2mg** [comment]
May I kindly ask for this issue to be reopened? Still happening with 3.0.1, at least on Win7 as I can tell. Midiproc.exe doesn't get launched with barebone GUS or MIDI setting in config.

Also, if you set Music level ingame with GUS or MIDI, then switch to OPL, it will use those values as min/max. For example, if you use MIDI/GUS, set them to lowest possible but hearable, switch to OPL, and bump it to the max, it will sound rather quiet.

**Comment by fabiangreffrath** [comment]
> PS: seems autobuild versions do NOT have _both_ of these issues: sfx tied to music, and MIDI/GUS <> OPL switch volume.

And since the issue has been fixed, there is no reason to repoen it,

**Comment by 2mg** [comment]
> > PS: seems autobuild versions do NOT have _both_ of these issues: sfx tied to music, and MIDI/GUS <> OPL switch volume.
> 
> And since the issue has been fixed, there is no reason to reopen it.

Sure, I'm just asking if this will make it into the final release.
