### ISSUE TITLE
Leverage SDL_Mixer for seamless OGG looping?

### ISSUE THREAD

**Issue by mikeday0** [chocolate-doom/chocolate-doom#1208]
### Background

Version of Chocolate Doom: ee9fc21f

Operating System and version: Ubuntu 18.04, Windows 10

Game: All

### Bug description

When using musicpack files, looping is not seamless even with well-chosen loop points. There is always a hiccup or drop-out. (See #1178) After some experimentation with the i_musicpack.c code, I am convinced the only way this can be properly fixed is to petition for (or contribute?) native loop point support to SDL_Mixer. Poking through the SDL_Mixer source (music_ogg.c), I was surprised to see that such support is already present for OGG files. (But unfortunately not FLAC or MP3)

If your OGG file contains LOOPSTART and LOOPEND comments which specify the loop points in sample position, SDL_Mixer will use those loop points whenever it plays the files with looping requested. (I guess it is an unfortunate coincidence that this differs just slightly from the zdoom LOOP_START and LOOP_END tags that Chocolate uses.) 

For illustration, I have attached a zip file containing two ogg files with an identical tone. It is five seconds of a 441 Hz sine followed by 1 second of silence.
[441Hz-Sinewaves.zip](https://github.com/chocolate-doom/chocolate-doom/files/3747411/441Hz-Sinewaves.zip)

The only difference between the two files is that one uses LOOPSTART/LOOPEND, and the other uses LOOP_START/LOOP_END. The loop points are selected so it should loop about every 3 seconds. If you have Chocolate Doom use these as substitute music tracks you can do a direct comparison of the SDL_Mixer and Chocolate looping. In my testing, I find that the SDL_Mixer looping is completely seamless.

My suggestion is to give the user the option to have Chocolate add LOOPSTART and LOOPEND tags to OGG files when it encounters the zdoom standard LOOP_START and LOOP_END tags. Maybe name it something like "Modify OGG tags to enable seamless looping" to clearly communicate that Chocolate is touching their music files.

If folks think something like this is worthwhile I'd be more than happy to take a crack at it!

**Comment by fragglet** [comment]
I wasn't even aware that SDL_mixer had native loop tag support. It seems like it ought to be trivial to make it also recognize the `LOOP_START`/`LOOP_END` tags as well?

**Comment by mikeday0** [comment]
Yes, provided that building your own SDL_Mixer wasn't out of the question. You'd need to edit the following in music_ogg.c:

![image](https://user-images.githubusercontent.com/43701387/67233276-e62eed80-f410-11e9-853d-604299b65c4b.png)

Unfortunately SDL_Mixer does not provide an external interface to directly manipulate the loop points. Also, it doesn't appear to support loop points for FLAC and MP3... yet.

If using a custom SDL_Mixer is a no-go, the only way I see to utilize the SDL_Mixer loop point is to have Chocolate add the LOOPSTART and LOOPEND comments to ogg files. I'd imagine you'd also want to turn off the Chocolate looping code whenever LOOPSTART and LOOPEND are present so Chocolate and SDL_Mixer aren't both trying to loop.

**Comment by fragglet** [comment]
Just a brief comment: with this talk about "building our own SDL_mixer" - while it's possible, I'd encourage you not to think of SDL_mixer as some kind of immutable thing handed down to us that's entirely outside our control or influence. From everything you're saying it sounds like the best approach here would be to just contribute some code to SDL_mixer itself. I don't see why they wouldn't accept it. In other words, when you said:

> I am convinced the only way this can be properly fixed is to petition for (or contribute?) native loop point support to SDL_Mixer. 

This sounds exactly correct.

There's an added advantage as well that doing so implicitly gives looping support to any and all other source ports using SDL_mixer for music playback.

**Comment by mikeday0** [comment]
Duly noted! I mistakenly assumed they didn't accept contributions due to the lack of any explicit language stating as such on the SDL_Mixer website. Digging a bit, it turns out that you can submit patches via their Bugzilla.

What would you like to see added to SDL_Mixer? The simple route would be to OR in matching the LOOP_* key names to the code above. However I have to wonder if it would be better implemented as an external-facing function where the user specifies to SDL_Mixer the comment/tag key name to look for. Something like:

`Mix_SetLoopKeyNames(char* loop_start_name, char* loop_end_name, char* loop_length_name)`

Or maybe it's better to set the loop points explicitly:

`Mix_SetLoopPoints(uint loop_start_position, uint loop_end_position)`

Or something else entirely?

**Comment by fragglet** [comment]
The ideal solution would be if SDL_mixer could take care of handling loop points entirely, and we can entirely get out of the business of having to deal with that in the Chocolate Doom codebase. I'd suggest you start with your proposed patch to `music_ogg.c` from a couple of comments back. Assuming that goes well, take a look at the FLAC integration and see if you can implement the same there as well.

Good luck and let me know if I can do anything to help.

**Comment by mikeday0** [comment]
Patch file for OGG looping submitted to SDL:
https://bugzilla.libsdl.org/show_bug.cgi?id=4849

FLAC support in progress...

**Comment by fabiangreffrath** [comment]
Great patch, thanks for that!

**Comment by mikeday0** [comment]
The OGG looping patch has been accepted!
http://hg.libsdl.org/SDL_mixer/rev/493a943d944a

**Comment by mikeday0** [comment]
Patch file for FLAC looping submitted to SDL:
https://bugzilla.libsdl.org/show_bug.cgi?id=4855

I also have a bug fix for the initial stutter when first playing FLAC files that I'll submit separately. (Also mentioned in #1178)

If anyone else wants to try it out, feel free to clone [my SDL_mixer fork](https://github.com/mikeday0/SDL_mixer).

**Comment by mikeday0** [comment]
All of my changes to SDL_Mixer are in and should be part of the official 2.0.5 release. Not sure when this will happen, but my baseless speculation is that they are trying to get something out before the end of the year. I have submitted #1225 which disables the Chocolate looping code.

Earlier you mentioned that there were other source ports which used SDL_Mixer. Do you happen to know which ones? I'd like to give them a heads up that this change is coming in case the developers might want to take advantage of it.

**Comment by fabiangreffrath** [comment]
> Earlier you mentioned that there were other source ports which used SDL_Mixer. Do you happen to know which ones? 

PrBoom+ and Eternity for sure.

**Comment by richterdeveloper** [comment]
Hello!! The unaccurate loop point bug is still present in the lastest build.

**Comment by mikeday0** [comment]
Chocolate Doom has not migrated yet to SDL Mixer 2.6. That needs to be done in order for the issue to be resolved.

**Comment by mikeday0** [comment]
Thanks to #1531, I think we can close this.
