### ISSUE TITLE
Wrong par time for MAP33

### ISSUE THREAD

**Issue by fabiangreffrath** [chocolate-doom/chocolate-doom#1209]
Reportedly, the par time shown when finishing MAP33 (Betray) is shown as "SUCKS" on real hardware [0], whereas it is initialized to zero [1] in Chocolate Doom.

I'd like to change this initialization value to e.g. `INT_MAX` to make sure it is always a huge number that exceeds `59*61` which is the limit after which the "SUCKS" patch is shown. 

One question remains: In a follow-up post, a user suggests to change the condition to `>= 33` to account for PWADs which provide more than 33 maps. However, I am not sure what par time DOOM2.EXE would show for such maps or if it would probably even crash. Does anyone have any experience here or do you consider it safe to change this line of code as suggested?

[0] https://www.doomworld.com/forum/topic/67168-crispy-doom-563-update-oct-04-2019/?page=47&tab=comments#comment-2038332
[1] https://github.com/chocolate-doom/chocolate-doom/blob/master/src/doom/g_game.c#L1463
[2] https://www.doomworld.com/forum/topic/67168-crispy-doom-563-update-oct-04-2019/?page=47&tab=comments#comment-2038392

**Comment by fabiangreffrath** [comment]
Alright, so I have taken a HEX editor and inspected DOOM.EXE v1.9 to see what int values we would find when reading past the `cpars[]` array. Here are my results for maps up to MAP40:

`cpars[32]` (MAP33): 1835884871 ("Gamm")
`cpars[33]` (MAP34): 1868767329 ("a co")
`cpars[34]` (MAP35): 1667592818 ("rrec")
`cpars[35]` (MAP36): 1852795252 ("tion")
`cpars[36]` (MAP37): 1179012896 (" OFF")
`cpars[37]` (MAP38): 0
`cpars[38]` (MAP39): 1632043008 ("  Ga")
`cpars[39]` (MAP40): 543255917 ("mma ")

So, I guess we are safe to say that the par time for maps > 32 is well approximated by `INT_MAX` with the single exception of MAP38.

**Comment by fabiangreffrath** [comment]
NB: We retrieve par time values > 3600 for each level up to MAP76, with the execption of MAP38.

**Comment by fabiangreffrath** [comment]
Hm, so I have just finished MAP33 with DOOM.EXE in DosBox using the BFG-Edition DOOM2.WAD file and interestingly, *no* par time is printed on the intermission screen. This is a significantly different result than what is presented here: https://www.youtube.com/watch?v=mYRtNFjrZrY

Is there probably any guard in DOOM.EXE that prevents printing par times for maps >32 that didn't make it into the source code?

**Comment by fabiangreffrath** [comment]
Oh, wait. DOOM.EXE does realize this isn't the original IWAD and prompts me to press Enter during start-up. May this be the reason why the par time isn't printed?

**Comment by nukeykt** [comment]
Which version of DOOM.EXE do you use? IIRC Ultimate Doom and Final Doom EXEs had some quirks with par times in 'commercial' mode

**Comment by fabiangreffrath** [comment]
I am using the regular 1.9 EXE which came with the shareware IWAD.

**Comment by nukeykt** [comment]
I think regular 1.9 Doom uses exactly the same EXE as Doom 2

**Comment by fabiangreffrath** [comment]
> I think regular 1.9 Doom uses exactly the same EXE as Doom 2

Yes.

**Comment by fabiangreffrath** [comment]
> Oh, wait. DOOM.EXE does realize this isn't the original IWAD and prompts me to press Enter during start-up. May this be the reason why the par time isn't printed?

Turns out this is because the BFG Edition DOOM2.WAD has the PWAD header instead of IWAD. This and I'll have to rename the DMENUPIC lump to TITLEPIC. Further tests will follow...

**Comment by fabiangreffrath** [comment]
So, I have finished MAP33 with any of the three regular DOOM.EXEs (i.e. 1.9, Ultimate, Final) and recorded the map stats with `statdump`. The par time is always reported as `-521:-10`:

```
===========================================
MAP33
===========================================

Time: 0:13 (par: -521:-10)

Player 1 (Green):
	Kills: 0 / 92 (0%)
	Items: 0 / 8 (0%)
	Secrets: 0 / 3 (0%)

```

Yes, I did IDCLIP myself to the exit switch. :wink:

**Comment by fabiangreffrath** [comment]
Riddle solved!
```
diff --git a/src/doom/g_game.c b/src/doom/g_game.c
index 9cabfaf8..879ea72b 100644
--- a/src/doom/g_game.c
+++ b/src/doom/g_game.c
@@ -1463,7 +1463,8 @@ void G_DoCompleted (void)
         // map33 has no official time: initialize to zero
         if (gamemap == 33)
         {
-            wminfo.partime = 0;
+            const int cpars32 = *(int *)GAMMALVL0;
+            wminfo.partime = TICRATE*cpars32;
         }
         else
         {
diff --git a/src/doom/statdump.c b/src/doom/statdump.c
index 5bacad67..59f935a4 100644
--- a/src/doom/statdump.c
+++ b/src/doom/statdump.c
@@ -268,7 +268,7 @@ static void PrintLevelName(FILE *stream, int episode, int level)
 
 static void PrintStats(FILE *stream, wbstartstruct_t *stats)
 {
-    int leveltime, partime;
+    short leveltime, partime;
     int i;
 
     PrintLevelName(stream, stats->epsd, stats->last);
```

**Comment by fabiangreffrath** [comment]
Well, strictly speaking this should probably be:
```
const int cpars32 = LONG(*(int *)DEH_String(GAMMALVL0));
```

**Comment by turol** [comment]
Casting a pointer like that is bad since the string is not guaranteed to be correctly aligned. Try this instead:
```
memcpy(&cpars32, DEH_String(GAMMALVL0), sizeof(int));
```

**Comment by fabiangreffrath** [comment]
Good point, thanks. Is this approach endian-safe?

**Comment by turol** [comment]
> Is this approach endian-safe?

No, but who still has big-endian hardware to test on? If you want it to work you could add an endianness swap after the copy.

**Comment by fabiangreffrath** [comment]
I know of at least one Wii fork, so I'd like to keep the code endianess clean. 

https://github.com/derek57/wii-doom

**Comment by fragglet** [comment]
> No, but who still has big-endian hardware to test on?

FWIW, the weekly Choco/Crispy regression tests are running on a big endian machine, deliberately for testing this kind of portability.
