### ISSUE TITLE
Broken GUS emulation in Chocolate Doom daily builds

### ISSUE THREAD

**Issue by sinisterseed** [chocolate-doom/chocolate-doom#1213]
### Background

Version of Chocolate Doom: 3.0.0 (Daily build as of Nov 6th 2019)

Operating System and version: Windows 10 ver 1903

Game: Doom.

Any loaded WADs and mods (please include full command line): None.

### Bug description

Observed behavior: It seems GUS emulation is broken in the daily builds of Chocolate Doom. I don't know when it broke however, but this morning I spent hours trying to get it work by setting it up through the setup program by using both the GUS (emulated) and the Native MIDI options. In both cases however, pointing the players to the right path (GUS emulation) or config (Native MIDI)
achieves nothing and in both cases it appears Native MIDI is used instead without anything else, and not doing what it is supposed to do. 

Eventually, @fragglet asked me to try the stable 3.0.0 release, and after following the exact same steps as instructed by the Chocolate Doom Wiki, **_it worked_**. In the case of the daily builds, **_it simply does not work_**. I also tried replacing the SDL2_mixer from the daily builds with that of 3.0.0... and it completely broke the sound effects. Also, still no GUS emulation. So, it's probably not related to SDL, but I can't know for sure.

More info:  https://www.doomworld.com/forum/topic/86366-chocolate-doom/?page=24

Expected behavior: GUS emulation actually works.

**Comment by fabiangreffrath** [comment]
> I also tried replacing the SDL2_mixer from the daily builds with that of 3.0.0... and it completely broke the sound effects.

I am pretty sure this cannot work. Would you please try again and replace the entire DLL stack of the daily build with the one from the 3.0.0. release?

**Comment by sinisterseed** [comment]
> > I also tried replacing the SDL2_mixer from the daily builds with that of 3.0.0... and it completely broke the sound effects.
> 
> I am pretty sure this cannot work. Would you please try again and replace the entire DLL stack of the daily build with the one from the 3.0.0. release?

Okay, I replaced **_all_** DLLs as requested with those from the stable 3.0.0 release. Both GUS (emulated) and Native MIDI work as intended now.

Now the question is: **_what_** broke in the daily builds then? Those DLLs from 3.0.0 did seem to fix the problem.

**Comment by Zodomaniac** [comment]
Fixed by @JNechaevsky in https://github.com/chocolate-doom/chocolate-doom/commit/f1fa7faf566e3e325c1b1fbf8ace8d5ac2db2b1e

**Comment by sinisterseed** [comment]
> Fixed by @JNechaevsky in [f1fa7fa](https://github.com/chocolate-doom/chocolate-doom/commit/f1fa7faf566e3e325c1b1fbf8ace8d5ac2db2b1e)

Alright, I'm closing this Issue then.
