### ISSUE TITLE
Crash in Doom v1.8 on E3M9

### ISSUE THREAD

**Issue by sinisterseed** [chocolate-doom/chocolate-doom#1214]
### Background

Version of Chocolate Doom: 3.0.0 (Daily build as of Nov 6th 2019)

Operating System and version: Windows 10 ver 1903

Game: Doom

Any loaded WADs and mods (please include full command line): -iwad doom.wad -gameversion 1.8

### Bug description

Observed behavior: I don't actually have much to say about this. I was casually playing through a Doom v1.8 IWAD today (downgraded from Ultimate Doom), and I crashed after I reached E3M9 (accessed normally through the secret exit). I crashed after entering the area right before the tunnel with Pinkies, with the error: P_PlayerInSpecialSector: unknown special 8.

After the crash, I warped (-iwad doom.wad -warp 3 9 -skill 4 -gameversion 1.8) to E3M9 and it didn't crash again, so, something funky happened the first time around. What, I don't know.

Here's a clip of the moment: https://clips.twitch.tv/CreativeGleamingAlligatorAMPTropPunch

Expected behavior: Chocolate Doom does not give up.

![gfgf](https://user-images.githubusercontent.com/57503728/68423723-3d6fe480-01ab-11ea-9149-b2c0fcf6559f.png)

**Comment by drfrag666** [comment]
Looks like a map bug. Which tool have you used? Iwadpatcher?

**Comment by sinisterseed** [comment]
> Looks like a map bug. Which tool have you used? Iwadpatcher?

Tool for what? Downgrade? Delta Patcher: https://github.com/marco-calautti/DeltaPatcher/releases/tag/2.0.1

I can send you my IWAD if you want too.

**Comment by tpoppins** [comment]
This is a well-known map design error that affects all DOOM IWADs between v1.2 and v1.9:
https://tcrf.net/Doom_(PC,_1993)/Revisional_Differences#E3M9:_Warrens

Chocolate Doom emulates the vanilla behavior correctly in this case,

**Comment by sinisterseed** [comment]
> This is a well-known map design error that affects all DOOM IWADs between v1.2 and v1.9:
> https://tcrf.net/Doom_(PC,_1993)/Revisional_Differences#E3M9:_Warrens
> 
> Chocolate Doom emulates the vanilla behavior correctly in this case,

Oh, so it's apparently intended behavior then.

> "In v1.25, the code used to lower the bridge with the shotgun was updated to copy from the lowest neighboring sector when changing its sector floor flat and type. This makes the bridge sections appear to sink beneath the blood, rather than sitting on its surface. 
> 
> This fix also introduced a crash into the level: A sector in the outside area to the right of the entrance was mistakenly given the same tag as one of the dropping bridge sections. In previous versions, this would only cause this sector's floor flat to be changed when the bridge was lowered, which was merely a cosmetic issue. The code change in 1.25, however, makes this sector read garbage for its type since there are no lower sectors surrounding it, and the game will crash when the player steps into a sector with an unknown type. Unlike in E3M1, where this could only be encountered by loading the v1.2 registered IWAD into one of the beta engines, the erroneous sector tag in this level was not corrected until v1.9."

Fair enough, in this case I will be closing the issue as it's not actually a Chocolate-related bug.
