### ISSUE TITLE
Native MIDI still crashing on OS X?

### ISSUE THREAD

**Issue by chocolate-import** [chocolate-doom/chocolate-doom#122]
> The following bug was [originally reported](https://sourceforge.net/p/chocolate-doom/bugs/122/) on Sourceforge by [xttl](https://sourceforge.net/u/xttl/profile/), 2011-01-06 21:52:08:

I was playing some Ultimate Doom coop and the game crashed on my computer after exiting E2M2. After this first crash I added -nomusic to my command line and had no problems thereafter (we played through the whole episode). The stack trace (attached) also seems to point to a crash inside audio-related / SDL_mixer code, which leads me to question whether what is said on the Chocolate Doom wiki's FAQ page is correct (which is that music does not loop in OS X but enabling it shouldn't cause crashes anymore).

I am using the official 1.5.0 binary package without any modifications and started the game via the launcher so I think the chance that I just did something wrong myself is pretty slim. ;-)

**Comment by fragglet** [comment]
Looks like we haven't heard anything about this bug since it was filed in 2011, and nobody else has reporting anything similar. Will probably be obsolete with the SDL2 migration.
