### ISSUE TITLE
GUS emulation not working with active Midiproc

### ISSUE THREAD

**Issue by JNechaevsky** [chocolate-doom/chocolate-doom#1244]
### Background

Version of Chocolate Doom: 3.0.0 and latest dev builds

Operating System and version: Windows 10

Game: all supported

Any loaded WADs and mods (please include full command line): -

### Bug description

I've got a bug report for RD regarding GUS music synth, but it's a Chocolate Doom bug in fact.

Observed behavior: when `midiproc.exe` is running, GUS emulation is not working. Instead, standard Windows MIDI is playing. If user will remove or rename `midiproc.exe`, GUS will play normally (after loading necessary patches, of course).

Expected behavior: should GUS work properly with existing `midiproc`?

**Comment by JNechaevsky** [comment]
This can be used as a small and quick workaround: https://github.com/JNechaevsky/russian-doom/commit/1739486e7ea1928f2f0cfb4f88f5e48eaea8f445

**Comment by JNechaevsky** [comment]
Uh.. Gentlemen? @fabiangreffrath, @AlexMax ?
Should we discuss something, or should we just use `if (snd_musicdevice != SNDDEVICE_GUS)` as a simplest solution?

**Comment by AlexMax** [comment]
midiproc should only be involved for instances where it is the only option for controlling the volume of the music, which is, as far as I know, only when using the built-in Windows MIDI player to play MIDI files.  In instances where sound and music volume work fine without it, then midiproc should be bypassed by whatever means necessary.

So yeah, as long as your solution properly bypasses midiproc in an instance when it's not needed and still uses it when it is, then I'm okay with it.

**Comment by JNechaevsky** [comment]
Okay, thanks! The only thing left: what comment should I leave in the code? I mean, how it should be properly written in English, so everyone can understand it.

**Comment by AlexMax** [comment]
Your comment's English was OK, but the problem is that it just restates what the code does without going into "why?".  I would write something along the lines of:

```
Don't enable it for GUS, since it handles its own volume just fine.
```

Also, I would make sure your if statement adheres to the coding standard of the port - from what I can see, there's no indentation between the `if` and the statement below it.
