### ISSUE TITLE
Joystick input broken in SDL2 since 2.0.9?

### ISSUE THREAD

**Issue by drfrag666** [chocolate-doom/chocolate-doom#1247]
### Background

Version of Chocolate Doom: latest master

Operating System and version: Win 10 1803 64 bit

Game: (Doom/Heretic/Hexen/Strife/other) All

Any loaded WADs and mods (please include full command line):

### Bug description

Observed behavior: Joysticks are not detected in setup

Expected behavior: They work?

Several dinput gamepads, they work replacing SDL2.dll with an older version but the game doesn't run becouse it's compiled with a different dll. Crispy 5.5.2 with 2.0.5 worked but 5.6 didn't.
 I'm still on 1803, are joysticks detected on later versions?

**Comment by drfrag666** [comment]
I've compiled with 2.0.8 and runs fine, seems the addition of the HIDAPI joystick drivers broke them.

**Comment by stevensmedia** [comment]
I'm seeing similar behavior. I just installed Chocolate Doom 3.0.1 on my new GPD Win Max, which has built-in a "Controller (XBox 360 Controller) which registers perfectly in JoyTest.

I'm in Windows 10 Pro Version 2004, OS Build 19041.450

The controller, which works fine in other apps, simply does not show in the Chocolate Doom set up.

I rolled back to Chocolate Doom 3.0.0 and it worked.

**Comment by drfrag666** [comment]
It's fixed in 2.0.12 but controllers still don't work on win due to this other issue with chocpkg:
https://github.com/chocolate-doom/chocpkg/issues/21
