### ISSUE TITLE
New warning on GCC 10

### ISSUE THREAD

**Issue by turol** [chocolate-doom/chocolate-doom#1249]
Version of Chocolate Doom: git master a8e8763cba49db50e4a9dc7198c6e4b6dcfbcbfe

Observed behavior: New warning on GCC 10  (not yet released but frozen so warnings should not change)
```
chocolate-doom/src/heretic/mn_menu.c: In function ‘MN_Responder’:
chocolate-doom/src/heretic/mn_menu.c:1529:29: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
 1529 |                 *textBuffer = ASCII_CURSOR;
      |                             ^
chocolate-doom/src/heretic/mn_menu.c:145:13: note: at offset -1 to object ‘SlotText’ with size 108 declared here
  145 | static char SlotText[6][SLOTTEXTLEN + 2];

```
https://github.com/chocolate-doom/chocolate-doom/blob/a8e8763cba49db50e4a9dc7198c6e4b6dcfbcbfe/src/heretic/mn_menu.c#L1529
False positive or a real error? How do we shut it up?

Also the same warning on hexen https://github.com/chocolate-doom/chocolate-doom/blob/a8e8763cba49db50e4a9dc7198c6e4b6dcfbcbfe/src/hexen/mn_menu.c#L1663

**Comment by turol** [comment]
GCC 10.1 has been officially released and this warning is still there.

**Comment by fabiangreffrath** [comment]
It seems to believe that `slotptr` can take negative values. Could you test if checking for `if (slotptr > 0)` in the condition above helps?

**Comment by turol** [comment]
It does not.

**Comment by fabiangreffrath** [comment]
This is absolutely puzzling to me.

**Comment by MistUnky** [comment]
It's likely a false positive, as something similar is being reported here:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=92955

**Comment by turol** [comment]
I don't think that's the issue, this warning happens even with loop unrolling disabled.
