### ISSUE TITLE
Error messages related to visplanes

### ISSUE THREAD

**Issue by chocolate-import** [chocolate-doom/chocolate-doom#125]
> The following bug was [originally reported](https://sourceforge.net/p/chocolate-doom/bugs/125/) on Sourceforge by [axdoom](https://sourceforge.net/u/axdoom/profile/), 2011-01-23 05:50:02:

Bugs related to visplane and error messages

1- If recording a demo with vanilla doom and that there's an error, the demo is not saved. Chocolate Doom save it sometimes. 
2- Chocolate Doom sometimes crash without an error message and stderr.txt is empty. But if you play a demo recorded demo, the error message is always show.
3- Sometimes, their's an other error message in stderr.txt that I don't know why it's their.
4- Chocolate Doom always crash with a "no more visplanes" or a "visplane overflow (129) error. The "visplane overflow (###)" in vanilla doom sometimes crash with higher value e.g. "visplane overflow (132)"

Look in the attached zip file for the Wad file used to test this, a demo that I been able to record with chocolate doom and stderr.txt with a warning message.

-demo.lmp: It was saved after I tried five times with chocolate-doom (Not suppposed to save the demo when their's an error). Vanilla didn't want to save a demo, I tried around 20 times. (Vanilla won't save a demo if their an error)
-Conduits.wad: I found this wad on the internet a long time ago. I found all these bugs with this wad.
-stderr.txt: Their's a warning that I don't know what it means. I think it happen when I tried to record a demo and the game crashed without an error message.

**Comment by AXDOOMER** [comment]
@fragglet  Please close because of https://github.com/chocolate-doom/chocolate-doom/commit/fbb2fa82c536671ce3d6518dabc8a5f6601dc612, error messages will for VPO will never be the same as vanilla.

**Comment by fragglet** [comment]
Thanks.
