### ISSUE TITLE
Chocolate Doom 3 crashing in Windows XP out of nowhere

### ISSUE THREAD

**Issue by POWERUPT** [chocolate-doom/chocolate-doom#1252]
### Background

Version of Chocolate Doom: 3.0.0

Operating System and version: Windows XP Home Version 2002 Service Pack 3

Game: Ultimate Doom and Doom 2

Any loaded WADs and mods (please include full command line): none

### Bug description

I tried Chocolate Doom on my Windows XP computer, which I use for retro games, yesterday for the first time, and everything ran flawlessly. Today, I turned it on, and it started crashing before even getting to the title screen.

Observed behavior:

* Menu music starts before crash occurs, so it plays once when the crash message box on a black screen is displayed.
* I looked into the error report, and the mod name was sdl2.dll. There was an offset of 0x000baee0.
* I would add a log file, but it seems that they are deleted when I exit. The filename always end in "_appcompat", so it could be an sdl2 issue with XP.
* I loaded Doom 2 with the same results.
* I replaced the wad with the one from the cd again, and it was fine. After a reboot, it proceeded to crash again.
* I did a fresh install of chocolate doom, and it now won't stop crashing, even after replacing the wad.

Expected behavior: Being able to play the game for more than one day.

Thanks!

**Comment by fragglet** [comment]
Do you find earlier (pre-3.0) versions are more stable? 2.x and earlier used SDL 1 rather than SDL 2, and I do suspect it may be an SDL2 / Windows XP compatibility issue.

**Comment by POWERUPT** [comment]
fragglet, I started using 2.3.0 with no issues. I'm sorry that I didn't update my issue! It seems to work perfectly fine, so I'll close the issue. If anyone should stumble upon this post, use 2.3.0 on Windows XP. Thanks!

**Comment by drfrag666** [comment]
I thought SDL2 still ran on XP. Have you tried the latest RUDE pre-release? And what about Crispy Doom?

**Comment by chungy** [comment]
> I thought SDL2 still ran on XP

In general, it's supposed to, but it's doubtful it gets much (if any) testing. Chocolate Doom is included in that.
