### ISSUE TITLE
Wrong music being played on Final Doom TNT Evilution MAP25

### ISSUE THREAD

**Issue by DavideCanno** [chocolate-doom/chocolate-doom#1269]
### Background

Version of Chocolate Doom:3.0.0

Operating System and version: Windows 10 1909

Game: (Doom/Heretic/Hexen/Strife/other) Final Doom: TNT Evilution

Any loaded WADs and mods (please include full command line):
None
### Bug description

Observed behavior: Playing a different music in MAP25, Baron's Den. It plays the MAP13's Doom II music

Expected behavior: Playing the correct one (d_ampie, damn is d_adrian sorry again)

**Comment by AXDOOMER** [comment]
You're talking about MAP23 in the title of this issue, but you're talking about MAP25 in the observed behavior section of your report. 

Which map is it? Can you clarify?

**Comment by AXDOOMER** [comment]
I can't confirm the issue on a build of the latest version on Linux. MAP23 plays the correct music (Doom II's MAP23 music) and MAP25 also plays the correct music (Doom II's MAP13 music). 

Maybe a midiproc.exe bug on Windows?

**Comment by DavideCanno** [comment]
> You're talking about MAP23 in the title of this issue, but you're talking about MAP25 in the observed behavior section of your report.
> 
> Which map is it? Can you clarify?

My bad. Im not very practical with issue reports forum. Sorry!

**Comment by AXDOOMER** [comment]
I couldn't reproduce the issue. Can you check if you are able to reproduce the bug using both "Native MIDI" or "OPL (Adlib/Soundblaster)" ?

You can change the music settings in "Configure Sound" in Chocolate-Setup.

**Comment by DavideCanno** [comment]
> I couldn't reproduce the issue. Can you check if you are able to reproduce the bug using both "Native MIDI" or "OPL (Adlib/Soundblaster)" ?
> 
> You can change the music settings in "Configure Sound" in Chocolate-Setup.

oh and I forgot that I use music pack, ooops 😓😓

**Comment by AXDOOMER** [comment]
It's alright. Out of curiosity, what is the music pack that you are using?

**Comment by DavideCanno** [comment]
> It's alright. Out of curiosity, what is the music pack that you are using?

I use the sc55.duke4.net's game pack. I use the .ogg one

**Comment by AXDOOMER** [comment]
Looks like `D_ADRIAN` is wrong in `tntevilution_sc55_ogg_raw.zip`. It's the music from Doom II's Bloodfalls MAP25.

**Comment by AXDOOMER** [comment]
I'll contact the author of the music pack to let him know about that. 

@DavideCanno  You can use the "boosted" version of the music pack instead of the "raw". It doesn't have the issue. 

Thank you for your bug report.

**Comment by DavideCanno** [comment]
> I'll contact the author of the music pack to let him know about that.
> 
> @DavideCanno You can use the "boosted" version of the music pack instead of the "raw" one. It doesn't have the issue.
> 
> Thank you for your bug report.

Ok thanks for the suggestion and the support, bye!

**Comment by DavideCanno** [comment]
I downloaded the "boosted" pack as you suggested me, but it continues to play wrong, the music is the same as you play it on Windows, but in-game doesn't play correctly

**Comment by DavideCanno** [comment]
I downloaded it and extracted it but it does the same problem

**Comment by AXDOOMER** [comment]
Can you upload your `*-music.cfg` file?

**Comment by DavideCanno** [comment]
> Can you upload your `*-music.cfg` file?

yes

> Can you upload your `*-music.cfg` file?
yes https://drive.google.com/file/d/1nWdI7j5_McvWCZmtPvB9M9zzCg7nxyjz/view?usp=drivesdk
`

**Comment by AXDOOMER** [comment]
Try replacing the SHA1 checksum `9490efededf697f4bf4b140d6d0bf0a8146794ed` with `be761175dba137b9fd578213ba5d28ee3fa5b8ee` for the file `d_adrian.ogg`. 

Make sure you extracted the right music pack, I made this mistake myself. Also try playing `d_adrian.ogg` in you media player to see if it's right. You should also notice that the boosted tracks are louder than the raw ones.

**Comment by DavideCanno** [comment]
> Try replacing the SHA1 checksum `9490efededf697f4bf4b140d6d0bf0a8146794ed` with `be761175dba137b9fd578213ba5d28ee3fa5b8ee` for the file `d_adrian.ogg`.
> 
> Make sure you extracted the right music pack, I made this mistake myself. Also try playing `d_adrian.ogg` in you media player to see if it's right. You should also notice that the boosted tracks are louder than the raw ones.

I tried but again, same problem

**Comment by AXDOOMER** [comment]
Weird problem. I can't help you further, I am unable to get the music pack working on my computer.

**Comment by DavideCanno** [comment]
> Weird problem. I can't help you further, I am unable to get the music pack working on my computer.

no problem, it's ok. Thanks for the help though.

**Comment by AXDOOMER** [comment]
You could try posting [in the Doomworld thread](https://www.doomworld.com/forum/topic/86366-chocolate-doom/), there are more people that could help you there.

**Comment by DavideCanno** [comment]
Ah ok thanks

> You could try posting [in the Doomworld thread](https://www.doomworld.com/forum/topic/86366-chocolate-doom/), there are more people that could help you there.

**Comment by DavideCanno** [comment]
Hello, if you see this I sorta fixed the problem. What I did is I renamed the files, I have the .mp3 version "raw", and I saw duplicates of Sadistic (MAP01) and of the incriminated d_adrian. I hope it helps to you. Bye and thanks again for the support!
