### ISSUE TITLE
Running chocolate-doom on docker container

### ISSUE THREAD

**Issue by n-jay** [chocolate-doom/chocolate-doom#1270]
### Background

Version of Chocolate Doom: 3.0.0

Operating System and version: Ubuntu 18.04 (running on docker 19.03.8)
The base image was pulled from [here](https://hub.docker.com/r/dorowu/ubuntu-desktop-lxde-vnc/) The particular image was chosen as it serves an Ubuntu 18.04 LXDE desktop environment via a VNC interface which can be accessed from the browser.

Game: Doom

### Bug description

Observed behavior: Running `./doom` or `./chocolate-doom` initially resulted in a warning requesting the _force-sofware-renderer_ to be activated. Upon activating that, the commands now result in a `Segmentation fault (core dumped)` error.

Expected behavior: The game to be launched as intended.

**Comment by mfrancis95** [comment]
@n-jay did you make a Dockerfile that you can share here?

**Comment by n-jay** [comment]
@mfrancis95, No, I did not. 
Atm, I've put this aspect of the project on ice and started working on a different component (which does include a Dockerfile). Once that component overlaps with this, I'll be sure to share the file here.

**Comment by mfrancis95** [comment]
@n-jay well in any case I played around in the base image you mentioned, built Choco on it, ran it and I didn't get any warning about requesting force_software_renderer to be activated. So, I haven't been able to reproduce it.

**Comment by n-jay** [comment]
Noted @mfrancis95.
Will recheck and update here.

Closing the issue now as it seems to be working.
