### ISSUE TITLE
Incorrect warning to enable force_software_renderer 

### ISSUE THREAD

**Issue by ETTiNGRiNDER** [chocolate-doom/chocolate-doom#1275]
# Background

Version of Chocolate Doom: 3.0.0 (self compiled)

Operating System and version: MX Linux 19.1

Game: All? (Applied for Doom, Heretic, Hexen. Did not check Strife. -timedemo tests done with Doom 2 only.)

Any loaded WADs and mods (please include full command line): None (-timedemo parameter used for testing)

### Bug description

When running Chocolate Doom on GNU/Linux systems using FLOSS video drivers, the following message appears in the output:

> WARNING: it looks like you are using a software GL implementation.
> To improve performance, try setting force_software_renderer in your
> configuration file.

For both an ATI/Radeon based system and an Nvidia based one, this recommendation turns out to be incorrect and force_software_renderer results in worse performance.  Here are -timedemo results for the three default demos in DOOM2.WAD:

**ATI / Radeon based system:**

Chocolate Doom 2 -timedemo with _force_software_renderer 0_

demo1 - timed 1205 gametics in 182 realtics (231.730774 fps)
demo2 - timed 2001 gametics in 271 realtics (258.431732 fps)
demo3 - timed 4471 gametics in 557 realtics (280.942535 fps)

Chocolate Doom 2 -timedemo with _force_software_renderer 1_

demo1 - timed 1205 gametics in 320 realtics (131.796875 fps)
demo2 - timed 2001 gametics in 497 realtics (140.915497 fps)
demo3 - timed 4471 gametics in 1067 realtics (146.658859 fps)

**Nvidia / Nouveau based system:**

Chocolate Doom 2 -timedemo with _force_software_renderer 0_

demo1 - timed 1205 gametics in 765 realtics (55.130718 fps)
demo2 - timed 2001 gametics in 1243 realtics (56.343525 fps)
demo3 - timed 4471 gametics in 2737 realtics (57.173912 fps)

Chocolate Doom 2 -timedemo with _force_software_renderer 1_

demo1 - timed 1205 gametics in 864 realtics (48.813656 fps)
demo2 - timed 2001 gametics in 1416 realtics (49.459747 fps)
demo3 - timed 4471 gametics in 3072 realtics (50.939129 fps)

Let's not get too sidetracked by the discrepancy in performance between the two machines, which is beside the point that _force_software_renderer 1_ performs worse on both of them.

While the quality of the drivers might be debatable I highly doubt that either of these systems are failing to do any sort of hardware acceleration since it's possible to run Sauerbraten and other (comparatively) "modern" things with them, so I suspect whatever auto detection is being done is doing something wrong.

Attached are full outputs of the glxinfo command for both systems:

[glxinfo-report-radeon.txt](https://github.com/chocolate-doom/chocolate-doom/files/4547143/glxinfo-report-radeon.txt)
[glxinfo-report-nvidia.txt](https://github.com/chocolate-doom/chocolate-doom/files/4547142/glxinfo-report-nvidia.txt)

**Comment by chungy** [comment]
This was already fixed in 3656db42047ce9e99a2aa984d54650b7cf54073f -- though there hasn't been a new release of Chocolate Doom yet since 3.0.0.
