### ISSUE TITLE
Cursor get stuck

### ISSUE THREAD

**Issue by chocolate-import** [chocolate-doom/chocolate-doom#128]
> The following bug was [originally reported](https://sourceforge.net/p/chocolate-doom/bugs/128/) on Sourceforge by [axdoom](https://sourceforge.net/u/axdoom/profile/), 2011-01-27 20:28:35:

The cursor can get stuck on the upper left of the screen. It rarely happen. 
You can't control your mouse because the cursor will always come back to the upper left.
How to get this happen (exemple with Microsoft Office): Start Chocolate-Doom and start Microsoft Word. Chocolate-Doom will start before Word and when Word will have finish loading, Chocolate-Doom will be interupted and will minimise in the TaskBar and the computer will activate Word's window.
You can use your keyboard only. To make the mouse stop always going to the upper left, you need to end Chocolate-Doom. 
Use: Ctrl-alt-delete and stop Chocolate-Doom using program menager.

**Comment by AXDOOMER** [comment]
This is a bug that does happen in Windows 7.

**Comment by chungy** [comment]
OK. Sorry I didn't post messages on GitHub, but I closed all the Win9x bugs on the basis that they're basically not going to get fixed, being a long-obsolete OS and all. If this still affects current Windows, then yeah, keep it open. :)

**Comment by fx02** [comment]
Think this issues will be fixed with sdl2.

**Comment by jmtd** [comment]
@AXDOOMER , I've put up a dev build of sdl2-branch here http://jmtd.net/tmp/chocolate-doom-sdl2-branch-win32-dbg.zip

Could you please let me know whether you still have this problem, and if sdl2-branch fixes it?

**Comment by AXDOOMER** [comment]
I don't play often enough on Windows. Don't expect me to report if it is fixed or not soon.

**Comment by CapnClever** [comment]
I tried the following batch file to guarantee that a program (in this case, Notepad) would interrupt fullscreen Chocolate Doom:

```
cd [path-to-chocolate-doom]
start "" chocolate-doom.exe -record test
timeout /t 5 /nobreak
start "" notepad.exe
```
Cursor didn't stick in Win7 64-bit. Can't say anything about WinXP, though.

**Comment by AXDOOMER** [comment]
When SDL2 will become the main release, I'll be using it to play and I will report if it is fixed or not. It happened two weeks ago when I started Chocolate-Doom (SDL 1.2), so it's not fixed on this release.

**Comment by fragglet** [comment]
Given that this is from 2011, let's assume that sdl2-branch will fix this. If it's still a problem we can reopen.
