### ISSUE TITLE
Plutonia 2 and possible OPL problem (win32-r2239)

### ISSUE THREAD

**Issue by chocolate-import** [chocolate-doom/chocolate-doom#129]
> The following bug was [originally reported](https://sourceforge.net/p/chocolate-doom/bugs/129/) on Sourceforge by [porschemonty](https://sourceforge.net/u/porschemonty/profile/), 2011-01-27 23:54:43:

I just noticed there's a big difference between the way Chocolate Doom and ZDoom handle the music for Plutonia 2's map01 in OPL mode. In Chocolate, certain notes die off much quicker, but they "seem" to play back wholly (normally?) in ZDoom. Unfortunately I can't test this on my 486 right now, thus I'm not a 100% certain which way this song's supposed to sound.

Be sure to load PL2.DEH in case you need to test it, otherwise the correct song won't play.

Regards.

**Comment by fragglet** [comment]
OPL code has changed a lot since 2013. Let's assume this is no longer the case, or at least it should match vanilla.
