### ISSUE TITLE
Request: use_artifact bindable to a mouse button (Heretic/Hexen)

### ISSUE THREAD

**Issue by unerxai** [chocolate-doom/chocolate-doom#1302]
Hi,

My request is to add the "use_artifact" function to the "mouse controls" menu in the Heretic and Hexen setup program (maybe Strife too?). 

Chocolate allows to select artifacts with the mousewheel so it would make sense to also use a mouse button to use the selected artifact.

Keep up the good work! (I hope I have better luck this time)

**Comment by turol** [comment]
Has this been fixed by #1459?
