### ISSUE TITLE
Fullscreen doesn't work in Manjaro XFCE

### ISSUE THREAD

**Issue by rohit-n** [chocolate-doom/chocolate-doom#1314]
### Background

Version of Chocolate Doom: git f700744969ac867649aa581ae19447a4c172179e

Operating System and version: Manjaro Linux XFCE

Game: Doom 2

### Bug description

Observed behavior:
When launching Chocolate Doom with fullscreen from the terminal, the screen will flicker, hide the XFCE task bar at the bottom, then bring it back. The game is never visible, and does not appear when I alt-tab, so I am forced to terminate the process. Sometimes, the task bar never comes back, and all of my windows are missing their minimize/maximize/exit buttons. The terminal is unresponsive to any more inputs, and I am unable to create another one, forcing me to hard reset my machine. Only rarely (around 5% of the time) does the game actually appear fullscreen.

Expected behavior:
Launching the game when the user specifies fullscreen should work 100% of the time.

**Comment by fabiangreffrath** [comment]
I can confirm it works fine with Gnome Shell on Debian, so the cause may be something odd on your side.

**Comment by rohit-n** [comment]
I can confirm it works fine on my laptop which also uses Manjaro with XFCE. Not sure why it's happening on my desktop. Maybe because it's using Nvidia drivers?

**Comment by Clownacy** [comment]
I'm having the same issue, except it's Arch Linux with AMD drivers, so I don't think it's an Nvidia thing.

**Comment by rohit-n** [comment]
I did some printf debugging, and it looks like the the game never gets past the first SDL_CreateRenderer call in i_video.c when this issue happens. In windowed mode, the call goes through fine and SetVideoMode proceeds normally.

**Comment by rohit-n** [comment]
I tested a modifed Duke3D source port that renders in a similar way to Chocolate Doom (software rendering to an SDL_Texture displayed with a SDL_Renderer) and I'm getting the same issue. I'm closing this issue and will look into filing a bug with SDL2.
