### ISSUE TITLE
[Duplicate] Feature suggestion: "use inventory" bindable to mouse button in Heretic, Hexen and Strife

### ISSUE THREAD

**Issue by hfc2x** [chocolate-doom/chocolate-doom#1319]
As suggested by @fabiangreffrath [here](https://github.com/JNechaevsky/russian-doom/issues/121#issuecomment-497964517), adding this feature suggestion in this repository as well.

Like it says in the title, it could be a useful option to let the player use (and maybe also cycle) the inventory with the mouse.

EDIT: Sorry, duplicate of #1302

**Comment by fabiangreffrath** [comment]
Why was this closed without any comment?

**Comment by fragglet** [comment]
Dupe of #350?

**Comment by chungy** [comment]
> Why was this closed without any comment?

hfc2x himself showed it was a duplicate. I didn't believe further elaboration was necessary.

**Comment by fabiangreffrath** [comment]
Oh, I haven't seen the initial message got edited. Now it's pretty clear, sure.
