### ISSUE TITLE
sometimes cant connect to network game

### ISSUE THREAD

**Issue by Mitschmaster** [chocolate-doom/chocolate-doom#1324]
### Background

Version of Chocolate Doom:
chocolate doom 3.0.1
but also marschmallow doom 0.78

Operating System and version:
windows 10

Game: (Doom/Heretic/Hexen/Strife/other)
doom and doom 2

Any loaded WADs and mods (please include full command line):
just doom.wad or doom2.wad

### Bug description

Observed behavior:
when i start a lan game sometimes my brother cant join. on his side the game says "waiting for game start". if waiting long enough it says "lost connection to server" on my computer he just does not appear in the list of players.
when i use marshmallow doom the things are the same except i can see a message "Client 'endlessorange' timed out and disconnected" in the console window, as soon as my brother connects.
my brother can find me in the list of games.
our workaround is to just start the server again. on 2nd or 3rd try it works.

Expected behavior:

player can joinn server on 1st try

**Comment by fragglet** [comment]
Thanks, this bug has been fixed. Please use a daily build from http://latest.chocolate-doom.org/ or build from Git HEAD
