### ISSUE TITLE
PC-98 YM2608 emulation alongside PC-98 WAD support   

### ISSUE THREAD

**Issue by arivega** [chocolate-doom/chocolate-doom#1325]
https://www.youtube.com/watch?v=Fj0-KvV0SC0 This video demonstrates PC-98 DOOM and I wondered if this version should be supported as most of the core game is the same except for the messages and the music although other music chips could be used. Could the YM2608 be supported as an option in the setup menu and could a language option be added?

**Comment by fragglet** [comment]
I'm going to say that this is out of scope for the project, at least at the moment. The language changes seem too intrusive to support. I think this would make more sense as a fork (like Russian Doom) or maybe this could even be reimplemented as a dehacked patch.

It's interesting to learn about new and obscure ports though - I hadn't seen this one before. Thanks for sharing and the suggestion.
