### ISSUE TITLE
libretro port? :)

### ISSUE THREAD

**Issue by DartPower** [chocolate-doom/chocolate-doom#1332]
Hi there, i have a idea, you want to port to libretro?
This is will be cool, really :)

Check this also please :)
https://www.libretro.com/index.php/mission/
https://docs.libretro.com/development/cores/developing-cores/
https://www.libretro.com/index.php/powered-by-libretro/
https://docs.libretro.com/development/cores/opengl-cores/

**Comment by fragglet** [comment]
No, see previous response to #563.
