### ISSUE TITLE
Install/build sdl1 version

### ISSUE THREAD

**Issue by symbios24** [chocolate-doom/chocolate-doom#1333]
Hello,im trying to build/install chocolate doom on raspbian stretch but since chocolate doom requires the latest sdl2- image library to build that is not available from the stretch repository,its failing to compile.
How can i install/compile the older branch version that uses sdl1 ?

For example:
git clone https://github.com/chocolate-doom/chocolate-doom/tree/chocolate-doom-2.x.git

Thanks

**Comment by symbios24** [comment]
I found a builded version about a month old but when i ran the rednukem i get a libm.so.6 / libc.so.6 Glibc_2.27 / Glibc_2.28 not found error
What librariea are missing here to install them??

**Comment by fabiangreffrath** [comment]
Sorry, but this is not a tutorial site. the last version still using SDL1.2 was 2.3.0, which you may get from here:
https://github.com/chocolate-doom/chocolate-doom/releases/tag/chocolate-doom-2.3.0

You'll need the SDL, SDL_Mixer and SDL_Net libraries and a proper build environment, of course.
