### ISSUE TITLE
Alien Vendetta map 20 crash

### ISSUE THREAD

**Issue by JuanchoES** [chocolate-doom/chocolate-doom#1335]
Version of Chocolate Doom: chocolate-doom-20201218-win32

Operating System and version: Windows 10 PRO 64bits version 20H2

Game: (Doom/Heretic/Hexen/Strife/other) Doom

Any loaded WADs and mods (please include full command line): AV.WAD

### Bug description The game crashes when you go to this area, 
![image](https://user-images.githubusercontent.com/70743149/102586009-aa251480-4109-11eb-8329-4bb49ddc82ef.png)
![image](https://user-images.githubusercontent.com/70743149/102586059-be691180-4109-11eb-8845-a2e465363c67.png)

Observed behavior: it crash

Expected behavior: no crash

**Comment by fabiangreffrath** [comment]
The visplane overflow is one of the most notorious limitations of the original vanilla Doom engine, that Chocolate Doom faithfully preserves here.

https://doomwiki.org/wiki/Visplane_overflow
