### ISSUE TITLE
demoname is too short in heretic/hexen

### ISSUE THREAD

**Issue by bond-ea** [chocolate-doom/chocolate-doom#1340]
### Background

Version of Chocolate Doom: current

Operating System and version: any

Game: Heretic/Hexen

Any loaded WADs and mods (please include full command line):

### Bug description 

Observed behavior: demoname is too short in heretic/hexen (32 bytes)

Expected behavior: pls make it like in doom (as given on the command line)

**Comment by fabiangreffrath** [comment]
This is already fixed in Heretic

https://github.com/chocolate-doom/chocolate-doom/commit/6a14787a8a25bf37aacecbd7c42e69ed35e7ad09

and Hexen

https://github.com/chocolate-doom/chocolate-doom/commit/df1837c1210b85ebc4ec84e42b5edb2001c66463
