### ISSUE TITLE
There are no monsters. 

### ISSUE THREAD

**Issue by kringlefant** [chocolate-doom/chocolate-doom#1341]
There are no enemies when I try to play the game.

**Comment by chungy** [comment]
A lot more information is required. What game are you trying to play? What kind of WAD file are you loading? Did you somehow set "-nomonsters" or uncheck "Monsters Enabled" in the warp menu in Setup?

**Comment by kringlefant** [comment]
I simply installed this: https://community.linuxmint.com/software/view/chocolate-doom
I ran it without doing any modifications. Every level is without any enemies.

**Comment by chungy** [comment]
Did it load FreeDM by chance? That IWAD doesn't have any monsters placed in any of its levels.

You'll probably want to run either Freedoom Phase 1 or 2 (especially the latest version, 0.12.1, which should be totally vanilla-compatible), or buy and load the Doom games. Instructions for the latter can be found here: https://doomwiki.org/wiki/How_to_download_and_run_Doom

**Comment by fabiangreffrath** [comment]
Most probably FreeDM. The Mint package is based on the Debian package which pulls in the freedm package by a "Recommends" relation.

**Comment by Catoptromancy** [comment]
The .desktop file from Debians 2.3.0 install does not mention iwad selection. Chocolate-doom must be defaulting to making freedm a priority when launched without any additional commands.

**Comment by Catoptromancy** [comment]
https://packages.debian.org/sid/chocolate-doom
Chocolate requires freedm. 

People need to manually add and know freedoom exists.

**Comment by fragglet** [comment]
> Chocolate-doom must be defaulting to making freedm a priority when launched without any additional commands.

This is the case in the latest release (3.0.1) but in commit 7d724dd54afc703002d2141d3b46fd53ad873087 the order was changed to prefer the single-player Freedoom IWADs over FreeDM. So I think this bug has already been fixed.

**Comment by fabiangreffrath** [comment]
> Chocolate package needs updated. 

This will be fixed with the next package upload:

https://salsa.debian.org/games-team/chocolate-doom/-/commit/405db22cf1548366a8e560bfa658f88e4774d7cd
