### ISSUE TITLE
"God mode health" DEHACKED parameter support not implemented correctly

### ISSUE THREAD

**Issue by maxmanium** [chocolate-doom/chocolate-doom#1345]
### Background

Version of Chocolate Doom: 3.0.1

Operating System and version: Windows 10, 19041.746

Game: Doom

Any loaded WADs and mods (please include full command line): chocolate-doom -deh godhp.deh (attached)

### Bug description

Observed behavior: Enable and then disable IDDQD. With "god mode health" set to 200, player mobj still dies after losing 100% health.

Expected behavior: Player health + player mobj health both set to 200, and acts as such.

[GODHP.zip](https://github.com/chocolate-doom/chocolate-doom/files/5826829/GODHP.zip)

**Comment by tpoppins** [comment]
Looks like an oversight in st_stuff.c:

```diff
--- src/doom/st_stuff.c	(revision 5690)
+++ src/doom/st_stuff.c	(working copy)
@@ -478,7 +478,7 @@
 	if (plyr->cheats & CF_GODMODE)
 	{
 	  if (plyr->mo)
-	    plyr->mo->health = 100;
+	    plyr->mo->health = deh_god_mode_health;
 	  
 	  plyr->health = deh_god_mode_health;
 	  plyr->message = DEH_String(STSTR_DQDON);
```

A single line change and it works like in vanilla v1.9 (tested with DHE 3.1).

**Comment by fabiangreffrath** [comment]
Great! Would you file a PR, please?
