### ISSUE TITLE
Server provides too little information about its settings and state

### ISSUE THREAD

**Issue by bond-ea** [chocolate-doom/chocolate-doom#1347]
### Background

Version of Chocolate Doom: any

Operating System and version: any

Game: any

Any loaded WADs and mods (please include full command line): any

### Bug description
Well, not a bug, but a request for missing functions.
I suggest making the program more "launcher-friendly" so that players can see more server settings in the launcher.
To do this, you can add an additional function of responding to launcher requests, for example:

Query: 
 - LAUNCHER_QUERY - some suitable constant
 - launcher_time - 4-byte integer value to be sent back to the launcher (for ping calculation)

Response: 
 - LAUNCHER_QUERY_RESPONSE - some suitable constant
 - launcher_time - value from query

 - protocol - ? (not sure if this is necessary, but maybe in future updates it can be used ?)
 - version
 - server name
 - numplayers - number of connected players

if( numplayers > 0 ) 
   - server_state (as defined in src)
   - iwad
   - iwad checksum (md5)
   - wadnumb - number of pwads (including deh)
   - for each pwad 
     - pwad name
     - pwad checksum (md5)
   (checksums of wads are optional but can help find and load the correct wads)

   - mapname (map01, e1m1 ...)
   - gametype (coop, dm ...)
   - skill
   - monsters (fast, respawn, no)
   - maxplayers
   - maxtime (0 - if none)

For all connected players - player stats:
   - name
   - ping
   - frags
   - death 

Sorry if i put this in inproper place - not sure where to ask it

**Comment by fragglet** [comment]
Sorry, this is too vague. I'm not sure what it even is that you're proposing. Please feel free to reopen with a better description of what it is you'd like to see. By "launcher" do you mean the setup tool? Assuming so, what do you think's missing from the current interface?
