### ISSUE TITLE
[REQUEST] Start Chocolate Doom in base directory, not execution directory

### ISSUE THREAD

**Issue by snoggie1487** [chocolate-doom/chocolate-doom#1351]
If I set .wad files to open in Chocolate Doom and double click one, it launches the game with default settings. I found Chocolate Doom config files in the directory where I stored the WADs, indicating that it tried to start Chocolate Doom as if the .exe was there. Most other source ports always execute in their install directory, allowing settings to be preserved. It would be really nice if this feature could make it's way to Chocolate Doom, so that people like me can simply double-click a PWAD anywhere and have it work.

Thank you for taking the time to read this, have a good day

**Comment by fabiangreffrath** [comment]
Looks like this would be the only required change:
```patch
--- a/src/m_config.c
+++ b/src/m_config.c
@@ -2291,7 +2291,7 @@ static char *GetDefaultConfigDir(void)
         return copy;
     }
 #endif /* #ifndef _WIN32 */
-    return M_StringDuplicate("");
+    return M_DirName(myargv[0]);
 }

 //

````
