### ISSUE TITLE
Config save path still wrong on Windoze

### ISSUE THREAD

**Issue by tpoppins** [chocolate-doom/chocolate-doom#1359]
Affected: daily builds since at least March 10 (following commit [a378d02](https://github.com/chocolate-doom/chocolate-doom/commit/a378d0288a77ef8efff439c5e250e82b03e2c502)). Tested on Win 7 x64 Pro.

Extracted the daily build as usual to **C:\DOOM\choco\test**
The config files are saved as **C:\DOOM\choco\test**default.cfg and **C:\DOOM\choco\test**chocolate-doom.cfg. That's right, into the parent dir, not the exec dir - still missing a delimiter?

```
                         Chocolate Doom 3.0.0
Z_Init: Init zone memory allocation daemon.
zone memory: 01F90020, 1000000 allocated for zone
Development mode ON.
Using C:\DOOM\choco\test for configuration and saves
V_Init: allocate screens.
M_LoadDefaults: Load system defaults.
saving config in C:\DOOM\choco\testdefault.cfg

```

This might or might not be related to the "no audio on daily builds" issue [reported](https://www.doomworld.com/forum/topic/86366-chocolate-doom/?do=findComment&comment=2274793) on DW by The Civ.

Additionally, a test savegame created with these builds was saved as C:\DOOM\choco\testsavegames\doom2.wad\doomsav0.dsg. Wrong dir again and two unnecessary subdirs are created.

**Comment by fabiangreffrath** [comment]
Sorry, but I fail to understand this. The trailing slash is explicitly added now.

**Comment by fabiangreffrath** [comment]
Cannot reproduce. Just checked the latest commit on a Windows system:
```
                         Chocolate Doom 3.0.0
Z_Init: Init zone memory allocation daemon. 
zone memory: 0377a020, 1000000 allocated for zone
Using D:\msys64\home\fgreffrath\chd\src\ for configuration and saves
V_Init: allocate screens.
M_LoadDefaults: Load system defaults.
saving config in D:\msys64\home\fgreffrath\chd\src\default.cfg
W_Init: Init WADfiles.
 adding D:\msys64\home\fgreffrath\cd\src\doom2.wad
===========================================================================
                         DOOM 2: Hell on Earth
===========================================================================
 Chocolate Doom is free software, covered by the GNU General Public
 License.  There is NO warranty; not even for MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE. You are welcome to change and distribute
 copies under certain conditions. See the source for more information.
===========================================================================
I_Init: Setting up machine state.
OPL_Init: Using driver 'SDL'.
NET_Init: Init network subsystem.
M_Init: Init miscellaneous info.
R_Init: Init DOOM refresh daemon - ......................................
P_Init: Init Playloop state.
S_Init: Setting up sound.
D_CheckNetGame: Checking network game status.
startskill 2  deathmatch: 0  startmap: 1  startepisode: 1
player 1 of 1 (1 nodes)
Emulating the behavior of the 'Doom 1.9' executable.
HU_Init: Setting up heads up display.
ST_Init: Init status bar.
```

**Comment by tpoppins** [comment]
Perhaps the problem is not with the code per se but with certain autobuilds. The one these results were obtained with was the March 10 build; I don't observe these issues with today's build, except for the _savegames_ subdir mentioned by chungy.
