### ISSUE TITLE
[Strife] Random symbols render at the end of mission objectives panel

### ISSUE THREAD

**Issue by K0stov** [chocolate-doom/chocolate-doom#1361]
### Background

**Version of Chocolate Doom**
3.0.1

**Operating System and version**
Windows 10 x64

**Game**
Strife

**Any loaded WADs and mods**
[strife-russian.wad](https://www.dropbox.com/s/gosbmqf4achkany/strife-russian.wad?dl=1)

### Bug description

**Observed behavior**
Random symbols are often sighted at the end of the mission objectives panel with `strife-russian.wad` loaded. Reproducible by accepting the first mission in the game from Rowan. (See screenshot below; replacing the logs with these characters is necessary for the port the WAD is designed for, [Russian Strife](https://github.com/K0stov/russian-strife), in which they appear as cohesive Cyrillic characters.)

**Expected behavior**
No extra symbols should appear at the end of objectives in the panel. The text should appear as is written in the respective lump (observe the very end of the string):
```
yfqlb cdznbkbot djpkt htrb> dyenhb cjlth;bncz gktyybr gj bvtyb ,tklby> pfcnfdm tuj pfvjkxfnm< b ghbytcb tuj rjkmwj hje'ye d rfxtcndt ljrfpfntkmcndf>
```

![image](https://user-images.githubusercontent.com/26684396/111520714-a761ac00-8758-11eb-8ba5-8487b93efa70.png)

**Comment by K0stov** [comment]
I’ve come up with a temporary solution for this in my own port: add around ten line breaks to every single quest log lump. This somehow gets rid of the extra symbols; not an ideal solution, so I’ll await a response from the developers here.

**Comment by fabiangreffrath** [comment]
I don't understand why you even expect strife-russian.wad to work with Chocolate Strife at all? Does it work with Vanilla Strife? Were some changes necessary to Russian Strife in order to get this working @JNechaevsky ?

**Comment by K0stov** [comment]
> Does it work with Vanilla Strife?

As a matter of fact, it does.

![image](https://user-images.githubusercontent.com/26684396/111584920-d1e65000-87be-11eb-9733-62f1d4af60e9.png)

**Comment by JNechaevsky** [comment]
Russian Strife isn't my project, and I'm afraid I can't say anything about changes @K0stov did.

However, if I'm getting this issue right, those trash symbol(s) are appering - _probably_ - because of some incorrect parsing/copying/printing  of `LOG&i` lump, despite of only US characters were usen in replaced lump.

I belive it happens here: https://github.com/chocolate-doom/chocolate-doom/blob/master/src/strife/p_dialog.c#L1222

That's all I can suggest, sorry.

**Comment by K0stov** [comment]
> Were some changes necessary to Russian Strife in order to get this working?

This is rooted in Chocolate Doom itself. I’ll give you a single file that should demonstrate the issue more clearly. Load it in Chocolate Strife and talk to Rowan, then look at the objectives (all I did was replace periods with > and commas with <).

[**LOG1003.txt**](https://github.com/chocolate-doom/chocolate-doom/files/6161970/LOG1003.txt)

![image](https://user-images.githubusercontent.com/26684396/111587291-4bcc0880-87c2-11eb-937f-ac6e3a590f63.png)

**Comment by fabiangreffrath** [comment]
This is probably because you have Windows style (CR LF) line endings in the file.

**Comment by K0stov** [comment]
> This is probably because you have Windows style (CR LF) line endings in the file.

Changed it to LF. Same issue, just slightly different characters.

![image](https://user-images.githubusercontent.com/26684396/111591281-88e6c980-87c7-11eb-94f4-09e96fc8f872.png)

Even when I export the original lump from the IWAD, it says it’s CRLF, though I am seeing some strange character at the end.

![image](https://user-images.githubusercontent.com/26684396/111591441-bfbcdf80-87c7-11eb-8e44-601318eecdb6.png)

**Comment by K0stov** [comment]
I’ve narrowed it down to a `00` byte located at the end of most (if not all) text lumps. By adding that to the Russian ones, the extra symbols disappear.

Still, the matter remains that the bug is exclusive to Chocolate Strife, and doesn’t appear in vanilla.

**Comment by fabiangreffrath** [comment]
Right. You are reading raw lump content from the WAD, which isn't necessarily formatted as a C string, which in turn has to end with a `\0` byte.

This code may serve as a workaround, but the underlying issue persists: Make sure that your replacement strings are formatted as valid C strings:

```patch
--- a/src/strife/p_dialog.c
+++ b/src/strife/p_dialog.c
@@ -1219,9 +1219,13 @@ void P_DialogDoChoice(int choice)

         if((objective = currentchoice->objective))
         {
+            int lumpnum, lumplen;
             DEH_snprintf(mission_objective, OBJECTIVE_LEN, "log%i", objective);
-            objlump = W_CacheLumpName(mission_objective, PU_CACHE);
+            lumpnum = W_GetNumForName(mission_objective);
+            lumplen = W_LumpLength(lumpnum);
+            objlump = W_CacheLumpNum(lumpnum, PU_CACHE);
             M_StringCopy(mission_objective, objlump, OBJECTIVE_LEN);
+            mission_objective[lumplen] = '\0';
         }
         // haleyjd 20130301: v1.31 hack: if first char of message is a period,
         // clear the player's message. Is this actually used anywhere?

```

**Comment by K0stov** [comment]
Thanks for the help. I’ve decided to just fill in the bytes properly.
