### ISSUE TITLE
Medusa, crash with sounds on

### ISSUE THREAD

**Issue by simc2** [chocolate-doom/chocolate-doom#1362]
**Version of Chocolate Doom:** chocolate-doom-20210316-win32, chocolate-doom-3.0.1-win32
**Operating System and version:** Windows 8.1 64-bit, Windows 10 64-bit
**Game: (Doom/Heretic/Hexen/Strife/other)** Doom2

**Any loaded WADs and mods (please include full command line):**
test wad and a demo file (Doom2 MAP01):
[medusa-test.zip](https://github.com/chocolate-doom/chocolate-doom/files/6160029/medusa-test.zip)
Commandline for the test wad and the demo:
chocolate-doom.exe -iwad doom2.wad -file medusa.wad -playdemo medusaX

**Observed behavior:**

Chocolate-Doom occasionally crash if the wad has a medusa error (multipatch texture as the mid texture on a 2s line) and sounds on. But if Chocolate-Doom is run with -nosound or -nosfx the crash doesn't seem to happen. Starting without chocolate-doom.cfg and default.cfg has no effect.

The crash may happen when:
a medusa error is at sight, 
the player is using the chainsaw, 
and a lift is about to make it's sequence sounds

For me the test level demo file produces a repeatable crash after 3-4 seconds from the start. The demo was recorded with PrBoom+ 2.6um -complevel 2, the Doom 1.9 compatalability. The demo runs without problems with Doom2.exe 1.9 in Dosbox. And in Chocolate-Doom too if it is run with -nosound or -nosfx parameters.

In Windows 8.1 (chocolate-doom-20210316-win32): (the daily build still numbers it being 3.0.0.0)
APPCRASH
chocolate-doom.exe
3.0.0.0
00000000
chocolate-doom.exe
3.0.0.0
00000000
c0000005
0003cce0
6.3.9600.2.0.0.768.101
1035
5861
5861822e1919d7c014bbb064c64908b2
9d53
9d539ab2d38cfad867f683ba4be72a2d

**Expected behavior:** The appcrash shouldn't happen.

**Comment by tpoppins** [comment]
This is not new: see issue #178 (and several others referenced thereby).

**Comment by simc2** [comment]
Ok. Duplicate.
