### ISSUE TITLE
About Travis CI

### ISSUE THREAD

**Issue by drfrag666** [chocolate-doom/chocolate-doom#1370]
Travis CI is now paid and i already ran out of credits, about Choco and Crispy have you emailed them asking for more OS credits? What do you plan to do? For my fork i'm considering switching to GitHub Actions but it's not trivial.

**Comment by fragglet** [comment]
Yes, it's definitely something that needs to be addressed. Switching to Github actions seems like the most sensible path forward.

**Comment by fabiangreffrath** [comment]
I have kindly asked Travis CI for credits for my open source projects and they promptly granted.

**Comment by drfrag666** [comment]
But that's not a solution, you need to apply for more when they run out and i've heard it can take some time to get them even months. Probably now it's faster since pretty much everybody seems to have moved to GitHub Actions.

**Comment by drfrag666** [comment]
Perhaps @alexey-lysiuk could help, he knows the syntax and migrated GZDoom from Travis.

**Comment by drfrag666** [comment]
Now GitHub actions are working here but apparently not in my repo after merging Choco's master. BTW thanks @mfrancis95 for the patch.
https://github.com/drfrag666/RUDE/commits/master

**Comment by mfrancis95** [comment]
@drfrag666 I noticed this as well. It was working at the time I got the PR merged in but for some reason afterward it stopped being able to find that libudev package. I might have to replace that `get-package` with a manual apt-get update and install.

**Comment by drfrag666** [comment]
It's trying to fetch a file that doesn't exist.
http://azure.archive.ubuntu.com/ubuntu/pool/main/s/systemd/libudev-dev_237-3ubuntu10.46_amd64.deb
I don't know where that filenaname comes from but there are similar files in that directory.

**Comment by drfrag666** [comment]
It's fixed after merging this PR: https://github.com/chocolate-doom/chocolate-doom/pull/1377
