### ISSUE TITLE
Orphan \r characters break DEH text substitution

### ISSUE THREAD

**Issue by mikeday0** [chocolate-doom/chocolate-doom#1375]
### Background

Version of Chocolate Doom: 174e8e8

Operating System and version: Ubuntu 20.04.2 LTS

Game: (Doom/Heretic/Hexen/Strife/other) Doom

Any loaded WADs and mods (please include full command line):

`chocolate-doom -iwad DOOM2.WAD -merge SpainRCFinal.wad -deh D2ISO_A.deh`

[D2ISORCF.zip](https://github.com/chocolate-doom/chocolate-doom/files/6396006/D2ISORCF.zip)

### Bug description

In the attached zip there is a deh file which consists solely of text substitutions. On line 161 there is an "orphan" carriage return not paired with a line feed. Whenever Chocolate Doom parses this file, any substitutions on lines after 161 are not properly applied. This deh file apparently works fine with vanilla. See: https://www.doomworld.com/forum/post/2300410

I have a fix that appears to work for at least this specific deh file. If the Chocolate team thinks this issue should be addressed I would be happy to submit a PR or patch.

**Comment by fabiangreffrath** [comment]
> I have a fix that appears to work for at least this specific deh file. If the Chocolate team thinks this issue should be addressed I would be happy to submit a PR or patch.

Yes, please do so.
