### ISSUE TITLE
chocolate-heretic does not honor -config parameter

### ISSUE THREAD

**Issue by wesleywerner** [chocolate-doom/chocolate-doom#1379]
### Background

Version of Chocolate Heretic: 3.0.1

Operating System and version: Win 10 Version 10.0.19043 Build 19043

Game: Heretic

Any loaded WADs and mods (please include full command line):

```
"W:\chocolate-heretic\chocolate-heretic.exe" -config "W:\chocolate-heretic\chocolate-heretic.cfg" -iwad "W:\heretic\wads\heretic.wad"
```

### Bug description

Running the executable within a console from another directory (for example when in `W:\heretic\mydemos\e1` to record my runs), the config parameter is not honored, and my key bindings revert to the default. 

On exit a new `chocolate-heretic.cfg` is written into the current directory, 

Observed behavior: config tries to load from the current directory, instead of from the file specified by the `-config` parameter

Expected behavior: config to load from the file specified by the `-config` parameter

**Comment by chungy** [comment]
You need to use `-extraconfig` for the non-vanilla configuration file.
