### ISSUE TITLE
Hexen demo desyncs

### ISSUE THREAD

**Issue by kraflab** [chocolate-doom/chocolate-doom#1381]
https://dsdarchive.com/wads/hexen

The following demos from the second cluster desync in the latest chocolate hexen:

https://dsdarchive.com/files/demos/hexen/50534/se2f2005.zip
https://dsdarchive.com/files/demos/hexen/50594/me2f4414.zip
https://dsdarchive.com/files/demos/hexen/50593/me2c4932.zip
https://dsdarchive.com/files/demos/hexen/50595/me2m5533.zip
https://dsdarchive.com/files/demos/hexen/773/fe2f4835.zip

The following demos from cluster 6 desync:

https://dsdarchive.com/files/demos/hexen/775/me6f7435.zip
https://dsdarchive.com/files/demos/hexen/776/me6f9105.zip

The following full game demos desync:

https://dsdarchive.com/files/demos/hexen/733/hexc0827.zip
https://dsdarchive.com/files/demos/hexen/699/hx4j1617.zip
https://dsdarchive.com/files/demos/hexen/778/dmf20215.zip

All 3 classes are involved, so the issue must not be class-specific. Also, all the demos for the first cluster are in sync, so it is likely something that comes up only in the later clusters. That being said, there aren't a ton of hexen demos in general, so we can't be 100% sure on that point.

**Comment by kraflab** [comment]
I should say, the demos desync in crispy - the demos don't play back far at all in choco itself. But the game engine behaviour issue is probably in choco itself, that's why I put the issue here.

**Comment by kraflab** [comment]
These desync in the chocolate releases since multilevel demo support was added (I checked 2.3+) and the demos can't play back at all in versions before that.

**Comment by kraflab** [comment]
Added a few more desyncing demos to the list.

**Comment by kraflab** [comment]
https://github.com/chocolate-doom/chocolate-doom/commit/9d51e5310899f3d0fefdd36c305dfe7a6d9ef3de

Probably will need to cherry-pick this commit onto 2.0.0 and see if the demos sync. If they do, we can then roll forward until the desync occurs.

**Comment by kraflab** [comment]
Got 2.0.0 working with demoextend, the first demo desyncs 😕 
I know there were some fixes to the order of rng calls in between then and now, so it's possible there wasn't ever a time where everything was compatible.

**Comment by kraflab** [comment]
Added a few more demos - this should now be the complete list (of demos stored on dsda). 10 demos.

**Comment by kraflab** [comment]
https://github.com/chocolate-doom/chocolate-doom/commit/d6693cc9e17fdbee7033e47b7b8da249da118d8f I haven't checked all the demos, but the first one is fixed by reverting this.

**Comment by kraflab** [comment]
me6f7435 and dmf20215 still desync unfortunately 😕 
coop probably needs a fix like this one: https://github.com/chocolate-doom/chocolate-doom/pull/1358
will check it out

**Comment by kraflab** [comment]
https://github.com/chocolate-doom/chocolate-doom/pull/1382 coop fix
https://github.com/chocolate-doom/chocolate-doom/pull/1383 P_LookForPlayers fix

Unfortunately, 3 demos still desync:

me6f7435, dmf20215, and hexc0827

**Comment by kraflab** [comment]
hexc0827 is syncing now with the coop fix - not sure why it wasn't working for me, but I rebuilt everything and it's fine now.

**Comment by fragglet** [comment]
Thanks for looking into this! I've left some comments on your PRs.

**Comment by kraflab** [comment]
The two demos left, me6f7435 and dmf20215, both desync in hub 6 (hexdd), both on map 46, and both while working on the puzzle with the shapes. Without a working syncing reference to compile and debug, I'm not sure how to proceed. As far as I know, there is no source port that runs on modern systems and can play back these demos. They are in sync in dos with hexen+.
