### ISSUE TITLE
fez1-924.lmp/fez1.wad desyncs (win32-r2249)

### ISSUE THREAD

**Issue by chocolate-import** [chocolate-doom/chocolate-doom#139]
> The following bug was [originally reported](https://sourceforge.net/p/chocolate-doom/bugs/139/) on Sourceforge by [porschemonty](https://sourceforge.net/u/porschemonty/profile/), 2011-02-16 11:27:09:

http://doomedsda.us/wad1490.html

I went through all of the vanilla wads that were mentioned in prBoom+'s changelog and found out that this one desyncs in Chocolate as well. I'm also aware that bugs relaying on the memory layout may indeed be impossible to fix, but apparently the author provides a workaround (for his port, that is):

"Improved emulation of "missed back side" overrun. There is no more desynch on fez1-924.lmp @ fez1.wad, but you still need to add "-setmem dosbox" or "-setmem dos71" command line parameter, because default "dos622" memory layout causes desynch"

Tested on XP Pro SP3.
Regards.

**Comment by mfrancis95** [comment]
I just ran through the demo in the latest version of Chocolate in Ubuntu as of my writing this and haven't noticed a desync. Can anyone else confirm?

**Comment by tpoppins** [comment]
The desync in my previous report must have been caused by a DEH autoloaded at startup. With no extraneous files loaded both Choco and Crispy play this demo correctly. This issue can probably be closed.
