### ISSUE TITLE
Chocolate Doom 3.0.1 error when using Doom v1.1.

### ISSUE THREAD

**Issue by Sijonda** [chocolate-doom/chocolate-doom#1392]
I just took a quick look through the FAQ and the Not Bugs sections. I don't believe what I'm getting fits into either of these.

### Background

Version of Chocolate Doom: 3.0.1

Operating System and version: Windows 10 21H1. 19043.1165

Game: (Doom/Heretic/Hexen/Strife/other) Doom v1.1 (specifically 1.1. Ultimate doom works fine.)

Any loaded WADs and mods (please include full command line): I've left out all optional WADS since I'm looking to play the game as close to vanilla as possible.

### Bug description

Observed behavior: Error when starting Chocolate Doom with the Doom 1.1 WAD file. "W_GetNumForName: STBAR not found!"
This error does not occur when I use Ultimate Doom which I bought years ago. I found this 1.1 version online specifically to find the first release without all of the changes that were made later on. Version 1.666 of Doom 2 also works.

Expected behavior: Doom 1.1 to run with Chocolate Doom.
![New Bitmap Image](https://user-images.githubusercontent.com/61842509/132269023-5d0a3756-80b7-4f8b-a3c3-6e9a1f1b529b.jpg)

**Comment by drfrag666** [comment]
This cannot be a bug, Doom 1.x is not supported in Choco. But it does run with RUDE (my limit removing fork).
https://github.com/drfrag666/RUDE/releases

**Comment by Sijonda** [comment]
Thank you for working on the fork. Works great 😊

**Comment by fragglet** [comment]
Not a bug - you need to upgrade your IWAD. I believe v1.2 is the earliest that works.

**Comment by fragglet** [comment]
Additional note: I believe that you could probably put together a small WAD containing the graphics lumps that were added between v1.1 and v1.2, and that would make it work. If someone wants to do that and submit it to idgames, I'd be happy to link it in the documentation.

**Comment by Sijonda** [comment]
Dondiego linked me to a branch without the catch allowing me to run the original release of Doom. I have other versions but I wanted to play through the original releases.On Sep 15, 2021 18:55, Simon Howard ***@***.***> wrote:
Additional note: I believe that you could probably put together a small WAD containing the graphics lumps that were added between v1.1 and v1.2, and that would make it work. If someone wants to do that and submit it to idgames, I'd be happy to link it in the documentation.
