### ISSUE TITLE
autogen fails when following build instructions: "Package requirements (sdl2 >= 2.0.7) were not met"

### ISSUE THREAD

**Issue by ChrisIdema** [chocolate-doom/chocolate-doom#1400]
### Background

Version of Chocolate Doom:
latest master branch: 5ad017e1713e0fccf33706757b57c17ccd700882
(also tried tag chocolate-doom-3.0.1 539ef367c9982c5945f8608b63d2236eaecc929a)

Operating System and version:

```
Edition      Windows 10 Pro
Version      21H1
Installed on 2021-‎07-‎14
OS build     19043.1288
Experience   Windows Feature Experience Pack 120.2212.3920.0
```

Game: (Doom/Heretic/Hexen/Strife/other)
Doom

Any loaded WADs and mods (please include full command line):
NA

### Bug description
Following the build instructions on https://www.chocolate-doom.org/wiki/index.php/Building_Chocolate_Doom_on_Windows failed at the autogen step.

Observed behavior:

- clone chocolate-doom 5ad017e1713e0fccf33706757b57c17ccd700882
- install latest MSYS2 (msys2-x86_64-20210725)
- `pacman -Syu`
- `pacman -Su`
- run :
```
pacman -S base-devel msys2-devel \
mingw-w64-i686-{toolchain,SDL2{,_net,_mixer},libsamplerate,libpng} \
python zip git
```
- `./autogen.sh --host=i686-w64-mingw32`
- Result:

> ...
> checking for SDL... no
> configure: error: Package requirements (sdl2 >= 2.0.7) were not met:
> Package 'sdl2', required by 'virtual:world', not found

Expected behavior:

sdl2 should be found

I tried installing SDL2 again, but it didn't help: `pacman -S mingw-w64-x86_64-SDL2`

**Comment by ChrisIdema** [comment]
Update

setting PKG_CONFIG_PATH via environment variables didn't help
setting SDL_LIBS in terminal didn't help
setting PKG_CONFIG_PATH in terminal helped and autogen succeeded.

Now it fails at make:


> /usr/lib/gcc/x86_64-pc-msys/10.2.0/../../../../x86_64-pc-msys/bin/ld: cannot find -lmingw32
> /usr/lib/gcc/x86_64-pc-msys/10.2.0/../../../../x86_64-pc-msys/bin/ld: skipping incompatible /mingw32/lib/libSDL2main.a when searching for -lSDL2main
...
> /usr/lib/gcc/x86_64-pc-msys/10.2.0/../../../../x86_64-pc-msys/bin/ld: cannot find -lSDL2
> /usr/lib/gcc/x86_64-pc-msys/10.2.0/../../../../x86_64-pc-msys/bin/ld: skipping incompatible /mingw32/lib/libSDL2.dll.a when searching for -lSDL2
> /usr/lib/gcc/x86_64-pc-msys/10.2.0/../../../../x86_64-pc-msys/bin/ld: skipping incompatible /mingw32/lib/libSDL2.a when searching for -lSDL2
> /usr/lib/gcc/x86_64-pc-msys/10.2.0/../../../../x86_64-pc-msys/bin/ld: skipping incompatible /mingw32/lib/libSDL2.dll.a when searching for -lSDL2
> /usr/lib/gcc/x86_64-pc-msys/10.2.0/../../../../x86_64-pc-msys/bin/ld: skipping incompatible /mingw32/lib/libSDL2.a when searching for -lSDL2
> /usr/lib/gcc/x86_64-pc-msys/10.2.0/../../../../x86_64-pc-msys/bin/ld: skipping incompatible /mingw32/lib/libSDL2.dll.a when searching for -lSDL2
> /usr/lib/gcc/x86_64-pc-msys/10.2.0/../../../../x86_64-pc-msys/bin/ld: skipping incompatible /mingw32/lib/libSDL2.a when searching for -lSDL2
> /usr/lib/gcc/x86_64-pc-msys/10.2.0/../../../../x86_64-pc-msys/bin/ld: skipping incompatible /mingw32/lib/libSDL2.dll.a when searching for -lSDL2
> /usr/lib/gcc/x86_64-pc-msys/10.2.0/../../../../x86_64-pc-msys/bin/ld: skipping incompatible /mingw32/lib/libSDL2.a when searching for -lSDL2
> /usr/lib/gcc/x86_64-pc-msys/10.2.0/../../../../x86_64-pc-msys/bin/ld: skipping incompatible /mingw32/lib/libSDL2.dll.a when searching for -lSDL2
> /usr/lib/gcc/x86_64-pc-msys/10.2.0/../../../../x86_64-pc-msys/bin/ld: skipping incompatible /mingw32/lib/libSDL2.a when searching for -lSDL2
> /usr/lib/gcc/x86_64-pc-msys/10.2.0/../../../../x86_64-pc-msys/bin/ld: skipping incompatible /mingw32/lib/libSDL2.dll.a when searching for -lSDL2
> /usr/lib/gcc/x86_64-pc-msys/10.2.0/../../../../x86_64-pc-msys/bin/ld: skipping incompatible /mingw32/lib/libSDL2.a when searching for -lSDL2
> /usr/lib/gcc/x86_64-pc-msys/10.2.0/../../../../x86_64-pc-msys/bin/ld: skipping incompatible /mingw32/lib/libSDL2.dll.a when searching for -lSDL2
> /usr/lib/gcc/x86_64-pc-msys/10.2.0/../../../../x86_64-pc-msys/bin/ld: skipping incompatible /mingw32/lib/libSDL2.a when searching for -lSDL2
> collect2: error: ld returned 1 exit status
> make[3]: *** [Makefile:337: guitest.exe] Error 1
> make[3]: Leaving directory '/c/git/chocolate-doom/textscreen/examples'
> make[2]: *** [Makefile:481: all-recursive] Error 1
> make[2]: Leaving directory '/c/git/chocolate-doom/textscreen'
> make[1]: *** [Makefile:562: all-recursive] Error 1
> make[1]: Leaving directory '/c/git/chocolate-doom'
> make: *** [Makefile:415: all] Error 2

**Comment by fragglet** [comment]
You need to have the appropriate SDL libraries installed - maybe the MSYS version doesn't have them or is missing the appropriate pkg-config files?

I'd recommend trying [chocpkg](https://github.com/chocolate-doom/chocpkg) which is intended to take care of this stuff automatically.

**Comment by ChrisIdema** [comment]
I feel dumb. I found the problem. I used MSYS2 instead of mingw32.  It builds and runs!

> At this stage, you must use the appropriate MSYS2 terminal (mingw32.exe or mingw64.exe) so that the $PATH environment variable points to the proper toolchain, for the mingw-w64-i686 toolchain (32-bit), use the MSYS MinGW 32-bit start menu/screen shortcu
