### ISSUE TITLE
[Feature Request] Sound fonts

### ISSUE THREAD

**Issue by Mechanical-sanity** [chocolate-doom/chocolate-doom#1416]
So crispy doom has a feature where you can add your own soundfonts, but will chocolate doom also have such a feature? Unless there is something in there already and I just don't know about it?

**Comment by fabiangreffrath** [comment]
In fact, Crispy has inherited this feature from Choco: 
https://github.com/chocolate-doom/chocolate-doom/commit/85bcd1c917864673aa86cc14921e0ac0f209da9a
