### ISSUE TITLE
Add Windows building to GitHub Actions pipeline

### ISSUE THREAD

**Issue by mfrancis95** [chocolate-doom/chocolate-doom#1426]
I'd like to get Windows-building added to the GitHub Actions pipeline. I was experimenting with this through a Windows container and MSYS2, but saw that there were efforts made to cross-compile instead: https://github.com/fabiangreffrath/woof/commit/fad2d48b8f40f72776be3fe7d39aa0e07b6a8567

@fabiangreffrath what is the status on that? Is it able to be backported to Choco?

**Comment by fabiangreffrath** [comment]
> @fabiangreffrath what is the status on that? Is it able to be backported to Choco?

Sure it's possible to port this over to Choco. The one issue is that there seems to be no format string for printing `size_t` type variables that's portable across all architectures and OSes. Thus, I had to change some of them to `unsigned long` type.

**Comment by mfrancis95** [comment]
Closing. This was successfully added via 5863d8e.
