### ISSUE TITLE
What order do IWAD, FILE, MERGE and DEH go in?

### ISSUE THREAD

**Issue by dftf-stu** [chocolate-doom/chocolate-doom#1428]
Version of Chocolate Doom: **3.0.1**
Operating System: **Windows 10 Version 21H2**
Game: **DOOM**
Any loaded WADs and mods (please include full command line):
**chocolate-doom.exe -MERGE -FILE DOOM.wad FDDM0121.wad FD1_0121.wad FDDM0121.deh**

### Help description

Observed behaviour:

Please help, as I'm finding things very-confusing!

I downloaded a mod called "Freedoom in DOOM" from the moddb site.  Its README.txt file doesn't give any example command-lines, but as it says their mod will work with _Chocolate Doom_, I struggled-on trying to figure-out how to make it work.

I ended-up coming-up with this command, which did work -- but I was advised it was incorrect as an "IWAD" command is needed:
**chocolate-doom.exe -MERGE -FILE DOOM.wad FDDM0121.wad FD1_0121.wad FDDM0121.deh**

The remaining four commands below are all what other-people have advised me I should be using instead:
- **chocolate-doom.exe -MERGE -IWAD DOOM.wad -FILE FDDM0121.wad FD1_0121.wad FDDM0121.deh**
- **chocolate-doom.exe -MERGE -IWAD DOOM.wad -FILE FDDM0121.wad FD1_0121.wad -DEH FDDM0121.deh**
- **chocolate-doom.exe -MERGE -IWAD DOOM.wad -DEH FDDM0121.deh -FILE FDDM0121.wad FD1_0121.wad**
- **chocolate-doom.exe -DEH FDDM0121.deh -MERGE -IWAD DOOM.wad -FILE FDDM0121.wad FD1_0121.wad**

Needless to say, I'm super-confused!

Expected behaviour:

It would be nice if one of the text-files that come supplied with Chocolate DOOM (or HTML files, in Crispy DOOM), or a page on its Wiki, gave some example commands, or explained for the various command-line arguments/parameters if they need to go in a certain order.

I have tried to find the answer via Google, but can't seem to find any guidance on the order, beyond the basic "to play a level-set, the order is IWAD first, then FILE", which I already knew.  But nothing for more-complicated setups.

I also checked on the _Chocolate DOOM Wiki_ to get some examples that might help me, but they also differ there.  For example, _Aliens TC_ has the commands in the order DEH, MERGE, FILE.  Whereas "All Hell Is Breaking Loose" has the order MERGE, FILE, DEH.

Can anyone please explain what order I should use, and maybe educate me as to why?  (Though just telling me which command is the correct one would be enough!)

Thanks

**Comment by fabiangreffrath** [comment]
To stay with your example:

chocolate-doom.exe -IWAD DOOM.wad -MERGE FDDM0121.wad FD1_0121.wad -DEH FDDM0121.deh

The order of FDDM0121.wad and FD1_0121.wad may be important, though, as it determines which of the two PWADs to add first to the IWAD assets. I can't say which is the right order, though.

**Comment by fabiangreffrath** [comment]
Any questions left?

**Comment by mfrancis95** [comment]
Closing due to the question being answered and over a year of inactivity.
