### ISSUE TITLE
[Feature request] 320, 200

### ISSUE THREAD

**Issue by Mechanical-sanity** [chocolate-doom/chocolate-doom#1429]
So the original Dos Doom release was in 320 by 200, but it appears that I cannot do that for chocolate doom. It just does this weird thing when I tried to set it's own resolution. Would it be possible to have support for this resolution?

**Comment by fabiangreffrath** [comment]
In Choco Doom, the game content is always rendered to a 320x200 frame buffer, which is then scaled up to whatever resolution you choose for your game window (or fullscreen, respectively).

**Comment by chungy** [comment]
Set `fullscreen_width` and `fullscreen_height` in `chocolate-doom.cfg` to make it use that resolution on your hardware. Mind that many GPUs and displays don't actually support it anymore and Chocolate tries to make the more sensible default of using your native resolution to scale up the 320×200 game image.
