### ISSUE TITLE
Doom 3.0.1 from site not able to start multiuser

### ISSUE THREAD

**Issue by dtsig** [chocolate-doom/chocolate-doom#1443]
### Background

Version of Chocolate Doom: 3.0.1 from [this site](https://www.chocolate-doom.org/wiki/index.php/Downloads)

Operating System and version: Win10 (current release)

Game: (Doom/Heretic/Hexen/Strife/other) Doom II wad from game cd

Any loaded WADs and mods (please include full command line): Doom2.wad from cd

### Bug description

Observed behavior:  Plays well in single user mode.  But when setting up multiplayer on local network (using wifi) Server 'starts' multi user game and server name is listed.  Then client tries to connect.  It finds the server IP and select to join.  Name never gets listed on server.  Eventually when server starts game, client gets message "disconnected from server".
This behavior happens on Win to Win machines .. RaspberryPi to Pi machines and Pi to Win machines.

Expected behavior: I expect the Server to see the client join when client has selected IP and select Connect/Join

I could find no where else to not this issue and hope this is ok.

**Comment by fragglet** [comment]
Can you try a daily build from http://latest.chocolate-doom.org/ and see if this fixes the problem?

**Comment by dtsig** [comment]
Thanks .. will give it a try and report back

Dsig
