### ISSUE TITLE
HACX.wad not working, no matter what revision/version 

### ISSUE THREAD

**Issue by ForeskinJohn** [chocolate-doom/chocolate-doom#1446]
im getting many errors when trying to start up hacx, I can get 1.2 to work if i use doom 2 as an IWAD and load it on top but alone it will not launch. ive tried every version i could find, even the latest "2.0" revision of the IWAD, nothing seems to work.

**Comment by hfc2x** [comment]
It's not supposed to launch by itself. It launches like this with no issues:
`chocolate-doom -iwad Doom2.wad -file HACX.WAD -dehlump`

Hacx 2.0 is a ZDoom mod, so it shouldn't work with Chocolate Doom at all.

**Comment by mfrancis95** [comment]
Hacx 1.2 works via `chocolate-doom -iwad HACX.wad`. Closing because of this and the comment above.
