### ISSUE TITLE
Doom forked from plymouth doesn't start

### ISSUE THREAD

**Issue by ericcurtin** [chocolate-doom/chocolate-doom#1448]
### Background

Version of Chocolate Doom: Fedora 35 version, running via KMS/DRM

Operating System and version: Fedora 35 x86_64

Game: Doom

Any loaded WADs and mods (please include full command line): Doom 1.9 WAD

### Bug description

Observed behavior:

When plymouth forks doom it gets as far as this but never starts:

```
                         Chocolate Doom 3.0.1
Z_Init: Init zone memory allocation daemon.
zone memory: 0x7fcadc8bd010, 1000000 allocated for zone
```

Expected behavior:

Doom starts. Doom does start on this machine if I start on CLI in KMS/DRM mode.

The overall intention is to be able to play doom as a bootsplash while the operating system is booting.

**Comment by chungy** [comment]
Does SDL even have a video driver that would allow it to run directly in DRM mode? Without Wayland or X.Org?

**Comment by ericcurtin** [comment]
Yes it does, you can even force it by setting "export SDL_VIDEODRIVER=kmsdrm" and running chocolate-doom in a non-Wayland/XOrg tty

**Comment by turol** [comment]
Try with `-devparm` command line parameter.

**Comment by fabiangreffrath** [comment]
Is sound hardware even initialized that early in the boot sequence?

**Comment by ericcurtin** [comment]
Probably not but I don't care about sound, even if I test this in plymouth once the system is fully booted, the same issue occurs

**Comment by fabiangreffrath** [comment]
Does setting `force_software_renderer` to `1` in the config file help?

**Comment by ericcurtin** [comment]
What will "-devparm" do?

**Comment by turol** [comment]
Enable some extra debug output, though apparently not much. Can you attach gdb when it hangs? If not, your best bet is probably to add more logging statements and try to narrow down where exactly it hangs.

**Comment by ericcurtin** [comment]
Fix https://github.com/chocolate-doom/chocolate-doom/pull/1449

**Comment by ericcurtin** [comment]
Fixed in opendoom, thanks for feedback @fabiangreffrath M_TempFile(NULL) works great

[e68c2693fc1cddc6a56e01f74e43ded8d8192a04](https://github.com/ericcurtin/opendoom/commit/7ef55ebd04d2ed343cdfad2e44d89f6ac38981bf)

**Comment by ericcurtin** [comment]
Also fixed in crispy:

https://github.com/fabiangreffrath/crispy-doom/pull/850
