### ISSUE TITLE
ctrl-"left arrow" on mac

### ISSUE THREAD

**Issue by DrEldonTyrell** [chocolate-doom/chocolate-doom#1455]
### Background

Version of Chocolate Doom: 3.0.0

Operating System and version: MacOs 12.3

Game: (Doom/Heretic/Hexen/Strife/other)
Doom
Any loaded WADs and mods (please include full command line):
no
### Bug description

Observed behavior: while playing shooting with ctrl and moving with left arrow, my Mac switches to another open app. This works only inside chocolate doom, not in the finder

Expected behavior: shoot and move?

**Comment by Pedro-Beirao** [comment]
That is normal on MacOS.
Ctrl + left/right arrow switches the workspace to left/right.
You can turn this off by changing the keyboard shortcut of this in System Preferences -> Keyboard

**Comment by fragglet** [comment]
Yes, what Pedro said. I don't think there's another way around it than to rebind those buttons - at least that's the solution I've taken.

Thank you for the report regardless.

**Comment by DrEldonTyrell** [comment]
Thank You. I already thought it could be stag like that, but did not find it in the control panels. Maybe it's time for a closer look : )
Thank You both veray much for Your kind answers
