### ISSUE TITLE
All ghosts glitch effect.

### ISSUE THREAD

**Issue by cyberdemon2004** [chocolate-doom/chocolate-doom#1456]
### Background

Version of Chocolate Doom: 5.11.1

Operating System and version: Windows 10.

Game: (Doom/Heretic/Hexen/Strife/other): Doom 2.

Any loaded WADs and mods (please include full command line): Doom 2, version 1.9.

### Bug description: There is a bug in Crispy Doom known as 'all ghosts glitch effect.'

Observed behavior:  'All ghosts glitch effect is triggered at many places.' 

Expected behavior:  Please fix this bug permanently. Its very annoying.

**Comment by turol** [comment]
As you were already told over at Crispy Doom issue tracker this is required for vanilla compatibility and therefore will not be done.
