### ISSUE TITLE
Flathub

### ISSUE THREAD

**Issue by Mailaender** [chocolate-doom/chocolate-doom#1466]
Hi, I created a Flatpak package at https://github.com/flathub/flathub/pull/3185.

**Comment by leolobato** [comment]
Hi. I've installed Chocolate Doom on the Steam Deck using Discover, but how can I run `chocolate-doom-setup` to configure the controller?

On Konsole, I can run `flatpak run org.chocolate_doom.ChocolateDoom` to start the game, but I can't find a way to run the setup binary.

**Comment by Mailaender** [comment]
As far as I understand https://docs.flatpak.org/en/latest/ there can only be one binary per package.
