### ISSUE TITLE
Choco Strife can't read DEH/SEH file.

### ISSUE THREAD

**Issue by Zerkseas** [chocolate-doom/chocolate-doom#1484]
### Background

Version of Chocolate Doom: 3.0.0 and 3.0.1

Operating System and version: 64-bit, Windows 10 Home version 21H2 

Game: Strife

Any loaded WADs and mods (please include full command line): \Downloads\chocolate-strife-3.0.1-win32\chocolate-strife.exe -merge RSFCS.WAD -deh RSFCS.SEH -warp 02

### Bug description

Observed behavior: "Error parsing dehacked file"

Expected behavior: The game to run with the name of MAP02 changed. I've tried both -seh and -deh and have changed the file extension to match; no dice. Here is the sehacked patch in question
[RSFCS.zip](https://github.com/chocolate-doom/chocolate-doom/files/9204384/RSFCS.zip)

**Comment by fragglet** [comment]
The first line of the file identifies it as a Dehacked patch, not a Sehacked patch. 

> Patch File for DeHackEd v3.0

It should be one of these:

https://github.com/chocolate-doom/chocolate-doom/blob/master/src/strife/deh_strife.c#L23

I've tried testing with DOS sehacked and it doesn't work there either, so I'm satisfied this is not a bug.

**Comment by Zerkseas** [comment]
I've replaced the first line and tried again but with no luck. I don't believe SeHackEd files are actually being read. To confirm, I took kaiser_13.wad and kaiser_13_b.wad off idgames, extracted the patch (which was actually DeHackEd), renamed the file extension to .SEH and changed to first line of it to "Patch File for SeHackEd v0.4", ran the wads and the patch with the -seh parameter and the map's title in the automap still reads "Area 2: Town".

Also, can you give me SeHackEd (she04.zip)? The only link to it I can find is dead. I was going to try to make a genuine patch from scratch instead of editing one from one of Kaiser's old wads only to run into that problem.

**Comment by fragglet** [comment]
The patch reads:
```
Text 13 19
AREA  2 townRusty Shekels for Cinnamon Sap
```
while from the Choco Strife source:
```
#define HUSTR_2         "AREA  2: town"
```
So the missing colon means it's the wrong string.

**Comment by Zerkseas** [comment]
```
Patch File for SeHackEd v0.4

# Note: Use the pound sign ('#') to start comment lines.

Doom version = 19
Patch format = 6

Text 13 18
AREA  2: townTEST
```
I tried the above in a new patch, with -seh parameter, and still no change to the map title. Perhaps the "Doom version" is wrong?

I had edited a patch from another strife wad (the kaiser one) to make my initial one since I can't get a copy of SeHackEd anywhere online and just assumed that would work. I apologize for all the trouble but I really just don't know what I'm doing wrong anymore.

**Comment by fragglet** [comment]
I've uploaded a version of she04.zip here for you: https://soulsphere.org/random/she04.zip

With respect, this is an issue tracker for reporting bugs in Chocolate Doom, not for seeking help with debugging your mod. I'd ask that if you're still having problems, please start a thread on the Doomworld forums in either the Editing or Editing Questions forums since there will be people there who can answer your questions for you.
