### ISSUE TITLE
WASM Version - Unable to turn on the music

### ISSUE THREAD

**Issue by ebellumat** [chocolate-doom/chocolate-doom#1496]
This is a bug related to the WASM version created by cloudflare, i'm unable to turn on the music on the game, when i remove the "-nomusic" argument, the game not run at all.

I think this can be a missing resources, but i don't know what resources on what folder. Can you guys help me with this?

https://github.com/cloudflare/doom-wasm/issues/4

You guys can test this version here: https://silentspacemarine.com/

I'm working to port this version to other devices like OLED TV's

### Background

Operating System and version: Google Chrome, Mac OS
Browser - Google Chrome
Game: DOOM

Any loaded WADs and mods (please include full command line):
Doom1.wad 
### Bug description
No Music
Observed behavior:

Expected behavior:
Works with music

**Comment by turol** [comment]
We don't support someone else's unmaintained fork. Now if someone were to port the changes back (#1496), then we could support it.

As far as I know SDL_mixer requires threads and WASM doesn't support those very well. That might an issue.

**Comment by ebellumat** [comment]
Thank you, unable to solve the issue but i learned something about SDL_mixer and WASM. I think i will port the version from JS DosBox to TV's
