### ISSUE TITLE
Textscreen TXT_NewInputBox forces crash when char* value is assigned

### ISSUE THREAD

**Issue by skynettx** [chocolate-doom/chocolate-doom#1497]
Hi,

i use for my project the lib textscreen from choco: https://github.com/skynettx/raptorsetup
and i have a problem with TXT_NewInputBox.
When I assign a char* to TXT_NewInputBox that contains a value textscreen crashes after editing the box and pressing enter.
Example code:
```
void AdditionalFeatures(TXT_UNCAST_ARG(widget), void* user_data)
{
  txt_window_t* window;
  static char soundfont[128];
  //static char *sf = NULL; 
  
  sf = (char*) INI_GetPreference("Setup", "SoundFont", soundfont, 127, "SoundFont.sf2"); //sf gets the right value from config file
  
  window = TXT_NewWindow("Additional Features                         ");
 
  TXT_AddWidgets(window, TXT_NewSeparator("Audio"),
      TXT_NewHorizBox(TXT_NewLabel("TSF SoundFont Name: "), TXT_NewInputBox(&sf, 20), NULL), NULL); 
}
```
The value is displayed correctly but when I edit the box and press enter textscreen crashed immediately.
When static char* sf = NULL prog runs fine but of course without read value from config file.
Is this a problem with textscreen or am I doing something wrong?

**Comment by turol** [comment]
1. Use Valgrind or ASAN to see what the problem is
2. If you can't, at least post a backtrace from the crash
3. Make a fully self-contained test program that demonstrates the problem

**Comment by fragglet** [comment]
Make sure you aren't passing a static string to `TXT_NewInputBox` because the input box code frees the old string when the value changes.

You can probably test if you're making this mistake with something like
```
sf = strdup(sf);
```
It's like if you did this
```
free("hello world");
```
which also crashes

**Comment by skynettx** [comment]
Many thanks `sf = strdup(sf);` fixes the problem.
