### ISSUE TITLE
potential overflow

### ISSUE THREAD

**Issue by chocolate-import** [chocolate-doom/chocolate-doom#150]
> The following bug was [originally reported](https://sourceforge.net/p/chocolate-doom/bugs/150/) on Sourceforge by [rtc_marine](https://sourceforge.net/u/rtc_marine/profile/), 2011-03-28 23:58:40:

trunk, line 1315, m\_config.c

The strparm buffer passed into fscanf does not have a field width limit, which may cause an overflow or crash on large input data

**Comment by njankowski** [comment]
Silently fixed in bc8517a05648054df17e556d4116e63a20fef75a
