### ISSUE TITLE
fatal  error C1083: Cannot open include file: 'config.h':

### ISSUE THREAD

**Issue by f1ames0ff** [chocolate-doom/chocolate-doom#1502]
The line #24 in the doomtype.h throws error 
`fatal error C1083: Cannot open include file: 'config.h':`
during the compilation

https://github.com/chocolate-doom/chocolate-doom/blob/899c34dd540451251d882883303c7347154dc287/src/doomtype.h#L24

**Comment by turol** [comment]
This is probably caused by your failure to run cmake properly.
