### ISSUE TITLE
Black bar appears to cover half of status bar with latest head. (HEAD-6e363ea)

### ISSUE THREAD

**Issue by jordie-sound-system** [chocolate-doom/chocolate-doom#1505]
### Background

Version of Chocolate Doom: 3.0.1 (HEAD-6e363ea)

Operating System and version: macOS 10.15.7

Game: (Doom/Heretic/Hexen/Strife/other) Tested on Ultimate Doom/Doom II

Any loaded WADs and mods (please include full command line): DOOM.WAD / DOOM2.WAD

### Bug description

Observed behavior: Black bar covering half the status bar on the bottom of the screen. 

Expected behavior: Regular play.

Notes: Previous to today this issue was not occuring. Built from Homebrew

![Screen Shot 2022-09-07 at 5 26 12 PM](https://user-images.githubusercontent.com/30581559/188995257-e5b2c45c-1f95-4020-83bf-0332af9ecd88.png)
![Screen Shot 2022-09-07 at 5 26 20 PM](https://user-images.githubusercontent.com/30581559/188995259-19267878-d847-4ced-96fe-66359f65d2e5.png)

**Comment by mikeday0** [comment]
Hmm, that’s a strange issue. Curious - do you happen to have a MacBook with a Touch Bar?

**Comment by jordie-sound-system** [comment]
> Hmm, that’s a strange issue. Curious - do you happen to have a MacBook with a Touch Bar?

No, I have a Mid-2012 MacBook Pro.

**Comment by mikeday0** [comment]
I can repeat this on my old Macbook Air. The behavior appeared after upgrading to SDL 2.24.0. Until the SDL bug gets fixed, you can workaround it by setting `force_software_renderer` to 1 in your `chocolate-doom.cfg` file. (For me this file is located in `/Users/<name>/Library/Application Support/chocolate-doom`.)

**Comment by jordie-sound-system** [comment]
> I can repeat this on my old Macbook Air. The behavior appeared after upgrading to SDL 2.24.0. Until the SDL bug gets fixed, you can workaround it by setting `force_software_renderer` to 1 in your `chocolate-doom.cfg` file. (For me this file is located in `/Users/<name>/Library/Application Support/chocolate-doom`.)

Thanks! I had figured it might've been due to a SDL update. Hope they're able to iron it out quickly. Will change my cfg until then :)

**Comment by mikeday0** [comment]
FWIW, this issue appears to be gone if I install the HEAD version of SDL2.

**Comment by mikeday0** [comment]
@jordie-sound-system This issue is fixed with SDL 2.26 on my system. Can you upgrade your SDL2 Homebrew package and see if it resolves the problem for you?

**Comment by jordie-sound-system** [comment]
@mikeday0 Thanks for coming back to this. This has fixed the issue on my system as well!

**Comment by mfrancis95** [comment]
Closing due to the resolution being determined.
