### ISSUE TITLE
Audio Bug

### ISSUE THREAD

**Issue by illiquid1** [chocolate-doom/chocolate-doom#1526]
### Background

Version of Chocolate Doom: 3.0.1

Operating System and version: windows 11 x64

Game: Doom

Any loaded WADs and mods (please include full command line): DOOM.WAD

### Bug description

Observed behavior: Only one second of a sound effect plays and then it just cuts off

Expected behavior: for the whole sound to play before ending

**Comment by illiquid1** [comment]
this doesnt happen in 3.0.0

**Comment by fabiangreffrath** [comment]
So, it's not this Vanilla bug we are talking about?
https://doomwiki.org/wiki/Sound_cutoffs

**Comment by illiquid1** [comment]
the sound always cuts off even if it is the only sound playing, it happens with every single sound in the game also the original (not sure what this is called but the beepy music) doesnt work and i have to use the higher quality music

**Comment by mikeday0** [comment]
Do you have the issue when running the latest autobuilds found [here](http://latest.chocolate-doom.org/)?

**Comment by fragglet** [comment]
I just updated all the SDL packages in the chocpkg repository and the daily builds are now running with these, so I'm going to consider this bug fixed unless someone tells me otherwise.
