### ISSUE TITLE
Garbage in window borders when resizing in Windows 2000/XP/7

### ISSUE THREAD

**Issue by chocolate-import** [chocolate-doom/chocolate-doom#153]
> The following bug was [originally reported](https://sourceforge.net/p/chocolate-doom/bugs/153/) on Sourceforge by [axdoom](https://sourceforge.net/u/axdoom/profile/), 2011-04-03 02:38:33:

You need to run Chocolate-Doom in windowed mode with grab mouse off and try to resize the window. There's two screenshots to show the problem. It's happening on Windows 2000 and XP but not on windows 7.

**Comment by jmtd** [comment]
@AXDOOMER , I've put up a dev build of sdl2-branch here http://jmtd.net/tmp/chocolate-doom-sdl2-branch-win32-dbg.zip

Could you please let me know whether you still have this problem, and if sdl2-branch fixes it?

**Comment by AXDOOMER** [comment]
This is a very very very old bug report. I don't have the computer on which it always happened anymore and I haven't seen this bug on newer systems for a while.

**Comment by jmtd** [comment]
Yes it is, I'm trying to close the oldest ones first. If I think it's fixed wit sdl2 but we can't confirm I'll just close them for now, we can always reopen them. Thanks for your report :)
