### ISSUE TITLE
NetBSD/i386 packages crash with segfault

### ISSUE THREAD

**Issue by sneakernets** [chocolate-doom/chocolate-doom#1542]
I know this probably isn't an issue _for_ here, but since NetBSD's Gnats tracker is hell on earth, I'm screaming here and hoping some pkgsrc maintainer sees it. I am not sure what to do at this point or what exactly is broken - I just know that it _is_ broken. 

### Background
NetBSD i386 packages are failing to start due to a segmentation fault
Version of Chocolate Doom:
3.0.1
Operating System and version:
NetBSD/i386 9.3
Game: (Doom/Heretic/Hexen/Strife/other)
Any
Any loaded WADs and mods (please include full command line):
No
### Bug description
Game crashes with a segfault
Observed behavior:
Game crashes before loading the title screen
Expected behavior:
title screen

**Comment by sneakernets** [comment]
Here are the core dumps. 
[coredump.zip.zip](https://github.com/chocolate-doom/chocolate-doom/files/9933845/coredump.zip.zip)

**Comment by turol** [comment]
Can you get a backtrace? I don't think NetBSD coredumps can be used on Linux.

**Comment by fragglet** [comment]
@sneakernets showed me a screenshot of a backtrace on Discord and the crash is inside the SDL libraries, so I don't think this is a Choco bug. I'm going to close this but it would be good to get some confirmation that other SDL programs crash in a similar way.

**Comment by fabiangreffrath** [comment]
Was this the obnoxious bug with SDL-Mixer causing fluidsynth to crash?

**Comment by sneakernets** [comment]
> @sneakernets showed me a screenshot of a backtrace on Discord and the crash is inside the SDL libraries, so I don't think this is a Choco bug. I'm going to close this but it would be good to get some confirmation that other SDL programs crash in a similar way.

They are. Seems to be something in SDL2 for sure.
