### ISSUE TITLE
MIDI stutter on track start when using hardware modules

### ISSUE THREAD

**Issue by Doomy65** [chocolate-doom/chocolate-doom#1547]
### Background

Version of Chocolate Doom: chocolate-doom-20221110-win32 (latest autobuild at time of posting)

Operating System and version: Windows 10 21H2

Game: Doom

### Bug description

Observed behavior: Midi tracks stutter at the initial beginning of playback when using hardware MIDI modules (in my case an SC-88VL), The first few notes will rush into each other before the rest of the track plays normally. Seems to be looping fine however. Can be recreated either when starting a new level, or when using IDMUS.

Expected behavior: Midi playback should be stutter free without any note rushing. In vanilla (from my limited DOSBox adventuring) the game seems to freeze for a second(ish) when using IDMUS to load a new track, but will begin playback afterward without any stutter. The stuttering also doesn't seem to occur in earlier versions of Chocolate (tested in 3.0.1).

### Additional Info

Just figured I'd leave this bug report here to follow on and document from discussions about the issue in a variety of sourceports found here: https://www.doomworld.com/forum/topic/131558-midi-stutter-on-track-start-and-when-looping-on-hardware-module/

**Comment by FozzeY** [comment]
Not reproduced on Sound Canvas VA, so it's definitely related to hardware.
PrBoom+ has a `mus_portmidi_reset_delay` config option which fixes the issue, perhaps a reset delay can be implemented here as well.

**Comment by ceski-1** [comment]
This is fixed in Woof, PrBoom+, DSDA-Doom, and now Chocolate Doom. Other source ports should soon follow. If you don't want to wait for an official release, you can try an autobuild/action or build from source.

If you look in the .cfg file you'll find a "delay after reset" setting. For real MIDI hardware modules, try around 100 to 300 (milliseconds). For everything else, just leave it at 0.

Woof and Chocolate:
```
winmm_reset_delay
```

PrBoom+ and DSDA-Doom:
```
mus_portmidi_reset_delay
```

**Comment by Doomy65** [comment]
Working flawlessly now with my SC-88VL after testing in the latest Chocolate Doom and Woof builds. I've set my delay to about 100 and can't notice any stutter!
