### ISSUE TITLE
Feature Request: Subtitles/Captions

### ISSUE THREAD

**Issue by RestlessRodent** [chocolate-doom/chocolate-doom#1568]
This is a feature request for sub-titles/captioning. I know it is not exactly vanilla, but I could implement this myself if there were a realistic expectation such a feature would get merged in... otherwise there would be no point in wasting my own time.

Visually, it would probably be similar-ish to Half-Life 2's and Minecraft's subtitle systems, but with directional indicators and counts. It would not use the Doom font, but rather something more sensible like a monospaced font that is centered on the screen with transparency matching the amplitude of a sound. Would be configurable but default being black on white.

example: `<<< Sound (Count) >>>`

Where the `<` are indicators on how far the balance is on a given speaker... that is the amplitude on the left/right channels.

Count would be the approximate number of times a sound has played such as: Once, Twice, Three, Many, Dozens, Hundreds. Naturally if dozens of monsters woke up at the same time their sound would be extremely loud as the sounds stack upon each other.

**Comment by rfomin** [comment]
I would like to see such a feature, but perhaps it is more suitable for Crispy Doom, which already has some accessibility features https://github.com/fabiangreffrath/crispy-doom/pull/755

**Comment by turol** [comment]
Not in scope for this project. Like @rfomin said it fits better in Crispy.
