### ISSUE TITLE
key_menu_back / Mouse 1 (Right) Double Binding Issue

### ISSUE THREAD

**Issue by JoLiKMC** [chocolate-doom/chocolate-doom#1569]
### Background
Version of Chocolate Doom: 3.0.1
Operating System and version: Windows 10 Professional, version 22H2, build 19045.2364
Game: _Doom / Doom II_
Any loaded WADs and mods (please include full command line):
`chocolate-doom.exe` \ `chocolate-doom.exe -iwad DOOM1.WAD`

### Bug description
Observed behavior:
If `key_menu_back` shares a bind with anything else, Mouse Button 1 (Right Mouse) will do whatever that "anything else" is.  If Mouse Button 1 is bound to anything at all, Double-clicking Mouse Button 1 will execute that function.  For example, if `key_menu_back` and `key_menu_decscreen` are both bound to Key 14 (Backspace), and `mouseb_use` is set to `1`, then pressing Mouse Button 1 will decrease the screen size while double-clicking Mouse Button 1 will make the player try and activate something in front of them.

Expected behavior:
Mouse Button 1 _should_ share functionality with `key_menu_back`, as per Vanilla _Doom_, but it should _not_ share functionality with anything bound to the same key as `key_menu_back`.
If Mouse Button 1 is bound to anything in the Mouse Configuration, then it should do that task.
If Mouse Button 1 is _not_ bound to anything in the Mouse Configuration, then it should do nothing at all.

**Comment by mikeday0** [comment]
I'm guessing this might do the trick:

```diff
diff --git a/src/doom/m_menu.c b/src/doom/m_menu.c
index baf01e33..073b8a12 100644
--- a/src/doom/m_menu.c
+++ b/src/doom/m_menu.c
@@ -1478,7 +1478,7 @@ boolean M_Responder (event_t* ev)
     }
     else
     {
-       if (ev->type == ev_mouse && mousewait < I_GetTime())
+       if (ev->type == ev_mouse && mousewait < I_GetTime() && menuactive)
        {
            mousey += ev->data3;
            if (mousey < lasty-30)

```
