### ISSUE TITLE
Commit 825f59b broke cross-compiling from mingw-w64

### ISSUE THREAD

**Issue by Aerocatia** [chocolate-doom/chocolate-doom#1573]
Commit 825f59bb89733078b572cd8557ab7e4001f2e9f6 broke cross compiling from mingw-w64

It now fails to link:
```
/usr/lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld: /usr/x86_64-w64-mingw32/lib/libSDL2main.a(SDL_windows_main.o):(.text+0x152): undefined reference to `SDL_main'
```

**Comment by rfomin** [comment]
If #1574 doesn't work, try disabling the `CMAKE_FIND_PACKAGE_PREFER_CONFIG` option: https://github.com/chocolate-doom/chocolate-doom/blob/825f59bb89733078b572cd8557ab7e4001f2e9f6/CMakeLists.txt#L31
