### ISSUE TITLE
Music doesn't seem to loop properly when Fluidsynth is used

### ISSUE THREAD

**Issue by thekovic** [chocolate-doom/chocolate-doom#1592]
### Background

Version of Chocolate Doom: latest master, x64 build

Operating System and version: Windows 10 21H2 64-bit

Game: Doom (others likely affected)

Any loaded WADs and mods (please include full command line): none

### Bug description

Observed behavior:
When the music track runs out, there's roughly 3 seconds of silence before the music starts over again.

Expected behavior:
When using other music methods (for example, AdLib emulation), the music loop is completely seemless and without moments of silence.

**Comment by mikeday0** [comment]
It's a known issue in FluidSynth 2.3.1. See: https://github.com/FluidSynth/fluidsynth/issues/1227 and https://github.com/fabiangreffrath/woof/issues/962

**Comment by thekovic** [comment]
I see, it was reported in fluidsynth itself a few days ago. I hope they get it fixed soon. In the meantime, I'll have to figure out how to downgrade the fluidsynth package in msys2 so that I can compile myself a version using 2.3.0

**Comment by mikeday0** [comment]
You might be able to just get away with replacing the dlls with those provided by the official FluidSynth release found [here](https://github.com/FluidSynth/fluidsynth/releases/tag/v2.3.0).

**Comment by mikeday0** [comment]
Looks like version 2.3.2 is released, but I'm not sure how long it will take for it to find its way into msys2.

**Comment by thekovic** [comment]
Since the issue is fixed in upstream, I think this issue can be closed now. Thank you.
