### ISSUE TITLE
Linux, Native MIDI, Error loading midi: Couldn't open /tmp/timidity.cfg

### ISSUE THREAD

**Issue by Rathmox** [chocolate-doom/chocolate-doom#1600]
### Background

Version of Chocolate Doom: 3.0.1

Operating System and version: Arch Linux

### Bug description

Observed behavior: No music, with error `Error loading midi: Couldn't open /tmp/timidity.cfg`

Expected behavior: Music played with TiMidity with the soundfont

I tried to use the EAWPATS soundfont with native MIDI, I selected the timidity.cfg from it, I modified it to point to the right directory, but I get the error `Error loading midi: Couldn't open /tmp/timidity.cfg`, and I get no music.

This issue doesn't happen on Crispy Doom

**Comment by turol** [comment]
Does this also happen with the latest git snapshot? The 3.0.1 release is quite old and there are a lot of music changes which are part of Crispy but not any Chocolate release.

**Comment by Rathmox** [comment]
It was exactly that, thanks
