### ISSUE TITLE
warnings and errors when running make

### ISSUE THREAD

**Issue by barnettg** [chocolate-doom/chocolate-doom#1609]
warnings and errors when running make
Ubuntu 22.04
Chocolate Doom V3.01 source

Example:

  CC       p_floor.o
  CC       p_inter.o
p_inter.c: In function ‘P_GivePower’:
p_inter.c:421:19: warning: array subscript 6 is above array bounds of ‘int[6]’ [-Warray-bounds]
  421 |     player->powers[power] = 1;
      |     ~~~~~~~~~~~~~~^~~~~~~
In file included from doomstat.h:34,
                 from p_inter.c:25:
d_player.h:122:25: note: while referencing ‘powers’
  122 |     int                 powers[NUMPOWERS];
      |                         ^~~~~~
  CC       p_lights.o
  CC       p_map.o
  CC       p_maputl.o

  CC       i_pcsound.o
  CC       i_sdlmusic.o
i_sdlmusic.c: In function ‘ReadSubstituteConfig’:
i_sdlmusic.c:653:9: warning: ignoring return value of ‘fgets’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  653 |         fgets(line, sizeof(line), fs);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  CC       i_sdlsound.o
  CC       i_sound.o

  CC       w_file_win32.o
  CC       w_merge.o
In file included from /usr/include/string.h:535,
                 from w_merge.c:23:
In function ‘strncpy’,
    inlined from ‘FindSpriteFrame’ at w_merge.c:219:5:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:95:10: warning: ‘__builtin_strncpy’ specified bound 4 equals destination size [-Wstringop-truncation]
   95 |   return __builtin___strncpy_chk (__dest, __src, __len,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   96 |                                   __glibc_objsize (__dest));
      |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~
  CC       z_zone.o
  CC       deh_io.o
  CC       deh_main.o
  CC       deh_mapping.o
  CC       deh_text.o
  CCLD     chocolate-doom
  CCLD     chocolate-heretic
  CCLD     chocolate-hexen
/usr/bin/ld: hexen/libhexen.a(g_game.o):/home/glen/doom/src/chocolate-doom-3.0.1/src/hexen/g_game.c:101: multiple definition of `demoextend'; hexen/libhexen.a(mn_menu.o):/home/glen/doom/src/chocolate-doom-3.0.1/src/hexen/mn_menu.c:134: first defined here
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:880: chocolate-hexen] Error 1
make[3]: Leaving directory '/home/glen/doom/src/chocolate-doom-3.0.1/src'
make[2]: *** [Makefile:1088: all-recursive] Error 1
make[2]: Leaving directory '/home/glen/doom/src/chocolate-doom-3.0.1/src'
make[1]: *** [Makefile:585: all-recursive] Error 1
make[1]: Leaving directory '/home/glen/doom/src/chocolate-doom-3.0.1'
make: *** [Makefile:438: all] Error 2

**Comment by jacobrogers256** [comment]
The Debian/Ubuntu source package for Chocolate Doom contains all the patches needed to fix the various compilation issues of Chocolate Doom 3.0.1

Use "apt source chocolate-doom" to get a fixed copy.

**Comment by turol** [comment]
The 3.0.1 release is really old and at least some of these are already fixed in git.

**Comment by jacobrogers256** [comment]
Why don't you guys make a new release?

**Comment by fabiangreffrath** [comment]
https://github.com/chocolate-doom/chocolate-doom/commit/3b1f3899c29aed3b767c2039541a9f51be9702a8
https://github.com/chocolate-doom/chocolate-doom/commit/56d1487bd65daefced1fb2eaab54ff79c9295585
https://github.com/chocolate-doom/chocolate-doom/commit/9a8f5dc9d9e9ec83e49b53daf208ea39b01fdab4
https://github.com/chocolate-doom/chocolate-doom/commit/a8fd4b1f563d24d4296c3e8225c8404e2724d4c2
