### ISSUE TITLE
Test key

### ISSUE THREAD

**Issue by chocolate-import** [chocolate-doom/chocolate-doom#161]
> The following bug was [originally reported](https://sourceforge.net/p/chocolate-doom/bugs/161/) on Sourceforge by [axdoom](https://sourceforge.net/u/axdoom/profile/), 2011-04-17 05:07:12:

1- There's no Test key in the joystick menu.
2- It's not really working because when I press T, I can wait very long and nothing will happen \(but I can hear the music\). Then, Chocolate-Setup stop responding and I need to close it using Task Manager.

**Comment by AXDOOMER** [comment]
Old bug. I have never experienced this on newer computers and there is a Test key in the joysitck/gamepad menu.
