### ISSUE TITLE
No Image 

### ISSUE THREAD

**Issue by actraiser30** [chocolate-doom/chocolate-doom#1616]
Hello i have a Raspberry Pi 4 and build the latest version of chocolate doom
upon running i get no image only the sound/audio i can hear,i think is the sdl2.0.14 fault on sdl2.0.10 i did not have this issue before
how can i compile chocolate doom by using sdl2.0.10 ??

thank you

**Comment by turol** [comment]
You can compile with a specific SDL version by installing it yourself but you probably shouldn't.

This is not a Chocolate Doom bug and there's nothing we can do about it. You should take it up either with Raspberry OS maintainers or SDL upstream maintainers.
