### ISSUE TITLE
www.chocolate-doom.org is down!

### ISSUE THREAD

**Issue by mfrancis95** [chocolate-doom/chocolate-doom#1617]
<img width="1115" alt="Screenshot 2023-10-07 at 7 27 54 AM" src="https://github.com/chocolate-doom/chocolate-doom/assets/4574480/f8c5c172-340f-4f56-8789-b09e08bb70b2">

@fragglet

**Comment by ShinyMark** [comment]
I am also seeing the same thing. Is there any way I can help?

**Comment by mfrancis95** [comment]
Closing because the site is back. I'm not sure what the root cause was or if there was any discussion/triaging on this.
