### ISSUE TITLE
Sound Cut-Off Issue (FIXED)

### ISSUE THREAD

**Issue by Bob8459** [chocolate-doom/chocolate-doom#1646]
whenever I try to play chocolate doom the sound keeps cutting off and is extremely loud for some reason, I am on windows 11 and using SONY INZONE H3 headphones but the audio doesn't work on my speakers either.

**Comment by rfomin** [comment]
Try "Win-ucrt64" artifact from this page: https://github.com/chocolate-doom/chocolate-doom/actions/runs/7023299728
![image](https://github.com/chocolate-doom/chocolate-doom/assets/5077629/85c812a2-3aba-48ef-a35a-18eaf2e5c22e)

**Comment by Bob8459** [comment]
thank you this helped me
