### ISSUE TITLE
Sound problems (Heretic and Hexen)

### ISSUE THREAD

**Issue by Robbbert** [chocolate-doom/chocolate-doom#1651]
### Background

Version of Chocolate Doom:20231221-win32 (from the download page)

Operating System and version:Win10 x64

Game: (Doom/Heretic/Hexen/Strife/other): Hexen and Heretic

Any loaded WADs and mods (please include full command line):no command line

### Bug description

Observed behavior:Heretic: most sounds only play for less than a second and then cut out
                              Hexen: sounds cut out as above, invalid noises, and the sound is not like the real game

Expected behavior:Proper complete sounds.

**Comment by rfomin** [comment]
Try artifact from this page: https://github.com/chocolate-doom/chocolate-doom/actions/runs/7240680697

![image](https://github.com/chocolate-doom/chocolate-doom/assets/5077629/862f5844-3d25-4e73-92f6-c8ec5f319dbd)

**Comment by Robbbert** [comment]
Hi, that build fixes the problems with Heretic and Hexen.

I have a question about Doom, not sure it's a bug as such, but it is a little different to the real game.
- If I pick up one or more rifles together with something else, the sound of the rifle gets truncated
- If I pick up a minor item such as health, armour or bullets, the sound level is so low that I can't normally hear it unless I listen very closely. Is it possible somehow to raise the volume of these things?

**Comment by rfomin** [comment]
This is a quirk of original Doom: https://doomwiki.org/wiki/Sound_cutoffs

You can try Crispy Doom, which fixes some of these problems.

**Comment by Robbbert** [comment]
That doesn't explain the absence of sound with minor items, which is 100% a problem with chocolate doom, but works correctly with the real game.

Can you point me to a crispy version artifact that has the working heretic sound?

**Comment by rfomin** [comment]
> Can you point me to a crispy version artifact that has the working heretic sound?

Latest release should work: https://github.com/fabiangreffrath/crispy-doom/releases/tag/crispy-doom-6.0

**Comment by Robbbert** [comment]
I used the x64 doom build and it certainly has a lot of interesting features. It also fixed the rifle sound truncation, however it does nothing for the minor items volume. I'll keep using it though, as it has certain features that I like. I notice though when I type a cheat, it causes movement. Is there some setting to set the controls back to normal? (or I may have inadvertently turned something on).

**Comment by rfomin** [comment]
There is a program "crispy-setup.exe" where you can change the controls. I recommend asking questions elsewhere, e.g. https://discord.gg/5M8K6vQ

**Comment by Robbbert** [comment]
Thanks.

**Comment by Robbbert** [comment]
I figured out the sound problems. I was using Doom 2 ver 1.666 on my 98SE machine, but 1.9 with Chocolate Doom. There seems to be a few differences between them in various ways.

**Comment by mikeday0** [comment]
There is a config variable `use_libsamplerate` in your chocolate-*.cfg files. If it's set to something other than 0, I recommend changing `libsamplerate_scale` from its default `0.65` to `1.0`. This will give the sounds a little more volume.
