### ISSUE TITLE
Compilation Errors in Chocolate Doom on Debian: SDL2 and sound.c

### ISSUE THREAD

**Issue by edwinsaunders** [chocolate-doom/chocolate-doom#1661]
Hello chocolate-doom community,

I'm currently facing compilation errors while trying to build Chocolate Doom as per the instructions found in the Tracking Git section [here](https://www.chocolate-doom.org/wiki/index.php/Building_Chocolate_Doom_on_Debian) on my Debian Linux system. It seems to be related to SDL2, and specifically, the sound.c file. Below are some of the 80 pages worth of errors I'm seeing:

CC       sound.o
In file included from /usr/local/include/SDL2/SDL_events.h:36,
from /usr/local/include/SDL2/SDL.h:41,
from ../../textscreen/txt_sdl.h:24,
from ../../textscreen/txt_main.h:24,
from ../../textscreen/textscreen.h:23,
from sound.c:28:
/usr/local/include/SDL2/SDL_joystick.h: In function ‘SDL_LockJoysticks’:
/usr/local/include/SDL2/SDL_joystick.h:138:54: error: expected declaration specifiers before ‘SDL_ACQUIRE’
138 | extern DECLSPEC void SDLCALL SDL_LockJoysticks(void) SDL_ACQUIRE(SDL_joystick_lock);
| ^~~~~~~~~~~
/usr/local/include/SDL2/SDL_joystick.h:153:56: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘attribute’ before ‘SDL_RELEASE’
153 | extern DECLSPEC void SDLCALL SDL_UnlockJoysticks(void) SDL_RELEASE(SDL_joystick_lock);
| ^~~~~~~~~~~
/usr/local/include/SDL2/SDL_joystick.h:167:29: error: storage class specified for parameter ‘SDL_NumJoysticks’
167 | extern DECLSPEC int SDLCALL SDL_NumJoysticks(void);
| ^~~~~~~~~~~~~~~~
/usr/local/include/SDL2/SDL_joystick.h:167:1: warning: ‘visibility’ attribute ignored [-Wattributes]
167 | extern DECLSPEC int SDLCALL SDL_NumJoysticks(void);
| ^~~~~~

Version of Chocolate Doom: 3.0.1

**System Information:**
- Operating System: Debian Linux 12 bookworm
- Compiler Version: gcc 12.2.0
- Build Commands Used: ./autogen.sh, make

Game: (Doom/Heretic/Hexen/Strife/other)
Compilation of the /src/setup files

Any loaded WADs and mods (please include full command line):
I can't get that far

### Bug description
I get a long list of errors (80 pages worth) when I run 'make' that starts as seen above and ends with the following:

sound.c:406: error: expected ‘{’ at end of input
make[3]: *** [Makefile:439: sound.o] Error 1
make[3]: Leaving directory '/home/edwin/Downloads/chocolate-doom-dev/chocolate-doom/src/setup'
make[2]: *** [Makefile:1133: all-recursive] Error 1
make[2]: Leaving directory '/home/edwin/Downloads/chocolate-doom-dev/chocolate-doom/src'
make[1]: *** [Makefile:565: all-recursive] Error 1
make[1]: Leaving directory '/home/edwin/Downloads/chocolate-doom-dev/chocolate-doom'
make: *** [Makefile:418: all] Error 2

Observed behavior:
It won't compile successfully.

Expected behavior:
Successful compilation

If anyone has encountered a similar issue or has suggestions for troubleshooting, any guidance or insights would be highly appreciated.

Thank you for your time.

**Comment by mikeday0** [comment]
I don't think this is a Chocolate Doom issue. It looks like you are linking against a version of SDL2 that you built yourself from source. (I can tell because your chocolate-doom build is using `/usr/local/include` instead of `usr/include`). If this was your intention, you might want to look at how you built SDL2.

**Comment by edwinsaunders** [comment]
Thank you very much, @mikeday0 .  That was the issue.  I deleted the local build I did of the SDL2 library, and it reverted to using the system install, and everything built just fine with chocolate doom.  Thank you again.
