### ISSUE TITLE
Someone needs to send a GPL compliance email to Husqvarna AB

### ISSUE THREAD

**Issue by wertercatt** [chocolate-doom/chocolate-doom#1673]
https://www.husqvarna.com/uk/learn-and-discover/news-and-media/terms-and-conditions-for-doom-1993-automower-beta-update/

That company which recently announced they're putting Doom on their Lawnmowers is using Chocolate Doom, according to their EULA. And it doesn't look like they have any intention of respecting the GPL.

**Comment by AXDOOMER** [comment]
> The software includes the aggregated Chocolate Doom game engine software **adapted** for use on certain Husqvarna Automower® NERA robotic lawnmower models

Seems like they had to modify it, so yes they must release the source code, but the software itself hasn't been released at the moment. You can't ask for them to release the source code for something that hasn't been released yet. They may release the source code somewhere when it'll be available.

**Comment by fragglet** [comment]
I resolved this with these folks, and they were never in violation of the GPL.

**Comment by fabiangreffrath** [comment]
So where is their source code?

**Comment by wertercatt** [comment]
> So where is their source code?

https://github.com/husqvarnagroup/automower-doom
