### ISSUE TITLE
PK3 Support

### ISSUE THREAD

**Issue by actraiser30** [chocolate-doom/chocolate-doom#1680]
Hello

Is it possible to add support for *pk3* mod files ??

thanks

**Comment by turol** [comment]
No, this is way out of scope for Chocolate Doom.

**Comment by actraiser30** [comment]
You should consider add pk3 support as most of the total conversion mods
are based on them and a lot of people using gzdoom that is slow for example
on raspberry pi.

Thanks

**Comment by fabiangreffrath** [comment]
If you could take the time and read the very first sentence in Chocolate Doom's project description...
