### ISSUE TITLE
Strife: Mouse1 input is intermittedly dropped while moving

### ISSUE THREAD

**Issue by maxmanium** [chocolate-doom/chocolate-doom#1689]
### Background

Version of Chocolate Doom: 3.1.0

Operating System and version: Windows 11 23H2

Game: Strife

Any loaded WADs and mods (please include full command line): N/A

### Bug description

Observed behavior: Holding Mouse1 to fire, it seems to drop the input if you are doing anything else (e.g. moving around) every 1-3 seconds.

Expected behavior: Weapon continues firing while Mouse1 held, with no dropped inputs.

**Comment by ceski-1** [comment]
This is a vanilla bug. It's fixed in Crispy Doom: https://github.com/fabiangreffrath/crispy-doom/pull/1014

**Comment by maxmanium** [comment]
Oops. Don't know much about vanilla strife. What a strange bug for them to never patch. Thanks.

**Comment by maxmanium** [comment]
Oops. Don't know much about vanilla strife. What a strange bug for them to never patch. Thanks.
