### ISSUE TITLE
installation program / bash file for older RaspberryPi OS (Stretch) ?

### ISSUE THREAD

**Issue by dsyleixa** [chocolate-doom/chocolate-doom#1709]
where / which is an installation program / bash file for older RaspberryPi OS (Stretch) ?
I have a Pi 3B running by Stretch.
sudo apt-get install chocolate-doom does not work because Stretch files/dependencies are not available any more, not even adding --fix-missing:
```
sudo apt-get install chocolate-doom --fix-missing
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.        
Statusinformationen werden eingelesen.... Fertig
The following additional packages will be installed:
  freedm libsdl-net1.2
Die folgenden NEUEN Pakete werden installiert:
  chocolate-doom freedm libsdl-net1.2
0 aktualisiert, 3 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
Es müssen 5.745 kB an Archiven heruntergeladen werden.
Nach dieser Operation werden 22,2 MB Plattenplatz zusätzlich benutzt.
Möchten Sie fortfahren? [J/n] j
Fehl:1 http://raspbian.raspberrypi.org/raspbian stretch/main armhf libsdl-net1.2 armhf 1.2.8-4
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
Fehl:2 http://raspbian.raspberrypi.org/raspbian stretch/main armhf chocolate-doom armhf 2.3.0-3
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
Fehl:3 http://raspbian.raspberrypi.org/raspbian stretch/main armhf freedm all 0.10.1-2
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
Fehlende Pakete konnten nicht korrigiert werden.
E: Fehlschlag beim Holen von http://raspbian.raspberrypi.org/raspbian/pool/main/s/sdl-net1.2/libsdl-net1.2_1.2.8-4_armhf.deb  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
E: Fehlschlag beim Holen von http://raspbian.raspberrypi.org/raspbian/pool/main/c/chocolate-doom/chocolate-doom_2.3.0-3_armhf.deb  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
E: Fehlschlag beim Holen von http://raspbian.raspberrypi.org/raspbian/pool/main/f/freedoom/freedm_0.10.1-2_all.deb  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
E: Installation abgebrochen.
```

**Comment by fabiangreffrath** [comment]
Please try running `apt-get update` before.

**Comment by dsyleixa** [comment]
> Please try running `apt-get update` before.

of course I did that already

**Comment by dsyleixa** [comment]
this is what apt update does:#

sudo apt-get update
Ign:1 http://raspbian.raspberrypi.org/raspbian stretch InRelease
OK:2 http://archive.raspberrypi.org/debian stretch InRelease
Fehl:3 http://raspbian.raspberrypi.org/raspbian stretch Release                
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
Holen:4 http://deb.nodesource.com/node_9.x stretch InRelease [4.623 B]         
Paketlisten werden gelesen... Fertig                                           
E: The repository 'http://raspbian.raspberrypi.org/raspbian stretch Release' does no longer have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by fabiangreffrath** [comment]
Seems that Debian stretch has reached end-of-life. Please upgrade to a more recent distribution.

**Comment by dsyleixa** [comment]
no, that is no option, and that's actually the reason of my topic here!
(Finally all files are created, they just have to be installed other way round - but how?

**Comment by chungy** [comment]
I don't see clues online that Raspbian keeps old releases around. You have a couple major options: upgrade your OS, or switch to a different one (If you insist on Stretch, you can use Debian Stretch with the assistance of snapshot.debian.org).

Whichever way, this isn't a Chocolate Doom issue :)

**Comment by chungy** [comment]
You're always free to build it yourself, either from the repository or source tarball, but if you don't already have the compiler and library dependencies, you'll continue being out of luck on Raspbian Stretch.

**Comment by dsyleixa** [comment]
I don't understand you, to be honest - 
I have installed Stretch, all files are on my Pi, so I only need all the relevant chocolate files to access my  OS to run.
Just like for Windows XP which is on an old Computer: 

E.g., I can install Borland C++ Builder 4.0 or even Arduino IDE 1.5 or Pinnacle Studio 9  from either source - It doesn't matter if Windows XP is still available somewhere on the net hosted by MS or if it's deprcated or not 
- I simply don't need the OS source again to install the apps, because the OS is already on my PC.

**Comment by dsyleixa** [comment]
I don't understand you, to be honest - 
I have installed Stretch, all files are on my Pi, so I only need all the relevant chocolate files to access my  OS to run.
Just like for Windows XP which is on an old PC: 

E.g., I can install Borland C++ Builder 4.0 or even Arduino IDE 1.5 or Pinnacle Studio 9  from either source - It doesn't matter if Windows XP is still available somewhere on the net hosted by MS or if it's depricated or not 
- I simply don't need the OS source again to install the apps, because the OS is already on my PC.
- I only need the files of the app, a related installation program ("setup.exe")  to copy the app files, and to write setup entries to the registry etc pp.

**Comment by dsyleixa** [comment]
I don't understand you, to be honest -
I have installed Stretch, all files are on my Pi, so I only need all the relevant chocolate files to access my OS to run.
Just like for Windows XP which is on an old PC:

E.g., I can install Borland C++ Builder 4.0 or even Arduino IDE 1.5 or Pinnacle Studio 9 from either source - It doesn't matter if Windows XP is still available somewhere on the net hosted by MS or if it's depricated or not

    I simply don't need the OS source again to install the apps, because the OS is already on my PC,
    I don't need a compiler to compile already compiled things like exe and dll file binaries and helper files or Windws system files
    I only need the files of the app, a related installation program ("setup.exe") to copy the app files, and to write setup entries to the registry etc pp.
    and that's just all what I would need for chocolate doom for Stretch.

**Comment by dsyleixa** [comment]
I don't understand you, to be honest -
I have installed Stretch, all files are on my Pi, so I only need all the relevant chocolate files to access my OS to run.
Just like for Windows XP or 7 which is on an old PC:

E.g., I can install either Windows XP/7 compatible app from either source - It doesn't matter if Windows XP/7 is still available somewhere on the net hosted by MS or if it's depricated or not:

- I simply don't need the OS source again to install the apps, because the OS is already on my PC,
- I don't need a compiler to re-compile already compiled things like exe and dll file binaries and helper files or Windows system files.
 - I only need the files of the app, a related installation program ("setup.exe") to copy the app files into the correct target directories and subdirs, and perhaps to write setup entries to the registry etc pp.  - or just a zip file with all and everything to c+p+extract
- and that's just all what I would need for chocolate doom for Stretch.

**Comment by chungy** [comment]
You're expecting a Windows model that doesn't quite apply to this Linux distribution. Raspbian has (apparently?) removed the software repositories for their fork of Debian Stretch, unless you can find an archive of old releases, you can't properly install software on it anymore. If you're lucky, it was a soft fork, and you can maybe install proper Debian Stretch packages on it, but I can't tell if you if that was the case.

We're not going to put in the work of supporting a Linux distribution release so old that even the repository has disappeared, if it's even possible to get to the point of building a binary. We don't provide precompiled Linux binaries of any kind, even; that has always been left to distributions (since they can manage the dependency trees properly and such).
