### ISSUE TITLE
ChocoDoom not crashing in craplift.wad

### ISSUE THREAD

**Issue by chocolate-import** [chocolate-doom/chocolate-doom#173]
> The following bug was [originally reported](https://sourceforge.net/p/chocolate-doom/bugs/173/) on Sourceforge by [axdoom](https://sourceforge.net/u/axdoom/profile/), 2011-05-23 02:36:57:

I found this wad somewhere on Doomworld but I don't remember where on Doomworld.
The person was saying it was crashing and bla bla...

After some tests with Ultimate Doom, I found that it's crashing in Vanilla and not in Chocolate \(crash rarely in Choco\).

The file is below with some demos. Uppercase name are Vanilla and lowercase name are Chocolate.

**Comment by AXDOOMER** [comment]
This bug seems fixed. I tested and Chocolate-Doom always crashes.

**Comment by haleyjd** [comment]
Is crashing at the OS level actually acceptable now? I was specifically instructed by fraggle during Choco Strife development that we should not be crashing but rather 1. elide the behavior safely if vanilla continued with no consequences or 2. detect the condition and exit the program gracefully with an I_Error if it did not. I pity the fool inappropriately running a choco dedicated server under a privileged linux account if we start taking the OS-level crash as a suitable response, to be frank.

**Comment by jmtd** [comment]
In this case we are catching this with an I_Error -- although there are a few cases of recursive I_Error calls happening (which are also caught) so there's some room for improvement.

**Comment by haleyjd** [comment]
Ah ok, thanks.

**Comment by fabiangreffrath** [comment]
> Is crashing at the OS level actually acceptable now?

God forbid, please no!

 - Fabian
