### ISSUE TITLE
f_ep2myk.lmp won't crash win32-r2342

### ISSUE THREAD

**Issue by chocolate-import** [chocolate-doom/chocolate-doom#179]
> The following bug was [originally reported](https://sourceforge.net/p/chocolate-doom/bugs/179/) on Sourceforge by [porschemonty](https://sourceforge.net/u/porschemonty/profile/), 2011-06-14 08:18:22:

While testing the alleged f\_ep2 demo crash from the other thread, I noticed this minor non-vanilla behavior: f\_ep2myk.lmp won't crash chocolate. When the demo is played back in vanilla \(Ultimate\), it immediately closes down with "Demo is from a different game version\!", whereas chocolate doesn't and proceeds like it's nobody's business.

I even tried "-gameversion 1.9" but to no avail, it just won't crash.

The command line I used for both vanilla and chocolate: -file f\_ep2.wad -playdemo f\_ep2myk

Wad download: http://doomedsda.us/lmps/1461/f\_ep2.zip
Demo download: http://doomedsda.us/lmps/1461/11/f\_ep2fda\_myk.zip

Tested on WinXP Pro SP3.

Regards.

**Comment by jmtd** [comment]
my understanding of the above is, the demo works in c-d because it's long tics, which are explicitly supported, and obviously vanilla doesn't.
