### ISSUE TITLE
Par times not hidden in Final Doom after idclev or reload 

### ISSUE THREAD

**Issue by chocolate-import** [chocolate-doom/chocolate-doom#200]
> The following bug was [originally reported](https://sourceforge.net/p/chocolate-doom/bugs/200/) on Sourceforge by [axdoom](https://sourceforge.net/u/axdoom/profile/), 2011-10-04 21:41:21:

I found this bug on the doomwiki engine bug page. This bug isn't emulated in Chocolate-Doom.

**Comment by AXDOOMER** [comment]
Emulation of hidden par bug in Final Doom by @khokh2001 here: https://github.com/chocolate-doom/chocolate-doom/pull/594

**Comment by jmtd** [comment]
@CapnClever fixed this in some recent work I believe, thanks
