### ISSUE TITLE
The cursor isn't hidden in fullscreen

### ISSUE THREAD

**Issue by chocolate-import** [chocolate-doom/chocolate-doom#231]
> The following bug was [originally reported](https://sourceforge.net/p/chocolate-doom/bugs/231/) on Sourceforge by [axdoom](https://sourceforge.net/u/axdoom/profile/), 2012-02-14 01:17:51:

The cursor doesn't disappear when the game starts in fullscreen and it stays in the middle of the screen. 
It can be fixed by disabling the graphical startup. 

Tested on Windows 7

**Comment by chungy** [comment]
I've tested this on both Windows 7 and 10, real hardware and virtual machines, cannot reproduce this bug. @AXDOOMER Does this still affect you?

**Comment by AXDOOMER** [comment]
I guess it was fixed. It does not happen on my current computer.

**Comment by chungy** [comment]
Thanks
