### ISSUE TITLE
Double display mode

### ISSUE THREAD

**Issue by chocolate-import** [chocolate-doom/chocolate-doom#237]
> The following bug was [originally reported](https://sourceforge.net/p/chocolate-doom/bugs/237/) on Sourceforge by [axdoom](https://sourceforge.net/u/axdoom/profile/), 2012-05-04 01:18:05:

I tried Chocolate-Doom 1.99.0 on a computer I never used before and I found this while changing the resolution. Some display modes are doubled.

These are doubled \(see the screenshot\): 
640x480
768x1024
800x600
1024x768

**Comment by jmtd** [comment]
Hey @AXDOOMER, can you remember anything about which OS/version you were using when this bug came up? I'd like to see if it happens with SDL2 branch. Thanks!

**Comment by AXDOOMER** [comment]
Windows XP. Must be SP3 Pro 32-bit.

**Comment by chungy** [comment]
Do you still have access to the computer with the issue?

**Comment by AXDOOMER** [comment]
No.

**Comment by chungy** [comment]
OK. It was probably an odd driver. I'll close this issue, at least unless anyone else can produce a system with the results (and the SDL2 port hasn't been completed by then)

**Comment by AXDOOMER** [comment]
XP is obsolete and yes, I think it was related to the drivers.
