### ISSUE TITLE
Implementation of hardware-based scaling

### ISSUE THREAD

**Issue by chocolate-import** [chocolate-doom/chocolate-doom#246]
> The following bug was [originally reported](https://sourceforge.net/p/chocolate-doom/bugs/246/) on Sourceforge by [twipley](https://sourceforge.net/u/twipley/profile/), 2012-08-23 23:02:51:

fraggle has written: "Ideally what I ought to be doing is investigating how to do \[scaling\] using OpenGL," adding, some months later, "that's the route I want to go down."

Such an objective, indeed, has been driven from time-ripen reflection from the part of the fraggle mind -- reflection concerning a definite issue in relation to modern monitors, springing from the fact that while the original resolution is of 320x200, the intended aspect ratio is of 4:3, therefore leaving no room at all\* for adequate integer-factor scaling.

As the mastermind notes, the solution best capable, at the same time, of achieving, on the one hand, proper scaling, and on the other, proper aspect-ratio output, might well be residing in the future implementation of an OpenGL-based hardware scaler.

\* outside of having to resort to 1600x1200 monitors or the like;

**Comment by jmtd** [comment]
Fixed in sdl2-branch I believe.
