### ISSUE TITLE
Add random sound pitch

### ISSUE THREAD

**Issue by chocolate-import** [chocolate-doom/chocolate-doom#274]
> The following bug was [originally reported](https://sourceforge.net/p/chocolate-doom/bugs/274/) on Sourceforge by [paar86](https://sourceforge.net/u/paar86/profile/), 2013-10-03 14:06:50.287000:

Would it be possible to add random sound pitch (or at least make it toggleable in the setup)? It was present in early versions of Doom but was removed in version 1.4 probably due to a bug (some problem with a sound library). The random pitch is back in console ports.

**Comment by jmtd** [comment]
I've been working on this slowly over the last couple of weeks, I should have something to show people in the next week or so.

**Comment by fabiangreffrath** [comment]
That would be awesome!

**Comment by derek57** [comment]
I'd also like to see a solution to this.

**Comment by derek57** [comment]
Maybe this can help as Strawberry DOOM is a Chocolate fork:

http://sourceforge.net/p/strawberry-doom/code/commit_browser

(Starting at R22)

**Comment by jmtd** [comment]
I've looked at the approach used in strawberry doom, as well as one of the doom legacy forks, and eternity. I have some ideas about how to integrate into the current sound code in C-D, but at the moment I'm focusing on making sure the pitch shifting I've implemented is as close to the original as is possible.

**Comment by twipley** [comment]
Interesting! I cannot wait to see this in action!

**Comment by jmtd** [comment]
I think I'm about 90% done on this. I've written a pitch-shifter, and I've done the integration work in c-d to run it, but I haven't bodged it into c-d yet as I need to rework bits of it for a different sample size (it presumed u8 samples which was a mistake!). That last bit shouldn't take me very long.

I've pushed the integration work with a place-holder pitch shifter that just reverses 50% of sound effects for anyone who is curious https://github.com/jmtd/chocolate-doom/tree/pitch-shifting - it means I have something that builds and I can test that all the integration work is OK and there are no memory leaks etc.

I must say some of the sound effects sounds pretty good backwards. I wonder whether doom retro would be interested in doing it for select sound effects, a bit like their sprite-flipping, heh.

**Comment by jmtd** [comment]
This can now be closed.

**Comment by fragglet** [comment]
\o/
