### ISSUE TITLE
Chocolate Doom not building on Mac OS X 10.9

### ISSUE THREAD

**Issue by golergka** [chocolate-doom/chocolate-doom#322]
Error message I get after trying to build it with the [script](http://www.chocolate-doom.org/wiki/index.php/Building_Chocolate_Doom_on_Mac_OS_X):

In file included from ./src/video/quartz/SDL_QuartzEvents.m:24:
./src/video/quartz/SDL_QuartzVideo.h:94:5: error: unknown type name 'CGDirectPaletteRef'
    CGDirectPaletteRef palette;            /* palette of an 8-bit display */

**Comment by fragglet** [comment]
No response in over a year; closing bug.

**Comment by sneakernets** [comment]
I believe this was a problem with XQuartz and not SDL. There's still an issue of SDL applications breaking on the secondary monitor.

**Comment by fragglet** [comment]
SDL bugs aren't our responsibility. I'd hope that #450 will make the story for multi-monitor setups better.

**Comment by fabiangreffrath** [comment]
> I'd hope that #450 will make the story for multi-monitor setups better.

Which reminds me... there's still a lot of work to do in this branch.
