### ISSUE TITLE
Chocolate Doom doesn't play well with tiling WMs

### ISSUE THREAD

**Issue by fragglet** [chocolate-doom/chocolate-doom#331]
Tried running in i3 but the game is unplayable because the screen is constantly trying to resize because it thinks the window size has been changed slightly.

The video code should check for the case where it is constantly trying to resize to a particular screen size and give up after several(?) attempts.

**Comment by chungy** [comment]
This bug should be resolved with SDL2. I don't think there ought to be much effort in fixing the SDL1.2 port for it, at this time.

**Comment by jmtd** [comment]
Would either of you guys be prepared to see how well sdl2-branch handles this now?

**Comment by fragglet** [comment]
Seems better, yes.
