### ISSUE TITLE
V_MarkRect() is a no-op and what the heck is dirtybox[]?

### ISSUE THREAD

**Issue by fabiangreffrath** [chocolate-doom/chocolate-doom#335]
Hi Simon,

chocolate-doom's source code is cluttered with calls to V_MarkRect(). This function calls M_AddToBox(), which in turn adds the coordinates to dirtybox[]. However, dirtybox[] is not further processed anywhere in the code, so I believe that this chain is a no-op and should better get removed from the source code.

 - Fabian

**Comment by jmtd** [comment]
All gone

**Comment by fabiangreffrath** [comment]
> All gone

I am not sure what you mean?

```
$ grep  MarkRect -r src/ | wc -l
26
```
