### ISSUE TITLE
mm09-512.lmp desync

### ISSUE THREAD

**Issue by fragglet** [chocolate-doom/chocolate-doom#368]
Desyncs on Mac OS X; haven't tried other platforms. It has been desyncing since the 2.0.0 release, at least. Player dies halfway through the level.

This is in the Compet-N archive in pwads/mm/speed/mm09-512.zip

**Comment by haleyjd** [comment]
Have you checked the map for a short reject?

**Comment by AXDOOMER** [comment]
The reject lump is 37265 bytes long.

**Comment by haleyjd** [comment]
OK and how many sectors does the map have? "Short" reject means a reject that is not large enough for the map in terms of sectors. Minimum correct reject size is `(((numsectors * numsectors) + 7) & ~7) / 8`

**Comment by AXDOOMER** [comment]
The sectors lump has 546 entries. The minimum size is exactly 37265 using your formula.

**Comment by haleyjd** [comment]
So much for that theory then. It was the easiest/simplest possible cause and so the best to eliminate first. This will require much deeper digging now.

**Comment by fabiangreffrath** [comment]
It's playing through in Crispy Doom, no shit!

**Comment by fabiangreffrath** [comment]
> It's playing through in Crispy Doom, no shit!

Well, that is, it desyncs as soon as I set use_libsamplerate to 0 in crispy-doom.cfg. Funnily, though, it still plays through when I run it with -nosound even then. The following patch makes the demo play through in Crispy Doom independent of the value of use_libsamplerate and the -nosound parameter. Sadly, it doesn't work in Chocolate Doom, though, and I have no idea why it fixes Crispy as well:

```
--- a/src/i_sdlsound.c
+++ b/src/i_sdlsound.c
@@ -651,8 +651,10 @@ static boolean CacheSFX(sfxinfo_t *sfxinfo)
     // need to load the sound
 
     lumpnum = sfxinfo->lumpnum;
-    data = W_CacheLumpNum(lumpnum, PU_STATIC);
+//    data = W_CacheLumpNum(lumpnum, PU_STATIC);
     lumplen = W_LumpLength(lumpnum);
+    data = malloc(lumplen);
+    W_ReadLump(lumpnum, data);
 
     // Check the header, and ensure this is a valid sound
 
@@ -709,7 +711,8 @@ static boolean CacheSFX(sfxinfo_t *sfxinfo)
 
     // don't need the original lump any more
   
-    W_ReleaseLumpNum(lumpnum);
+//    W_ReleaseLumpNum(lumpnum);
+    free(data-16);
 
     return true;
 }

```

**Comment by fabiangreffrath** [comment]
Alright, I got this. The reason for the desync is that the floor->crush flag is left uninitialized for a specific floor in EV_BuildStairs() which is called at leveltime 2860. Instead, the flag is set to whatever data was saved at this memory region before, so the chance being non-zero is higher if more zone-memory has been occupied before, e.g. for pre-caching of sound effects.

Setting it to a "random" value fixes the desync:
```
--- a/src/doom/p_floor.c
+++ b/src/doom/p_floor.c
@@ -536,6 +536,7 @@ EV_BuildStairs
                floor->sector = sec;
                floor->speed = speed;
                floor->floordestheight = height;
+               floor->crush = 10;
                ok = 1;
                break;
            }

```

Thanks to Valgrind, PrBoom-Plus and GDB for helping me find this. ;)

**Comment by fragglet** [comment]
Nice! Awesome to see that we've got a proper fix - I really wasn't comfortable about the idea of random hacks to the sound code that coincidentally happened to fix the problem.

Unfortunately Doom's zone memory allocator often tends to make these kinds of issue hard to track down properly.

**Comment by haleyjd** [comment]
That isn't the only uninitialized field here (see http://doomwiki.org/wiki/Stairs_create_unknown_sector_types ). See either BOOM v2.02 or SVE for the full fix.

**Comment by fabiangreffrath** [comment]
Yes, there are more occurences of uninitialized fields around this code:
```
$ grep STAIRS_UNINITIALIZED_CRUSH_FIELD_VALUE -nr prboom-plus/src
p_floor.c:47:#define STAIRS_UNINITIALIZED_CRUSH_FIELD_VALUE 10
p_floor.c:158:                if (crush == STAIRS_UNINITIALIZED_CRUSH_FIELD_VALUE)
p_floor.c:819:            floor->crush = STAIRS_UNINITIALIZED_CRUSH_FIELD_VALUE;
p_floor.c:834:            floor->crush = STAIRS_UNINITIALIZED_CRUSH_FIELD_VALUE;
p_floor.c:914:            floor->crush = STAIRS_UNINITIALIZED_CRUSH_FIELD_VALUE;
```
I think we should fix them all while at it. 

However, there are still some oddities surrounding this code:

1) In Boom and MBF, the fields are only initialized "if (!demo_compatibility)". Nevertheless, both ports manage to play back the demo flawlessly. May I assume they are reading uninitialized memory in these cases?

2) The floor->type fields are also left uninitialized and Boom sets them to "buildStair". However, this floor type is not defined in Choco. Should we simply set this field to 0 then, i.e. lowerFloor?

3) PrBoom-Plus sets the crush field to 10 in the "if (demo_compatibility)" case (compare(1)) which seems a rather arbitrary value. Given that the field is of type boolean and is thus 32-bit wide and given that anything non-zero is considered "true" in C, there is a 1/2^32 chance that the field gets set to "false" from uninitialized memory. Shouldn't we simply set this field to "true" then? Why on earth does PrBoom-Plus set it to 10?

**Comment by haleyjd** [comment]
The problem is really that some values may desync some demos while making others sync. This error falls squarely into the "impossible to emulate perfectly" category because it relies on uninitialized memory pulled from the heap. I do not know entryway's justification for "10"; I'm guessing though that he probably dumped the memory from vanilla running under DOS or from Doom95 and used the same value that was present during demo playback.

Boom and MBF are only sync'ing the demo by accident, since their idea of a fallback is to persist in undefined behavior.

Adding "buildStair" was a solution for defining a unique type for stair building floor thinkers so that they wouldn't accidentally fall into any other type. SVE does the same thing by necessity (but our goals there are just to fix the bug, not to try to be compatible with it - not that there are Strife demos anyways to worry about :smiley: )

**Comment by fabiangreffrath** [comment]
> The problem is really that some values may desync some demos while making others sync. This error falls squarely into the "impossible to emulate perfectly" category because it relies on uninitialized memory pulled from the heap. 

Since PrBoom+ sets this value to "10" (i.e. "true") in the "if (demo_compatibility)" case and is known for its adequate demo playback, I assume it is safe to set it to "true" in Choco as well. Chances are rather low that it will read "false" from random memory.

> I do not know entryway's justification for "10"; I'm guessing though that he probably dumped the memory from vanilla running under DOS or from Doom95 and used the same value that was present during demo playback.

I have asked Andrey via e-mail. This is his reply:

> Sorry, I just don't remember. 10 was a random value i think

> Adding "buildStair" was a solution for defining a unique type for stair building floor thinkers so that they wouldn't accidentally fall into any other type.

I am not sure about this field, but it doesn't seem to make such a huge difference in the case at hand.

**Comment by fabiangreffrath** [comment]
So, @fragglet, let's get this issue off the table. How are we going to fix it? 

I propose the following:
- Unconditionally set the floor->crush fields to "true" in all three occurrences.
- Leave the other fields uninitialized.
- Add comments.

Do you want to fix it yourself or will you accept patches?

**Comment by fragglet** [comment]
That's functionally equivalent to what PrBoom+ is doing, right? Assuming so, let's do it.

I'm happy to fix it though I don't have much time at the moment. Or you can fix it if you wish.

**Comment by fabiangreffrath** [comment]
> That's functionally equivalent to what PrBoom+ is doing, right? Assuming so, let's do it.

Not exactly, PrBoom+ is also setting floor->type to a harmless dummy (that would need to get added to enum floor_e, though).

**Comment by fabiangreffrath** [comment]
> that would need to get added to enum floor_e, though

Either that, or we unconditionally set the floor->type field to e.g. lowerFloor, i.e. 0. 
Looking at T_MoveFloor(), anything but donutRaise, i.e. 11, and lowerAndChange, i.e. 6, should be safe.

**Comment by fabiangreffrath** [comment]
Damnit,I first pushed it to the wrong branch. I still had the sdl2-branch checked out, sorry! :(

**Comment by fabiangreffrath** [comment]
Gosh, and I messed up the logic in the commit message! Sorry, i was too tired. /o\
