### ISSUE TITLE
Blank screen in Framebuffer mode on Raspberry Pi thru RCA (default options)

### ISSUE THREAD

**Issue by sneakernets** [chocolate-doom/chocolate-doom#396]
I am not sure if this is a Raspi-specific bug, but in composite (RCA) mode, chocolate-doom shows a black screen and hangs if ran through the framebuffer. In HDMI mode, this problem does not occur.

I did some googling and it appears that the framebuffer is lost, but can be regained if SSH'd into.

This might help us: http://www.raspberrypi.org/forums/viewtopic.php?t=6680&p=90534

"I have managed to get it to run on the console - in composite video mode, but never in HDMI mode. Even in composite mode, it's a real fiddle - having to use one of their default video modes and catering for overscan - trying to force a screen size works OK for X, but never for my app 
So when I really want 640x480, I set framebuffer_width=784, framebuffer_height=638 and (start), then I get a 640x480 screen, but if I try to start my app. in 640x480 mode on the framebuffer before starting X it crashes the Pi"

Is there a way to implement a check of the framebuffer size?

**Comment by jmtd** [comment]
@sneakernets, is this fixed with sdl2-branch?

**Comment by sneakernets** [comment]
Yes, this is fixed, but only if one uses the RetroPie libraries. I will be writing up a document on how to obtain these libraries soon.

**Comment by jmtd** [comment]
I put a quick note at https://www.chocolate-doom.org/wiki/index.php/Raspberry_Pi#Chocolate_Doom_v3_.28sdl2-branch.29 , this should be expanded (but with that I'll close this issue)
