### ISSUE TITLE
When mute music, mute sfx sound too 

### ISSUE THREAD

**Issue by doomgay** [chocolate-doom/chocolate-doom#397]
It can fix?

**Comment by Zodomaniac** [comment]
For some reason it works correctly now! :)

**Comment by CapnClever** [comment]
For the record, SDL2_mixer did not fix this bug. At least, it's not fixed in Win7.

> For some reason it works correctly now! :)

@Zodomaniac Are you using Win10? If so then that might be the "solution".

**Comment by Zodomaniac** [comment]
@CapnClever No, I'm using Win7 Home Premium :) maybe it got updated and the Windows mixer bug has been squashed?
