### ISSUE TITLE
Chocolate-Doom changes the screen resolution permanently on Linux

### ISSUE THREAD

**Issue by AXDOOMER** [chocolate-doom/chocolate-doom#399]
On Linux Mint, if I set Chocolate-Doom's screen resolution to 640x480 and that my desktop resolution was 1920x1080, my desktop resolution will become 640x480 when I quit Chocolate-Doom. 

Then I need to use "xrandr -s 1920x1080" or run Chocolate-Doom again at 1920x1080 to set my desktop resolution back to normal. 

Tested on Linux Mint.

**Comment by AXDOOMER** [comment]
I think this is distro specific. Some other Linux distributions are not effected by this bug.

**Comment by jmtd** [comment]
Closing this because sdl2-branch will fix it.
