### ISSUE TITLE
CPU consumption

### ISSUE THREAD

**Issue by fabiangreffrath** [chocolate-doom/chocolate-doom#418]
Hi fraggle,

this is not an actual bug, but merely a question if I understand things correctly.

When running chocolate-doom in a 640x480 window, "top" reports it consumes roughly between 5%-10% of my CPU time. That is on a i7-3520M quad-core at 2,9 GHz. I remember Doom eating up 100% CPU on my old i486/33MHz in 1993, but I assume my current system to be more than factor 10-20 more powerful.

Is this expected behaviour? Is there an actual culprit known in the rendering pipeline? I repeated a similar test with Crispy Doom and the CPU consumption is a fair bit higher, though not exactly by a factor 2. So is this really just the software renderer pushing pixel by pixel to the framebuffer the bottleneck?
- Fabian

**Comment by fabiangreffrath** [comment]
This may be related to https://github.com/chocolate-doom/chocolate-doom/commit/d6556ee4b4d9d2c4c9ac48f998bd387f5416b75d, now "top" reports CPU consumption between 3% and 4% for chocolate-doom on my system.

**Comment by AXDOOMER** [comment]
You're right. On a Intel Core2, where the difference is more noticeable, it went from ~26% to ~15%. The performance change will be substantial on the Raspberry Pi.

**Comment by fragglet** [comment]
Interesting. I'd expect the CPU to halve after that commit on machines where we can run at full FPS (as most CPU is spent in scaling and we're halving the number of rendered frames). Sounds like that's what's happened.

Improvement for the Raspberry Pi has already been noticed.
