### ISSUE TITLE
Chocolate Doom should enforce the PWAD size limit

### ISSUE THREAD

**Issue by fragglet** [chocolate-doom/chocolate-doom#430]
Vanilla Doom doesn't like WADs with more than 4046 lumps:

http://www.doomworld.com/vb/source-ports/57163-surprising-strict-limit-on-pwad-size-in-vanilla-doom/

**Comment by edward-san** [comment]
Thanks for fixing the '4096' typo and for adding the comment!

**Comment by jmtd** [comment]
No problem (my brain kept auto-correcting to 4096 too); sorry it took so long to merge this!
