### ISSUE TITLE
The screen's color depth is not changed to match the chosen setting

### ISSUE THREAD

**Issue by AXDOOMER** [chocolate-doom/chocolate-doom#457]
My desktop is in true colors 32-bit. 
If I start Chocolate-Doom in windowed mode with a color depth of 8-bit or 16-bit, the screen remains in 32-bit per pixel. 

This doesn't occur in fullscreen mode because I can see the color degradation of the gray that goes toward the green in dark areas. 

BTW, is it possible to do a better translation from the 8-bit palette to the 16-bit screen? I know this is a common problem with 16-bit because it as one more bit for the green. Like I said above, some colors tend to become greener, but maybe I'm just wrong and the translation is already done to the best accurate result possible.

**Comment by jmtd** [comment]
We don't want to change the OS BPP. No suggestion that window rendering BPP is wrong.
