### ISSUE TITLE
Hexen segfaults upon Loading first demo on RasPi

### ISSUE THREAD

**Issue by sneakernets** [chocolate-doom/chocolate-doom#475]
I will be tracking this one down personally with GDB and will post the results soon.

Compiler: gcc-4.8
OS: Raspian Stable
Firmware: current (as of this date)
Running in 640x400 windowed.

Stack trace indicates:
```
#0 0x0004afe0 in P_PlayerThink()
```

I'll compile with no optimizations, and see if I can still trigger it.

**Comment by haleyjd** [comment]
@sneakernets Were you using the 1.1 IWAD for this?

**Comment by sneakernets** [comment]
I'm not sure - I'll have to check!

**Comment by sneakernets** [comment]
As Choco didn't check Hexen versions back when I reported this, it was discovered later that I was using a 1.0 IWAD even though my source disk stated that it was v1.1. However, Chocolate-doom shouldn't segfault as this may cause issues on some OSes.

**Comment by fabiangreffrath** [comment]
AFAIK v1.0 is the retail version and all v1.1 versions have been patched once.

**Comment by sneakernets** [comment]
.....Well, then that explains a lot (I got this CD years ago at a flea market).

**Comment by haleyjd** [comment]
Just for posterity, in case similar things happen in the future, what finally tipped me off was the fact that P_SpawnPlayer only got called 4 times. This means players 5 through 8 had their data read out of ticcmds in the demo stream and this is what was causing the memory corruption.

**Comment by fabiangreffrath** [comment]
Yes, the same maxplayers = 4 fix that was required for Demo support would also need to get applied for 1.0 support.
