### ISSUE TITLE
Code under incompatible license

### ISSUE THREAD

**Issue by haleyjd** [chocolate-doom/chocolate-doom#479]
Code in files aes_prng.c and sha1.c states that it is under the GNU GPLv3, which is incompatible with the GPLv2. I'd be tempted to allow you to ignore this if the copyright holder were not the Free Software Foundation.

**Comment by fabiangreffrath** [comment]
This is the latest snapshot before they changed the license to GPL-3+:
http://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg.git;a=tree;h=49c49918b0e18b84ab5b242d796e36cdc6215710;hb=f54b85bc2d9b80f40ee025f74857fb3bb1436f9a

**Comment by fabiangreffrath** [comment]
An, sorry, that was from the GnuPG 2.0 branch!

This is the current implementation from libgcrypt:
http://git.gnupg.org/cgi-bin/gitweb.cgi?p=libgcrypt.git;a=blob;f=cipher/sha1.c;hb=HEAD

and this is the latest implementation from GnuPG 1.x under GPL-2+:
http://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg.git;a=blob;f=cipher/sha1.c;h=d150fad1e4e757a64cbda3f7bb62e965e916ec4a;hb=960ac800487dbc9d91bbef005fee4ecbfae72e83

**Comment by fabiangreffrath** [comment]
Same for AES/Rijndael:

http://git.gnupg.org/cgi-bin/gitweb.cgi?p=libgcrypt.git;a=blob;f=cipher/rijndael.c;hb=HEAD

http://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg.git;a=blob;f=cipher/rijndael.c;h=e52e01e96a608bc8add27785e7053c88fdd540c0;hb=960ac800487dbc9d91bbef005fee4ecbfae72e83

**Comment by fragglet** [comment]
Not yet fixed because we need to do the same for sha1.c.

**Comment by fabiangreffrath** [comment]
Now that I have a bug filed in Debian about this, I have thought about the issue again: How could the GPLv2-or-later and the GPLv3-or-later be considered incompatible with each other? Do we have any GPLv2-only code in Choco?

[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=785122

**Comment by haleyjd** [comment]
GPLv3 is not compatible with GPLv2, it's that simple. If you are going to link GPLv3 code into a project that is GPLv2+, you are obligated to utilize the upgrade option at that point.

Date: Tue, 19 May 2015 23:37:03 -0700

**Comment by chungy** [comment]
I think the main issue is that fraggle intends to keep Chocolate Doom licensed as v2-or-later. Otherwise he could have resolved it by just upgrading the whole project to v3.

**Comment by fragglet** [comment]
GPLv3 is compatible with GPLv2-or-later via the upgrade clause, which is precisely why there is no problem here and I'm not worrying about this mistake. If it helps then just imagine that the last release as having been GPLv2/GPLv3 dual-licensed.

That's all I'm going to say about this because I don't think this is a useful or productive conversation and I'd like to draw it to a close. I still need to replace the sha1.c code and then I'll be closing the bug.

**Comment by fabiangreffrath** [comment]
Thank you for clarifying this, @fragglet!
Do you think this warrants a point release? I mean, the previous two releases were accidentally released under an unintended license, and technically we do at least have support for the Hexen Demo now.

**Comment by chungy** [comment]
If I may comment about it, I have my own [chocolate-doom-2.1](https://github.com/chungy/chocolate-doom/tree/chocolate-doom-2.1) branch that I've used primarily for the purpose of patching the Arch Linux package. The patches for substitute audio fixes were so soon after the release I decided to include them, and the setup patch fixes a crash with too many IWADs. Just a suggestion for a place to start. It's hard to say what a "stable branch" of Chocolate Doom should be properly.

**Comment by fragglet** [comment]
Sure, I'm not opposed to doing another release. We're probably not doing releases regularly enough anyway.

Only thing that needs to be done is to revert the OPL MIDI changes from a couple of months ago that screw up some tracks (see #468) - or maybe we need to merge #516? Either way I don't want to ship with broken OPL output.

**Comment by fragglet** [comment]
Side note that's completely unrelated:

Would there be any interest in a Chocolate Doom mailing list? Chat like this seems like it would fit a mailing list and I've been wondering if a mailing list would be nice to have.

**Comment by sneakernets** [comment]
#468 code is fine, on OPL2 the guitar solos will cut off near the end all the time. What is really needed is the OPL3 code merge.

**Comment by haleyjd** [comment]
Footnote 3 on the FSF's own GPL FAQ contradicts:
"3: If you have the ability to release the project under GPLv2 or any later version, you can choose to release it under GPLv3 or any later version—and once you do that, you'll be able to incorporate the code released under GPLv3."
IANAL, but Eben Moglen is last time I checked.

**Comment by fragglet** [comment]
@haleyjd - I gave my answer already and the problem has now been resolved in Git. Is there anything productive in continuing to debate this? What are we hoping to achieve?

**Comment by haleyjd** [comment]
I just wanted to be clear why I brought up the issue in the first place, and your previous comment seems to insinuate that my initial statement about incompatibility is factually incorrect, while AFAIK, it is accurate.

I know you want to keep Choco v2+ so I was surprised to find v3 code in it while we were working on SVE. This was an actual problem for us - the terms of our contracts specifically named GPLv2+ as the license the code was being provided under, and when I found this code I had to expunge it (by doing the same replacement I initially suggested) in order to be by-the-letter with this. I wasn't going to risk messing with the FSF's copyrights in a commercial project. Other than that, I don't have more to say.

**Comment by fragglet** [comment]
I do indeed want to keep the project v2+ and the inclusion of v3 code was an honest mistake on my part. I'm sorry that it caused you problems during the Strife VE development.

That said, in project terms I don't really see this as a huge deal - for example for the reasons I've given I don't see the 2.1 release as illegal and we're certainly still well within the spirit of the GPL. While we could sit around and try to argue over the details of the licenses, I don't think it's likely to achieve anything useful, especially as none of us are copyright lawyers anyway.

I like Fabian's suggestion that we put out a new release. Other than that I'm not sure that there's anything else we can do to put this to rest.

**Comment by haleyjd** [comment]
Yeah I agree. Thanks.

**Comment by fabiangreffrath** [comment]
> Would there be any interest in a Chocolate Doom mailing list? Chat like this seems like it would fit a mailing list and I've been wondering if a mailing list would be nice to have.

Yes, sure, why not. Is it possible to set one up on Github or do we need to go elsewhere for this?

**Comment by fragglet** [comment]
I actually already set it up last night. Please send an email to chocolate-doom-dev-list+subscribe@chocolate-doom.org
