### ISSUE TITLE
exits with a segfault instead of vpo

### ISSUE THREAD

**Issue by chocolate-import** [chocolate-doom/chocolate-doom#48]
> The following bug was [originally reported](https://sourceforge.net/p/chocolate-doom/bugs/48/) on Sourceforge by [gammafactorial](https://sourceforge.net/u/gammafactorial/profile/), 2008-09-29 22:26:47:

chocolate-doom -file shdwpit.wad -warp 01 exits with a segmentation fault instead of the visplane overflow message like the exe

**Comment by jmtd** [comment]
WAD in question: http://www.doomworld.com/idgames/levels/doom2/deathmatch/Ports/s-u/shdwpit

**Comment by fabiangreffrath** [comment]
This happens because `R_CheckPlane()` does not have a check if `MAXVISPLANES` is reached before making a new one and `R_FindPlane()` only checks for `(lastvisplane - visplanes == MAXVISPLANES)`, not `>=`.

**Comment by mfrancis95** [comment]
You can add a NULL check to the visplane in `R_CheckPlane` and error out early, and this seems to catch it, but I don't think this is the most ideal way of solving the issue.

```diff
diff --git a/src/doom/r_plane.c b/src/doom/r_plane.c
index 16dde4c2..db882e57 100644
--- a/src/doom/r_plane.c
+++ b/src/doom/r_plane.c
@@ -266,7 +266,11 @@ R_CheckPlane
     int		unionl;
     int		unionh;
     int		x;
-	
+    if (pl == NULL)
+    {
+        I_Error ("R_DrawPlanes: visplane overflow (%" PRIiPTR ")",
+         lastvisplane - visplanes);
+    }
     if (start < pl->minx)
     {
 	intrl = pl->minx;
```

**Comment by mfrancis95** [comment]
So @fabiangreffrath could that be merged in? Is there anything else that would need to be done?

**Comment by fabiangreffrath** [comment]
I expressed some objections against your approach, but have none against mine. :wink: Could you confirm that it works as expected?

**Comment by AXDOOMER** [comment]
Is something else than the VPO wrong with this map? It won't even run in Doom+. It locks up with the music playing, either there's a missing player 1 start position or there's more than 1024 visplanes. I don't have tools to check.

**Comment by AXDOOMER** [comment]
@fabiangreffrath I implemented your fix in my source port and it works as expected. 

https://github.com/AXDOOMER/doom-vanille/commit/56ccf3adebefc669e59df453d707e3cbaaff6d61
