### ISSUE TITLE
libsamplerate-enabled Win32 binaries?

### ISSUE THREAD

**Issue by PorscheMonty** [chocolate-doom/chocolate-doom#486]
Forgive me this my comment, shall it be mistaken for a problem, given the place it's being published at, as so far I've had none, but is there a libsamplerate-enabled Win32 build of the latest official release anywhere on the web? there used to be one, even a svn, but it seems it's been taken down or moved to another host.

Thank you Fraggle+contributors for such an amazing work, and sorry for the inconvenience.

**Comment by haleyjd** [comment]
Failing that, even just having a linear interpolation pass and low-pass filter (I see one in the code, but it seems to be conditionally enabled, so I don't know if it's being used or not) during sound effect conversion would be nice. As-is, sounds have noise, and those that are high sample rate (22050) stick out sorely compared to the rest, and I think these factors are partially to blame. Choco's sound quality is distinctly lower than EE, though, perhaps it is closer to DMX in that regard (maybe somebody can do some spectroscopic analysis :sound: :ear: :stuck_out_tongue: )

**Comment by fragglet** [comment]
As an encore to Chocolate Strife, can we have a new project to reverse engineer DMX? :)

**Comment by PorscheMonty** [comment]
I can't remember if DMX actually upsamples 11khz to 22khz or downsamples 22khz to 11khz before presenting the mixed stream to the audio hardware, but regardless or what happens at that stage, it is an utmost necessity that it's output be properly upsampled and the inherent aliasing filtered out so that we don't get this vile, polluting frying egg hiss, because the sample rates we're upsampling to these days are way too heavy for the aliasing to be adequately managed by anything DMX could have possibly offered, specially with OPL signals mixed in, which should be generated at the original clock rate and up/down-sampled to the closest matching native sample rate available to the system for retention of maximum quality.

Nevertheless, without re-enabling libsamplerate (sinc), which's as good as it gets, everything else is an exercise of futility.

Regards.

**Comment by fragglet** [comment]
With the v3.0 release this is now fixed - we distribute libsamplerate binaries now.
