### ISSUE TITLE
.lmp extension appending on case-sensitive systems

### ISSUE THREAD

**Issue by ioan-chera** [chocolate-doom/chocolate-doom#501]
Doom automatically and always adds the .lmp extension to the -playdemo/-timedemo parameter. There's a problem on case sensitive systems (e.g. GNU/Linux) where .lmp files extracted from old ZIPs tend to come out as .LMP. The program won't recognize them so the user has to rename them to .lmp. This was of no concern on vanilla Doom because it has always run on case-insensitive systems.

**Comment by chungy** [comment]
I'm not really sure how big of an issue it is. It should only really crop up for those that purposefully don't use the full file name, which seems a little unusual. Additionally, having explicit support for *.LMP just opens the door for more suggestions to support *.Lmp and *.LmP and all other forms, with very little gain. Personally I think it's easier to just remember to use `unzip -L` if this really matters to you.

(Seems similar to how the IWAD file names are only automatically detected with lower-case names)

**Comment by fragglet** [comment]
I don't think this is a problem because ​Chocolate Doom already supports
passing the whole filename to -playdemo and -timedemo. For example if your
file is named "FOOBAR.LMP" you can just run with -playdemo FOOBAR.LMP.
There's no need to rename it to FOOBAR.lmp and run with -playdemo FOOBAR.

**Comment by ioan-chera** [comment]
Actually it won't detect the extension from the parameter unless it ends with `.lmp` (lowercase). So `FOOBAR.LMP` will be changed to `FOOBAR.LMP.lmp` and will fail. Code proof (in `D_DoomMain`):

    if (M_StringEndsWith(myargv[p + 1], ".lmp"))

**Comment by fragglet** [comment]
Ah, okay. I wasn't aware of that. That should be the fix for this bug then.

**Comment by fabiangreffrath** [comment]
Maybe M_StringEndsWith() should do a case-insensitive compare.

**Comment by fabiangreffrath** [comment]
We could explicitly check for the upper-case variant as well.
```
--- a/src/doom/d_main.c
+++ b/src/doom/d_main.c
@@ -1477,7 +1477,8 @@ void D_DoomMain (void)
     {
         // With Vanilla you have to specify the file without extension,
         // but make that optional.
-        if (M_StringEndsWith(myargv[p + 1], ".lmp"))
+        if (M_StringEndsWith(myargv[p + 1], ".lmp") ||
+            M_StringEndsWith(myargv[p + 1], ".LMP"))
         {
             M_StringCopy(file, myargv[p + 1], sizeof(file));
         }
```

**Comment by AXDOOMER** [comment]
I have built Chocolate-Doom from the latest source code. Let's say I have two demo files in my home folder, they are named "BUNKER.LMP and bunker.lmp".

First, if I do:
-playdemo bunker: It works
-playdemo BUNKER: Doesn't work
-playdemo bunker.lmp: Works
-playdemo BUNKER.LMP: Works

If I add a copy of the file named "BUNKER.lmp", then "-playdemo BUNKER" will work. 

Second, if I want to load a demo that doesn't exist: 
-playdemo boubou.lmp
It will say "W_GetNumForName: boubou.l not found!"
Only height characters are displayed. Doesn't Chocolate-Doom support long file names?

Do these two tests result in the expected/appropriate behavior?

**Comment by fragglet** [comment]
This is really a byproduct of the awkward syntax fur the -playdemo argument that auto appends the .lmp extension. I think the best answer is that you should just provide the full filename.

**Comment by PorscheMonty** [comment]
@fragglet: "Chocolate Doom already supports passing the whole filename to -playdemo and -timedemo"

In a completely theoretical and unimaginably unlikely scenario, wouldn't this be a problem if somebody were using CD for recording vanilla demos and decided to create a batch file referencing the whole name of the demos (which he'd have presumed to work in vanilla as well) for a speedy launching (as it often happened back in the day) just to have rather unseasoned vanilla users comment that it wouldn't work?

Regards.
