### ISSUE TITLE
turning mouse wheel may lead to lock-up in Hertic and Hexen

### ISSUE THREAD

**Issue by fabiangreffrath** [chocolate-doom/chocolate-doom#503]
Hi fraggle,

this has been reported against Crispy Doom here:
http://www.doomworld.com/vb/post/1335057

Summary:
In Heretic & Hexen, if you scroll the mouse wheel in the main menu the game locks. Doom and Strife do not. 

Actually, this bug is also reproducible with Chocolate Heretic if you apply some action (e.g. change to prev and next weapon) to the mouse wheel "buttons". The main difference is that these mappings are set by default in Crispy Doom/Heretic.

The main reason for the lock is that in Heretic and Hexen, the MN_Responder() function refuses to "eat" mouse events and these are thus passed over to the G_Responder() function, This, in turn, tries to change weapons in a game that hasn't even started. Boom.

The following patch should fix this:
```
--- a/src/heretic/mn_menu.c
+++ b/src/heretic/mn_menu.c
@@ -1083,6 +1083,10 @@ boolean MN_Responder(event_t * event)
         }
     }
 
+    if (event->type == ev_mouse)
+    {
+        return true;
+    }
     if (event->type != ev_keydown)
     {
         return false;
```

**Comment by fragglet** [comment]
Thanks for the report, though I have reservations about the patch you've proposed to fix it. If there's a problem with the weapon cycling code, we should just fix it - rather than "papering over" the problem by changing the menu code so that the problem code isn't executed.

**Comment by fabiangreffrath** [comment]
I agree that the first patch I proposed in the initial post is just band-aid. But the second patch is not: It copies code from Doom, which is missing in Heretic and Hexen. If you comment out that specific block of code in Doom, it will hang in the menu as well.

**Comment by fabiangreffrath** [comment]
> But the second patch is not: It copies code from Doom, which is missing in Heretic and Hexen. If you 
> comment out that specific block of code in Doom, it will hang in the menu as well.

Hm?

**Comment by fragglet** [comment]
Pushed out a proper fix for the weapon cycling infinite loop.

> But the second patch is not: It copies code from Doom, which is missing in Heretic and Hexen. 

Is there any need for this patch? I don't understand the need for it.

I performed a quick check - ran chocolate-heretic, waited for the first demo to start, then hit a key, and the menu appeared. So what is this fixing?

**Comment by fabiangreffrath** [comment]
> Is there any need for this patch? I don't understand the need for it.

It forces any user input to open the menu when the title screen is active and thus prevents it from slipping through into the actual game controls.

>  performed a quick check - ran chocolate-heretic, waited for the first demo to start, then hit a key, and the menu appeared. So what is this fixing?

Well, the game actually locked in the title screen. If you waited for the demo it wouldn't. ;)

However, your patch is fine. I think it is the GS_LEVEL check that actually fixes the issue at hand.
