### ISSUE TITLE
Bleeding edge builds download page doesn't work

### ISSUE THREAD

**Issue by AXDOOMER** [chocolate-doom/chocolate-doom#505]
It says "Server error!"

http://www-users.cselabs.umn.edu/~delbe001/chocolate-doom/
http://www-users.cselabs.umn.edu/~delbe001/chocolate-doom-gl-branch/

**Comment by fabiangreffrath** [comment]
@delbel Could you please have a look at this?

**Comment by delbel** [comment]
I moved the builds to my http://exp.mancubus.net space and updated the links on the wiki.

**Comment by fabiangreffrath** [comment]
Thanks! I think we can close this issue then.
