### ISSUE TITLE
[RPMLINT] Program is likely to break with new gcc

### ISSUE THREAD

**Issue by posophe** [chocolate-doom/chocolate-doom#507]
I: Program is likely to break with new gcc.
W: chocolate-doom strict-aliasing-punning aes_prng.c:693, 702, 725, 732, 740, 748, 781, 782, 783, 785, 786, 787, 789, 790, 791, 793, 794, 795, 805, 806, 807, 809, 810, 811, 813, 814, 815, 817, 818, 819

**Comment by fabiangreffrath** [comment]
This coincides with https://github.com/chocolate-doom/chocolate-doom/issues/479, this code needs urgent replacement.
