### ISSUE TITLE
manpages use hyphens as minus signs

### ISSUE THREAD

**Issue by fabiangreffrath** [chocolate-doom/chocolate-doom#512]
Hi again,

in the manpages created by docgen, command line parameters are recited with leading minus signs, e.g. -devparm. The joke is that in troff, unescaped minus signs are hyphens and actual minus signs need to get escaped, e.g. \-devparm. If this isn't done properly, it is impossible to copy&paste command line parameters from manpages into the shell via double-click/middle-click.

I would fix this myself, but I am not fluent in Python at all. :/

 - Fabian

**Comment by fabiangreffrath** [comment]
For reference: https://lintian.debian.org/tags/hyphen-used-as-minus-sign.html

**Comment by fragglet** [comment]
You should learn Python!

![xkcd 353](https://sslimgs.xkcd.com/comics/python.png)

But seriously though, this should be relatively easy to fix. I'll take a look when I have time.

**Comment by chungy** [comment]
@fabiangreffrath Could you pull from chungy/chocolate-doom master to see if this fixes your issue?

It's just a very simple string replacement. Maybe not suitable if an actual hyphen is desired, but at the same time, the source text could just include U+2010 when such is intended.

**Comment by fragglet** [comment]
Looks good.
