### ISSUE TITLE
support playing music in OGG/FLAC formats from lumps in PWADs

### ISSUE THREAD

**Issue by fabiangreffrath** [chocolate-doom/chocolate-doom#513]
I have another one...

For quite some time it is possible to play replacement music in Chocolate Doom by calling the -dumpsubstconfig command line parameter and maintaining the music as separate files in $HOME/.chocolate-doom/music. But how about music in OGG/FLAC format that is stored in lumps inside PWADs? Currently, the required workflow is to "deutex -x" the PWAD, copy the lumps into the music directory below ~/.chocolate-doom and adjust file names and extensions while at it.

This sounds quite inconvenient to me and could actually be abbreviated, since the file format of the music lumps is supported out-of-the-box. We simply do not attempt to properly read them.

What I have in mind is this:
https://github.com/fabiangreffrath/crispy-doom/commit/db85196419046554c4ffc7db0e9ab60391151c59

Do you think this is acceptable as "workflow shortcut" for Choco or is this out of scope?

Cheers,

Fabian

**Comment by fragglet** [comment]
You're talking about PWADs that include Ogg files inside music lumps rather than .MUS or .MID data? If so, that's definitely out of scope.

**Comment by fabiangreffrath** [comment]
Yes, that's what I was talking about. Good we have cleared that.
