### ISSUE TITLE
Undefined behavior in D_DoomMain

### ISSUE THREAD

**Issue by haleyjd** [chocolate-doom/chocolate-doom#519]
The line:
```I_AtExit((atexit_func_t) G_CheckDemoStatus, true);```
is in violation of Annex J.2 section 6.3.2.3 of the ISO C standard because of the fact that the function is invoked with a different signature:

"A pointer to a function of one type may be converted to a pointer to a function of another type and back again; the result shall compare equal to the original pointer. If a converted pointer is used to call a function whose type is not compatible with the pointed-to type, the behavior is undefined."

Indeed, while it's likely to work on most architectures due to use of a regular calling convention which renders void and word-returning functions indistinguishable at the assembly level, this is no guarantee. A purely stack based architecture for example might push return values and thus leave the stack unbalanced after the return.

**Comment by fabiangreffrath** [comment]
Would it help if atexit_func_t was turned into a union of void and boolean?

**Comment by haleyjd** [comment]
No, that would make it worse.

The simple solution is to register a thunk for G_CheckDemoStatus that has void (void) signature.

**Comment by fabiangreffrath** [comment]
You mean something like
```
void G_CheckDemoStatusAtExit (void)
{
  G_CheckDemoStatus ()  
}
```
and then
```
I_AtExit((atexit_func_t) G_CheckDemoStatusAtExit, true);
```
?

**Comment by haleyjd** [comment]
Yes except you no longer need and should not have the cast there, as it implies a conversion is taking place where one is not.
