### ISSUE TITLE
Every menu in the setup tool should have a wiki help page

### ISSUE THREAD

**Issue by fragglet** [chocolate-doom/chocolate-doom#520]
The setup tool contains a nested set of menus of configuration options. Each of these menus ought to have an associated wiki page that describes all of the items on that page (along with a screenshot) and describes what they do. This would help in the case of some of the more complicated windows, such as the mouse configuration window, where the process to configure your mouse is non-obvious (it's documented at http://www.chocolate-doom.org/wiki/index.php/Mouse_configuration - but as far as I know that's not linked anywhere).

The libtextscreen library then ought to support associating a help URL with each window, and display an "F1=Help" entry in the bar at the top of the screen when the top (active) window has an associated help page.

These pages should be arranged in the wiki in some kind of structured/ordered way that can then be turned into something better resembling a proper user guide. The current "User guide" is kind of an unstructured collection of random things that probably isn't the most helpful thing ever.

**Comment by fragglet** [comment]
The wiki page on the setup tool can be a start:

http://www.chocolate-doom.org/wiki/index.php/Setup

I've added some broken links to pages to be created.

**Comment by chungy** [comment]
I've uploaded screenshots of all the screens taken from a Windows 7 computer, likely to be the most common OS that users will have for the moment. I've written up at least a page for the display configuration, hopefully with language that's neither too technical nor too condescending, but it's a difficult balance.

**Comment by fragglet** [comment]
Looks great, thanks!

**Comment by fragglet** [comment]
For reference, 356554c22998264769a5c516697cbfbd43847ce4 and 710e963acad611dfd1c5780d9f68f6ef91e93a22 added help URLs for the pages that have been created so far. We still need docs for multiplayer setup. The wiki has a "Multiplayer" page that explains how to set up a multiplayer game from the command line, but it's really not very good - the setup tool is integrated with the master server now for server browsing, which leaves a lot of the content of that page obsolete. In the context of creating a help page for the setup tool we need to completely rewrite it.

**Comment by AXDOOMER** [comment]
^ Doesn't work on Windows. It only opens the console.

**Comment by fragglet** [comment]
Ah, thanks for letting me know. The code uses the "start" command which I assumed would be sufficient to open a URL, but I guess that doesn't work. It seems the correct way is to use the ShellExecute API:

https://support.microsoft.com/en-us/kb/224816

**Comment by fragglet** [comment]
I committed what I believe may fix the issue on Windows; can someone confirm?

**Comment by AXDOOMER** [comment]
I'd test it, but the latest bleeding edge build is dated May 12th, so looks like the automatic builds are broken again. I don't want to build it manually, it's too much of a hassle on Windoze.

**Comment by fragglet** [comment]
@AXDOOMER exp(x)'s build server has stopped building new versions and it seems that he won't be able to run the daily builds any more. I set up a replacement server:

http://latest.chocolate-doom.org/

If you can check if the URLs open now that would be really helpful.

**Comment by AXDOOMER** [comment]
Ok, I'll check that now.

**Comment by AXDOOMER** [comment]
It just opens the console. Once the console is opened, if I type "start www.google.com" or "cmd /c www.google.com" directly in the console, it opens the browser to the desired webpage.

**Comment by chungy** [comment]
Seems like a fairly easy change to make, i've sent a pull request to hopefully fix it. Seems to work under Wine, do you mind testing this binary to see that it works in Windows itself too?

https://dl.dropboxusercontent.com/u/13513277/doom/chocolate-doom-shellexec.zip

**Comment by chungy** [comment]
I've just gotten confirmation from a Windows user that it works. Success :P

**Comment by chungy** [comment]
This issue should be resolved now, except that the redirects set up on the web server for e06b8d3e5a650a61307d644eae1269a64817c02b still do not point to the Setup/* pages directly.

**Comment by fragglet** [comment]
This should now be fixed, thanks.

There's a bug in that the "Warp" window's help link redirects to the "Start multiplayer game" page due to shared code.
