### ISSUE TITLE
-dumpsubstconfig handled at wrong layer of game engine

### ISSUE THREAD

**Issue by haleyjd** [chocolate-doom/chocolate-doom#528]
The code for -dumpsubstconfig, to generate music substitution configuration files, is embedded into the SDL_mixer MIDI driver and as a result, this command line parameter is unnecessarily ignored if the user's music device setting does not result in the activation of that subsystem. This is a fine example of something being implemented inside the wrong layer of abstraction.

This code ought to be moved upward into the shared music engine initialization code, or what EE would refer to as the "HAL".

We first ran into this during SVE development and just had the problem come up again as a result of a user trying to understand how the substitution system works.

**Comment by fragglet** [comment]
Arguably this could be considered related to #440. But we can fix this more easily without needing to fix that as well.
