### ISSUE TITLE
Fails to parse DEHACKED files without newline at EOF

### ISSUE THREAD

**Issue by fabiangreffrath** [chocolate-doom/chocolate-doom#531]
Hi,

currently Chocolate Doom fails to properly parse the last line in DEHACKED files that are missing a newline character at the end of the file (which might have been a common sickness in DOS editors).

This is, because DEH_GetChar() returns -1 at EOF and DEH_ReadLine() in turn immediately returns NULL if the result of (DEH_GetChar() < 0), regardless of the content of the readbuffer. It only returns a pointer to the content of the readbuffer if DEH_GetChar() returns '\n' which is, however, impossible if there is no such character before the file ends.

I propose the following patch, which only returns NULL if the readbuffer is empty at the end of the file and returns a valid pointer else:
```
--- a/src/deh_io.c
+++ b/src/deh_io.c
@@ -235,7 +266,7 @@ char *DEH_ReadLine(deh_context_t *context, boolean extended)
     {
         c = DEH_GetChar(context);
 
-        if (c < 0)
+        if (c < 0 && pos == 0)
         {
             // end of file
 
@@ -282,7 +313,7 @@ char *DEH_ReadLine(deh_context_t *context, boolean extended)
             escaped = false;
         }
 
-        if (c == '\n')
+        if (c == '\n' || c < 0)
         {
             // end of line: a full line has been read
 
```

**Comment by fragglet** [comment]
Looks like this is probably fine, but what happens if the 'escaped' flag is set? ie. file ends in a backslash?

**Comment by fabiangreffrath** [comment]
Nothing should happen, because "escaped" is only checked for in conjunction with isspace(c) which returns "false" for c=-1.

**Comment by fragglet** [comment]
It would be a good idea to add a c >= 0 check to the start of this expression:

        if (escaped && isspace(c) && c != '\n')

Because different compilers / C libraries can give different results for isspace() and I wouldn't rely on the behavior you've observed working everywhere.

**Comment by fabiangreffrath** [comment]
> It would be a good idea to add a c >= 0 check to the start of this expression

I'll do so. Is it alright to get commited then?

**Comment by fragglet** [comment]
Sounds good.

**Comment by fabiangreffrath** [comment]
This could have been another, maybe cleaner, approach. Should I revert and apply this instead?

```
--- a/src/deh_io.c
+++ b/src/deh_io.c
@@ -204,6 +204,11 @@ int DEH_GetChar(deh_context_t *context)
         ++context->linenum;
     }
 
+    if (result < 0 && !context->last_was_newline)
+    {
+        result = '\n';
+    }
+
     context->last_was_newline = result == '\n';
 
     return result;
```

**Comment by fragglet** [comment]
Late reply, but I think the patch as applied is fine.

**Comment by fabiangreffrath** [comment]
Alright, thank you. This other patch appeared in my mind's eye literally a minute after I pushed the current one. ;)
