### ISSUE TITLE
Setup changes wont save

### ISSUE THREAD

**Issue by Puggerugger** [chocolate-doom/chocolate-doom#532]
Whenever I click the "save parameters and launch DOOM" option on the setup menu my changes don't actually save

**Comment by fragglet** [comment]
Tried this out myself and it works for me. What OS are you using?

**Comment by Puggerugger** [comment]
Win 8

**Comment by chungy** [comment]
How did you extract Chocolate Doom? As another user, or is it on a read-only media?

**Comment by Puggerugger** [comment]
I've finally been able to solve the problem by running both programs as an administrator. Thank you for the help!
