### ISSUE TITLE
Fix "Sky not changing" when gameversion is final2

### ISSUE THREAD

**Issue by AXDOOMER** [chocolate-doom/chocolate-doom#533]
The version of DOOM2.EXE found in the id Anthology has this bug fixed.

**Comment by chungy** [comment]
934c9c337b6dc5dd8e78f616e818df67b4fef811 is when Chocolate Doom restored the sky behavior of vanilla; it seems that a partial reversion (case it out for when exe_final2 is being emulated) should be suffice to resolve this.

**Comment by fabiangreffrath** [comment]
You could cherry-pick this
https://github.com/fabiangreffrath/crispy-doom/commit/909067494a0fbf5da3e7c58758e3ec72e75c0e9d
and add an additional check for (gameversion == exe_final2).
