### ISSUE TITLE
doom 1 wont run and there is no controls, 

### ISSUE THREAD

**Issue by tinbutts** [chocolate-doom/chocolate-doom#541]
so i got and ran chocolate doom and it runs with doom 2 just fine, but if i want to set it up with doom 1 none of my configs transfer over, yet when i go to change them in the options menu for chocolate it show's all my binds and other configs, trying to change the warp options to run doom 1 instead of doom 2 by default causes nothing to happen, if i close and save the options it still opens doom 2, if i choose close save and run doom, it still runs doom 2, the only way i can get it to work is to drag my doom wad from its steam folder to chocolate doom.exe, any way to fix this?

**Comment by fragglet** [comment]
Hi,

Thanks for your bug report. However, your report is quite difficult to follow. I'll respond inline:

> so i got and ran chocolate doom and it runs with doom 2 just fine, but if i want to set it up with doom 1 none of my configs transfer over, yet when i go to change them in the options menu for chocolate it show's all my binds and other configs,

By "options menu" I assume you're mistaken and mean [the setup tool](http://www.chocolate-doom.org/wiki/index.php/Setup)? Chocolate Doom has no in-game options menu like other source ports have.

> trying to change the warp options to run doom 1 instead of doom 2 by default causes nothing to happen, if i close and save the options it still opens doom 2

No configuration option exists to change which game (IWAD) is used by default. The setup tool has a warp option on the main menu, but that only triggers a one-off launch of the game. It isn't a configuration setting.

> if i choose close save and run doom, it still runs doom 2

To clarify, you mean to say that the following sequence of actions occurs?

1. Open chocolate-doom-setup.exe
2. Click "F1=Warp" to bring up the warp menu
3. Click on "Game: Doom II", and in the dropdown list select "Doom"
4. Click F10=Start to launch the game.
5. The game launches but the Doom II title screen appears.

Is that correct? Please go through the sequence of actions and confirm for sure.

**Comment by tinbutts** [comment]
im sorry i should've worded this better.
yes i did mean the setup tool that it comes with. 
i see well alright i can understand. 
and thank you that worked and got doom to run without any trouble, i wasnt hitting f10 before,

**Comment by fragglet** [comment]
Okay, so if there's no problem I'll close the bug then. Thanks again for the report regardless.
