### ISSUE TITLE
saving game on top of platform problem

### ISSUE THREAD

**Issue by ozzyyzzo** [chocolate-doom/chocolate-doom#544]
Just reporting this because i have seen it a couple of times.
When you are saving a game while standing on a wall or a plateform surrounded by void in front or around you, when reloading you are falling and you are stuck into walls or any object and you are unable to move.  I can send a saved game concerning this issue on the plutonia.wad.

This is a general issue it can happens on any wad and it is 100% reproductability.

**Comment by fabiangreffrath** [comment]
Hi there,

this is a well-known bug of Vanilla Doom and is thus present in Chocolate Doom as well:
http://doomwiki.org/wiki/Moving_platform_heights_not_preserved_in_saved_games

**Comment by ozzyyzzo** [comment]
Hey,

Oh i see,

But in my case it is a static platform :)

(Maybe it is a dynamic object into the map itself but it is not moving at
all.  -> It has not moved , maybe it will move ?? ^^ )

So i'm not sure it corresponds to the problem above.


Regards,

Sylvain.

PS: attached saved game.

Select Ow
It needs plutiona experiment.



2015-05-28 15:17 GMT+03:00 Fabian Greffrath <notifications@github.com>:

**Comment by fabiangreffrath** [comment]
Am Donnerstag, den 28.05.2015, 05:31 -0700 schrieb ozzyyzzo:
> PS: attached saved game.

So?

**Comment by ozzyyzzo** [comment]
So?

As it is not moving it should not fall when reloading don't you think ?

2015-05-28 15:56 GMT+03:00 Fabian Greffrath <notifications@github.com>:

**Comment by fabiangreffrath** [comment]
Erm, sorry for being so short with you. I meant to say that there was no savegame attached to your message. I don't even know if this is possible on Github at all?

**Comment by ozzyyzzo** [comment]
Oh.. on my side i can see doomsav0.dsg attached in previous email.

so i send it again to be sure...



2015-05-28 16:37 GMT+03:00 Fabian Greffrath <notifications@github.com>:

**Comment by chungy** [comment]
GitHub strips your email attachments. Use another file hosting service and link to it, if you really want to send a file.

That being said, this really sounds like you're hitting a vanilla bug. Chocolate Doom purposefully maintains all of these bugs as part of its mission. If you have the vanilla doom2.exe from Final Doom (afaik all copies come with it), try loading it in DOSBox with your saved game. The same behavior should be apparent.

**Comment by ozzyyzzo** [comment]
ok i'll try it against original version and let u know about it.

keep on the good work

cya

2015-05-28 16:51 GMT+03:00 Mike Swanson <notifications@github.com>:

**Comment by fragglet** [comment]
Thanks for the report anyway @ozzyyzzo !
