### ISSUE TITLE
TNT MAP04 desync

### ISSUE THREAD

**Issue by fx02** [chocolate-doom/chocolate-doom#547]
TNT movie tnt-speed-movie-0443131.lmp: http://www.doom.com.hr/index.php?page=download&cndb=10&record_id=100028 will desync with latest build on MAP04, 2.1.0 works without a problem.

**Comment by fabiangreffrath** [comment]
git bisect tell me that this commit is at fault:
https://github.com/chocolate-doom/chocolate-doom/commit/1bcff874c52aca3134cee636178ab5d6272fef58

**Comment by fx02** [comment]
Yes that fixed it.

**Comment by fragglet** [comment]
Maybe currentthinker->function.acp1(currentthinker); can change currentthinker->next?

**Comment by fragglet** [comment]
Fixed. Thanks.
