### ISSUE TITLE
MSVC and Codeblocks project files missing from source releases

### ISSUE THREAD

**Issue by fragglet** [chocolate-doom/chocolate-doom#551]
chocolate-doom/codeblocks/libopl.cbp
    chocolate-doom/codeblocks/strife.cbp
    chocolate-doom/msvc/libopl.vcproj
    chocolate-doom/msvc/strife.vcproj
    chocolate-doom/msvc/win_opendir.c
    chocolate-doom/msvc/win_opendir.h

**Comment by fx02** [comment]
If I remember correctly older versions of MSVC can't open new MSVC project files so maybe it would be good to create separate dirs inside msvc for each one? But I might be wrong, didn't use it for long time.

**Comment by fragglet** [comment]
I think having one set of project files should be enough.

**Comment by sneakernets** [comment]
if you use an older format, the new MSVCs can convert them to the newer formats, which is nice.  I know that works in VS2010.
