### ISSUE TITLE
music_delay

### ISSUE THREAD

**Issue by fx02** [chocolate-doom/chocolate-doom#553]
I've noticed that if I use startup_delay 2000 (I have weird reasons for this :) music will start to play while screen is blank and I think it should start when the game starts? Well if i'ts possible to delay it via config option that would be great.

**Comment by sneakernets** [comment]
Not sure this is what you were looking for, but in my experience that is similar to vanilla behavior, especially on slower computers.

**Comment by fx02** [comment]
Hmm, maybe it is like vanilla, I don't remember and too lazy to fire up old dos pc.

**Comment by fragglet** [comment]
Yeah, the music deliberately begins before the game itself starts. I have fond memories of my old 486 starting the music playing at least a second or two before the video started up
