### ISSUE TITLE
Heretic, Hexen, and Strife could use their own icons

### ISSUE THREAD

**Issue by chungy** [chocolate-doom/chocolate-doom#554]
On Unix desktops when Chocolate is installed, the same ice cream cone + D icon is used for all four games, this appears a bit bad and lazy. I think the ice cream cone should remain, but it shouldn't be too hard for someone with an eye for graphics to make three more for the non-Doom games. The obvious choices are stylized "H", "X", and "S" in place of the "D" (but with the likewise avoidance of infringing on the games' actual logos).

**Comment by fragglet** [comment]
We have open bugs for these in the chocolate-doom/icon repository already, so I think this is a dupe.

https://github.com/chocolate-doom/icon/issues

**Comment by chungy** [comment]
Ah ok, I didn't realize there was another repository!
