### ISSUE TITLE
Inconsistent Strife 'spechit' declarations in code

### ISSUE THREAD

**Issue by edward-san** [chocolate-doom/chocolate-doom#560]
In `src/strife/p_enemy.c`, `spechit` is an array of length 8, but in `src/strife/p_map.c`, it's an array of length 20.

Discovered with gcc 5 LTO compilation:

```
../../../src/strife/p_enemy.c:388:16: warning: type of ‘spechit’ does not match original declaration
../../../src/strife/p_map.c:102:10: note: previously declared here
```

**Comment by mfrancis95** [comment]
This seems to have been resolved in a later commit. Looking into `src/strife/p_enemy.c` now, the `spechit` variable is declared as such:

`extern	line_t*	spechit[];`

When it used to be declared like this:

`extern	line_t* spechit[MAXSPECIALCROSS];`

**Comment by fabiangreffrath** [comment]
In `p_enemy.c` it is sufficient for the compiler to know that `spechit` is a pointer to an array of type `line_t`. The actual size of the array is irrelevant.

**Comment by fabiangreffrath** [comment]
> pointer to an array 

Erm, rather an array of pointers...
