### ISSUE TITLE
Libretro port

### ISSUE THREAD

**Issue by chungy** [chocolate-doom/chocolate-doom#563]
[Libretro](http://www.libretro.com/) is somewhat similar to SDL in being a huge abstraction of display, input, configuration, save files, and so on functions. It's primarily meant for emulators, but has already been used by other kinds of software, including an [unofficial PrBoom port](https://github.com/libretro/libretro-prboom).

I think it might be beneficial if Chocolate Doom could have an official Libretro target; it could greatly simplify a few areas of development, especially screen scaling (no need to do it within Chocolate Doom, a Libretro frontend would do that on its own, including aspect correction) and input (game controllers are abstracted through a generic "[RetroPad](http://wiki.libretro.com/index.php?title=RetroPad)", designed around the common Xbox 360 and PlayStation layouts). Also, the reference frontend RetroArch is already ported to a great deal of platforms, such as Android and game consoles, that Chocolate Doom doesn't presently have good support for; having a Libretro port should allow running on such systems nearly effortlessly.

**Comment by fragglet** [comment]
You'll notice that Chocolate Doom doesn't include multiple backends; SDL is understood to be a fundamental dependency. Realistically making use of this would require a wholesale conversion over from SDL to Libretro.

If it had existed 10 years ago I might have considered it as an alternative to SDL (as well as others like SFML). As it stands, although it looks like a nice library I'm not convinced that the advantages are worth the effort of converting, especially once the SDL2 port is complete.

**Comment by sneakernets** [comment]
Given that prboom had to be modified to work by the LibRetro team, they seem to know how to do this better than we do.

**Comment by chungy** [comment]
It only makes sense that the libretro developers know their API better than others. Not sure what point is trying to be made about that.

**Comment by fabiangreffrath** [comment]
It's not only that the libretro developers had to modify prboom to make it work with libretro in the first place. They also increased the TICRATE from 35 to 60 for a "smoother" gaming experience.

Related discussion here:
http://libretro.com/forums/showthread.php?t=623

**Comment by leilei-** [comment]
Sorry to dig this old issue up but there's at least this project now:

https://github.com/libretro/sdl-libretro

It's SDL 1.2-based however

**Comment by jmtd** [comment]
> like the Pi, which has poor desktop video drivers making choco timedemo demo1 45fps at best in a 320x200 surface window, whereas the prboom core in lakka sees 60fps in 640x400 upscaled to 1920x1080

sdl2-branch timedemos much better than those for me on the Pi, ~ 500fps last I checked (but that was with very little upscaling, up to 800x600 or so I think)

**Comment by chungy** [comment]
I recall discussions on IRC saying that libretro requires its cores to output at 60fps, which just won't happen for Chocolate. Crispy might do fine.

**Comment by jmtd** [comment]
> I recall discussions on IRC saying that libretro requires its cores to output at 60fps, which just won't happen for Chocolate. Crispy might do fine.

we're discussing doing exactly this in #845...

**Comment by jmtd** [comment]
> sdl2-branch timedemos much better than those for me on the Pi, ~ 500fps last I checked (but that was with very little upscaling, up to 800x600 or so I think)

New monitor attached to my pi, scaling up to 1280x1024, timedemo demo1 now 87.864586fps

**Comment by leilei-** [comment]
How about on Raspbian Stretch? There have been huge performance regressions for the display driver in that
