### ISSUE TITLE
Crash on OS X

### ISSUE THREAD

**Issue by Xeriphas1994** [chocolate-doom/chocolate-doom#569]
After installing a fresh copy of v2.2.0, I identify doom.wad's path in the launcher and press the Launch button to begin a new game.  The program exits silently.

I try again in the terminal:
```
Steel:MacOS Xeriphas1994$ cd //Applications/Chocolate\ Doom.app/Contents/MacOS/

Steel:MacOS Xeriphas1994$ ./chocolate-doom -iwad //Users/Xeriphas1994/Library/Application\ Support/PrBoom-Plus/doom.wad -nograbmouse -width 320 -height 200 -bpp 16 -window
dyld: Library not loaded: /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
  Referenced from: /Applications/Chocolate Doom.app/Contents/MacOS/./libSDL-1.2.0.dylib
  Reason: image not found
Trace/BPT trap
```
Both methods worked in v2.0.0 (although I couldn't use fullscreen due to a different bug, since fixed), but then v2.1.0 started doing this to me.  So I assume it's the package and not because I got drunk and randomly zeroed files in my system area.

Continued gratitude for your hard work over the years.

**Comment by fragglet** [comment]
What version of OS X are you using?

**Comment by Xeriphas1994** [comment]
Oh, duh. 10.6.8.

**Comment by fragglet** [comment]
Does it make any difference if you remove -bpp 16 from the command line? I don't recommend using that parameter.

**Comment by Xeriphas1994** [comment]
No difference, sorry.

**Comment by WhoKnowscs** [comment]
This is an OS version problem.  It affects me to, basically if you go to "/system/library/frameworks", you won't see a CoreGraphics.framework folder in 10.6.8.  Whatever compiled version of libSDL they are using, it is looking for this framework which is not in 10.6.8(although I'm not sure which version it is first in - I would guess Lion but I know it is present by Yosemite)  I'm going to go exploring and see if some weird hacks work.

This is in version 2.2.1 from the main site.

**Comment by fragglet** [comment]
Hi,

In chocolate-doom/buildscripts/67bf4adb3261ca8f47a9d13853d63a2c13956aca I changed the OS X deployment target to target the OS X 10.7 API. Snow Leopard is over 6 years old now and we can't continue supporting old versions forever - attempting to do so was causing a whole host of problems.

If you're using a version of OS X older than 10.7 I'm afraid you'll just have to upgrade to a newer version. Sorry.

**Comment by WhoKnowscs** [comment]
That's perfectly all right.  I've come to expect most software moving away for X.6.8.  I just keep it around because of Rosetta apps(and I have another Mac that can run it fine).  You might want to list the OS version as a requirement for the compiled builds.
