### ISSUE TITLE
Non-opaque filename for preferences (OS X)

### ISSUE THREAD

**Issue by Xeriphas1994** [chocolate-doom/chocolate-doom#570]
launcher.plist, seriously?  I'm surely not the only one who had trouble identifying that.  As it doesn't correspond to a legacy DOS name, I assume it's within project mission to improve it --- uk.org.soulsphere.chocolate-doom.plist perhaps. :>

**Comment by fragglet** [comment]
Sorry, what's the bug here? You seem confused.

Preferences are stored in ~/.chocolate-doom, not a plist file.

**Comment by Xeriphas1994** [comment]
!!

That would explain why savegames were persisting even after I thought I'd uninstalled.  You see how infrequently I find new problems here -- I forget stuff.  :>

The issue submission form didn't have a severity menu (perhaps because my rackety browser didn't render it), or I'd have chosen the most trivial.  That said, I note that the plist file appears to contain config-related items, such as IWAD paths and my last command line arguments, so I suggest that it might benefit from a name related to Doom, buried as it is among a crowd of other plist files with names of varying clarity.
