### ISSUE TITLE
I_Error during GothicDM DEMO1 playback

### ISSUE THREAD

**Issue by fragglet** [chocolate-doom/chocolate-doom#572]
G_CheckSpot: unexpected angle 7168

**Comment by fragglet** [comment]
Present in 2.2.0 release, in the Mac version at least

**Comment by fragglet** [comment]
Not present in the 2.1.0 release. I'm not sure what's changed here. I'm wondering if it's a compiler effect.

**Comment by fragglet** [comment]
A fresh compile of 2.1.0 also bombs out, so I think this is definitely a compiler change that has changed behavior. Now to figure out exactly what undefined behavior is being triggered here.

**Comment by fragglet** [comment]
Uh, so:

        an = (ANG45 * ((signed int) mthing->angle / 45));
        printf("an %i -> %i\n", an, an / (1 << ANGLETOFINESHIFT));
        // Right-shifting a negative signed integer is implementation-defined,
        // so divide instead.
        an /= 1 << ANGLETOFINESHIFT;

Gives this for the output:

    an -536870912 -> 7168

A negative number divided by a positive number equals a positive number?

**Comment by fragglet** [comment]
If I recompile g_game.c with -O0 instead of -O2, it works, and I get this output:

    an -536870912 -> -1024

This might actually be a compiler bug.

**Comment by fragglet** [comment]
printf("an = %i, an/2 = %i\n", an, an / 2);

Gives

    an = -536870912, an/2 = 1879048192

**Comment by fragglet** [comment]
>>> an = -536870912
    >>> (an & 0xffffffff) >> 1
    1879048192

The compiler seems to be doing right bitshifts to divide by powers of two, but not filling the upper bits, even though the type of 'an' is 'signed int'.

**Comment by fragglet** [comment]
I have a minimal example program that demonstrates it:

    #include <stdio.h>
    #include <stdlib.h>
    
    #define ANG45 0x20000000
    #define ANGLETOFINESHIFT 19
    
    int main(int argc, char *argv[])
    {
        short angle;
        signed int an;
    
        angle = atoi("315");
        an = (ANG45 * ((signed int) angle / 45));
    
        printf("an %i -> %i\n", an, an / (1 << ANGLETOFINESHIFT));
    
        return 0;
    }

This gives different outputs when compiled with -O0 and -O2.

This might be related to the fact that bitshifting a signed value right is implementation defined:

    The result of E1 >> E2 is E1 right-shifted E2 bit positions. If E1 has an unsigned type
    or if E1 has a signed type and a nonnegative value, the value of the result is the integral
    part of the quotient of E1 / 2E2. If E1 has a signed type and a negative value, the
    resulting value is implementation-defined.

So if it was ```an >> ANGLETOFINESHIFT```, it would be perfectly valid to give this result. But we're dividing, not bitshifting. I suspect the compiler falsely optimizes to a bitshift expression internally.

**Comment by fragglet** [comment]
Clang bug filed: https://llvm.org/bugs/show_bug.cgi?id=24090

**Comment by fragglet** [comment]
And we have an answer:

>David Majnemer 2015-07-11 00:55:26 CDT
>Your code relies on undefined behavior.  Because of this, LLVM's optimizations cannot ensure your program will have the same result as an -O0 build.

>angle is 315. angle / 45 is 7.  ANG45 * 7 == 536870912 * 7 == -536870912.  Multiplying two positive signed integers cannot result in a negative number without violating C or C++'s rules on undefined behavior: signed overflow is undefined.

>The operations you perform with 'an' assume that signed overflow does not occur, because doing so is undefined, and thus the incongruent behavior between -O0 and -O3.

**Comment by haleyjd** [comment]
Aren't there a number of places in Hexen that potentially rely on this same behavior? I may be wrong as I'm going off memory but I seem to remember a lot of ugly gymnastics with angle_t and signed<->unsigned conversions in that game's action functions. Probably worth an audit.

**Comment by sneakernets** [comment]
Stuff like this is in every major Doom source port I've used.
Methinks a Doomworld Forums thread is in order.
