### ISSUE TITLE
Error loading midi: /etc/timidity.cfg: line 1: syntax error

### ISSUE THREAD

**Issue by YuGiOhJCJ** [chocolate-doom/chocolate-doom#575]
Hello,

When chocolate-doom-2.2.0 is configured for using "Native MIDI" or "GUS (emulated)" and that the /etc/timidity.cfg file content is:
trysource /etc/timidity/crude.cfg
trysource /etc/timidity/freepats.cfg

No music is played and I got this error:
Error loading midi: /etc/timidity.cfg: line 1: syntax error

To solve this problem, you need to edit the /etc/timidity.cfg file content like this:
source /etc/timidity/crude.cfg
source /etc/timidity/freepats.cfg

I don't understand why the "trysource" statement is not recognized whereas the "source" statement is recognized.
When I am using an other game like eduke32, the "trysource" statement of timidity++-2.13.0 is recognized and the music is working without any error.

Why the behavior with chocolate-doom is different?

Thank you.
Best regards.

**Comment by fragglet** [comment]
Chocolate Doom uses SDL_mixer, which has its own internal version of Timidity that is probably older than the version installed on your system. Specifically I doubt it supports the "trysource" syntax. Try switching to just "source" instead.

If you're really dedicated I believe you can recompile SDL_mixer to run against the system-installed version of Timidity.

Hope this helps!

**Comment by bam80** [comment]
Hmm I'm afraid SDL_mixer can't be compiled with external Timidity :(
