### ISSUE TITLE
the -servername command line option does not work

### ISSUE THREAD

**Issue by YuGiOhJCJ** [chocolate-doom/chocolate-doom#576]
Hello,

I have just created a chocolate-doom server that you can see here: http://master.chocolate-doom.org/ but its name is "Unnamed server".
I try the -servername command line option but it does not help.

Any idea how to customize the server name, the max players and any other available options please?

That's how I start the server:
$ sudo -u chocolate chocolate-doom -servername "YuGiOhJCJ" -dedicated &

Thank you.
Best regards.

**Comment by fragglet** [comment]
Bear in mind that server metadata is cached by the master server and only refreshed every few hours. So if you initially ran the server without the -servername parameter, leave it running and come back again in a few hours to see if it has resolved itself.

**Comment by YuGiOhJCJ** [comment]
OK so I am waiting 24 hours to be sure...
For the moment, only 4 hours have been elapsed.
During this time have you any idea how to change the "Max. players" value which seems to be "8" by default?
I see nothing about that on this wiki page: http://www.chocolate-doom.org/wiki/index.php/Command_line_arguments
Is there a better page to find all the possible options for configuring my server?

**Comment by fragglet** [comment]
There is no way to increase the limit on the number of players. Different game types support different numbers of players, but Doom only supports 4.

**Comment by YuGiOhJCJ** [comment]
Nice, the master server has refreshed the metadata!
Now, my server name is "YuGiOhJCJ" see here: http://master.chocolate-doom.org/
OK, so we can't change the number of players.
Indeed you have right I am on "4" players with the Doom video game.
Last question please: Is there a way to change the episode or the skill level of the server like when you start a new game in single player mode?

**Comment by fragglet** [comment]
Episode / skill level, etc. are determined by the players who are using the server (actually, by the first player to join the server). There isn't (currently?) any way for server operators to control this.

**Comment by fragglet** [comment]
And, thanks for running a dedicated server!

You might want to build and use chocolate-server rather than chocolate-doom -dedicated, in order to save some memory.

**Comment by YuGiOhJCJ** [comment]
OK thank you for the information.
Problem solved.
