### ISSUE TITLE
A spectator mode instead of a respawn

### ISSUE THREAD

**Issue by YuGiOhJCJ** [chocolate-doom/chocolate-doom#578]
Hello,

In multiplayer mode, when a player dies, he can respawn by pressing the "Use" button.
I am a bit disappointed of this behavior because I don't think it is a good idea for at least two reasons:
1) It breaks the cooperation between players because a player don't care about the remaining life of an other player (as if someone dies, this player can respawn with full life)
2) It breaks the difficulty of the game because a player does not make effort to survive because he knows that he can respawn when he is dead (on the contrary, in singleplayer mode, you take care to survive because when you die, the level is restarted and you must collect again all the items, kill all the enemies and find all the secrets)

The expected behavior, in my point of view, is to have a spectator mode:
1) The dead player must wait that all players die in the level or that they finish the level to be able to play again
2) The dead player can press the "Use" button to switch camera to see the screen of other players while he is waiting like in a spectator mode (because it is boring to stay on a fixed camera at the location of your death)
3) If all players are dead, then the level is restarted and you must collect again all the items, kill all the enemies and find all the secrets

The advantages of a spectator mode is that it increases the cooperation aspect and the difficulty of the game.
You must take care of other players because they will help you to survive to finish the level if they are not dead and you have not "infinite lives" (by respawning each time you are dead).

Do you think it is a good idea to have a spectator mode like this and is it hard to implement this behavior in Chocolate Doom?

Thank you.
Best regards.

**Comment by fragglet** [comment]
There might be some merit to your ideas, but unfortunately they aren't in line with the philosophy of the project, which is to preserve Vanilla Doom's behavior.

There are other Doom source ports that might be more interested in implementing this kind of behavior - Odamex is one example of a multiplayer-focused source port that has a lot of these kind of options.

Sorry if this disappoints you.

**Comment by YuGiOhJCJ** [comment]
The philosophy of the project is also : "The surrounding aspects of the game that aren't part of the central gameplay experience can be extended as long as there's a good reason and Vanilla behavior is respected." (extracted from the "PHILOSOPHY" file contained in the "chocolate-doom-2.2.0.tar.gz" archive). So, if my idea is implemented as an option that is disabled by default, it may be accepted.

Anyway, I found the part of code that I need to modify in order to have a spectator mode.
In fact, the "F12" key already helps to spy players like in spectator mode.
So, nothing to change here.
The only part of code affected is the one that allow the player to reborn with the "USE" key.
I just have to disable that behavior when the "-noreborn" new option is activated.

You can find the patch here:
https://gensiteweb.1s.fr/uploaded_files/52/chocolate-doom-2.2.0-20150729.tar.xz

**Comment by fragglet** [comment]
I consider the features you describe to be part of the central gameplay experience, so that doesn't apply. In any case, that document is descriptive, not proscriptive.

Sorry but this isn't a feature that is going to be incorporated. Maybe @fabiangreffrath would be interested in it for Crispy Doom?
