### ISSUE TITLE
Aspect ratio of screenshots may not match what was displayed

### ISSUE THREAD

**Issue by jmtd** [chocolate-doom/chocolate-doom#579]
Chocolate Doom faithfully reproduces the behaviour of vanilla Doom with respect to screenshots via `-devparm`: it writes out a PCX at 320x200, which is the frame buffer size of Doom, not taking into account the aspect ratio skew caused by projecting that to a 4:3 display. I'd like to suggest/request that c-d scales the screenshots to respect aspect ratio correction *if* aspect ratio correction is enabled.

Paging @fabiangreffrath, I can understand and respect that @fragglet may well not look at this request favourably for chocolate-doom. What do you think about it for crispy? Combined with writing out PNGs, it would make crispy a very useful port for taking screenshots for [The Doom Wiki](http://doomwiki.org/). (I've not filed a dupe bug against crispy.)

**Comment by jmtd** [comment]
OK I think I've got a preliminary patch sorted, it's at https://github.com/jmtd/chocolate-doom/tree/aspect-ratio-screenshots which is against crispy-doom, I've also only tested one resolution and PNG output. About to rework against c-d.

**Comment by jmtd** [comment]
OK, patch applies clean to either port but needs some tweaking for both. 640x480 is fine (suspect any proper multiplication of 320x240 is fine). I'll keep working.

**Comment by AXDOOMER** [comment]
>  I'd like to suggest/request that c-d scales the screenshots to respect aspect ratio correction if aspect ratio correction is enabled.

What about people who want aspect ratio correction, but 320x200 screenshots?

> Combined with writing out PNGs, it would make crispy a very useful port for taking screenshots for The Doom Wiki.

It's easy to take Paint or GIMP and do the scaling manually. If it creates a screenshot of the 640x480 frame buffer, you can't scale it back to 320x200 without artefacts or distortion.  In other words, you'd have to remove the sub-pixels before you scale it back to 320x200 if you want it to look genuine.

**Comment by jmtd** [comment]
> What about people who want aspect ratio correction, but 320x200 screenshots?

Are there really people who want distorted screenshots? If so perhaps we could discuss this being optional. But I'm pretty surprised. I imagine most people these days expect that the screenshot will reflect what was displayed on the screen.

> It's easy to take Paint or GIMP and do the scaling manually.

You have to remember that the screenshots are distorted, and it's not that easy if you have a lot of them to do. There's also the issue that the software you use might employ an algorithm that gives you a different result to the stretching algorithm in C-D (and, both might differ from the effect of projecting 320x200 onto a 4:3 CRT display via VGA, but I guess if it was possible to emulate that more closely, then c-d would accept patches to do so)

**Comment by chungy** [comment]
I personally would hate if screenshots from Chocolate were lossy by nature. The advantage of dumping out the 320x200 buffer is that it's exactly what the game's pixels are, no more or less. The smallest lossless 4:3 scale is 1600x1200, and that's impractical for other reasons...

PNG actually has a [pHYs](http://libpng.org/pub/png/book/chapter11.html#png.ch11.div.8) chunk that can describe the aspect ratio independent of the source pixels. Unfortunately, most software doesn't handle it (no common browsers, image editors, etc... the only exception I know of off-hand is ffmpeg).

**Comment by jmtd** [comment]
By the way recent-isn chocolate-dooms don't write out 320x200 anymore, they write out 640x400. Not sure exactly when that crept in.

**Comment by jmtd** [comment]
Here's the options as I see it.

1. change the behaviour to make a "screen shot" (aspect corrected)
2. change the behaviour for PNG only, leave PCX as a simulation of a buffer dump of the original doom (wrong aspect)
3. write out both screenshots, one as 1) and one as 2)
4. put another configuration option in.
5. leave as-is. (sub-option 5.1: add pHYs chunks to the PNGs, leave PCX as-is).

My preference is 1, 2, 3, 4, 5.

I'd suggest taking a step back and asking, is the original doom behaviour of writing out 320x200 a bug, or by design? Can it really be by design if the game was intentionally designed to be 4:3 aspect? What is reasonably expected behaviour of a 'screen shot' feature? 

> I personally would hate if screenshots from Chocolate were lossy by nature. 

Aspect-corrected screenshots aren't lossy. The process of aspect correction is additive: all the original pixels are there, but there are 20% more ones added to stretch one dimension. It's true that a naive resizing of an aspect-correct screenshot to an aspect-incorrect one would not give you the same data as vanilla doom's screen buffer. But that's a fault of using a naive resizing to try and get that. It would be perfectly possible to write an algorithm to de-aspect-correct a screenshot losslessly. Especially if the correction algorithm was well specified.

**Comment by chungy** [comment]
> By the way recent-isn chocolate-dooms don't write out 320x200 anymore, they write out 640x400. Not sure exactly when that crept in.

Are you sure you're looking at Chocolate Doom? I just built HEAD (b81ba59d6649794cfba735d1ffa0e9458a6ee486 as of now), and in both PCX and PNG output options the screenshot is 320x200.

Anyhow, as I see it, a screenshot should represent the view the game is in, exactly; the games use an internal 320x200 buffer (and Chocolate purposefully preserves this). If a utility can indeed exist to convert a Chocolate aspect-corrected screenshot to an "uncorrected" one, I might find it acceptable; keeping PCX exactly as vanilla does it would be as well, though I view the PNG support mainly as being a less obscure/obsolete replacement (imagemagick and ffmpeg can handle it, so it's not totally bad) than a target that's supposed to be extensible.

**Comment by fragglet** [comment]
A fix for this is now in place after merging #580. Sorry I haven't taken part in the discussion here.

I'm pretty happy with the solution we've come up with - the decision to just make PNG screenshots 1600x1200 (while maintaining 320x200 PCXs by default) seems like a very "chocolatey" approach, avoiding a bunch of unnecessary and potentially confusing options. As mentioned in #580, I'd still quite like to have a secret option to allow the user to manually override the screenshot size by editing the .cfg file if they really care.
