### ISSUE TITLE
Can't build on OSX

### ISSUE THREAD

**Issue by linguica** [chocolate-doom/chocolate-doom#584]
I tried the apparently-canonical method of building Chocolate Doom as per http://www.chocolate-doom.org/wiki/index.php/Building_Chocolate_Doom_on_Mac_OS_X by invoking:

     curl http://www.chocolate-doom.org/build-chocolate-doom | sh

And it went fine until the following error:

    In file included from ./src/video/quartz/SDL_QuartzEvents.m:24:
    ./src/video/quartz/SDL_QuartzVideo.h:94:5: error: unknown type name 'CGDirectPaletteRef'

From my understanding, CGDirectPaletteRef has been deprecated in the years since this was last updated. But I don't know how to fix it, and Googling is not terribly helpful. It would be nice if the build script were updated to actually work, or if there were at least additional instructions for fixing the errors.

**Comment by fragglet** [comment]
Same issue as #322 and #445. This is actually SDL bug 2085: https://bugzilla.libsdl.org/show_bug.cgi?id=2085

In #445 I mentioned that the fix ought to be included in the build script but somehow that bug got fixed without it ever happening. There still hasn't been a new SDL 1.2 release in ~2 years.

**Comment by linguica** [comment]
So how do you build on Mac then? What do you have installed? I literally don't know how a person is supposed to do it.

**Comment by fragglet** [comment]
Good question because I don't even appear to have that patch applied in my build tree. It looks like I'm just using stock SDL 1.2.15.

Are your xcode tools all up to date?

**Comment by fragglet** [comment]
Reason I ask is that I think this CGDirectPaletteRef is a bug in an older version of the XCode headers and if you upgrade the problem goes away.

**Comment by linguica** [comment]
OK I finally got it working. Someone (like me I suppose) should update the wiki to reflect the following steps or whatever subset of steps are necessary:

* Install XQuartz from http://xquartz.macosforge.org/landing/
* Make sure you have run xcode-select --install since a full XCode install apparently likes to lie about whether the command line tools are truly installed
* Individually build SDL, SDL_net, and SDL_mixer from source
* Fixing SDL of course
* Install homebrew http://brew.sh/
* brew install autoconf
* brew install automake
* git clone https://github.com/chocolate-doom/chocolate-doom or whatever you do to get the files
* ./autogen.sh
* ./configure
* make
* make install
* peep /usr/local/games yo

**Comment by linguica** [comment]
Also even after be able to build it the Hard Way, trying to do it the easy way gives me the following: http://pastebin.com/1yyEWD3p

**Comment by fragglet** [comment]
Glad to hear you got it working but I'd rather stick with the auto-build script for the instructions, broken as it may be at present. It sounds like it needs fixing, I'll see if I can get it working.

**Comment by fragglet** [comment]
Build script fixed. The biggest thing here is that I was building against the Mac OS X 10.4 SDK (as I wanted the built binaries to run on as many older versions of OS X as possible). But 10.4 is really ancient now. I've bumped up the deployment target to 10.7 instead and this fixes the compile error.

Sorry that you had a bad experience here.

**Comment by fragglet** [comment]
Also: as part of this I pinged icculus about why there hasn't been a new SDL 1.2 release. Looks like 1.2.15 is the end of the line, which makes the migration to SDL2 all the more important:

https://twitter.com/icculus/status/623284805321494529
