### ISSUE TITLE
Respect XDG base directory specification

### ISSUE THREAD

**Issue by chungy** [chocolate-doom/chocolate-doom#597]
This was recently brought up in freedoom/freedoom#159, and solves at least one real-world shortcoming: the lack of standard location for IWADs in purely user-writable locations. While it's fairly trivial to have the engine installed under `$HOME/bin` or any other location in your `$PATH`, there's no good standard for placing IWADs under your own home tree, which can be a problem on multi-user systems, or even single-user systems where someone might not understand the concept of root nor creating directories/files as it. Chocolate Doom does, of course, support `$DOOMWADPATH`, but that is still somewhat advanced and requires a great deal of extra steps for a casual user; creating `$HOME/.local/share/games/doom` and putting IWADs into it is simple by comparison, and can be done entirely via a GUI file manager, as well. I think supporting people using GUI as the only computer interaction is important; Chocolate Setup already fills a great role as a basic launcher for such people.

XDG is slightly more nuanced than the original referenced bug report suggests, though `$HOME/.config` and `$HOME/.local/share` are fallbacks when environment variables to control their locations don't exist. See http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html for all the details

One thing I'm not completely thrilled about is that following the spec would require moving the configuration directory from `$HOME/.chocolate-doom` to `$XDG_CONFIG_HOME/chocolate-doom`, but in full honesty, it wouldn't bother me that much, and a symlink can restore the old path if really desired. It would probably create confusion for people upgrading without reading the release notes, but even that is probably minor.

**Comment by fragglet** [comment]
/usr/share/games/doom is the de-facto standard place to store IWAD files that is supported by most source ports but isn't user-writeable. So ~/.local/share/games/doom sounds like a good addition that is consistent.

To do this properly we should check $XDG_DATA_HOME, and also $XDG_DATA_DIRS. I'd suggest that the latter should replace the current /usr/share/games/doom default. From the xdg spec page you linked:

> If $XDG_DATA_DIRS is either not set or empty, a value equal to /usr/local/share/:/usr/share/ should be used.

So we should check $dir/doom for each $dir in $XDG_DATA_DIRS, where $XDG_DATA_DIRS=/usr/local/share/:/usr/share unless overridden.

**Comment by chungy** [comment]
Specifically, `$dir/games/doom`, so that we remain consistent with the pre-existing de facto standards. But yes, extending it to $XDG_DATA_DIRS makes sense too. I can imagine some of the more experimental distros that shake up the file system (they may not have a /usr tree) would appreciate the flexibility.

**Comment by fragglet** [comment]
Sorry yes, I mean $dir/games/doom.

**Comment by GreenLunar** [comment]
I think of writing an external GTK+ or Qt program to launch Doom game engines (Chocolate Doom, GZDoom, PrBoom etc.) that would associate with IWAD (`.wad`) files.

When user clicks on an IWAD file, the program would ask the user whether they like to install that file only for current user or all users (system).

When user selects for all users, the program would ask for a root password, when otherwise, it would copy the given IWAD file to `~/.local/share/games/doom/`

Currently EDuke32 (using DUKE3D.GRP and DUKE.RTS) has a GTK+2 GUI, so we may start to implement this idea there, for start.

**Comment by fragglet** [comment]
Hi @GreenLunar, thanks but that really is offtopic. Please feel free file a separate bug to discuss that. Thanks

**Comment by GreenLunar** [comment]
I wanted to write a short sentence, and the idea kept develop while I was at it.

**Comment by fragglet** [comment]
XDG_DATA_HOME and XDG_DATA_DIRS are now supported.

There's one remaining question here:

> One thing I'm not completely thrilled about is that following the spec would require moving the configuration directory from $HOME/.chocolate-doom to $XDG_CONFIG_HOME/chocolate-doom, but in full honesty, it wouldn't bother me that much, and a symlink can restore the old path if really desired. It would probably create confusion for people upgrading without reading the release notes, but even that is probably minor.

To be honest we probably should be using ~/.config/chocolate-doom nowadays. It used to be perfectly acceptable to just create your own dotfile (dotdir in this case) in the user's home directory to store stuff. But over time that's become less common/acceptable. There's also a parallel issue here: on OS X we store config in ~/.chocolate-doom as well, which is the wrong place to put it (should be somewhere in ~/Library/Preferences).

SDL2 has this nice function named [SDL_GetPrefPath](https://wiki.libsdl.org/SDL_GetPrefPath) that I think we should be using, as every OS is likely to have its own special place to put this stuff.

**Comment by chungy** [comment]
Seems a little bit oriented for commercial releases with the organization name. I don't think Chocolate Doom needs anything as elaborate. Do you know if it works well if that string is empty?

**Comment by fragglet** [comment]
Heh, reminds me of the Windows CE port [which also required a company name](https://soulsphere.org/img/screenshots/ce-company-name.png). But I don't know what the result of those different arguments is - we'll have to experiment.

**Comment by fabiangreffrath** [comment]
We should handle this as we do on Github, i.e. "chocolate-doom" for both strings.

**Comment by fragglet** [comment]
I agree.

**Comment by chungy** [comment]
Using SDL_GetPrefPath is as straightforward as you should expect, although I don't think the result is as good as it probably should be. Using PACKAGE_NAME for both the org and app arguments, the end result is something like this:
```
chungy@turanga:chocolate-doom$ src/chocolate-doom-setup 
Using /home/chungy/.local/share/Chocolate Doom/Chocolate Doom/ for configuration and saves
saving config in /home/chungy/.local/share/Chocolate Doom/Chocolate Doom/default.cfg
```

The first "Chocolate Doom" is the org, and is entirely redundant. There aren't going to be other programs from the "Chocolate Doom" organization, so its presence is a little bit silly. Merely passing in "" (empty string) as the argument causes "~/.local/share//Chocolate Doom" to be used; on POSIX systems, this won't be an issue. This function is kind of obviously geared towards studios that would have multiple games; I even have such examples personally from Almost Human/Legend of Grimrock and cdprojektred/The Witcher -- the org business makes sense for commercial releases like this.

I also observe that SDL on Unix systems is using $XDG_DATA_HOME, when we really want $XDG_CONFIG_HOME. To go by the full XDG specs, the *.cfg files would go into $XDG_CONFIG_HOME/chocolate-doom, and things like music replacements and save games into $XDG_DATA_HOME. I personally find the split confusing and we should keep everything into one directory. Save games are not large (part of the point of ~/.local is for when the rest of $HOME is mounted via NFS and you want to keep large private files from applications from eating server space), I think it would do no real harm.

All in all, I think we can maintain better, and more consistency with other free software applications, by ignoring said SDL function and doing things ourselves; going that route would mean the change can be incorporated before the full SDL2 port, even. The downside, of course, is much more special-casing for every operating system people run Chocolate Doom on, but at the very least Unix and OS X should cover nearly everyone. Perhaps those on Amiga and such will get the fallback to the executable's directory -- if it's wrong for them, it can always be changed too.

**Comment by jmtd** [comment]
> I also observe that SDL on Unix systems is using $XDG_DATA_HOME, when we really want $XDG_CONFIG_HOME. 

It would be interesting to know their rationale here, because on the face of it that does seem wrong. Perhaps this is a bug in SDL that should be fixed?

> Perhaps those on Amiga and such will get the fallback to the executable's directory -- if it's wrong for them, it can always be changed too.

Could we fall back to SDL behaviour for non-whitelisted systems?

**Comment by GreenLunar** [comment]
I think, iwad should be stored under `$XDG_DATA_HOME/doom/` and configurations under `$XDG_DATA_HOME/chocolate-doom/`.

Nonetheless, thank you for solving this issue.

**Comment by jmtd** [comment]
> I think, iwad should be stored under `$XDG_DATA_HOME/doom/` and configurations under `$XDG_DATA_HOME/chocolate-doom/`.

So the good news is this is now behaviour for sdl2-branch (the future chocolate doom version 3).

**Comment by fragglet** [comment]
Rather surprised SDL uses `XDG_DATA_HOME` rather than `XDG_CONFIG_HOME`, but still, this seems good - best to just go with what SDL gives us. Thanks for fixing.

**Comment by jmtd** [comment]
> Rather surprised SDL uses `XDG_DATA_HOME` rather than `XDG_CONFIG_HOME`

Me too, to be honest.
