### ISSUE TITLE
Should add check for default path to IWAD in GOG install

### ISSUE THREAD

**Issue by linguica** [chocolate-doom/chocolate-doom#600]
Now that the Doom games are available on GOG.com, Chocolate Doom should add a check to the default install path, like the one for Steam.

**Comment by fragglet** [comment]
Neat, I wasn't aware of that. I agree.

**Comment by chungy** [comment]
@linguica Have you purchased the GOG.com games?

If so, it would help if you can install them on Windows (or Wine, should work both ways) and find the registry key under `HKLM\Software\Microsoft\Windows\CurrentVersion\Uninstall` (if it's like other GOG.com, it would be a series of numbers followed by _is1; it might be easy to look under `HKLM\Software\GOG.com` to figure out what these numbers arem, too). Under that key should be a RG_STRING value containing the installed location of the game; check the directory to find out if the IWADs are directly under it or another directory or two below it.

**Comment by chungy** [comment]
I've pushed a branch called gog.com on my private fork that might resolve this issue, but I'm not presently able to test it directly (I don't own the GOG.com versions (yet)). If someone wants to verify it works, a compiled build is here: https://dl.dropboxusercontent.com/u/13513277/doom/chocolate-doom-gogcom.zip

**Comment by Gaerzi** [comment]
Feel free to use [this ZDoom commit](https://github.com/rheit/zdoom/commit/98f214ee66fd5223c2d277fb982848e03e0200d2) as a reference.
