### ISSUE TITLE
bring back the disk activity indicator

### ISSUE THREAD

**Issue by jmtd** [chocolate-doom/chocolate-doom#603]
Breaking out the conversation from #583. I might work on this when #583 is done, but don't let that stop you if you want to do it first! Related: `STCDROM`...

**Comment by fabiangreffrath** [comment]
Not sure if you have seen, I have implemented an idea in the `diskicon` branch. Maybe you'd like to have a look.

**Comment by jmtd** [comment]
Hi Fabian, thanks, I took a look yesterday. It took me a while to figure out why I couldn't see anything: it was still disabled on Mac OS X. I've re-enabled it and it looks pretty good! `-cdrom` works too. There are two commits in [my fork](https://github.com/jmtd/chocolate-doom/tree/diskicon) you might be interested in.

For me, the status bar numbers are (re-)drawn over the top of the disk icon. Just to be sure, does this happen on other platforms (or could it be a symptom of the Mac OS X double buffering that got this feature disabled in the first place)?

**Comment by fabiangreffrath** [comment]
Very nice, merged, thank you!

**Comment by fabiangreffrath** [comment]
There is still some logic error inside this code. If I start `chocolate-doom -mb 2` to restrict available memory and force frequent lump reload, parts of TITLEPIC are saved in the `saved_background` buffer and restored at the beginning of the level.

![doom00](https://cloud.githubusercontent.com/assets/6449237/9631073/c183cac0-517e-11e5-8a92-c4c5a3be7bc5.png)

**Comment by jmtd** [comment]
I think we should probably not save/restore the backdrop and instead force a redraw of the whole titlebar. I was thinking it is possible we could be restoring the wrong ammo figure if the player picked up a backpack in the middle of the disk activity.

**Comment by jmtd** [comment]
Hmm. The tricky part is the fact this is doom/strife specific. We can't call the ST_* code from I_* code, easily, because that doesn't work on heretic/hexen. So we need to signal to the ST_ code that it needs to redraw. Some adjustments around `src/doom/st_stuff.c#1073` might work. If you hack that to do a full redraw always, it fixes most of the corruption. There is still some during the wipe, but I don't think that can be avoided. Actually it almost looks like the patch height is not quite right. Is there an off-by-one somewhere?

**Comment by jmtd** [comment]
![topline](https://cloud.githubusercontent.com/assets/63694/9635752/d4df7ad6-518f-11e5-999c-81ffcac18ad2.png)

that top line looks wrong

**Comment by haleyjd** [comment]
I do not think the Strife IO indicator even draws in the same place as DOOM's. We didn't bother implementing it accurately because it looked like the feature was going away in Choco at the time.

**Comment by jmtd** [comment]
OK, I've fixed the corruption issue. Instead of pre-rendering the lump and caching the result, just use `V_DrawPatch` each time. That way we handle transparent pixels properly. I haven't adequately solved the status bar redraw issue; the new patch in my fork just redraws it entirely each tic. The result is it's drawing properly, but we probably want to reduce the number of status bar redraws.

**Comment by fabiangreffrath** [comment]
The status bar isn't our only problem. While I generally appreciate using V_DrawPatch(), I am afraid the icon will never disappear on the title screen, intermission screens, etc with your approach.

My main concern at the moment is wipes: The screen is backed up right before a wipe, then the wipe is performed and the backed up part of the screen written back after the wipe. This is why parts of TITLEPIC appear on the status bar in the picture I posted above.

**Comment by fabiangreffrath** [comment]
In the context of my comment above, maybe we should untangle the "backup screen area" from the "draw icon to screen area" function.

**Comment by jmtd** [comment]
With my current HEAD, I'm seeing the icon appear and disappear on the title screen, intermissions, end-episode texts etc...

**Comment by fabiangreffrath** [comment]
Oh, I didn't even know that these screens get completely redrawn every tic. So, indeed remains the status bar issue. However, I find it unacceptable to redraw the status bar every tic...

**Comment by jmtd** [comment]
> However, I find it unacceptable to redraw the status bar every tic...

Yes it's not great. My first thought was to introduce a st_dirty global and use that to signal a full redraw is required,  but again that ties i_video to doom/st_* too closely. I seem to recall seeing something about dirty regions somewhere so I might see if that can be used.

**Comment by fabiangreffrath** [comment]
Please have a look at my latest commit.

**Comment by jmtd** [comment]
Hi, well, it works! :) I talked to @haleyjd last night about the Strife indicator. He isn't sure but seems to recall it might have appeared in the top-left corner. Some more refactoring might be needed to eventually support this in chocolate-strife. I personally find the background save/restore a bit awkward, and for Doom liked the idea of getting ST_* to redraw itself, but that wouldn't apply for Strife since the indicator (an hour glass) didn't overdraw the HUD, so background save/restore may be needed for that case anyway.

I imagine an eventual refactoring for strife support will move a lot of the current code out of i_*, since it's very doom specific... but strife support is really an issue for another bug. I'm personally happy with what you've got there :)

I wonder, do you think this should be optional? Although I do hate option proliferation...

**Comment by fabiangreffrath** [comment]
> Hi, well, it works!

\o/

> I personally find the background save/restore a bit awkward,

Me too, but for static content it is really needed. :/

> and for Doom liked the idea of getting ST_* to redraw itself,

Well, it does now. Whenever the status bar needs a full redraw, it refreshes the background buffer.

> but that wouldn't apply for Strife since the indicator (an hour glass) didn't overdraw the HUD, so background save/restore may be needed for that case anyway.

Only if it covers static screen content. The area rendered by R_RenderPlayerView() is refreshed each tic anyway.

**Comment by fabiangreffrath** [comment]
Hm, I am not sure if in DOOM.EXE the icon was drawn atop the wipe effect or if it was wiped away with it?

**Comment by jmtd** [comment]
If there was loading in both frames (pre and post wipe) I guess the icon would be there... but not every time, as there would not always be loading in both frames. In our case it will be every time due to keeping it around for a full tic.  So not quite identical behaviour to vanilla. What could we do about it? I suppose we could avoid putting the disk on any wipe at all...

**Comment by fabiangreffrath** [comment]
Hm, I think it's sufficient if we just call `I_EndRead()` right before `wipe_EndScreen()` in `src/doom/d_main.c:D_Display()`.

**Comment by fabiangreffrath** [comment]
No, this still isn't the whole story. Seriously, this would be so much easier if we would just introduce a global (boolean) variable that is set `true` whenever `W_ReadLump()` is called. This variable would be checked in `D_Display()` and if it is `true`, then the disk icon would be drawn right before the call to `I_FinishUpdate()` and then the variable is reset `false`. And when it gets reset, then `redrawsbar = true`.

**Comment by jmtd** [comment]
> Seriously, this would be so much easier if we would just introduce a global (boolean) variable ...

I'm a few beers in but I'll have a crack at that now. Watching "Mr Robot". Not bad so far.

**Comment by jmtd** [comment]
OK I haven't made head nor tail of the logic around another global, but I did [do this](https://github.com/chocolate-doom/chocolate-doom/issues/603#issuecomment-137700411), and the disk isn't in wipes for me. What edge case remains? (commit [here](https://github.com/jmtd/chocolate-doom/commit/2193fa1e0fb7261d332b5643ccaf576d2cd9744d)).

**Comment by jmtd** [comment]
Hey @fabiangreffrath , latest seems fine for Doom. One thing left to fix for Strife, that is the border around the game needs to be prompted to refresh if the hour glass is drawn on top - default setting seems to be to have a border (i.e. have to press "+" to get full screen)

**Comment by haleyjd** [comment]
Which is not correct. The default for Strife is supposed to be fullscreen. I already corrected this in the game's code itself but my request for someone to fix the defaults that are written by chocolate-setup has been ignored.

**Comment by fabiangreffrath** [comment]
> One thing left to fix for Strife, that is the border around the game needs to be prompted to refresh if the hour glass is drawn on top

This is fixed now. I am considering moving the "you might need to redraw something" variable directly into `I_BeginRead()` instead of maintaining one of them in each Doom and Strife. I'd like to know what @fragglet thinks about it?

**Comment by jmtd** [comment]
`> Which is not correct. The default for Strife is supposed to be fullscreen. I already corrected this in the game's code itself but my request for someone to fix the defaults that are written by chocolate-setup has been ignored.

Should be easy enough to fix, I'll take a look.

**Comment by jmtd** [comment]
> Should be easy enough to fix, I'll take a look.

Mike beat me to it :)

@fabiangreffrath, `diskicon` lgtm in Doom and Strife now.

**Comment by fragglet** [comment]
Bit surprised you think that 7a29515569b6543c31b1fc0b2ef4875ab75708b6 is the better solution - isn't this more fragile than just saving the background and restoring?

**Comment by fabiangreffrath** [comment]
The latter turned out to be more fragile. We had artifacts when the background was backed up before a wipe and restored afterwards. Also, the background was restored on intermission and map end screens when it was strictly not necessary.

**Comment by fragglet** [comment]
Fair enough then.

One request: it seems like there is very little connection left between the disk icon code and the i_video.c code any more. Can we factor this out into a separate file? It probably doesn't even belong in i_* as we're just drawing a patch.

**Comment by fabiangreffrath** [comment]
Sure, we could move it elsewhere. But we should keep it out of the doom/* and strife/* name spaces as the code is common to both games.

**Comment by fabiangreffrath** [comment]
Please find it in the src/v_diskicon.[ch] files now.

**Comment by PorscheMonty** [comment]
+1

Diskicon gives Doom that extra touch of character.
