### ISSUE TITLE
Can't compile on linux

### ISSUE THREAD

**Issue by MrCrispy21** [chocolate-doom/chocolate-doom#604]
It's going great, when all of a sudden:

  CC     deh_io.o
  CC     deh_main.o
  CC     deh_mapping.o
  CC     deh_text.o
windres resource.rc -o resource.o
windres: can't get BFD_RELOC_RVA relocation type: No error
make[3]: *** [resource.o] Error 1
make[3]: Leaving directory `/home/user/choco-git/src'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/user/choco-git/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/user/choco-git'
make: *** [all] Error 2

**Comment by fabiangreffrath** [comment]
Eh, windres? What compiler are you using?

**Comment by MrCrispy21** [comment]
gcc 4.8.2

**Comment by fragglet** [comment]
Please pastebin a copy of your config.log file and post a link to it.

Thanks

**Comment by MrCrispy21** [comment]
http://pastebin.com/5tn7VPuf

**Comment by fragglet** [comment]
```
configure:4354: checking for windres
configure:4370: found /usr/bin/windres
configure:4381: result: windres
```
What distro are you using?

**Comment by MrCrispy21** [comment]
Salix OS 14.1

**Comment by fragglet** [comment]
Context: windres is a tool used for building Windows resource files. It's not obviously not appropriate for Linux compiles and usually doesn't get built unless you're targeting Windows. So it's very weird that you have it installed.

**Comment by MrCrispy21** [comment]
I don't remember installing windres specifically (i have no need for it), it must have been included with something else.

**Comment by MrCrispy21** [comment]
Do i just delete /usr/bin/windres ?

**Comment by fragglet** [comment]
It's part of binutils.

The Slackware chocolate-doom package has a patch to work around this issue:

http://slackbuilds.org/cgit/slackbuilds/plain/games/chocolate-doom/chocolate-doom.SlackBuild

We should probably fix it properly though. The simplest solution is that we should probably just change configure.in to only check for windres if a Windows target is specified.

**Comment by fragglet** [comment]
Deleting (or better, renaming) /usr/bin/windres should fix the problem. I doubt it will have any negative impact on your system.

**Comment by MrCrispy21** [comment]
I took /usr/bin/windres out of the equation and that worked. Thank you for the help.

**Comment by fabiangreffrath** [comment]
@MrCrispy21 Nice user name ;)

I don't think /usr/bin/windres is meant to be shipped by Linux distributions, at least the Debian packages does not contain it. I think it belongs to Cygwin, Mingw and probably cross-compilers with win32 targets. Maybe you should file a bug report at your Linux distro's bug tracker?

**Comment by fragglet** [comment]
I agree with Fabian - it's definitely worth filing a report. This seems to be an issue with Slackware in general (Salix OS is a fork of Slackware).

But we should still fix Chocolate Doom to tolerate a windres tool if it exists.
