### ISSUE TITLE
possible to crash in MAP06

### ISSUE THREAD

**Issue by fabiangreffrath** [chocolate-doom/chocolate-doom#609]
Hi all,

in map06 of DOOM2.wad there are two lines of type 117 (DR Open Door /fast) that will immediately crash Chocolate Doom upon activation. The reason is that they are missing a tag and are 1-sided, i.e. they have no sector on their backside. These lines are linedef #24 and #25, inside the red door.

This happens in `EV_VerticalDoor()` in `src/doom/p_doors.c`:
```
sec = sides[ line->sidenum[side^1]] .sector;
```
Now imagine what happens if `line->sidenum[1] == -1`...

DOOM.EXE also does strange things as reported by dosbox, but it does not crash. Boom already has a check for this in EV_VerticalDoor() and does thus not crash either. So, how should we Chocolate Doom behave, then?

**Comment by haleyjd** [comment]
What happens under DOOM.EXE is arbitrary (properties of a sector at a pseudorandom address in memory are manipulated, possibly corrupting other parts of memory). 

Implementing the BOOM fix is certainly not behaving in a vanilla manner, because I have in fact had DOS DOOM cause a venetian blinds crash by activating one-sided door lines.

**Comment by chungy** [comment]
Seems to leave the process hanging consistently in DOSBox. The music plays, but nothing else.

Crashing where vanilla does is of course appropriate. I think crashing where vanilla locks up isn't bad either. At least on Linux and Windows, a hung process that has captured the mouse and keyboard can cause some grief with killing the process and using the system even afterwards.

**Comment by linguica** [comment]
I feel like it would probably be better if Chocolate Doom added an I_Error() message instead of just silently crashing, so that people would at least have some idea of what happened.

**Comment by jmtd** [comment]
Venetian blind crashes trigger a segfault in DOSBox for me on OS X.

I agree with @linguica; it's appropriate for c-d to exit when the error occurs, as exiting is vanilla behaviour; it's in-line with project philosophy to give a clear message to the user as to what happened; but it should be a 'clean', captured exit, not a sigbus, segfault or whatever.

**Comment by fabiangreffrath** [comment]
Since https://github.com/chocolate-doom/chocolate-doom/commit/0cb9b40b21e08efc10cd33ead3e4d83c2ff8438b we now exit with a proper error message instead of crashing.
