### ISSUE TITLE
Differing values for reserved PCX header byte

### ISSUE THREAD

**Issue by PorscheMonty** [chocolate-doom/chocolate-doom#623]
The official reference papers for the PCX format, which Doom uses for saving screenshots, dictates the header's 64th byte to be reserved (defaulting to 00h), meaning we can use it for whatever purpose we please, and Doom does indeed appear to be using it, even though I don't have much of a clue as to what's actually being written there.

Vanilla Doom writes down the same value to the reserved byte regardless of screenblocks setting under normal conditions. However, upon triggering the HUD glitch (which's also replicated in Chocolate Doom), screenblocks 11 and 10 get one value,  while 9 to 3 get another, presumably because of the tiles.

The same pattern holds consistently true for Chocolate Doom under the exact same circumstances, yet the values will differ.

I have run a simple screenshot test for a static scenery and right at the bottom of the message is a download link with the resulting screenshots plus the save file I used with "-loadgame 0". They're named as follows:

VN = Vanilla Doom + Normal
VG = Vanilla Doom + Glitched HUD
CN = Chocolate Doom + Normal
CG = Chocolate Doom + Glitched HUD

The 2 leftmost digits are the screenblocks setting in denary, and the 2 rightmost the reserved byte in hexadecimal.

Yes, this is so much a low priority issue (and likely in the same category as different colors for a tutti-frutti effect) that you'd probably be better off skipping over this thread altogether,  yet I find it intriguing enough to leave a record thereof.

Tested on 32-bit WinXP Pro SP3 with the latest svn build and default settings excepting mouse's which I disabled for the purpose of capturing the same exact image every time (a mouse so sensitive a fly landing on it would move it!)

Regards.

http://s000.tinyupload.com/?file_id=13428271975280489876

**Comment by fragglet** [comment]
Had a quick look at this. Offset 64 is the field named 'reserved' in the pcx_t struct defined in v_video.c. WritePCXfile() instantiates the pcx_t it writes to the screenshot file on the stack, and 'reserved' isn't populated, so it ends up getting random junk from the stack as a value.

**Comment by fragglet** [comment]
Oh, correction - it's instantiated in the zone heap, not on the stack. Which is probably even harder to emulate in terms of predicting random junk left in there by the previous user of the memory.

**Comment by jmtd** [comment]
Hang on. We're talking about a single byte of random heap data that is not used by anything? Surely there's no point trying to do anything different to what is done already?

**Comment by fragglet** [comment]
Yeah I think this is probably a hopeless cause. We should probably just initialize the reserved field to a fixed value and close the bug.

**Comment by chungy** [comment]
I think the PHILOSOPHY document already provides a good precedence for ignoring this. One unused byte in PCX is not going to affect the game in any way whatsoever, nor any software that can still read PCX files (not even to mention that most people will probably want to use PNG output, being much more useful today).

**Comment by haleyjd** [comment]
If PCX files are to be written out, I believe they should be properly formed files. For years, BOOM was generating PCX files with an incorrect palette type byte. Turns out the Windows shell in Win98 paid attention to that field and would therefore display all of them in 256 grayscale instead as 8-bit paletted images. I think there's room in PHILOSOPHY to do with this what was done with, for example, creating the save directories in Choco Strife, and just do it the "right" way.

**Comment by chungy** [comment]
> If PCX files are to be written out, I believe they should be properly formed files. For years, BOOM was generating PCX files with an incorrect palette type byte.

I agree with you to this point, but this issue is about an unused/reserved byte field totally inconsequential and vanilla otherwise writes with random (largely unpredictable) junk. ;)

**Comment by haleyjd** [comment]
Right. According to the spec (http://web.archive.org/web/20100206055706/http://www.qzx.com/pc-gpe/pcx.txt) all reserved and padding bytes should be zero-filled.

**Comment by chungy** [comment]
Following the PCX spec is probably the right thing to do, ignoring whatever vanilla does to the format.

**Comment by PorscheMonty** [comment]
Thanks for looking into this. I was expecting it to go more or less ignored given the warning.

**Comment by haleyjd** [comment]
Closing.
