### ISSUE TITLE
A little test pwad that will crash Chocolate but not Vanilla

### ISSUE THREAD

**Issue by PorscheMonty** [chocolate-doom/chocolate-doom#624]
http://s000.tinyupload.com/?file_id=36713374412117827702

Yes, I can think of better ways of tagging a sector...nevertheless, if vanilla can handle it, so should CD.

Tested with chocolate-doom-20151011-win32.zip on 32-Bit WinXP Pro SP3, default settings. No relevant stderr message given.

Regards.

**Comment by fabiangreffrath** [comment]
PrBoom+ doesn't load it either:
```
linedef 4 for seg 3 references a non-existent sidedef 65535
```

**Comment by fabiangreffrath** [comment]
Even if Vanilla doesn't crash (yet!), I think we can say for sure that it reads invalid memory and thus causes a segmentation fault. DOS just doesn't catch this. 

We could implement the following error message from PrBoom+ in PLoadSegs():
```
      //e6y: check for wrong indexes
      if ((unsigned)ldef->sidenum[side] >= (unsigned)numsides)
      {
        I_Error("P_LoadSegs: linedef %d for seg %d references a non-existent sidedef %d",
          linedef, i, (unsigned)ldef->sidenum[side]);
      }

```

**Comment by haleyjd** [comment]
It does not in fact cause a page fault as DOS4GW would terminate the program; however, DOS4GW assigns address space to the application in a very lenient manner so it takes considerably out-of-range, non-sense addresses in order to achieve this. The result when a page fault *is* triggered is usually a Venetian blinds crash since the video hardware isn't reset properly.

**Comment by PorscheMonty** [comment]
Thanks for looking into this. Is there a particular setup in which vanilla would actually crash upon loading this mangled map?

Regards.

**Comment by fabiangreffrath** [comment]
Hard to say, try running it with less available memory (see e.g. the effect this has on https://github.com/chocolate-doom/chocolate-doom/issues/530).

I think it it safe to error our if this occurs, though. There is no way for us to properly handle this map bug or properly emulate the invalid memory read it causes, right?

**Comment by PorscheMonty** [comment]
I wonder if DOS/32 and it's many settings would help anybody figure this one out.
