### ISSUE TITLE
Let's add bash-completion scriplets

### ISSUE THREAD

**Issue by fabiangreffrath** [chocolate-doom/chocolate-doom#626]
Dear friends,

I would like to add bash-completion scriptlets for the four chocolate-* games. Bash-completion is the program that interprets the incomplete command line in bash when [tab][tab] is pressed. I will paste an example below.

The problem is to keep all the possible command line options in sync with the features selected at build time (plus, not all features are available for all four games and some should probably not get exposed on the command line). I know that we currently achieve this for the generation of the manpages, but I am still not fluent in Python.
Second, some command line parameters expect further options which may vary from game to game, e.g. the number of available episoses for `-episode` or the valid file extensions for `-deh`. I am not sure if we should simply not suggest further options for these parameters at all or if we should go the hard way and auto-generate the patterns.
Third, of course, I'd like the template to remain as simple as possible and probably use the same template for all four games.

Example of a rather complete bash-completion file (to test install as `~/.bash_completion` and restart `bash`):
```
# bash completion for Chocolate Doom                       -*- shell-script -*-

_chocolate_doom()
{
    local cur prev words cword
    _init_completion || return

    case $prev in
        -config|-extraconfig)
            _filedir cfg
            ;;
        -episode)
            COMPREPLY=(1 2 3 4)
            ;;
        -file|-iwad|-aa|-af|-as|-merge|-nwtmerge)
            _filedir wad
            ;;
        -loadgame)
            COMPREPLY=(0 1 2 3 4 5)
            ;;
        -pack)
            COMPREPLY=(doom2 tnt plutonia)
            ;;
        -skill)
            COMPREPLY=(1 2 3 4 5)
            ;;
        -gameversion)
            COMPREPLY=(1.9 ultimate final final2 hacx chex)
            ;;
        -setmen)
            COMPREPLY=(dos622 dos71 dosbox)
            ;;
        -playdemo|-timedemo)
            _filedir lmp
            ;;
        -deh)
            _filedir bex deh
            ;;
    esac

    if [[ $cur == -* ]]; then
        COMPREPLY=( $( compgen -W '-1 -2 -3 -aa -af -altdeath -as -autojoin -avg
        -cdrom -config -connect -deathmatch -dedicated -deh -dehlump -devparm
        -donut -dumpsubstconfig -dup -episode -extraconfig -extratics -fast
        -file -fullscreen -gameversion -geometry -grabmouse -height
        -ignoreversion -iwad -left -loadgame -localsearch -longtics -maxdemo -mb
        -merge -mmap -newsync -noblit -nocheats -nodeh -nodes -nodraw
        -nograbmouse -nomonsters -nomouse -nomusic -nonovert -nosfx -nosound
        -novert -nwtmerge -pack -playdemo -port -privateserver -query -record
        -respawn -right -search -server -servername -setmem -skill -solo
        -spechit -statdump -timedemo -timer -turbo -warp -width -window
        -zonescan -zonezero ' -- "$cur" ) )
    fi
} &&

complete -F _chocolate_doom chocolate-doom chocolate-heretic chocolate-hexen chocolate-strife

# ex: ts=4 sw=4 et filetype=sh
```

**Comment by fragglet** [comment]
Oh, nice. We should definitely do this.

Considering we already have a script that can determine the full list of command line arguments, we should probably extend docgen to generate the argument list as well. But what you've posted here looks fine to commit as an initial version.

**Comment by fragglet** [comment]
One question: is it worth including completions for -skill and -episode? As they're only a single character long there's nothing to complete, surely?

**Comment by fragglet** [comment]
-gameversion is also missing some of the newer values (1.666, 1.8, etc.) - compare to 29187fab9c9c39b77a8a07fef9fee299ae0125f4 that was committed a couple of days ago. When we do the docgen thing, we should add a new @ tag for "enum-type" arguments like this, so that we can document this within the source code.

**Comment by fabiangreffrath** [comment]
> we should probably extend docgen to generate the argument list as well

Yes, please. I just don't feel capable of doing this myself.

> But what you've posted here looks fine to commit as an initial version.

I can probably push this tomorrow. Should I integrate its installation into any of the `Makefile.am` or should we leave proper installation as an exercise to distributors? I don't know if there is a canonical place for bash-completions.

> is it worth including completions for -skill and -episode?

Maybe not, but I found it nice for them to show the possible valid values, although they are only single-digit.

> -gameversion is also missing some of the newer values (1.666, 1.8, etc.) 

Ack. I have compiled the list against an outdated snapshot.

> When we do the docgen thing, we should add a new @ tag for "enum-type" arguments like this

I'd leave this to the actual implementors. ;)

**Comment by fragglet** [comment]
> Yes, please. I just don't feel capable of doing this myself.

You can learn Python, Fabian! I believe in you! :)

> I don't know if there is a canonical place for bash-completions.

I don't know either. It sounds like something that's probably highly distribution-specific. Let's leave it for manual installation for the time being.

**Comment by AXDOOMER** [comment]
-scanline is missing? Should it be added?

**Comment by fragglet** [comment]
-scanline is a hack that is deliberately undocumented.

**Comment by fabiangreffrath** [comment]
> You can learn Python, Fabian! I believe in you! :)

I am sure, but I doubt that `docgen` is the right script to start learning the language with.

I think we could even auto-generate the first part of the snippet as well. If we add another @ tag for the possible valid options to a command line parameter, we should probably also accept file name extensions like `*.wad` which would result in the corresponding `_filedir` line.

**Comment by fabiangreffrath** [comment]
This should be fixed by https://github.com/chocolate-doom/chocolate-doom/commit/ad37a8ff334476f57a1d0ea55b5022bca5010fe8 and some of the latter commits.
