### ISSUE TITLE
Can't seem to access http://latest.chocolate-doom.org

### ISSUE THREAD

**Issue by PorscheMonty** [chocolate-doom/chocolate-doom#627]
Is it normal?
Regards.

**Comment by fragglet** [comment]
The server hosting the daily builds has died. I'm hoping to be able to get it back up in a couple of weeks.

**Comment by fabiangreffrath** [comment]
Am Sonntag, den 18.10.2015, 13:31 -0700 schrieb Simon Howard:
> The server hosting the daily builds has died. I'm hoping to be able
> to get it back up in a couple of weeks.

Since I get asked this regularly, but cannot set up a build server on
my own: Would you mind extending the current build server
infrastructure to also buid Crispy Doom snapshots as well?

Thank you!

 - Fabian

**Comment by jmtd** [comment]
> The server hosting the daily builds has died. I'm hoping to be able to get it back up in a couple of weeks.

Why don't we move daily builds to chew/redmars (and do crispy ones too?)

**Comment by fabiangreffrath** [comment]
I have never heard of this before, could you please elaborate?

**Comment by jmtd** [comment]
> I have never heard of this before, could you please elaborate?

`chew.redmars.org` is a VPS which Fraggle, myself and a few others share. It hosts http://www.chocolate-doom.org/, http://www.soulsphere.org/ and http://jmtd.net, amongst others, and used to host the Freedoom nightly builds. I'm suggesting we could put chocolate-doom (and related) nightlies on there.

**Comment by PorscheMonty** [comment]
@fragglet: thanks, I'll be keeping an eye on this thread.

**Comment by fragglet** [comment]
HEAD builds are back. There are no SDL2 builds yet.

**Comment by fabiangreffrath** [comment]
Am Dienstag, den 24.11.2015, 19:56 -0800 schrieb Simon Howard:
> HEAD builds are back. There are no SDL2 builds yet.

Hm, may I possibly ask if it is possibly possible to also build Crispy
Doom snapshots on this server? Please!

Thank you!

 - Fabian

**Comment by fragglet** [comment]
Done.

**Comment by nukeykt** [comment]
Got missing libgcc_s_sjlj-1.dll error.

**Comment by fragglet** [comment]
Which binary?

**Comment by nukeykt** [comment]
All.

**Comment by nukeykt** [comment]
The problem in SDL.dll

**Comment by fabiangreffrath** [comment]
Am Mittwoch, den 25.11.2015, 17:49 -0800 schrieb Simon Howard:
> Done.

Thank you so much! \o/

One further request: Could you please only provide crispy-doom*.zip?
The other three games are effectively unmaintained.

Thanks,

Fabian

**Comment by fabiangreffrath** [comment]
Am Mittwoch, den 25.11.2015, 21:43 -0800 schrieb Alexey Khokholov:
> The problem in SDL.dll

Let me guess, you are building in an MSYS2 environment? They are using
dynamic linking for *everything*, even the GCC helper libraries.

https://github.com/Alexpux/MINGW-packages/issues/865#issuecomment-153721934

Cheers,

Fabian

**Comment by fabiangreffrath** [comment]
From the build log:
```
checking for src_new in -lsamplerate... no
checking for zlibVersion in -lz... no
checking for png_get_io_ptr in -lpng... no
```
Unfortunately, this means no sound resampling and no PNG screenshots. :(

**Comment by fragglet** [comment]
I'm building on a Linux machine. I never use MSYS.

I can probably substitute in the official SDL DLLs from the SDL website; I imagine that should solve the problem.

**Comment by fragglet** [comment]
https://stackoverflow.com/questions/12921911/mingw-libgcc-s-sjlj-1-dll-is-missing

**Comment by fragglet** [comment]
Do the binaries work okay now? I added -static-libgcc.

**Comment by nukeykt** [comment]
No, still getting error the same error.

**Comment by nukeykt** [comment]
It works with SDL.dll from SDL site.

**Comment by fragglet** [comment]
Sorry, didn't update all the files. Is it better now?

**Comment by nukeykt** [comment]
Missing:
libsamplerate-0.dll
libgcc_s_sjlj-1.dll

**Comment by fabiangreffrath** [comment]
Reportedly, any attempt to start Crispy Doom downloaded from this site still fails with error messages like 
```
"crispy-doom-setup.exe - Unable To Locate Component
This application has failed to start because libgcc_s_sjlj-1.dll was not found. Re-installing the application may fix this problem."
```

**Comment by fabiangreffrath** [comment]
The `libgcc_s_sjlj-1.dll was not found` issue still isn't fixed for the Crispy Doom snapshots. I cannot currently test the Chocolate Doom snapshots, though, because I am not near a Windows system, but are there any chances that this gets fixed soon? Thank you!

**Comment by chungy** [comment]
> I cannot currently test the Chocolate Doom snapshots, though, because I am not near a Windows system

I imagine you should be able to use Wine...

**Comment by fabiangreffrath** [comment]
Choco is also affected.

Maybe we should just include this friggin DLL in the ZIP archives and be done with it. It won't hurt anyway.

**Comment by fabiangreffrath** [comment]
The file is in
```
/usr/lib/gcc/i686-w64-mingw32/*-win32/libgcc_s_sjlj-1.dll
```
in the `gcc-mingw-w64-i686` package.

**Comment by fragglet** [comment]
So I previously added -static-libgcc but it didn't work because the libSDL build was dropping the arg at the final linker step. The version of libtool in SDL 1.2.15 is from 2012 so it may be way out of date, and of course there are no new SDL 1.2 releases expected. So this seems like another reason we should finish the SDL2 port :)

For now I believe I've resolved the issue by just copying in the version of SDL.dll from the 2.2.1 release, but of course I can't check myself so if someone can take a look I'll appreciate it.

**Comment by Danfun64** [comment]
Well the good news is that the exe can run properly. The bad news is  "
Failed to load substitute music file: doom2-music\d_dm2ttl.flac: Unrecognized music format" and "I_SDL_InitSound: use_libsamplerate=1, but libsamplerate support not compiled in."

In other words, it will run, but libsamplerate is *still* missing.

**Comment by fabiangreffrath** [comment]
Hey Simon,

do you think it would be possible to also add libsamplerate to the
build environment for the snapshot builds?

Thank you!

 - Fabian

**Comment by fragglet** [comment]
I'm planning to do it - just haven't gotten around to it yet.

**Comment by Danfun64** [comment]
Are you also planning on including whatever is necessary for fluidsynth (because microsoft synth breaks volume controls and gus patches are limited) and music replacements?

**Comment by fabiangreffrath** [comment]
Am Freitag, den 05.02.2016, 22:30 -0800 schrieb Danfun64:
> Are you also planning on including whatever is necessary for
> fluidsynth (because microsoft synth breaks volume controls and gus
> patches are limited) and music replacements?

Fluidsynth may be a bit tricky, because it pulls in quite some heavy-
weight dependencies such as libglib.

 - Fabian

**Comment by Danfun64** [comment]
When I said fluidsynth, I meant to say something like SDL_FORCE_SOUNDFONTS=1 SDL_SOUNDFONTS="/usr/share/sounds/sf2/WeedsGM3.sf2:/usr/share/sounds/sf2/WeedsGM4 Update.sf2"

What about the music replacement dlls?

**Comment by fabiangreffrath** [comment]
In this case you'll need to replace `sdl_mixer.dll` with a fluidsynth-enabled version. You may want to try the one shipped with MSYS2.

**Comment by Danfun64** [comment]
and what dlls would I need for the music replacement feature?

**Comment by Danfun64** [comment]
With all the dlls, I got the music replacement feature working, but I haven't figured out how to use SDL_SOUNDFONTS.

**Comment by fabiangreffrath** [comment]
You will also have to set `SDL_FORCE_SOUNDFONTS=1`.

**Comment by Danfun64** [comment]
I already knew that, I just don't know how to set those variables in a windows batch file.

**Comment by fabiangreffrath** [comment]
Hi Simon,

it has been brought to my attention that from last Friday (11 Mar) on the
Crispy Doom builds on latest.chocolate-doom.org aren't updated anymore.
What could probably be the cause for this?

Thanks!

 - Fabian

**Comment by fabiangreffrath** [comment]
Am Freitag, den 18.03.2016, 18:07 +0100 schrieb Fabian Greffrath:
> it has been brought to my attention that from last Friday (11 Mar) on
> the
> Crispy Doom builds on latest.chocolate-doom.org aren't updated anymore.
> What could probably be the cause for this?
> 

Simon?

Is it possible to read the build logs of the apparently failed builds?

Thanks,

Fabian

**Comment by fragglet** [comment]
Hey,

Sorry for taking so long to look at this. It's failing because of fabiangreffrath/crispy-doom@70b7eb43 which disabled the builds of the heretic/hexen/strife .exes. If you can update the ZIPS variable in pkg/win32/GNUmakefile to match, it should all work again.

**Comment by fabiangreffrath** [comment]
Oh, great, thanks for looking into this! I just commited a patch that
should fix this.

 - Fabian


Am Donnerstag, den 24.03.2016, 10:44 -0700 schrieb Simon Howard:
> Sorry for taking so long to look at this. It's failing because of fab
> iangreffrath/crispy-doom@70b7eb4 which disabled the builds of the
> heretic/hexen/strife .exes. If you can update the ZIPS variable in
> pkg/win32/GNUmakefile to match, it should all work again.

**Comment by fragglet** [comment]
Seems to be working again now.

**Comment by fabiangreffrath** [comment]
Am Freitag, den 25.03.2016, 08:59 -0700 schrieb Simon Howard:
> Seems to be working again now.

This is great, thank you very much!

 - Fabian
