### ISSUE TITLE
Doom 2 - level 14: 0% secrets

### ISSUE THREAD

**Issue by YuGiOhJCJ** [chocolate-doom/chocolate-doom#633]
Hello,

I remark that when I finish the level 14 of doom 2, I got a 0% secrets completed.
But this map has no secrets so it should show 100%, isn't it?

I followed a video walkthrough on the Internet and the player got a 100% secrets done on this map (with zdoom) : https://www.youtube.com/watch?v=7NE8fpPPvBI

Do you know why I got 0% secrets done instead of 100%?

Thank you.
Best regards.

**Comment by fragglet** [comment]
Thanks for the report. This is Vanilla behavior. See: http://doomwiki.org/wiki/Secret
