### ISSUE TITLE
Visual Studio solution out of date (slightly).

### ISSUE THREAD

**Issue by Super6-4** [chocolate-doom/chocolate-doom#636]
"v_diskicon.c" is not referenced in the source and "v_diskicon.h" is not referenced in the headers for each individual game project.
***
*Extra Stuff*

I'm not sure what version of VS everyone else is using (if at all), but upgrading the solution to at least VS2010 could be a slight benefit. This is because VS2010 and beyond support solution roundtripping.

Also, if you are trying to build with precompiled SDL (1.2 or even 2) with VS2015, you will need to compile SDL yourself (with VS2015) in order to link properly with SDL. [Why](http://stackoverflow.com/questions/30412951/unresolved-external-symbol-imp-fprintf-and-imp-iob-func-sdl2)

**Comment by chungy** [comment]
Most Chocolate Doom contributors don't use Visual Studio, nor even run Windows. These solutions often go out of date and aren't noticed until much later and somebody tries using them. Looks like this particular issue was resolved with the PR #637 -- you can feel free to send PRs as well whenever this happens :)

**Comment by fabiangreffrath** [comment]
Am Donnerstag, den 05.11.2015, 22:33 -0800 schrieb Super6-4:
> Also, if you are trying to build with precompiled SDL (1.2 or even 2)
> with VS2015, you will need to compile SDL yourself (with VS2015) in
> order to link properly with SDL. Why

Yay for silent ABI breaks in stdlib! \o/

 - Fabian
