### ISSUE TITLE
Chocolate Strife A_FireSigil appears to use signed rather than unsigned shift right

### ISSUE THREAD

**Issue by fragglet** [chocolate-doom/chocolate-doom#641]
I posted this on Doomworld about a week ago in response to a comment by jval:

https://www.doomworld.com/vb/post/1519320

**Comment by fragglet** [comment]
Fix is probably just a matter of changing that one line to:

            an = (unsigned int) player->pitch >> ANGLETOFINESHIFT;

But I want to hear back from Quasar first to see if he agrees with my reasoning.

**Comment by haleyjd** [comment]
Seems the results are reliable as long as the value of UINT_MAX is 2^32 - 1. If it isn't, then that code won't function as expected (but then likely most of the rest of the engine will not as well).

**Comment by haleyjd** [comment]
Looks like this got forgotten amidst a million other things... working on the fix right now. Adding the unsigned int cast is not deleterious for the MSVC build at least. I'll need you to check the assembly output from GCC and Clang though to make sure a `shr` comes out instead of a `sar`.

**Comment by haleyjd** [comment]
Issue addressed in 21668ac ; leaving ticket open for verification.

**Comment by haleyjd** [comment]
Closing as fixed.
