### ISSUE TITLE
Broken multitrack midi playback

### ISSUE THREAD

**Issue by nukeykt** [chocolate-doom/chocolate-doom#643]
AV.wad map20 music playback broken in chocolate doom. Some tracks start playing much earlier than should (drums and basses for example).

**Comment by nukeykt** [comment]
Sample:
https://drive.google.com/file/d/0B4n8cpbZ9qicQ1JJTHozS2U2VWM/view?usp=sharing

**Comment by nukeykt** [comment]
You can see how integrated MIDI2MUS converter handles multitrack midi on my reverse engineered code:
https://drive.google.com/file/d/0B4n8cpbZ9qicSzNyaDBVa2VQdGs/view?usp=sharing

**Comment by sneakernets** [comment]
Yep, can confirm. Glad you found this one! O_O
