### ISSUE TITLE
The "MRJONES" cheat in Hexen shows the current build date

### ISSUE THREAD

**Issue by fabiangreffrath** [chocolate-doom/chocolate-doom#644]
Hi all,

typing the MRJONES cheat in Hexen is supposed to show the date the binary was built. Correctly so, in the case of Chocolate Hexen it shows some date in 2015, which is most probably not the same date the original HEXEN.EXE showed. I don't have a DOS executable at hand right now to check, but maybe we should just hard-code the build date shown by the MRJONES cheat to match the one of HEXEN.EXE.

Also, this will enable Chocolate-* to build reproducibly: https://reproducible-builds.org/

 - Fabian

**Comment by fragglet** [comment]
Slightly counterintuitive but ultimately a good call I think. The reproducible builds issue makes it a lot more clear-cut.

**Comment by fabiangreffrath** [comment]
> Slightly counterintuitive but ultimately a good call I think.

What do you mean by "counterintuitive"? Hard-coding an ancient build date? ;-)

**Comment by fragglet** [comment]
Exactly.

**Comment by chungy** [comment]
> I don't have a DOS executable at hand right now to check

You can grab one from my iwad-patches repo: https://github.com/Doom-Utils/iwad-patches/tree/master/vanilla-engine/Hexen%201.1

**Comment by fabiangreffrath** [comment]
> You can grab one from my iwad-patches repo

I forgot about this. Very useful, though, thanks!
