### ISSUE TITLE
Chex Quest crashes when starting server

### ISSUE THREAD

**Issue by Danfun64** [chocolate-doom/chocolate-doom#647]
First of all, do chex.wad and chex2.wad even have coop and deathmatch starts? If not, then I can see why this bug exists...

if not...

When I try to create a chex quest multiplayer match using the latest stable chocolate doom, it immediately crashes when I press f10.

When I open chocolate-doom-setup through the terminal, the following happens: https://paste.debian.net/?hidden=48ad70fe;lines=0

Suggestions?

**Comment by fragglet** [comment]
I assume you mean F10 at the multiplayer waiting screen and not within the game.

Probably a bug in the level number checking code causing the internal server to reject start packets from the internal client.

**Comment by Danfun64** [comment]
For whatever reason, the bug can be worked around by setting the iwad to doom.wad, having chex.wad as the pwad, and setting "-gameversion chex".

**Comment by fragglet** [comment]
Bug fixed; thanks for the report.
