### ISSUE TITLE
http://latest.chocolate-doom.com autobuilds don't come with every dll necessary to load the game.

### ISSUE THREAD

**Issue by Danfun64** [chocolate-doom/chocolate-doom#648]
In order to test an unrelated bug, I am trying to access the windows autobuilds. However, when I try to access them, I get dll errors. As I assume the point of autobuilds is to use the latest code without compiling anything, this is a rather big issue.

**Comment by Danfun64** [comment]
I'm an idiot. This bug is mentioned in #627. Perhaps this should give the issue a little "push" to get I resolved?

**Comment by fragglet** [comment]
Thanks for the report; marking as dupe.
