### ISSUE TITLE
autogen.sh should not run ./configure

### ISSUE THREAD

**Issue by andwj** [chocolate-doom/chocolate-doom#652]
It is not expected behaviour that autogen.sh also runs ./configure.  That is annoying because the user has no opportunity to run ./configure --help and select the options which they prefer, and/or to use the --quiet option.  This is the first time I have encountered a project where autogen.sh has behaved this way.

**Comment by jmtd** [comment]
> It is not expected behaviour that autogen.sh also runs ./configure.

I've seen both, so I'd be interested to know what is "correct", and separately, whether there's any kind of broad consensus on which way to go.

> That is annoying because the user has no opportunity to run ./configure --help and select the options which they prefer, and/or to use the --quiet option.

At least until after it runs, when the can run it again. So it's not "destructive", just annoying.

> This is the first time I have encountered a project where autogen.sh has behaved this way.

I've seen it plenty of times; I'm just not sure which is "correct" (if there is such a notion: such as whether the GNU folks have indicated what to do in a style guide, although I'm not sure whether autogen is a post-hoc addition to the GNU auto* build philosophy) nor which is more common (I'm not sure which I've seen more often.)

**Comment by fragglet** [comment]
Running configure is always the behavior I've always seen. Any parameters passed to it get passed through to configure, so you can just do ./autogen.sh --help or ./autogen.sh --quiet if you want. There are plenty of examples of projects which do this; all the gnome libraries and tools do it for example. But in my brief Google searches it does seem to be a toss-up between the two approaches - about half do it this way, about half leave it to the user to run configure.

It might be argued that the script is kind of redundant now that all it does is run autoreconf (it used to run all the commands individually). But it's probably best to keep it around for the sake of existing documentation and for convention.

**Comment by andwj** [comment]
I hadn't realised this behavior was so common.  I did have a look around the GNU documentation and did not find any recommendation either way.  Indeed "autoreconf" seems to be the preferred way these days.

**Comment by jmtd** [comment]
My memory is that autogen.sh is something that many packages started to add on top of autotools but was never a "blessed" or official part of the build chain. autoreconf seems to me to be a recognition of the need to do what people were writing autogen.sh for.

**Comment by chungy** [comment]
It'd probably be better to just get rid of the script and promote using autoreconf directly. While it might obsolete documentation, most of it is on wikis that are easily edited to repair any damage this might do to process guides.
