### ISSUE TITLE
play e1m8b with shareware doom1.wad

### ISSUE THREAD

**Issue by romeroyakovlev** [chocolate-doom/chocolate-doom#654]
Can i play new Romero's level with chocolate-doom and shareware doom1.wad? chocolate-doom -file e1m8b.wad say me 'Please, register'

**Comment by chungy** [comment]
Playing PWADs with Doom shareware is unsupported and the EULA of the shareware prohibits it.

You'll either have to buy Ultimate Doom (on Steam or GOG), or download Freedoom and use Phase 1 (`-iwad freedoom1.wad`) for it.

**Comment by jmtd** [comment]
e1m8b requires a limit-removing port in any case so it won't work with `chocolate-doom`. Try crispy doom or another port.
