### ISSUE TITLE
Savegame read errors can cascade into Z_Malloc error.

### ISSUE THREAD

**Issue by njankowski** [chocolate-doom/chocolate-doom#658]
Edit:
This is specifically talking of Doom, but all other games should/could be affected by this, especially since their savegame reading code is similar.

Old:
See #85

p_saveg
`boolean savegame_error`
Set properly on a read error, but never used for anything.
`saveg_read8()`
Returns a valid value of 0 on a read error.

In the case of #85, `P_UnArchiveThinkers()` is where the error (EOF) occurs, but the problem doesn't surface until `P_UnArchiveSpecials()`.

`tc_end == 0`
Causes `P_UnArchiveThinkers()` to return after the read error.
`tc_ceiling == 0`
Causes `P_UnArchiveSpecials()` to keep building ceilings until Zone runs out of memory, with `saveg_read8()` returning 0 each time in the `while(1)` loop.

**Comment by bb010g** [comment]
Closed by #800.
