### ISSUE TITLE
What's missing to merge the sdl2 branch?

### ISSUE THREAD

**Issue by vanfanel** [chocolate-doom/chocolate-doom#664]
Hi,

Some of us are in systems where SDL1 is more of a legacy thing, plagued with workarounds and hacks to work, as in the case of the Raspberry Pi.
So, what's missing for SDL2 branch merging? We really could use modern SDL1 and get rid of it at last...

**Comment by fragglet** [comment]
Thanks for the interest. It's really not finished yet, but we're making progress. There's a summary of the status here:

http://www.chocolate-doom.org/wiki/index.php/Sdl2-branch

If you want to try it out and report any bugs on #450 it would be most helpful.
