### ISSUE TITLE
Chocolate-Doom doesn't use m_random for its pitched sounds?

### ISSUE THREAD

**Issue by AXDOOMER** [chocolate-doom/chocolate-doom#665]
When I launch Chocolate-Doom with  "chocolate-doom -playdemo demo1" many times in a row, I notice that the sound pitch is always different. 

I did the same for Doom v1.1 in DOSBox, I noticed that every time I play the same demo, the sounds are always pitched the same way. 

According to the Doom Wiki, M_Random is used for pitched sounds in Doom. I didn't read the source code changes when sound pitching was added, so I don't really know if it's because M_Random is not used. When I look at Chocolate-Doom's PRNG's source code file , M_ClearRandom seeds the M_Random index with the time and in the linuxdoom-1.10 source code from id, the index is only set to 0.

**Comment by jmtd** [comment]
`M_Random` is used for the pitch-shifting in chocolate: that part of the code was actually already in, and is unmodified from vanilla (it was other parts that were disabled that we added back in). `M_Random` has to be used for it, and for screen wipes, or net games will go crazy.

However, I think that demo playback should be exactly the same. So that's weird.

**Comment by AXDOOMER** [comment]
Did you look at this?
https://github.com/id-Software/DOOM/blob/master/linuxdoom-1.10/m_random.c#L71
https://github.com/chocolate-doom/chocolate-doom/blob/master/src/doom/m_random.c#L73

Is Chocolate-Doom faithful to Vanilla Doom or it's Linux Doom that does the correct behavior?

**Comment by jmtd** [comment]
> You're talking about this, right?

Hm, I didn't realise we did that. Simon seemed to decide to do that in `59aad53b` (10 years ago!)

I guess the question is, do we think it is important that `M_Random` consumers are reproducible? I suppose it could be important if we ever advanced beyond doing framebuffer comparisons to multimedia comparisons for accuracy comparison.

I've pushed a simple revert to [here](https://github.com/jmtd/chocolate-doom/tree/jmtd-revert-mrandom-seeding) to act as a talking-point.

**Comment by AXDOOMER** [comment]
Although this removes the randomization from the first wipe screen, it's not pixel perfect with Vanilla. 
Choco: ![choco](https://cloud.githubusercontent.com/assets/6194072/13448181/e7dd7dd4-dfee-11e5-8757-efd945e9824b.jpg)
Vanilla: ![van](https://cloud.githubusercontent.com/assets/6194072/13448182/e8b39fb8-dfee-11e5-8024-465ea2fec1ec.jpg)

The far left of the wipe screen is much different (but you can't see it in my pictures).

**Comment by jmtd** [comment]
Chocolate should at least be reproducible now, so it should be possible to fine-tune the wipe behaviour and pitch behaviours to match vanilla. Where I would start is tapping the original EXEs and finding out how many M_Random calls take place before the first tic of the level and see if that matches Chocolate. Come to think of it, is the wipe consistent across all vanilla versions?

**Comment by fragglet** [comment]
Can't help thinking we may have entered the realm of madness if we're trying to make the M_Random() behavior deterministic.
