### ISSUE TITLE
Freedoom and FreeDM are not mentionned in INSTALL.txt

### ISSUE THREAD

**Issue by AXDOOMER** [chocolate-doom/chocolate-doom#666]
INSTALL.txt is a file that comes with the Windows builds. It explains how to obtain WAD files. It doesn't mention that Chocolate-Doom supports freedm.wad, freedoom1.wad and freedoom2.wad, but only the following:
`doom1.wad                   (Shareware Doom)`
`doom.wad                    (Registered / Ultimate Doom)`
`doom2.wad                   (Doom 2)`
`tnt.wad                     (Final Doom: TNT: Evilution)`
`plutonia.wad                (Final Doom: Plutonia Experiment)`
`chex.wad                    (Chex Quest)`

**Comment by Danfun64** [comment]
To be fair, freedoom1.wad and freedoom2.wad can't be played on their own (as of this writing) in Chocolate, but require pwads.

**Comment by fragglet** [comment]
Let's add freedm.wad to the list.
