### ISSUE TITLE
OPL3 emulation

### ISSUE THREAD

**Issue by nukeykt** [chocolate-doom/chocolate-doom#667]
Will it be possible to integrate my Nuked OPL3 emulator to Chocolate Doom. Nuked OPL3 seems now pretty accurate compared to real OPL3.
Also my emulator in some cases can produce bit-perfect sound.
But Nuked OPL3 has some disadvantages:
My code slower than DBOPL.
My emulator works only at 49716hz sample rate. So, resampler will be required.

Code:
https://github.com/nukeykt/chocolate-doom-beta-opl/blob/master/opl/opl3.c

Side by side comparison of Real OPL3(Right channel) and Nuked OPL3(Left channel).
https://drive.google.com/file/d/0B4n8cpbZ9qicQnhtMWJXRWh2Q3c/view?usp=sharing

You can request more samples.

**Comment by fragglet** [comment]
This sounds like a great idea. Your code is written entirely from scratch?

**Comment by nukeykt** [comment]
Phase generator and tremolo lfo are based on code from http://forums.submarine.org.uk/
Other code is written from scratch

**Comment by fragglet** [comment]
If we can get permission from the authors of that code then we can certainly include it.

**Comment by nukeykt** [comment]
I think i should write my own code

**Comment by nukeykt** [comment]
More comparisons:
https://youtu.be/6qXMIm4eSCc

I wrote own tremolo code.
Now i'm writing own phase generator.

**Comment by nukeykt** [comment]
Updated my emulator to 1.6.2 version.
