### ISSUE TITLE
Is there a way to have chocolate doom ignore the visplane limit?

### ISSUE THREAD

**Issue by CraftedPixel** [chocolate-doom/chocolate-doom#670]
I wanted to play freedoom 1 and 2 on chocolate doom but had no choice but to run on a modern doom engine like zdoom and gzdoom. Any way I can have chocolate doom ingnore limits without intentionally crashing?

**Comment by fragglet** [comment]
No, it is out of scope for the project. You might want to check out Crispy Doom.

**Comment by CraftedPixel** [comment]
I have a mac and want to know how to compile the source code for crispy doom. I don't have windows

**Comment by fragglet** [comment]
I don't think @fabiangreffrath is doing Mac builds yet. There are instructions on the wiki on how to build Chocolate Doom:

http://www.chocolate-doom.org/wiki/index.php/Building_Chocolate_Doom_on_Mac_OS_X

You can probably adapt the build script to build Crispy instead - you need to edit the script and change the Git repository address to point to the Crispy Doom one (then run it with -git). As far as I know you'd be the first Mac Crispy user though so this is kind of uncharted waters. Good luck!

**Comment by jmtd** [comment]
[I've put a compiled crispy-doom and crispy-doom-setup for OS X here](http://jmtd.net/tmp/crispy-doom.zip). I offer this now and temporarily and with no further support: I don't know whether it will work for you or not, but it's worth a shot I suppose. It needs SDL libraries installed, you might be able to extract them from the chocolate doom OS X release.

**Comment by CraftedPixel** [comment]
Woah thanks man! The only problem is not having a launcher, but I can still -wad wadfile.wad
You don't have to, but including a launcher would be convenient. Yeah I used the terminal to run the crispy doom. Thanks!
