### ISSUE TITLE
chaingun sfx should be slightly pitched up

### ISSUE THREAD

**Issue by jmtd** [chocolate-doom/chocolate-doom#671]
Apparently all DOS versions (not just <=1.2) pitched DSPISTOL up when the chaingun fires. ([doomworld thread](https://www.doomworld.com/vb/post/1565764)).

**Comment by jmtd** [comment]
I'm looking at this one. I'm not convinced that the chaingun should be pitched up unless pitch shifting is enabled, but when it is, the base pitch should be higher than it is. The issue seems to be that the check `if(sfx->link)` is never true. I'm investigating why.

**Comment by jmtd** [comment]
I'm pretty sure this was a red herring. The SOUND_LINK stuff should indeed mean the chaingun pitch is higher than the pistol, but the chaingun sound entry is never used anyway. I believe the base pitch was always the same for pistol and chaingun in vanilla. It was probably their intention to have it higher but they never finished implementing it.

**Comment by fragglet** [comment]
ISTR pitch shifting broke because the stereo and pitch parameters got switched by mistake in Vanilla? Or DMX swapped the order? So maybe there's a constant upwards pitch.
