### ISSUE TITLE
Can mouseb_reverse be implemented?

### ISSUE THREAD

**Issue by Danfun64** [chocolate-doom/chocolate-doom#689]
I would have loved to bind the "180 turn" key to the middle mouse button, but atm that is impossible? Are you willing to add that? Is this question more appropriate for Crispy?

That is, of course, if Chocolate has the 180 turn key at all.

**Comment by fragglet** [comment]
Chocolate Doom doesn't have any 180 degree turn bindings, I'm afraid. This seems like more of a crispy feature.

**Comment by Danfun64** [comment]
The problem with Crispy is that sometimes added features are obvious, and other time it isn't so.

**Comment by fabiangreffrath** [comment]
> Sometimes added features in Crispy are obvious, and other time they aren't. Oh well...

And so you decided to ask in Choco first?

Honestly, I admit that it is sometimes hard to understand and confusing which features I find fit for Crispy and which not -- and sometimes I am not so sure myself and have to sleep about it for a night or a year. But, as a rule of thumb, a feature request that either
1) endangers demo or network compatibility, 
2) requires another switch in the Crispness menu
or
3) will take me ages to implement (and by "implement" I mean "implement properly", see point 1)
has rather low chances to make it in. On the other hand, I am always very grateful for pull requests for picking low-hanging fruit. *hint*

In this specific case, the chances for adding a mouse button bound to a key that was introduced in an earlier Crispy release are rather good. ;)

**Comment by fragglet** [comment]
Wasn't unreasonable to ask! To be honest this feature is kind of on the very edge of being almost acceptable; my decision mostly came down to a matter of taste.

**Comment by fabiangreffrath** [comment]
Am Dienstag, den 29.03.2016, 12:00 -0700 schrieb Simon Howard:
> Wasn't unreasonable to ask! To be honest this feature is kind of on
> the very edge of being almost acceptable; my decision mostly came
> down to a matter of taste.

My point was that he asked to add a mouse binding to Choco for a key
which was added to Crispy in the first place. ;)

BTW, would a demo using the half-turn key be considered TAS?

 - Fabian
