### ISSUE TITLE
Choppy frame rate/gameplay from 2.0.0 beta2 onwards

### ISSUE THREAD

**Issue by Steroid-King** [chocolate-doom/chocolate-doom#693]
I have noticed choppy frame rate or gameplay from the current version, 2.2.1,  and every single version back to and including 2.0.0 beta2.  Every version from 2.0.0 beta1 and prior does not have this issue and is very smooth.  The frame rate is very choppy when compared to Crispy Doom run at 35 frames per second, vanilla DOSBox Doom, and Zandronum at its current version with frame cap on at 320x240 software renderer.  Did the author or anybody else notice this ?  Is there something I can do to fix this  ?  Am I missing anything here ?

**Comment by AXDOOMER** [comment]
Something like me maybe? https://github.com/chocolate-doom/chocolate-doom/issues/662

**Comment by Steroid-King** [comment]
Yez'zir

**Comment by Steroid-King** [comment]
I was able to pinpoint the exact build from which this issue begun to be observed

**Comment by fragglet** [comment]
Closing as dupe. By the way, what OS are you using?

**Comment by Steroid-King** [comment]
Windows 10

**Comment by fabiangreffrath** [comment]
Is this probably related to this?

https://github.com/fabiangreffrath/crispy-doom/issues/71

**Comment by Steroid-King** [comment]
I should clarify, I did in fact observe the same choppiness with the latest build for Crispy Doom @ 35fps as I did with the latest build for Choco Doom 2.2.1 so I believe it is.

**Comment by Steroid-King** [comment]
The video AXDOOMER linked to shows exactly what I was experiencing

**Comment by fabiangreffrath** [comment]
And did you try this?

https://github.com/fabiangreffrath/crispy-doom/issues/71#issuecomment-130753708

**Comment by Steroid-King** [comment]
Not yet, I will try when I get back home to-nite

**Comment by fragglet** [comment]
I'm kind of hoping that the SDL2 migration should eventually make this bug obsolete.

**Comment by Steroid-King** [comment]
changed video_driver from "" to "directx" in chocolate-doom.cfg, looks like that fixed the problem.

**Comment by AXDOOMER** [comment]
It did a difference for me too. It fixed my problem. It's simply Windows GDI that hates weird framerates. Perhaps I should completely ditch Microsoft's virus and use a better OS.
