### ISSUE TITLE
Please implement flags for dm/co-op

### ISSUE THREAD

**Issue by Steroid-King** [chocolate-doom/chocolate-doom#694]
There is a flag that I would like to request, and that would be the ability upon death in a co-op game, to keep all weapons, ammo, etc upon respawn.  Or,  to turn off team damage or adjust team damage scalar. Or, to activate cheats in a multiplayer game.  Maybe this could be implemented as a command line argument.

**Comment by Steroid-King** [comment]
Me and my buds play co-op in chocolate doom and we (that means me) have a nasty habit of team killing my buds in close quarters with a shotgun. It sort of sucks to have to go back through the entire level and pick up or find whatever weapons are available with  what little ammo is still available for them.

**Comment by AXDOOMER** [comment]
This is not in the scope of the project because it's not in Vanilla Doom.

**Comment by Steroid-King** [comment]
Could it be done or could somebody else do it ? I really don't have the talent to do it myself

**Comment by AXDOOMER** [comment]
Go ask there: https://github.com/fabiangreffrath/crispy-doom

**Comment by Steroid-King** [comment]
Thanks

**Comment by fragglet** [comment]
Out of scope for Chocolate Doom.

**Comment by plumsinus** [comment]
Hi @Steroid-King, since your requests got rejected, have you considered just playing with a dehacked patch that gives you a lot more ammo? It sounds like this would at least partly solve your issues.

**Comment by Steroid-King** [comment]
I have tried that, it's really not enough. The extra ammo would bring problems of it's own. It would cause unbalance during normal game play, make it too easy, and it would still not resolve the need for, upon respawn, to go through the map and dig for whatever weapons are out there in whichever inaccessible part of the map they happen to be in.  There are other ports that support multiplayer that has this flag able to be implemented, specifically Zandronum, but you don't get the authentic vanilla/DOS Doom experience with any of them. Zandronum has numerous issues of its own that I won't go into too much detail on here.
