### ISSUE TITLE
Heads-up on breaking change with SVE 1.3 beta IWAD detection

### ISSUE THREAD

**Issue by haleyjd** [chocolate-doom/chocolate-doom#707]
Beginning with Strife: Veteran Edition 1.3, the IWAD and voice wad file will be named STRIFE1.WAD and VOICES.WAD respectively, all caps. This is unavoidable due to a glitch in the SteamPipe CDN wherein it will not accept filename case changes w/o a corresponding change to the hash of a file; we do not want to disturb the hash codes for these files, so we have modified Veteran Edition itself to tolerate such uppercased file names (see https://github.com/svkaiser/strife-ve/blob/7b2b048140275d4851f78ee7323aebecb037bfb5/strife-ve-src/src/d_iwad.c#L418 and https://github.com/svkaiser/strife-ve/blob/7b2b048140275d4851f78ee7323aebecb037bfb5/strife-ve-src/src/d_iwad.c#L686)

I am mentioning this here because it will break IWAD autodetection for installs of Strife: Veteran Edition on Linux, unless a similar allowance is made here. How to handle this is up to you, but I will note that requests for case insensitive treatment of file names during search operations have been requested previously.

**Comment by haleyjd** [comment]
I should add a note that for users with the game already installed, the filename case will not change to the best of our knowledge, meaning a mix of lower and uppercase filenames will persist indefinitely.

**Comment by nukeykt** [comment]
I see there will be GOG release?

**Comment by haleyjd** [comment]
Soon, yes. Possibly within the week, depends on how fast they get on it. NDS still hasn't officially announced it so I'd be courteous of that if you could.

**Comment by haleyjd** [comment]
I'll note this has now been released on all platforms, but the IWAD naming may *not* be an issue after all as the very last depot we uploaded had the lowercase file names again. The GOG version will be lowercase regardless as they don't have a depot system.

**Comment by chungy** [comment]
1.3 on Steam was pushed out without the file names changing case. I believe this issue can be closed.

**Comment by haleyjd** [comment]
Technically yes but the fact users had requested this before might have been reason enough to not do so, or at the least, to find and bump one of those older issues if they're still open. In SVE I just modified the loops to check for all-lowercase or all-uppercase, which are the most common variants of the filenames which would exist. A more thorough approach would have changed to using opendir() to locate a file of that name, preferring the specified case but matching any case-insensitive match should an exact one not be found.
