### ISSUE TITLE
Chex Quest level warp cheat behavior inconsistent with original

### ISSUE THREAD

**Issue by nveaa1** [chocolate-doom/chocolate-doom#716]
In the latest Chocolate Doom (2.2.1), the behavior of the ingame level warp cheat for Chex Quest (LEESNYDER##) is inconsistent with the behavior of chex.exe.  Chocolate Doom correctly does not allow warping to episodes higher than 1 (e.g., LEESNYDER24 warps to E1M4) when emulating the Chex Quest executable.  However, using a map number higher than 5 warps to that map number for episode 1 in Chocolate Doom when emulating Chex Quest's behavior (e.g., LEESNYDER37 goes to E1M7, LEESNYDER18 goes to E1M8).  Additionally, using a map number of 6 seems to crash the whole program but _only_ when using chex.wad as the IWAD.  When using -gameversion chex with the Ultimate Doom IWAD (for example), using a map number of 6 with map warp does not crash the program.

The proper behavior in chex.exe for map numbers higher than 5 is to warp to E1M5, which I tested using the original executable in a DOSBox environment.

The only thing in stderr.txt after crashing with a map number of 6 is this:

`IOperm_InstallDriver: OpenSCManager failed (5).`

However, I seem to get that message after running Chocolate Doom at all (at least on my machine), so I don't know that the error has anything to do necessarily with the crashing issue in chex.wad.

If it matters, (not that I think it would), I'm running the Windows version on Windows 10 x64.

**Comment by nukeykt** [comment]
This bug already was fixed in 38da738 commit. I guess that E1M6 crashes due to medusa effect.

**Comment by nveaa1** [comment]
I'm a bit confused now: looking at the code, it seems like it should be fixed, yet testing the level warp with chex.wad and chex.exe in the latest Chocolate Doom I get the behavior I described in my opening post.

**Comment by nukeykt** [comment]
Chocolate Doom 2.2.1 does not include this fix. This fix will be included in next stable release. Try daily development builds: http://latest.chocolate-doom.org/

**Comment by nveaa1** [comment]
OK, that would make sense. Thanks!

**Comment by fabiangreffrath** [comment]
For the rationale: The chocolate-doom-2.2 branch has been split off of the master branch at the chocolate-doom-2.2 release tag. It gets only a chosen few fixes backported from the master branch, but not everything (understandibly). So, even if this bug has been fixed on the master branch after the chocolate-doom-2.2 branch has been split off, the latter doesn't necessarily contain this fix.
