### ISSUE TITLE
detect infinite mobj state cycles (and error out gracefully)

### ISSUE THREAD

**Issue by fabiangreffrath** [chocolate-doom/chocolate-doom#718]
Currently, it is rather easily possible to freeze Chocolate Doom in an infinite loop, consuming 100% CPU (and even crashes have been reported on Windows). Typically, this is due to the Demon Speed Bug [1], i.e. the Demon's state durations are reduced to 0 tics in an attempt to load a Nightmare difficulty or `-fast` game when another game was already started in that mode (or similar, please refer to the Doomwiki article for details).

This leaves users with an unresponsive system and while I agree that this bug also occurs in Vanilla Doom, I consider leaving it as is as a disservice to our users. We should at least error out when an infinite loop is detected and state that Vanilla would have frozen infinitely at this point.

The question is now how to detect such an infinite state loop. There is already code for this in MBF's P_SetMobjState(), but I consider this a bit too invasive for inclusion in Choco. The general recipe should be: "Has this state already been set before for the same mob_t in the same gametic?". Any ideas are welcome!

[1] http://doomwiki.org/wiki/Demon_speed_bug

**Comment by fragglet** [comment]
Yeah, this type of bug comes under exception 1 in the philosophy document. We shouldn't preserve this behavior.

Detecting such a state is difficult. Normally you could use a standard cycle-finding algorithm (eg. tortoise and hare) but P_SetMobjState() can call arbitrary action pointers which can potentially cause branching behavior so that you don't end up looping forever.

I'd probably be happy with a heuristic approach - count the number of times the loop in P_SetMobjState() executes and exit with an error once an arbitrary very large limit is reached.

**Comment by fabiangreffrath** [comment]
You mean like this?
```
--- a/src/doom/p_mobj.c
+++ b/src/doom/p_mobj.c
@@ -50,6 +50,7 @@ P_SetMobjState
   statenum_t   state )
 {
     state_t*   st;
+    int        counter = 0;
 
     do
     {
@@ -72,6 +73,12 @@ P_SetMobjState
            st->action.acp1(mobj);      
        
        state = st->nextstate;
+
+       if (++counter > SHRT_MAX)
+       {
+           I_Error("P_SetMobjState: Infinite state cycle detected!");
+       }
+
     } while (!mobj->tics);
                                
     return true;
```

**Comment by haleyjd** [comment]
Use of SHRT_MAX makes this unnecessarily subject to language in the C standard that would have that value differ between platforms.


________________________________

**Comment by fabiangreffrath** [comment]
Yes, right. What I actually meant was something like
`(const unsigned int)(1 << 16)`
or similar.

**Comment by fragglet** [comment]
SHRT_MAX has no semantic meaning either. I'd prefer just defining a proper constant, eg.

    #define MOBJ_CYCLE_LIMIT 1000000

**Comment by fabiangreffrath** [comment]
Forgot to close this in the commit message:

https://github.com/chocolate-doom/chocolate-doom/commit/7607140288b936d29f86b67eec1cbfa3eb60f5ca
