### ISSUE TITLE
Doom 1 title screen theme sounds weird in OPL mode

### ISSUE THREAD

**Issue by pazi11** [chocolate-doom/chocolate-doom#719]
Im not sure if this happens versions other than the Mac version, but the title screen theme has a weird instrument playing before it ends, which I dont think is supposed to happen. That weird instrument doesn't play when I try the game on DOSBox...

**Comment by fragglet** [comment]
Sounds the same to me. Can you describe the weird instrument you're hearing?

**Comment by pazi11** [comment]
Its near the end. It sounds like a "Neeeeeeeerrrrrr" to me.

**Comment by nukeykt** [comment]
In dosbox title duration after launch is shorter than in chocolate doom and this bad note is skipped. But in dosbox after ending game through menu you'll hear this bad note.

**Comment by pazi11** [comment]
This is what Im hearing: https://www.youtube.com/watch?v=JYWukEHGgXU

**Comment by plumsinus** [comment]
That video is set to private.

**Comment by pazi11** [comment]
Oh wait...

**Comment by pazi11** [comment]
Now it should work...

**Comment by haleyjd** [comment]
Sounds correct to me?

**Comment by pazi11** [comment]
It doesn't to me... I may be wrong though.

**Comment by sneakernets** [comment]
they sound completely different. Here's why:

The Doom exe was modified later to play "D_INTROA" for Adlib soundcards. It's likely that v1.2 doesn't have it. Not sure.

**Comment by pazi11** [comment]
I tried the regular doom IWAD and it does the same thing, and then crashes...

**Comment by sneakernets** [comment]
Are they all upgraded to v1.9? Chocolate Doom expects a v1.9 IWAD.

**Comment by pazi11** [comment]
I upgraded it to 1.5, but I cant find a patch from 1.5 to 1.9... Ugh....

**Comment by sneakernets** [comment]
http://doomwiki.org/wiki/Game_patch here is a listing of patches for you. There's a v1.2 to v1.9. I think you'll need that one.

**Comment by pazi11** [comment]
I used a 1.2 to 1.9 patch and it doesn't work. :(

**Comment by sneakernets** [comment]
Is it Doom Registered or Doom Shareware? If it's Doom Shareware, then https://www.doomworld.com/idgames/idstuff/doom/doom19s this link should be Shareware v1.9.

**Comment by pazi11** [comment]
Its registered.

**Comment by sneakernets** [comment]
Hmm. there is one more option. http://doomgate.de/content/files/ladopato/index_en.html This thing. I haven't tried it, but it should be able to patch the IWAD without worrying about having other files.

**Comment by chungy** [comment]
This patch should work if you're coming from 1.2: ftp://ftp.idsoftware.com/idstuff/doom/12_19drp.exe

**Comment by pazi11** [comment]
It randomly stopped working the second I went on it.

**Comment by pazi11** [comment]
I guess its something id decided to add into the game. Thanks!

**Comment by fragglet** [comment]
Thanks for clarifying.
