### ISSUE TITLE
SDL2: libtextscreen keyboard input seems broken

### ISSUE THREAD

**Issue by fragglet** [chocolate-doom/chocolate-doom#721]
Accelerator keys in some setup dialogs are broken.

**Comment by jmtd** [comment]
Just built ec90c9fa062440dd25e4e7fe9a3df58db7c55081 and I can't find any broken accelerators. Any idea which ones you meant? I do recall e.g. A for Advanced under GFX being broken in the dim and distant, but that's fixed.

**Comment by jmtd** [comment]
Closing assuming this has been resolved ,please reopen if I missed one.

**Comment by fragglet** [comment]
I don't think this is resolved just yet.

There are some subtleties in how input works in SDL2 and I want to make sure we get them right. For example, if we're entering text we should call `SDL_StartTextInput()` and use `SDL_TEXTINPUT` events. The reason is that doing so will activate the on-screen keyboard if one is present on the system. We already do this in the `i_input.c` code but textscreen doesn't do this yet.

The textscreen API currently has a function called `TXT_EnableKeyMapping` which is supposed to switch between input modes - "normal" input mode and a "raw" mode for binding keyboard bindings. Actually it looks like this feature is currently completely broken and the function does nothing. 

I think instead for SDL2 we need three modes:

* A "normal" mode used when interacting with the textscreen interface. In this mode the native keyboard mapping applies; for example suppose that you have a French AZERTY keyboard and a window has an accelerator bound to 'A', pressing 'A' should work as intended.

* A "text input" mode which is activated temporarily when using one of the text input widgets (eg. when entering a chat macro), and which supplies input using `SDL_TEXTINPUT` events. When we switch to this mode we also call `SDL_StartTextInput()` to activate the on-screen keyboard.

* A "raw input" mode which is activated temporarily when binding a key. In this mode keyboard mapping does not apply; we act like a US layout keyboard and provide input values which can be stored in the config file `key_` variables.

**Comment by fabiangreffrath** [comment]
When I run chocolate-doom-setup to bind "menu confirm" to my Y key (see https://github.com/chocolate-doom/chocolate-doom/issues/712), it prints Z. I have a German keyboard. Is this the issue we are talking about here?

**Comment by fragglet** [comment]
I believe this should now be fixed, as of c1ff9bfd5b0effd4377c0a9f669ca96093547d98 (what I described in my comment above is now implemented).
