### ISSUE TITLE
SDL2: Fix the window_position config variable

### ISSUE THREAD

**Issue by fragglet** [chocolate-doom/chocolate-doom#724]
This works differently now in SDL2. We need to use the parameters to SDL_CreateWindow().

**Comment by jmtd** [comment]
We should probably have the heretic start-up window and the endoom windows honour this too; and perhaps the setup programs. For me at least, the SDL 1.x branch never worked (window position is always OS determined = vaguely central for all windows regardless of window_position setting) but this might be a regression if it did work on any platforms.

**Comment by jmtd** [comment]
I keep getting the Fix: syntax wrong (or forgetting it :))

**Comment by jmtd** [comment]
ENDOOM and Heretic text start-up windows (anything using libtextscreen) don't honour this yet. (possibly bits of Strife too)

**Comment by fragglet** [comment]
I think it's fine to make do with the ENDOOM/startup screens as they are for now. Let's fix that later.
