### ISSUE TITLE
Duplicate code could be reduced

### ISSUE THREAD

**Issue by haleyjd** [chocolate-doom/chocolate-doom#725]
This might be overruled by the desire to leave the code in a pristine state and not have to introduce callbacks for minor differences, but there is still a lot of code which is 99.9% or even in some cases 100% identical between all 4 id Tech 1 games, to the point that a merging together of these could reduce the size of the codebase - and related maintenance efforts - significantly.

I wanted to test the waters with this idea; I think that the renderer is the primary target that could serve as the first test case - aside from addition of additional blending modes, support for scrolling flats, support for look up/down, and support for sprite foot clipping, I am unaware of changes made to the vast majority of the rendering infrastructure in the various games. Files like r_bsp.c show to be nearly if not completely identical.

**Comment by fragglet** [comment]
Conventional programming wisdom is certainly to de-dupe code wherever possible, and most source ports dedicate considerable effort towards this. I certainly understand the desire to do this.

It might be the right thing to do, but we should question whether it's really worth it. I de-duped a lot of stuff when I did the raven-branch work, and stopped short when I got to the actual game code. Firstly, it's likely to be a large amount of work to achieve. Secondly, the nature of the source port means that we want to be absolutely sure to preserve the correct game behavior. There are likely to be subtle but important differences between the different codebases which might get missed or lost in a merge effort. The game logic (p_*) is the most concerning part but this might extend to things like the rendering code too.

So I'm not necessarily opposed to the idea, but it needs to be carefully considered and carefully implemented if we decide to do it.

**Comment by fragglet** [comment]
One other thing to bear in mind: for other source ports like Eternity or ZDoom, this kind of de-dupe refactoring would be essential to keep the codebase clean so you can build new features (new rendering tricks, new gameplay features, etc.) without the overhead of having to make the same change four times. 

For Chocolate Doom the focus is on maintaining the code rather than adding new stuff, so this kind of refactor isn't so pressing. It's occasionally annoying when I've had to apply small changes to the menu code four times but in general most of the changes we make to Chocolate Doom are to the code that's already common (video code, sound/music code, multiplayer code, etc.)

**Comment by jmtd** [comment]
The non-obvious attitude to code duplication in chocolate-doom makes it an attractive platform for currently-vapourware projects like chocolate-boom and chocolate-mbf, which would attempt to maintain a mergeable fork with ./boom and ./mbf sub-directories, matching doom/heretic/hexen/strife, and as small a set of changes from the original sources as possible.

**Comment by haleyjd** [comment]
I fail to see how that would be impacted, as you can simply remove the game folders you have no intention of using. There would potentially be extra features in some of the modules that weren't there in the vanilla code, but not anything that would prevent these kinds of projects from still going ahead any more than the already merged portions of the code do so.


To be clear I don't think there's a suitable approach to this for stuff like the vast majority of the P_ code - there may be exceptions, like the core thinker loop, but these are lower priority to me than would be something like the renderer, which is a big fat tempting target for this approach. Some parts of the D_ code also suffer from vast duplication.


I suppose it's not a big deal and if most people are against it then I won't even test the waters but I'd really like to at the least demonstrate a concept using the renderer and see how much can actually be folded together without any special casing going on, becaus

________________________________

**Comment by fragglet** [comment]
Given that chocolate-{boom,mbf} are still vaporware it's probably best to just say YAGNI and ignore those cases until we have something more concrete to work with. 

The rendering code is probably the least controversial part to dedupe. The biggest problem there is probably defining common structure definitions that all games can use - things like the linedef, sidedef, sector types etc. which tend to subtly differ between games.

To reiterate, I'm not opposed to doing this; I just think it will be a lot of work and it's hard for me to see that it would be worth the effort. If someone wants to start a branch to try doing it they're welcome to do so.

**Comment by fx02** [comment]
I'm also interested in this "merge".

**Comment by chungy** [comment]
In addition to this, it might be a good idea to strip dead Doom code from Strife. Quite a lot is there that never runs in the game (and I don't imagine it'll all be optimized out in builds, either. switch/case statements checking for gamemodes and such).

**Comment by haleyjd** [comment]
Some of it was left deliberately to highlight the differences and changes, as far as commented out code goes anyways, and because we believe, based on how Heretic and Hexen look, that Rogue's code was probably similarly "dirty"; code that is live on the other hand, and not doing anything, may have slipped through and could be removed in some instances. I'd have to know exactly what statements you're referring to.

**Comment by jmtd** [comment]
It seems like busy-work to me, there are more exciting things to work on for sure

**Comment by haleyjd** [comment]
I'd particularly like somebody to see if they could wake up the slumbering Medusa emulation branch and find a better way of doing it than allocating a 4 MB fake heap. Since fraggle agreed that emulation of the slowdown isn't important, it might be possible to just get by with a few hundred KB for example. Some of the attempts to randomize it might be removed too as they tend to generate hitches in the framerate and don't end up really reflecting the stochastic nature of heap allocations anyway (you'd need some kind of hook into Z_Malloc to pull that off, and that's both slow and weird).

**Comment by jmtd** [comment]
> I'd particularly like somebody to see if they could wake up the slumbering Medusa emulation branch

I had a little look at it last year and if I find some time I could certainly try and take another look. It's something I would love to see finished.

**Comment by haleyjd** [comment]
I think I will close this as Carmack's recent take on the "DRY" fad that seems to be blazing itself out right now has made me see the value in the current simplicity.

**Comment by fabiangreffrath** [comment]
Am Dienstag, den 19.07.2016, 08:07 -0700 schrieb James Haley:
> Carmack's recent take on the "DRY" fad that seems to be blazing
> itself out right now

What does this mean?

 - Fabian

**Comment by haleyjd** [comment]
"Don't Repeat Yourself", the idea that duplicate code should be avoided at all costs due to maintenance issues.
