### ISSUE TITLE
SDL2: Use the game controller API

### ISSUE THREAD

**Issue by fragglet** [chocolate-doom/chocolate-doom#736]
We currently have a collection of well-known gamepads which will be auto-configured by the setup tool. As it turns out, SDL2 has a [game controller API](https://wiki.libsdl.org/CategoryGameController) which appears to do a very similar thing, and we probably ought to make use of it - either to replace the existing system or to complement it.

Should not block the v3 release.

**Comment by jmtd** [comment]
I took a brief look at that when I planned to work on sdl2/joystick support (before I had to give up for personal raisins); it didn't support my controller OOTB, but sdl2 do take commits to add controllers, see the comments at the top of [SDL_gamecontrollerdb.h](https://hg.libsdl.org/SDL/file/e12c38730512/src/joystick/SDL_gamecontrollerdb.h).

This is interesting too, a sort-of clearing house perhaps
https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt

**Comment by fragglet** [comment]
The controller database is what the game controller API is based upon. I suspect we ought to be trying to move some of our own data that we have on various game controllers upstream into the SDL database - or at least storing our own data in the same format SDL uses.

**Comment by jmtd** [comment]
Yes I think that's a good goal. There are some conventions that SDL2 imposes that aren't immediately obvious - such as, what do you map the dpad to on a controller with only a dpad when the controller model expects there to be an analog stick and possibly a dpad optionally. The controllermap tool in the SDL2 sources won't even let me use the physical d-pad to map to the virtual d-pad buttons (but will let me map it to an analog axis). Also there is likely convention as to which of the shoulder buttons (front or back) are the "main" ones (for again the situation where the controller has only one set of shoulder buttons)

I imagine, but don't know for sure, that it might take a while to get an SDL2 change pushed and then distributed around. The controllerDB also seems to annex mappings by platform: so we will need to generate DB entries multiple times for each controller :(

**Comment by jmtd** [comment]
..but in the shorter term we could support merging our own (or user supplied) db of controllers with the SDL2 one (that seems to be the point behind that second github URL I added, it's a third party project)

**Comment by fragglet** [comment]
I think the game controller API supports importing your own config strings that aren't in the standard database, so we can probably do that.

**Comment by fragglet** [comment]
Oh, and assuming we're going down this path: we currently have the [joytest program](https://github.com/chocolate-doom/joytest) which I've been using to gather controller data from people. It would be a cool project to beef this up with a proper UI and make it into a full project for generating SDL2 game controller configurations. I bet the SDL folks would find that useful, although maybe check that nothing similar already exists.

**Comment by jmtd** [comment]
It already does: it's called tests/gencontroller (or similar) in the sdl2 sources

**Comment by jmtd** [comment]
controllermap even
