### ISSUE TITLE
PNG screenshots broken on OS X; 32 bit true colour on other platforms

### ISSUE THREAD

**Issue by jmtd** [chocolate-doom/chocolate-doom#752]
@linguica reported that with the sdl2-branch, screenshots are coming out at 32bit (so >100KB each). I've confirmed this (and double checked that on OSX  at least they're correctly 8bit). I'm attempting a revert of the SDL2_Image commit to see if the older libpng code suffers this problem,but haven't coerced MSVC to link libpng12 properly yet.

**Comment by jmtd** [comment]
The SDL2_image dependency also brings with it a lot of DLLs for Windows as dependencies that we don't use but are (I believe) necessary (jpeg, tiff, smpeg, smpeg2)

**Comment by fabiangreffrath** [comment]
Am Donnerstag, den 14.07.2016, 12:08 -0700 schrieb Jonathan Dowland:
> The SDL2_image dependency also brings with it a lot of DLLs for
> Windows as dependencies that we don't use but are (I believe)
> necessary (jpeg, tiff, smpeg, smpeg2)

Please do check this. I know that e.g. SDL_Mixer is able to dynamically
link to its backends at runtime via dlopen(), so none of them is a hard
dependency for packages depending on SDL_Mixer (except for libmad, but
I believe the cause for this is license-related).

So, I am pretty confident that SDL_Image behaves in a similar matter
and merely uses the additional libraries if they are available instead
of pulling them on the system.

 - Fabian

**Comment by jmtd** [comment]
You're right, I deleted libjpeg and all was well.

**Comment by jmtd** [comment]
Hmm, SDL_image2 forcibly converts the input surface to 32bit on write-out according to https://hg.libsdl.org/SDL_image/file/4088a517f9a5/IMG_png.c (last routine in the file)

**Comment by jmtd** [comment]
...and I hadn't noticed but on OSX I'm getting 8 bit PNGs output that are all corrupted (basically they're empty)

**Comment by jmtd** [comment]
I might see if we can get these reported/fixed in SDL2_Image but in the meantime I would sadly suggest we go back to libpng until the fixes are available.
