### ISSUE TITLE
SDL2: chocolate-setup doesn't support binding the PrintScreen key

### ISSUE THREAD

**Issue by chungy** [chocolate-doom/chocolate-doom#765]
Trying to bind the PrintScreen key just doesn't work, my GNOME desktop eats up the combination for its own screenshot function. In the SDL1.2 version, I've used the key for binding to the screenshot function in-game.

There is a `SDL2-TODO` in src/setup/txt_keyinput.c before an SDL1.2 function that seemed to achieve to desirable behavior. The SDL documentation shows that [SDL_HINT_GRAB_KEYBOARD](https://wiki.libsdl.org/SDL_HINT_GRAB_KEYBOARD), used in the manner of `SDL_SetHint(SDL_HINT_GRAB_KEYBOARD, "1")`, might work, but this didn't have an effect for me.

**Comment by chungy** [comment]
Amendment: the game doesn't support the bind either.

**Comment by fragglet** [comment]
I think it's specifically supposed to be possible to bind PrintScreen so you can use it for screenshots. So we should fix that if it's broken.

**Comment by jmtd** [comment]
I recently re-tested 1.2 under X and Wayland: SDL 1.2 under X on Linux can bind the print screen key, but SDL 1.2 under Wayland, or SDL2 under X *or* Wayland, cannot.

So the working case is almost an edge-case!

**Comment by jmtd** [comment]
If the key is unbound in GNOME Shell, setup can bind it and it functions fine. If it is bound in GNOME, then GNOME eats it.

**Comment by jmtd** [comment]
@chungy: I think we would need to both set that SDL hint *and* add some stuff to the textscreen API to toggle `SDL_SetWindowGrab` on the relevant SDL window (which, as far as I can see, is not exposed to `src/setup/txt_keyinput.c`)

**Comment by jmtd** [comment]
...and it still might not work.

**Comment by jmtd** [comment]
OK - adding that hint, and setting the grabs appropriately, means that the setup program lets you bind the print screen key again, and also, in game, the bind works. But only if the mouse is grabbed: so it works during play, but not in a menu. I'll push my WIP code somewhere, but I'm in two minds whether this is an improvement, or whether we just don't support binding those kinds of keys.

**Comment by jmtd** [comment]
I'm going to close this as "unfixable" for now. I think it's an SDL2 limitation, and the work-around (grab keyboard as well as mouse) breaks alt-tab etc., which is not acceptable.
