### ISSUE TITLE
HEX support (dehacked equivalent for Hexen)

### ISSUE THREAD

**Issue by jmtd** [chocolate-doom/chocolate-doom#766]
There was never a Dehacked for hexen, but there was a 3rd party project called HEX

http://ia800801.us.archive.org/isoview.php?iso=/32/items/3dGameAlchemy/3dgamealchemy.iso&file=UTILS%2FEXE_EDIT%2FHEX%2FREADME.TXT

Not yet on idgames (I'll fix that)

And I've no idea how much functionality actually worked

**Comment by jmtd** [comment]
Nothing to support here; HEX didn't have any patch files, it only supported directly editing an EXE.

**Comment by fragglet** [comment]
Yep, looked at this before myself and concluded it was infeasible.
