### ISSUE TITLE
SDL2: Crash when attempting to dynamically switch windowed/fullscreen

### ISSUE THREAD

**Issue by CapnClever** [chocolate-doom/chocolate-doom#774]
I swear it worked the very first time I ran Doom 2 (as it started in fullscreen and I wanted to switch to windowed), but every time since then it crashes after resizing the screen (via Alt-Enter) but before anything new is rendered. I tried deleting the config files, in case that was somehow related, but no improvement. Unsure if related, but it does occasionally take a couple seconds for some screens (e.g., exit window) to properly render, and appear all-white until then.

I couldn't find a Windows build of the latest sdl2-branch so I built it myself using MSVC: if there happens to be a known, working Windows build for the branch, I'll try that as well. Under debugging, it crashes with the following stack trace (don't have SDL2 symbols loaded so it only goes to the function call `SDL_RenderClear()`):
```
chocolate-doom-dbg.exe!I_FinishUpdate() Line 686
chocolate-doom-dbg.exe!D_Display() Line 307
chocolate-doom-dbg.exe!D_DoomLoop() Line 479
chocolate-doom-dbg.exe!D_DoomMain() Line 1911
```
Using Win7 64-bit, NVIDIA GeForce GTX 650 Ti (since it's graphics-related). Library versions included were SDL2-2.0.4, SDL2_mixer-2.0.1, and SDL2_net-2.0.1.

**Comment by jmtd** [comment]
Just to be clear, was that the current-latest commit to the sdl2-branch you tried, i.e. 93e591e18a0091c038d722d6e2081af7f701bc6d ?

> I couldn't find a Windows build of the latest sdl2-branch so I built it myself using MSVC

There isn't an official one but I did one a few months ago here: https://jmtd.net/tmp/chocolate-doom-sdl2-branch-win32-dbg.zip which is from https://github.com/chocolate-doom/chocolate-doom/commit/b0ad1460fa9d7e747a7722962e9a56668e2e12d7

It might be worth a try but I think it should behave the same as current HEAD.

**Comment by fabiangreffrath** [comment]
Am Mittwoch, den 14.09.2016, 05:50 -0700 schrieb Jonathan Dowland:
> Just to be clear, was that the current-latest commit to the sdl2-
> branch you tried, i.e. 93e591e ?

I cannot confirm this on Linux, although the window content looks a bit
weird for a split-second when returning from full screen.

 - Fabian

**Comment by CapnClever** [comment]
Looks like it's a problem with the library I was using rather than Chocolate Doom itself. @jmtd's build worked once I installed VS2015, and using the libraries from that package also fixes the issue with my own build. (On a related note, trying to gather together all the necessary libraries to build Chocolate Doom is a pain with VS2015: see #636 regarding SDL/SDL2).

Closing.
