### ISSUE TITLE
Stuck moving forward on RMB (as first mouse action)

### ISSUE THREAD

**Issue by CapnClever** [chocolate-doom/chocolate-doom#782]
Tested on 2.2.1 release, Win7:

1. Check that "move forward" in Chocolate Doom's mouse configuration is not bound to RMB. (For the sake of the test, ensure it's bound to another button.)
2. Start up Doom2, new game
3. Click RMB before doing anything else with the mouse (keyboard inputs are okay)
4. Player will begin moving forward and continue to do so
5. Click button assigned to "move forward"
6. Player will stop moving forward

I also tested on the sdl2-branch and didn't see this issue, so it can likely be closed out once 3.0 hits.

**Comment by chungy** [comment]
I cannot reproduce this. Can you upload your chocolate-doom.cfg? (https://gist.github.com should work for this purpose)

**Comment by CapnClever** [comment]
[`chocolate-doom.cfg`](https://gist.github.com/CapnClever/500ccd36349c226e26715feb7e0a7ae3)
If you need `default.cfg` as well I'll edit this to contain it.

**Comment by chungy** [comment]
I forgot about that file actually. Please do include it :)

**Comment by chungy** [comment]
Still cannot reproduce, even on Windows 7... i had to edit the cfg to remove `video_driver "directx"`, which results in no display on my W7 install (yay for another reason SDL2 will be good...), but I don't believe that's making the difference. :/

**Comment by haleyjd** [comment]
Confirmed to be an issue with the SDL 1.2 directx video driver; not a Choco specific issue and should be repaired by SDL2 migration.
