### ISSUE TITLE
Setup: crash testing mouse when "Acceleration Threshold" is zero

### ISSUE THREAD

**Issue by CapnClever** [chocolate-doom/chocolate-doom#791]
Cause is this line in `v_video.c`:
```
// Calculate line length

linelen = (original_speed * redline_x) / mouse_threshold;
```
Not sure if we should disallow zero threshold or if the thermometer should act differently.

**Comment by AXDOOMER** [comment]
There is a division by 0. In the case ```mouse_threshold``` is 0, there should be a default result.
