### ISSUE TITLE
Support `-save` / `-savedir`

### ISSUE THREAD

**Issue by Kroc** [chocolate-doom/chocolate-doom#792]
I am creating a self-contained portable DOOM launcher presented in the style of a '90s disk-zine; PortaDOOM: https://gitlab.com/dosmag/PortaDOOM

![portadoom](https://cloud.githubusercontent.com/assets/142650/19909164/adb3ed60-a086-11e6-98be-d4788b18394e.png)

PortaDOOM utilizes a batch script doom.bat to normalise behaviour between engines and to spearate engines and user-data like savegames: https://gitlab.com/dosmag/PortaDOOM/blob/master/PortaDOOM/files/doom.bat

![doom bat](https://cloud.githubusercontent.com/assets/142650/19909362/a17aebc4-a087-11e6-9c7c-c14728f05745.png)

Chocolate-doom is the only engine that does not support `-save` (prboom+) or `-savedir` (zdoom) to relocate where savegames are written. This makes it very difficult to normalise the behaviour of chocolate-doom/heretic/hexen/... and separate the savegames from the executable.

If you have to choose one or the other, go with `-save` as this descends from boom and I suppose that's closer to vanilla (both prboom+ and chocolate-doom use ".dsg" savegames rather than zdoom-saves ".zds")

I hope that you consider this addition worthwhile as it would help greatly with the accessibility of DOOM to new players through PortaDOOM.

**Comment by AXDOOMER** [comment]
`-save` and `-savedir` are not supported by vanilla Doom.

**Comment by Kroc** [comment]
Vanilla DOOM wasn't designed for Windows, let alone x64 either *shrug*. Adding a save parameter isn't going to break vanilla gameplay but it is going to help with portability.

**Comment by AXDOOMER** [comment]
Chocolate-Doom is meant to "emulate" vanilla Doom  (make it work without an emulator on every different platform, such as ARM) and I don't see a portability reason that would require these command line parameters to be added. Chocolate-Doom's savegame system works as close as possible to vanilla Doom. On Windows systems, it behaves as vanilla did in DOS and in other OSes like Linux, it already has a savegame system that organizes the files in suitable directories. Adding new command line parameters from other ports would mean that every other similar request would be welcomed, thus bloating Chocolate-Doom with features.  

>  it is going to help with portability.

How does it help with portability? Chocolate-Doom's savegame system is already portable, it works on everything. Yours seems to organize savegames PWAD, but that's not a vanilla supported feature. Your program is written in batch which is only supported on Windows. Please explain your point. Please feel free to correct me if I'm wrong.

**Comment by CapnClever** [comment]
> -save and -savedir are not supported by vanilla Doom.

I could name a lot of parameters that aren't supported by vanilla but are used by Chocolate Doom: as a means to emulate vanilla (e.g., `-setmem`), to support vanilla-like hacks (e.g., `-longtics`), or just to assist the scoped improvements Chocolate takes in (e.g., `-extraconfig`). I wouldn't outright declare an option invalid just because it's not vanilla.

I did a quick check of the original Boom port and found this:
```
-save <dirname>
If <dirname> exists, and is a directory, it becomes the path where save
games are stored, and loaded from. If -save is not specified or the
directory does not exist, then the current directory is used.  The
parameter -cdrom overrides -save. The -save option is new to BOOM, it was
not available in DOOM.
```
so at least there's some precedent with respect to an older port.

Conceptually, I like the idea. Currently when I play through Chocolate Doom I have to worry about overwriting games from a previous megawad, or accidentally loading a game from an incompatible wad and crashing. My current solution is to copy around savegames myself, but `-save` would certainly simplify that process. It doesn't exactly break anything in-engine either, as pointing to a save directory would amount to the same thing (and is already done on non-Windows OSes).

I can't really comment on scope, but a lot of the code is already there to make this work: Hexen would need to be made aware of the `savegamedir` variable but the rest of the games already know how to load and save from a directory other than the current one. The way I see it, this would amount to nothing more than exposing functionality that's already in Chocolate Doom.

**Comment by Kroc** [comment]
OK, so maybe I don't explain myself well. I'll see if I can articulate this better;

I actually don't know the full details of where chocolate-doom puts saves games, but I observe it writing them to the 'current directory' which, when running the executable directly, is of course that of the executable. If we use a shortcut or batch script to launch it, then the 'current directory' will be that of the batch script, or basically anywhere if we change it there in. All ports have this behaviour, and it's the basis of doom.bat's functionality to split off user-data (configs and savegames) from the engines -- (there is a slight flaw with how chocolate-doom does it however, which I will get to soon).

We want to do this in the first place because the ports included with PortaDOOM could be replaced, moved and upgraded as time goes by and we therefore want to avoid placing user-data in the executable directory. This would prevent the use of an auto-updater or the like.

In addition, given the infinite combination of IWADs/PWADs it is not helpful to place *all* savegames across all PWADs in the same folder! This would just be confusion and render autosaves (in other engines) useless. doom.bat uses a separate save folder first for each port, and then for the IWAD or PWAD in question. Ergo, each PWAD is treated as its own self-contained "game". Config files for zdoom, for example, would be saved to "`saves/zdoom`" and the savegames for breach.wad in "`saves/zdoom/breach`".

All ports spit out their default config files into the 'current directory'. doom.bat sets the current directory to the port's personal save folder (e.g. "`saves/zdoom`") and then uses `-savedir` to put savegames into the folder for the particular IWAD/PWAD.

This is where things go wrong for chocolate-doom. Since we can change the 'current directory' but not separate to the save directory we have only two evils to choose from:

1. Every IWAD/PWAD has its own separate chocolate-doom configuration!
2. Every IWAD/PWAD shares the same saves list!

There is, in all likelihood, some kind of chocolate-doom specific workaround using parameters and the current-directory, but I would like to not have to special-case this port otherwise I may just abandon the use of it in PortaDOOM.

Regards 'portability' though, this is a multi-faceted issue.

In my opinion it is not good practice to store user-data within the executable's directory. This is bad for source control, bad for multi-user envirnonments and is, in effect, a dying practice as more operating systems move to app-directories and binary signatures / verification. I assume that you do not save files into the .app bundle on OS X?

Now, if the answer to that is 'no it goes into the user's $HOME directory' then there still remains an issue; what of portability in the sense of running software from USB and not leaving user-data (or anything, really) on the host machine? And what if the external device is read-only? Then we really do need `-save` to put the files somewhere where they can go. I even have an external drive with read-only and write-able partitions.

Regards vanilla and feature-creep, I can begin with the things that I am not asking of you, nor would ever for this port:
* This proposal presents no user-visible change in the actual playing of chocolate-doom
* This proposal requires no menu alterations and no additional graphics
* This proposal alters no aspect of gameplay
* This proposal breaks no historical script, WAD or any other vanilla-related assumption or behaviour, it is safely opt-in, forwards-only

I hope that clears things up.
Kind regards,

Kroc Camen.

**Comment by AXDOOMER** [comment]
> I could name a lot of parameters that aren't supported by vanilla but are used by Chocolate Doom

They are there for a better emulation. That's a valid reason to add  parameters that aren't supported by vanilla. 

>  . Currently when I play through Chocolate Doom I have to worry about overwriting games from a previous megawad, or accidentally loading a game from an incompatible wad and crashing. My current solution is to copy around savegames myself

That's what I do too, but I don't play lots of PWADs at the same time. When I do, it's not a problem because I use only one savegame file at the time. I don't keep my savegame files when I'm done playing a PWAD. 

> Hexen would need to be made aware of the savegamedir variable but the rest of the games already know how to load and save from a directory other than the current one.

Also, Doom has a command line (-cd) parameter that changes the savegame directory to a fixed location if it runs on a CD-ROM. 

By adding a command line to change the savegame directory, I guess someone will ask for another one to change the config directory. It doesn't bloat Chocolate-Doom too much and even though it makes it easier for some people to play Chocolate-Doom with lots of different PWADs at the same time, in my head it's out of scope. If it wasn't possible to do it in anyway possible with vanilla, then it shouldn't be possible with Chocolate-Doom.

I would write an external tool that would move my savegames back and forth from my custom PWAD directories if I wanted this. I wouldn't modify Chocolate-Doom to do this. It is completely doable in this batch script without modifying Chocolate-Doom and it would be simple. You just have to get them in the savegame directory of the current PWAD and move them into the main directory where Chocolate-Doom is (only temporarily), then when Chocolate-Doom exists, you would move them back to the PWAD's savegame directory. By doing what I just described, @Kroc would make his tool vanilla-compatible as it would work with the original Doom executable and everyone would be happy. No out of scope change required for Chocolate-Doom.

**Comment by Kroc** [comment]
PortaDOOM / doom.bat launches Chocolate-doom without waiting for it to exit (`START ...`), this is by design. It leaves less console windows cluttering the screen and also prevents PortaDOOM from locking up completely as it sits and waits for the console to return. The user may also want to alt-tab between the game and PortaDOOM, as PortaDOOM will contain reference information too (such as secret lists) and that isn't possible if it has to wait to clean up after chocolate-doom.

The entire purpose of PortaDOOM is to make DOOM more accessible. Literally a single executable to open that has tons of WADs to choose from for which the correct engine, correct settings and all that will be automatically handled for them. Playing even a moderate number of WADs in DOOM right now is a chore even for the experienced, let alone someone who is somehow expected to know the arcane ways of juggling IWADs & PWADs. So, if I make a large selection of DOOM WADs easy to browse, should they deal with having a hundred different save games all combined in one list? That's rather a rediculous situation to defend in the name of 'vanilla'. The MS-DOS exe was single user, made for a single game, not hundreds of WADs, otherwise ID would have come up with something better.

> I guess someone will ask for another one to change the config directory

That is its own discussion and shouldn't be used as something with which to beat other requests over the head with! :/ Examine the merits of what I am requesting, not what others may or may not do according to their own predilictions!

**Comment by chungy** [comment]
This sounds like a useful feature to have. (FWIW, you can *already* set the config directory with command line parameters :P)

**Comment by AXDOOMER** [comment]
> config directory with command line parameters

-config and -extraconfig I believe.

**Comment by fabiangreffrath** [comment]
Alexandre-Xavier Labonté-Lamoureux wrote:
> -config and -extraconfig I believe.

These set config *files*, not directories.

That being said, I think the requested feature is a useful addition, as it
enabled people to play Choco from read-only USB-Sticks or similar setups.
Also, it defaults to Vanilla behaviour, so people not using it will
probably not even be ware of its introduction.

 - Fabian

**Comment by jmtd** [comment]
> These set config *files*, not directories.

I wonder if we could have one solution for both use-cases, by having `-configdir` or similar, and deprecating `-config`.

**Comment by CapnClever** [comment]
I'm working on a simple implementation of this feature. It basically looks like this in each of the `d_main` files, with minor differences where necessary:

```
    //!
    // @arg <directory>
    //
    // Specify a path from which to load and save games. If the directory
    // does not exist then it will automatically be created.
    //
    p = M_CheckParmWithArgs("-savedir", 1);
    if (p)
    {
        savegamedir = myargv[p + 1];
        if (!M_FileExists(savegamedir))
        {
            M_MakeDirectory(savegamedir);
        }

        // add separator at end just in case
        savegamedir = M_StringJoin(savegamedir, DIR_SEPARATOR_S, NULL);
        
        printf("Save directory changed to %s.\n", savegamedir);
    }
    else
    ... // original code path to determine savegamedir
```
Seems to work just fine, too. I have, however, hit two little snags:
1. Hexen has a "savedir" parameter in its original config file, which is currently set to "hexndata". Should I merely override this parameter when using `-savedir` or additionally change the config value in the process?
2. There's this incredibly odd problem in Windows passing in a command line that includes `\"`. Not only does it read the value as `"` (like an escape character) but when used singularly (e.g., `-savedir ".\savegame\" -warp 1) the argument array itself gets screwed up (e.g., `savegamedir` becomes `.\savegame" -warp 1\` using the above code, and `-warp 1` itself never executes). There are a few ways to avoid this problem from the user end, including just forward slash usage, but I can't figure out a simple way to prevent this unique case from presenting a problem once it's passed in.

**Comment by Kroc** [comment]
IMHO;
1. override. Imagine having many different shortcuts that all passed different parameters. You wouldn't want the default game to reflect the settings of the last WAD you played because these should be considered separate, different "games".

2. Do nothing. The problem is part of Windows and anybody scripting has to learn to watch out for this for any and all programs they may call. If chocolate-doom behaves differently then you just teach the user a bad habit that will bite them the very next program they assume works like that.

**Comment by fragglet** [comment]
Now implemented - thanks @CapnClever !

**Comment by Kroc** [comment]
Did this make it into 2.3.0? I didn't see it mentioned in the release notes.

**Comment by chungy** [comment]
No, it was merged post-release.

I could include it in the (currently non-existent) chocolate-doom-2.3 stable branch for inclusion with a future 2.3.1 point release. I'd only shy from it because it's not a pure bug-fix change.

**Comment by Kroc** [comment]
How you release your software is up to you, it may be a little-used feature and not get noticed. OTOH I have had to work around the lack of savedir support as doom64ex lacks it too, so the presence of this in chocolate-doom is helpful, but no longer critical.

**Comment by fragglet** [comment]
You're welcome to use one of the daily builds from http://latest.chocolate-doom.org/ which should now include the -savedir parameter.

**Comment by Kroc** [comment]
Thanks always for your software, for making my little distribution project possible; now if only G/ZDoom were so evangelic on backwards & forwards compatibility :P
