### ISSUE TITLE
[Suggestion] CRT monitor brightness emulation

### ISSUE THREAD

**Issue by JNechaevsky** [chocolate-doom/chocolate-doom#793]
Jonathan pointed me on IRC to start this topic, so here it is.

**Situation:** 
On modern LCD displays, and especially on cheap ones, ingame palette may looks too overbright. Ofcurse, this is neither Vanilla bug, nor Chocolate, but idea of making game color looks not better, but more similar to CRT days may be interesting. 

I've spent some time on googling information about this, and found an only one simple solution. A wad file with remapped `PLAYPAL` lump ([idgames link](https://www.doomworld.com/idgames/graphics/pal_plus)) which makes game a bit darker. But for me, it looks bad. It replaces some original colors and makes the game too contrast. So I've decided to make my own `PLAYPAL` hack, and here's what I got:

http://i.imgur.com/FSVA0if.png
http://i.imgur.com/Nqo0e3T.png
http://i.imgur.com/eRnG63u.png
http://i.imgur.com/JwX58KF.png

A wad-file can be downloaded from [Google Drive](https://drive.google.com/file/d/0BwUBKvr8Ksp3aGdhRE93NFN1WGs/view?usp=sharing) (10 Kb.).

**Solution:**
Please, don't get me wrong - I don't want to say that my version of brightness/contrast is optimal, neither I don't want to mean placing additional or modified `PLAYPAL` in Chocolate Doom. Nope. 

But it might be a good idea to implent some kind of command line argument like `-crtcolor` of `-crtbrightness` which will use darkener or more contrast colors by default, not from any modified `PLAYPAL`/wad file ofcurse, but from hacked original palette by similar method like gamma-correction does in "backwards".

Unfortunately, I have no ready-made solution.

I understand that any non-vanilla command line arguments is not very right way to do, but again, making ingame colors looks like good old CRT monitors in Chocolate Doom "from the box", not from 3rd side wad file, may be interesting, since it may be acceptable by port's philosophy.

**Comment by fragglet** [comment]
There's a whole area we haven't explored for the project in terms of CRT emulation (I'm not sure it's something we *should* do, but it's something that's maybe worth discussing). 

The referenced WAD talks about wanting to "make Doom look better [on LCD monitors]". That's great as a goal for a mod, but for Chocolate Doom any similar feature should probably have some kind of experimental backing (ie. evidence) to show that it really does make the game look more like it did on CRT monitors.

**Comment by AXDOOMER** [comment]
If the screen looks darker on LCD displays, isn't it because of scanlines?

**Comment by JNechaevsky** [comment]
@AXDOOMER, in my case, Vanilla/Chocolate screen looks much brighter on LCD, not darker. However, making it darker through recoloring PLAYPAL have nothing about scanlines, this is just darker and a bit more contrast colors of game palette.

**Comment by linguica** [comment]
I own a colorimeter and one of my side projects has long been to profile an actual CRT monitor to create a custom PLAYPAL that emulates it as closely as possible on an LCD screen, but first I need to get my hands on a CRT monitor, obviously.

**Comment by AXDOOMER** [comment]
> @AXDOOMER, in my case, Vanilla/Chocolate screen looks much brighter on LCD, not darker. 

Sorry, I corrected myself. I meant CRT displays, there are no scanlines on LCD displays.

**Comment by chungy** [comment]
We should also mind that no monitor is created equal. You won't really emulate all CRTs in general, nor will the emulation even look identical on all LCDs...

I think, generally, this is another good case where shader support would be helpful. With shaders, you can emulate all kinds of fuzzy and color effects.

**Comment by JNechaevsky** [comment]
Thanks for clarification. Not actually sure about scanlines in CRT, but this can be reason too.
In my opinion, LCDs problem is in three reasons:
1. Overpowered and unbalanced LED backlight, which makes colors overbright. 
2. Quality of the matrix. Well, this is not exactly a problem, but plays it's role.
3. Quality of screen glass. If it is too reflective, it collects a lot of lights, making the colors washed-out.

**Comment by sneakernets** [comment]
I wrote a thing about this some time ago in issues; the reasoning is that the Stella team (in MAME) have a CRT "emulator" in the works. It's needed for programmers to quickly test sprite flicker routines. iirc, it will be GPL and tuned for SDL2, so we should have no problems implementing it when it's "done".

**Comment by fragglet** [comment]
@sneakernets - interesting, thanks. If other teams are working on this already then we should definitely look into it. This seems like a complicated problem to solve and to some extent beyond the project's main scope.

**Comment by AXDOOMER** [comment]
> there has been an effort on Vogons forums to make a universal CRT monitor shader. From what I've seen, it's pretty impressive.

Their filter even emulates the curve of CRT monitors. Some of their filters look more like a TV screen emulation rather than a computer monitor emulation though.

**Comment by jmtd** [comment]
I still have a CRT, but it's ancient and the (analog) input is not a D-SUB, so I've no idea how to drive it from a PC: http://img15.hostingpics.net/pics/778819693310592o.jpg

But that got me thinking, what inputs did CRTs have? all my PC ones had VGA D-SUBs. Did anyone in the early-to-mid nineties use one with a composite or component input? Because the results would be very different.

It turns out some late 90s monitors had digital interconnects with built-in DACs, but I imagine the result was probably not much different to VGA/D-SUB. https://www.reddit.com/r/GloriousCRTMasterRace/comments/3kgszv/crt_monitors_with_dvi_port_dont_upvote/

**Comment by AXDOOMER** [comment]
I see a CGA port (DE-9). I guess you can use a D9 male to HD15 female cable or converter. 
![cga-d-sub-9-pin-to-hd15-pin-vga-adapter](https://cloud.githubusercontent.com/assets/6194072/19992268/f0d7a55e-a212-11e6-8cc8-2e6a86de1d41.jpg)
![a159fm](https://cloud.githubusercontent.com/assets/6194072/19992277/fb4f2ae8-a212-11e6-8a86-08addec268e3.jpg)

**Comment by jmtd** [comment]
> I see a CGA port (DE-9). I guess you can use a D9 male to HD15 female cable or converter. Why don't you want to use the D-sub?

Sorry if I wasn't clear enough. My monitor doesn't have a D-SUB input, it has component or CGA (I guess) only.

**Comment by JNechaevsky** [comment]
The idea of using shaders sounds good (IMO, only if it will optional and will not cost too much for hardware), but if it will be rejected, here's an abstract idea for gamma-correction trick. I'll try to explain...

Changing current values of gamma-correction and messing with PLAYPALs in source code is obviously forbidden. It is okay. I'm not 100% sure how gamma-correction works in code, but belive it's something like:

- G-C Off: no changes to palette.r,g,b
- GC- level 1: palette.r,g,b values + 15
- GC- level 2: palette.r,g,b values + 25 ... and so on.
(I may be completely wrong with digits, but that's not the point)

By adding command line parameter like "-darken", these gamma settings will have a bit different reverse way:

- G-C Off: palette.r,g,b values - 10
- GC- level 1: palette.r,g,b values - 20 ... and so on.

But ofcurse, it must not change any Gamma-Corretion messages, only technical palette stuff in enginge itself. I.e, all gamma settings in config files should remain same with or without "-darken".

**Comment by AXDOOMER** [comment]
> -darken

If we want to implement shaders, better not go with a command line parameter for each of them, because I'm sure there will be a lot of shader requests and there will be a lot of them.

**Comment by jmtd** [comment]
> If we want to implement shaders, better not go with a command line parameter for each of them, because I'm sure there will be a lot of shader requests and there will be a lot of them.

Shaders are just a tool to achieve something. if CRT emulation is deemed chocolatey, then implementing that with shaders might make sense. If a user wants to turn on CRT emulation, why not a command line parameter? How else? What other shader-based features do you think the project is likely to accept?

**Comment by AXDOOMER** [comment]
> If a user wants to turn on CRT emulation, why not a command line parameter?

Maybe one command line parameter for shaders, but not for each of them. There are a thousand of different ways to emulate a CRT.

**Comment by chungy** [comment]
I think the sensible way is to have a command-line parameter to specify a shader file. It would make it easy to develop and implement shaders externally of the Chocolate Doom project itself.

Maybe a select few, such as CRT simulation, could be included.

**Comment by AXDOOMER** [comment]
^ I second that

**Comment by jmtd** [comment]
> I think the sensible way is to have a command-line parameter to specify a shader file. It would make it easy to develop and implement shaders externally of the Chocolate Doom project itself.

I dunno. I think the use of a shader here is really an implementation detail. I don't think the user should have to know what a shader is, nor source a shader from somewhere else. I would imagine we would develop and include a shader that did the CRT emulation that we agreed on, but permit an expert user to override it with one of their own if they wanted; perhaps as an undocumented feature?

**Comment by AXDOOMER** [comment]
>  include a shader that did the CRT emulation that we agreed on

There are tons of different ways to emulate a CRT monitor with shaders and there is a variety of CRT monitors. I consider `-scanline` to be already one, but it wouldn't be faithful to a real CRT on other resolutions than 1600x1200 for which it is designed.  I don't know if we could all agree on what should be included with Chocolate-Doom. If we created a pack of shaders that people could download independently from Chocolate-Doom, I think it would be great.

**Comment by JNechaevsky** [comment]
Perhaps, better place for shaders options is setup.exe, as pop-up listing in Display options > Advanced?

This placing looks harmless, and must not break any vanilla look. Also might be a good solution in case user is not interested in reading README/CHANGELOG/CMDLINE files, and may simply don't know about this new command line parameter.

**Comment by AXDOOMER** [comment]
In my opinion, it should be an hidden feature.

**Comment by chungy** [comment]
The advanced options menu doesn't sound like a bad place. It is called "advanced" after all.

**Comment by AXDOOMER** [comment]
There was a shader feature request right there: https://github.com/chocolate-doom/chocolate-doom/issues/628 ("Phosphor afterimage effect")

**Comment by jmtd** [comment]
Thanks, I'll close this one as a duplicate.
