### ISSUE TITLE
Choco doesn't handle file I/O errors when reading or writing savegames

### ISSUE THREAD

**Issue by fabiangreffrath** [chocolate-doom/chocolate-doom#794]
Chocolate Doom (I haven't checked the other games) currently doesn't properly handle file I/O errors when reading or writing savegames. Thus, it is perfectly possible to read a savegame beyond the end of the file and thus crash or even freeze the game.

For example, try to load doomsav6.dsg from this archive when batman_fixed.wad is loaded as PWAD:
https://github.com/fabiangreffrath/crispy-doom/files/568412/Batman.5.D2.6.zip

Actually, there is already a `boolean savegame_error` variable in Choco that is set to `true` if either `fread()` or `fwrite()` fail, but this variable is never processed any further (apart from resetting it back to `false`).

**Comment by CapnClever** [comment]
This might be related to #658 (see also #85). In a debug version of the current master branch I actually get `Unknown tclass 204 in savegame` so it's almost certainly happening around that area.

**Comment by fabiangreffrath** [comment]
So, it seems that `fread()` doesn't read beyond the end of the file, which is a good thing. However, the `result` variable does not get initialized in `saveg_read8()`, so if `fread()` fails to read a single byte, `result` still contains some random value from the stack which is then returned.

Yes, this is a duplicate of both #658 and #85. However, in contrast to what is being reported in the former issues, `saveg_read8()` does not *always* return `0`, though it does most of the time. It could be fixed by initializing the `result` variable in `saveg_read8()` to some improbable value, e.g. `-1`.
