### ISSUE TITLE
SDL2: Mouse not regrabbed after cursor leaves window

### ISSUE THREAD

**Issue by CapnClever** [chocolate-doom/chocolate-doom#798]
This is on a Win7 64-bit computer, testing via sdl2-branch commit 31285f01f292ca3b70851e5551e97f2d483924f4.

In Chocolate Doom 2.2.1, you can activate the menu during a level, move the mouse away from the window (without changing window focus), then deactivate the menu, at which point the mouse is automatically grabbed. Using the SDL2 version, the mouse cursor stays where it is after deactivating the menu and won't grab until it's manually moved into the window. This occurs whenever the cursor is available, including intermission screens.

**Comment by fragglet** [comment]
I think it's because we no longer do mouse warping as part of reading movement like we used to.

**Comment by fragglet** [comment]
Fixed!
