### ISSUE TITLE
Wiimote: Crash when mapping buttons in Chocolate-Setup

### ISSUE THREAD

**Issue by AXDOOMER** [chocolate-doom/chocolate-doom#799]
I installed bluez and xwiimote on Ubuntu so I could connect my wiimote using blueman. I can setup the axes (d-pad) in Chocolate-Setup, but when I try to map a button (example: I want to set B to 'fire'), Chocolate-Setup will crash with the following message being printed into the terminal:

```
*** stack smashing detected ***: src/chocolate-setup terminated
Aborted (core dumped)
```

Also, when I'm mapping the d-pad buttons on the axes, I need to press A + B (A first then B at the same time) to confirm. Is that normal?

I can run Chocolate-Doom and play with the default layout without getting any crashes. 

I'm running the latest version.

**Comment by jmtd** [comment]
Thanks for the report. Which version of chocolate-doom were you attempting? If you built from source, what git commit did you build from? Thanks!

**Comment by haleyjd** [comment]
This code is wrong:

https://github.com/chocolate-doom/chocolate-doom/blob/master/src/setup/txt_joybinput.c#L101

all_joystick_buttons is not the same length as new_mapping; someone has added a new joystick button to all_joystick_buttons which is not accounted for in NUM_VIRTUAL_BUTTONS, so it can write one past the end of new_mapping and corrupt the stack.

**Comment by AXDOOMER** [comment]
> Which version

The latest git commit, from November 1st.

**Comment by AXDOOMER** [comment]
I fixed the crash. How I did:
1- Increased NUM_VIRTUAL_BUTTONS to 11. 
2- Went in src/setup/txt_joybinput.c and increased JOYSTICK_INPUT_WIDTH to 11. 
3- Went in src/m_config.c and added a new button: `"CONFIG_VARIABLE_INT(joystick_physical_button10),"` after `"CONFIG_VARIABLE_INT(joystick_physical_button9),"`.

When I run the game, A, B and the d-pad don't work. Other buttons (1, 2, +, - and Home) work. What could be wrong?

**Comment by jmtd** [comment]
> The latest git commit, from November 1st.

Thanks.  The reason I ask is if the bug stays open for a long time it's hard to know what environment/commit/branch etc were relevant at the time, looking back. So this must have been 48e19c69bf470517353101a445b8d824d1b3f7bb (on master).

**Comment by haleyjd** [comment]
The error I found is on the master HEAD revision.
