### ISSUE TITLE
Mouse ball emulation 

### ISSUE THREAD

**Issue by jmtd** [chocolate-doom/chocolate-doom#801]
Most modern mice and mice-like devices are trackpads or optical, whereas nearly all mice in the 90s were physical balls rotating in a cradle.

After a few long deathmatch sessions the ball and/or rollers would usually gunk up with stuff from the desk. It became a ritual to clean the rollers. Sometimes you'd temporarily misplace the ball whilst you did it.

We should emulate this experience, perhaps by steadily reducing the mouse sensitivity during extended play, or varying it by random amounts. We should also add a "clean mouse" binding that temporarily reset this effect, and possibly wiggled the player left and right by issuing sharp random turn events for a few seconds.

**Comment by fragglet** [comment]
Should have saved it for April 1st :)

**Comment by jmtd** [comment]
I couldn't wait!

**Comment by sneakernets** [comment]
hahaha I love this so much. This would be a good joke feature for an april fools version.
