### ISSUE TITLE
When playing comp-dm.wad (the one with fixes by Fraggle), the pistol-wielding bot appears to have 100 hp instead of 300 hp mentioned in orig-dm.txt

### ISSUE THREAD

**Issue by Zodomaniac** [chocolate-doom/chocolate-doom#808]
I launch it with command line chocolate-doom.exe -file (or -merge) comp-dm.wad -deh comp-dm.deh
 -respawn -altdeath (or -deathmatch) -warp 3 -solo-net
Is there something wrong with DEH parsing or something like that, if the pistol marine appears to have 100 hp instead of 300 hp mentioned in orig-dm.txt?
Here's the zip with the files and the launching shortcut.
[comp-dm.zip](https://github.com/chocolate-doom/chocolate-doom/files/592748/comp-dm.zip)

**Comment by CapnClever** [comment]
The original readme (orig-doc.txt in the given zip) suggests six enemies of varying HP values: pistol with 300, shotgun with 300, chaingun with 200, rocket with 200, plasma with 150, and BFG with 100. I opened up the DEH file in a text editor and the notable HP edits include 3 entries with 400, 2 with 100, a 300, and a 75 (presumably anything with unchanged values aren't used as they'd require different death sounds, pain sounds, etc). It's possible that a number of values are off, though it's also possible the original hacked EXE wasn't accurate: without access to the latter it'd only be speculation from me.

Having played it a little bit, it's clear that the HP values aren't quite right: it took more than two close SSG shots to kill some of the enemies most of the time, which should be incredibly unlikely if no enemy is above 300. The plasma enemy was gib-able with a single rocket blast, which would also be impossible at 150HP.

This said, I'm not sure why it's a Chocolate Doom issue. Does it play differently using a DeHackEd-patched DOOM2.EXE? My guess would be no, though I can give it a quick check anyway.

**Comment by Zodomaniac** [comment]
>My guess would be no, though I can give it a quick check anyway.

I cannot give it a quick check, so please do ;)

**Comment by CapnClever** [comment]
I got the patch files working with a Final Doom executable and the pistol guy is killed consistently in a single SSG shot: definitely possible at 100HP, basically never happens at 300HP.

After some minor searching I managed to find what I think is the original COMP-DM.EXE (which is the hacking executable: you have to give it a DOOM2.EXE to work with). By itself, the modified DOOM2.EXE plays very similarly, with the pistol guy still being consistently killed by a single SSG. *However*, after applying some of the given WADs that came with COMP-DM (e.g., IMMY-DM2.WAD), I found that playing on the given deathmatch map actually had what appears to be different values for said pistol guy. Warping to a different map, however, "reverts" the original HP.

From all this, I can tell you Chocolate Doom is doing what it's supposed to be doing. As for the inconsistency itself, at worst I'd say the repackaging of COMP-DM is incomplete in a way I can't quite explain.

**Comment by jmtd** [comment]
Thanks for a thorough review!
