### ISSUE TITLE
"Doom-plus" support?

### ISSUE THREAD

**Issue by linguica** [chocolate-doom/chocolate-doom#811]
Chocolate Doom already supports "longtics" a la [Doom "1.91"](http://www.doom2.net/doom2/doomp191/). As long as it's supporting EXE hacks, I think it would be nice to also support Doom-plus aka [Doom "1.92"](https://www.doomworld.com/vb/source-ports/36097-doom2-v1-92-no-more-visplanes-and-drawsegs-overflows/). As far as I know this would be as straightforward as optionally changing a bunch of constants in the code.

This was motivated by seeing the [Lemon Doom](https://github.com/aynrandjuggalo1/lemon-doom) branch that backports Crispy Doom's limit-raising / removing features.

**Comment by fragglet** [comment]
Already been asked for many times and judged to be out of scope. See #427.
