### ISSUE TITLE
Longtics demo extensions should be forbidden in WADs

### ISSUE THREAD

**Issue by fragglet** [chocolate-doom/chocolate-doom#817]
As per my comment on #427:

https://github.com/chocolate-doom/chocolate-doom/issues/427#issuecomment-261829980

Longtics demos allow people to record and play back demo files without affecting mouse turning resolution. But these shouldn't be allowed in WAD files (PWAD or IWAD).

**Comment by AXDOOMER** [comment]
Why forbid? If you patch vanilla with the longtics hack, it will play longtics demo inside WAD files. The problem is the autodetection that Choco does.

**Comment by fragglet** [comment]
I think we're splitting hairs, but okay, sure.

I'm not anticipating anyone making WADs with longtics demos inside so it's probably simplest to just forbid them.

**Comment by AXDOOMER** [comment]
> I'm not anticipating anyone making WADs with longtics demos inside so it's probably simplest to just forbid them.

That wouldn't be vanilla behavior. 

Also, do you agree that we should crash on v1.666 demos in WAD files if `-gameversion 1.666` was not specified?

**Comment by AXDOOMER** [comment]
> I'm not anticipating anyone making WADs with longtics demos inside so it's probably simplest to just forbid them.

That wouldn't be vanilla behavior. 

Also, do you agree that we should crash on v1.666 demos in WAD files if `-gameversion 1.666` was not specified?

**Comment by CapnClever** [comment]
Okay I just didn't understand what this meant earlier, I get it now.

Well I see how the problem can manifest itself, albeit in the reverse. I tested this out myself:

* Patch DOOM2.EXE with the longtics hack
* Start the game via recording (i.e., `doom2 -record longdemo`)
* End the game in-menu
* Wait until the first demo starts up

At this point the longtic-hacked game crashes with "W_GetNumForName: demo1lt not found!". This strikes me as suspicious, as I don't recall the original longtics writeup mentioning changes to the lump names. (I didn't write up the patch myself, just grabbed it from idgames.) Either way I suppose you want to prevent this kind of problem from appearing by quitting at startup if the WAD demo lumps contain a version incompatible with the gameversion detected? Sounds fair to me.

**Comment by fragglet** [comment]
> Either way I suppose you want to prevent this kind of problem from appearing by quitting at startup if the WAD demo lumps contain a version incompatible with the gameversion detected?

Basically we should exit with an error ("demo is from a different game version") if an attempt is made to play a longtics demo from inside a WAD. Same as how vanilla would behave if you gave it a longtics demo .lmp. We should only enable support for longtics demo playback if the user has started the demo from the command line (via `-playdemo`, `-timedemo`, etc.).

**Comment by fragglet** [comment]
Recent commits now forbid extended demos inside WAD files (they'll be interpreted the same as Vanilla). I still need to update PHILOSOPHY to give some reasoning; I need to give that some thought first.

**Comment by chungy** [comment]
I believe the best reason is that if someone is composing their own PWAD (or even IWAD), complete confidence that Chocolate Doom behaves as vanilla does is desirable.

**Comment by fragglet** [comment]
Right. What needs to be added to PHILOSOPHY is some kind of rationalization for why we support longtics demos (ie. Doom v1.91) but not any other DOS exe hacks.

**Comment by fragglet** [comment]
PHILOSOPHY doc is now updated, and I've made changes to the relevant bits of code to conform to the new restrictions that it imposes. We now always print a warning when doing something which is a non-vanilla demo extension, and it can be disabled with the new argument `-strictdemos`.
