### ISSUE TITLE
Bloodworks music distored and clipping badly in OPL mode

### ISSUE THREAD

**Issue by chocolate-import** [chocolate-doom/chocolate-doom#82]
> The following bug was [originally reported](https://sourceforge.net/p/chocolate-doom/bugs/82/) on Sourceforge by [porschemonty](https://sourceforge.net/u/porschemonty/profile/), 2010-08-23 19:26:08:

You're not supposed to play this wad with vanilla Doom or vanilla ports, but music is a different story. Warp directly into map03 and let the tune play. Should be many times slower than intended and at some point you'll start hearing a real nasty clipping, so handle with care.

Happens with any sample rate including the default one. Works fine in DosBox.
I'm running [r1964](//github.com/fragglet/chocolate-doom/commit/966089e8bdc5d2cae9c1b9e889c9ca1405d6c29e) on WinXP Pro SP3 32bit.

Get the wad here: http://www.doomwadstation.com/descent/bludwrks.zip

Regards.

**Comment by jmtd** [comment]
Closing as OP seems to think it's fixed.
