### ISSUE TITLE
State that PNG screenshot support is not universal

### ISSUE THREAD

**Issue by ceyt** [chocolate-doom/chocolate-doom#821]
PNG screenshots are mentioned multiple times in changelog, release notes, and on wiki, and the only place that hints they can be unavailable is a help page for specific setup options page.

I've spent quite some time staring at .pcx files, changing configuration file options, and wondering if there's another switch for that “non-vanilla” behavior before realizing released Windows binaries come without libpng at all.

**Comment by fragglet** [comment]
This will be fixed in the 3.0 release.
