### ISSUE TITLE
Inconsistent scaling on a 1680x1050 monitor in 2.2.1

### ISSUE THREAD

**Issue by AnotherLife** [chocolate-doom/chocolate-doom#826]
[vanillaFOV.zip](https://github.com/chocolate-doom/chocolate-doom/files/625616/vanillaFOV.zip)

I was doing some tests and thought I would create a map to see the exact field of view of the player in vanilla Doom with the status bar enabled. I was using Chocolate Doom for testing this test map. But then when I loaded it in vanilla Doom 2 (in Dosbox) I saw that there is a discrepancy in the right of the field of view, it is not the same as in Choco.

**Comment by linguica** [comment]
Screenshot from Chocolate Doom using -devparm:

![choco](https://cloud.githubusercontent.com/assets/5770757/20810707/a6bd6608-b7bf-11e6-90ef-f2fa062bbe2a.png)

Screenshot from DOSBox doom2.exe using -devparm:

![dosbox](https://cloud.githubusercontent.com/assets/5770757/20810713/b0f45d5c-b7bf-11e6-8265-ce9cae5c5119.png)

It appears that these are perfectly identical.

**Comment by AnotherLife** [comment]
You get the red column in both? In Chocolate Doom 2.2.1 I don't get it.

**Comment by linguica** [comment]
My build of the SDL2 branch is pretty old, but I still see it there too.

![sdl2 choco](https://cloud.githubusercontent.com/assets/5770757/20813287/e74988f0-b7c9-11e6-9d14-7d9d1746bc7c.png)

**Comment by AnotherLife** [comment]
I do my test on stable Choco Doom 2.2.1 with default settings. No red column on the right. 1680x1050 fullscreen

**Comment by AXDOOMER** [comment]
@AnotherLife  Post a screenshot

**Comment by AnotherLife** [comment]
![001](https://cloud.githubusercontent.com/assets/7148117/20815110/44f6f752-b825-11e6-9d42-5c3a9531b7ae.png)

Wtf, in the screenshot the reb column shows. But not ingame. Some scaling problem?

**Comment by linguica** [comment]
I went and redownloaded Chocolate Doom 2.2.1 from the website and ran the WAD with -width 1680 -height 1050 -fullscreen and this is what my monitor showed:

![choco fart](https://cloud.githubusercontent.com/assets/5770757/20815155/9a7b8ba6-b7d1-11e6-98f4-6f0ca31db144.png)

This might sound dumb, but are you sure your monitor doesn't have some sort of overscan going on?

**Comment by AXDOOMER** [comment]
It may be your monitor that hides the border a bit.

**Comment by AnotherLife** [comment]
devparm + F1 also shows the red bar.

I can't see how it can be an overscan problem since my monitor is 1680x1050 and the game has big black bars on the sides. I think it happens because my monitor is 16:10 or something related to that.

**Comment by jmtd** [comment]
Are you starting choco with `-width 1680 -height 1050 -fullscreen`, if not can you try that, same result?  Can you double-check that those are the values in your `chocolate-doom.cfg`?

**Comment by fragglet** [comment]
This sounds like it may be a bug in the video scaling code, rather than anything to do with field of view?

**Comment by AnotherLife** [comment]
I added the parameters "-width 1680 -height 1050 -fullscreen" in ZDL and I could see the red column and black borders all around.
Then I removed the parameters and I could see the red column still.
Then I deleted the cfg and now I cannot see the red column. Also I am missing about 5 to 10 pixels from the bottom and have a little black border on top. I had not paid any attention to this earlier. This is some ghetto-ass scaling :D 

Maybe it's better on the SDL2 branch and this discussion is redundant. I originally thought that Choco showed a slightly different field of view than vanilla, I will edit the title.

(So width and height are saved permanently in the cfg once used? Weird.)

**Comment by chungy** [comment]
Chocolate Doom might be setting your display to 1280x960 while in full screen, and your monitor is cutting off the sides. You can verify that if you open `stdout.txt` after launching and reading the messages.

I'll close this as a non-issue, and it should be better on the SDL2 branch that doesn't change your screen mode anymore.
