### ISSUE TITLE
possibly wrong argument order for P_Random calls

### ISSUE THREAD

**Issue by jmtd** [chocolate-doom/chocolate-doom#831]
eccc7950039820344a10a3a330ea39637c301370 introduced a L-R evaluation order for expressions with multiple calls to P_Random(). @nukeykt later discovered that Heretic (Watcom) actually evaluated those expressions R-L and Heretic was fixed in #827. Hexen was not changed and as @haleyjd points out, likely has the wrong evaluation order. This should be provable via demo desync.

**Comment by nukeykt** [comment]
I've already fixed it in #829

**Comment by jmtd** [comment]
Thanks! I'll retag this doom to check the doom behaviour. I'd be surprised if a mistake snuck in there, but certainly L-R versus R-L evaluation for `P_Random() - P_Random()` should be different, and there are a lot of `P_SubRandom()` calls.

**Comment by haleyjd** [comment]
I can't tell if there's some confusion here or not but, the order of evaluation for function arguments is not the same as for a situation like P_SubRandom.

**Comment by jmtd** [comment]
Yes, you are right. They are both strictly undefined, so are you saying that watcom happened to choose L-R for function arguments (now all fixed) but L-R for expressions (matching the choice in `P_SubRandom`?)

**Comment by haleyjd** [comment]
Yes, it does not treat these situations the same way.

**Comment by jmtd** [comment]
In which case I'm sure that things must all be OK now then. Thanks!
