### ISSUE TITLE
2.3.0 release has a missing dependency

### ISSUE THREAD

**Issue by haleyjd** [chocolate-doom/chocolate-doom#833]
The 2.3.0 binary release for Windows is dependent on missing DLL libgcc_s_sjlj-1.dll - it should probably be rebuilt to link statically with the runtimes.

**Comment by chungy** [comment]
This appears to have been fixed with https://github.com/chocolate-doom/releases/commit/dc0e05e1cc42b87a86cf4db9402edadb9e6904ec

**Comment by fabiangreffrath** [comment]
Ah, sorry! I couldn't find that linker flag anywhere and so I thought it was a good idea to add it. Should I revert the commit?

**Comment by fragglet** [comment]
No problem. I think it is best reverted, since it's a linker flag that really needs to be set at a higher level (ie. for all packages, not just Chocolate Doom itself). I've filed chocolate-doom/chocpkg#10 since it's currently missing for chocpkg.
