### ISSUE TITLE
FreeBSD server cannot checkin with master.chocolate-doom.org

### ISSUE THREAD

**Issue by shirkdog** [chocolate-doom/chocolate-doom#835]
Tested on 2.2.1 and 2.3.0 with chocoloate-server in standalone mode with only -servername flag

Server is working when hitting it directly (over the Internet) but there is an issue with trying to register with the master server. I have checked layers 1-4 through and I am able to see the registration packet go out to the master server, but only one response packet, and apparently it is not a success.

I am currently looking at the master server code and the chocolate-doom client to get an understanding of what is going on. The only other thing I can see is if my IP or the server was banned for some reason as I saw that code in the master server repo :)

**Comment by fragglet** [comment]
If you can email me your IP address then I might be able to find more details about why your server is not registering with the master, since I have logs.

**Comment by shirkdog** [comment]
I might have found a config issue on my side...I now see it registered on master, sorry for the noise. 

The issue was that I had my server using an IP alias on my host, but I have the server running in a FreeBSD jail with firewall redirects. Direct connections worked, but there was some broken routing that I have resolved.

**Comment by shirkdog** [comment]
I still see periodic fails to register...so I leave this open.

**Comment by fragglet** [comment]
As mentioned, please contact me with your details. Email address is fraggle at Google's email service.

**Comment by fragglet** [comment]
Resolved over email.

**Comment by shirkdog** [comment]
Thanks fragglet, as you pointed out in email, I was missing a static-port option in my firewall config on FreeBSD to keep the same source port required when NATing with my jail.
