### ISSUE TITLE
"Visplane Overflow" crash message not being displayed

### ISSUE THREAD

**Issue by chocolate-import** [chocolate-doom/chocolate-doom#84]
> The following bug was [originally reported](https://sourceforge.net/p/chocolate-doom/bugs/84/) on Sourceforge by [porschemonty](https://sourceforge.net/u/porschemonty/profile/), 2010-08-27 02:56:25:

Download http://www.johnromero.com/lee\_killough/editing/bin/conduits.zip plus the save I've attached below (this is a vanilla Doom2 save) Now try this on the command line: chocolate-doom -iwad doom2.wad -file conduits.wad -loadgame 1

After the save loads, move backwards so to crash chocolate-doom. Repeat like 10 or 15 consecutive times and see if you can confirm what happens here: the crash message is displayed only a few times instead of every single time like it's the norm for vanilla.

I'm running [r1964](//github.com/fragglet/chocolate-doom/commit/966089e8bdc5d2cae9c1b9e889c9ca1405d6c29e) on WinXP Pro SP3 32bit.

Regards.

**Comment by mfrancis95** [comment]
@fabiangreffrath close because of fbb2fa82c536671ce3d6518dabc8a5f6601dc612?

**Comment by fabiangreffrath** [comment]
I think so, yes.
