### ISSUE TITLE
[Setup.exe] Weird symbols appears

### ISSUE THREAD

**Issue by JNechaevsky** [chocolate-doom/chocolate-doom#840]
Tested on chocolate-setup executable from SDL-2 branch (01/17/2017), 
Windows 10 x64, Windows 7 x86 (VM) and Windows XP (VM).

Weird symbols appears when keyboard layout changes from US to non-US (Russian in my case). Here's how it looks: http://i.imgur.com/E4EDqpy.png

Trying to investigate this, I have noticed that this happens only with buttons that does not contain English alphabet chars, i.e. these ones: http://i.imgur.com/eUOdC58.png
Anyway, this is only a visual graphical bug, there is no any problems with saving information to config file.

**Comment by fragglet** [comment]
Interesting. I think this is because I recently switched it to use SDL's key names instead of our own hard-coded ones. I didn't consider that some key names wouldn't be representable on-screen.

**Comment by fragglet** [comment]
Fixed - thanks!
