### ISSUE TITLE
Chocolate Doom can't find doom.wad

### ISSUE THREAD

**Issue by odhnera** [chocolate-doom/chocolate-doom#841]
Version - 2.3.0 Raspian
IWAD - Ultimate Doom (original version)
PWADs - None

I installed chocolate-doom on my Raspberry Pi (from the git repo). Everything works great, except for multiplayer. Normally, when I run chocolate-doom, I have to run it from terminal with the "-iwad" parameter. This works fine in single player mode, but in multiplayer, whenever I try to make a connection, I receive the error "IWAD file 'doom.wad' not found!" despite running chocolate-doom-setup it with the "-iwad" command. This error happens when trying to start a network game and also when trying to join a network game.

**Comment by chungy** [comment]
Were is the IWAD located? Two locations that should work are the directories `$HOME/.local/share/games/doom` and `/usr/share/games/doom`

**Comment by odhnera** [comment]
The IWAD is located in /home/pi/.chocolate-doom. Neither "$HOME/.local/share/games" or "/usr/share/games/" exist on my Raspberry Pi.

**Comment by odhnera** [comment]
I found the issue: the -iwad parameter for some reason only works in single player mode. In a network game, the -iwad parameter is being ignored. When I have both doom.wad and doom2.wad in the "$HOME/.local/share/games/doom" directory, chocolate-doom will only use one of the 2 .wad files and it will use that .wad file regardless of what I specify in the -iwad parameter.

**Comment by fragglet** [comment]
There are various ways to configure how Chocolate Doom finds your IWAD file. One is to `mkdir ~/.local/share/games/doom` and copy/move your IWADs there. Another is to set the `DOOMWADPATH` variable to point to your IWADs. You could also add the -iwad parameter to the "extra parameters" dialog when setting up the network game. Or if all this sounds too complicated, just run `chocolate-doom-setup` from the directory containing the IWAD file you want to use - it will check the current directory too. Hope this helps!

**Comment by odhnera** [comment]
I have documented the issue on video: when playing single-player, chocolate-doom loads the specified iwad. However, this isn't the case on multiplayer. Link to video: ftp://guest:guest@64.121.175.224/chocolate-doom.tar.xz

**Comment by chungy** [comment]
I see. The arguments list isn't passed through as expected in the multiplayer setup. Still, you can just change the game drop down to Doom when you're in the "start a network game" menu.

For what it's worth, too, you don't need to specify the full path to the files in the ~/.local directory, just "doom.wad" or "doom2.wad" is suffice.

**Comment by odhnera** [comment]
Thanks. I didn't see the dropdown menu until you mentioned it. Everything is working now.
