### ISSUE TITLE
support doom2f.wad

### ISSUE THREAD

**Issue by jmtd** [chocolate-doom/chocolate-doom#842]
The french IWAD

https://doomwiki.org/wiki/DOOM2F.WAD

**Comment by fabiangreffrath** [comment]
Where should it appear in the list of IWADs that we search for. Escpecially, should it come before or after the regular DOOM2.WAD, the Final Doom IWADs, the FreeDoom IWADs, HACX?

**Comment by chungy** [comment]
Just after standard doom2.wad, I'd think. It's basically just an alternative to it.

**Comment by fragglet** [comment]
You can already do this by using my [French Doom patch](https://www.doomworld.com/idgames/utils/exe_edit/patches/french) that I put together a few years ago after acquiring a copy of the French IWAD. The result should be identical.

**Comment by jmtd** [comment]
I raised this when copying the IWAD list and search path logic out of chocolate; it occurred to me if someone had the french IWAD it wouldn't work. I realise that in practice, anyone wanting the french translation is likely to use your patch. I'm still not sure whether we should have doom2f in the list anyway.

**Comment by fragglet** [comment]
I'd oppose adding doom2f.wad support unless we're going to do it properly. I think it's easiest to just declare it out of scope, but maybe we can list my patch on the "gameplay enhancements" page? I'm hesitant to toot my own horn but perhaps it's something people could find useful.

Would also be good to link @JNechaevsky's Russian Doom translation with it.
