### ISSUE TITLE
No message on weapon pickup in co-op and deathmatch (but displays in deathmatch 2.0)

### ISSUE THREAD

**Issue by Zodomaniac** [chocolate-doom/chocolate-doom#847]
That seems to be coop- and deathmatch-specific, in deathmatch 2.0 (altdeath) the weapon pickup messages are displayed.
Will this be fixed in Choco? The Choco philosophy seems to contain no reason against fixing this rather stupid-looking bug, this is no engine limitation or other important feature of Vanilla Doom.

**Comment by fragglet** [comment]
Is this a vanilla bug, then?

**Comment by Zodomaniac** [comment]
>Is this a vanilla bug, then?

Not sure, cannot test the vanilla executable.

**Comment by chungy** [comment]
Looks like they display in vanilla.

**Comment by jmtd** [comment]
I just tried the first demo from http://doomedsda.us/deathmatch.html in Chocolate and vanilla and the messages did not display in either. I haven't tested altdeath, I would need a demo recorded with altdeath to do so.

**Comment by Zodomaniac** [comment]
> I would need a demo recorded with altdeath to do so.

Here you are :) the demo, the map and the BAT-file to launch. You'll also need a version 1.666 Doom2 IWAD renamed to doom2v16.wad to play it.
[Altdeath demo.zip](https://github.com/chocolate-doom/chocolate-doom/files/737348/Altdeath.demo.zip)

**Comment by jmtd** [comment]
Thanks. So, what we know:

 * vanilla doom2 v1.9 in normal deathmatch mode doesn't print weapon pick-up messages in multiplayer
 * chocolate-doom doesn't either
 * vanilla doom2 v1.666 in altdeath mode does print weapon pick-up mesages in multiplayer
 * chocolate-doom (with the 1.666 IWAD, at least) does too
 * choco with the 1.9 IWAD refuses to play demos from 1.666

So it seems choco is perfectly vanilla consistent on this bug, for what that's worth.

The real question is, is this a bug which should be preserved according to the project goals?

**Comment by Zodomaniac** [comment]
Also, in v.1666 Normal DM mode and coop Choco doesn't print weapon pickup messages, see this demo (also requires doom2v16.wad IWAD) (remove the .txt extension, Github has a glitch in uploading ZIPs from this comp)
[CROSS DM demo.zip.txt](https://github.com/chocolate-doom/chocolate-doom/files/738995/CROSS.DM.demo.zip.txt)

**Comment by fabiangreffrath** [comment]
Where is the code that decides if weapon pick-up messages are printed or not depending on the game version?

**Comment by AXDOOMER** [comment]
The code of the weapon pickup is in there: https://github.com/chocolate-doom/chocolate-doom/blob/30f853b65820280931e06e07fd5f624313670305/src/doom/p_inter.c#L331

There must be a bug somewhere.

**Comment by AXDOOMER** [comment]
It's when the weapons are left on the ground for the other players after being picked up that the message doesn't show up (coop and normal deathmatch).

The code goes down this path when not in alt dm: https://github.com/chocolate-doom/chocolate-doom/blob/30f853b65820280931e06e07fd5f624313670305/src/doom/p_inter.c#L169

It returns false, the switch-case from P_TouchSpecialThing breaks before the message is set.

**Comment by AXDOOMER** [comment]
It's when the weapons are left on the ground for the other players after being picked up that the message doesn't show up (coop and normal deathmatch).

The code goes down this path when not in alt dm: https://github.com/chocolate-doom/chocolate-doom/blob/30f853b65820280931e06e07fd5f624313670305/src/doom/p_inter.c#L169

It returns false, the switch-case from P_TouchSpecialThing breaks before the message is set.

**Comment by fabiangreffrath** [comment]
Great, thanks for the explanation!

So, we should probably add a gameversion check to `P_GiveWeapon()`?

**Comment by Zodomaniac** [comment]
@fabiangreffrath 
>So, we should probably add a gameversion check to P_GiveWeapon()?

The game type (coop/DM/AltDM) makes the difference, not the game version.
This bug is the same in case of both 1.666 and 1.9 IWADs.

**Comment by AXDOOMER** [comment]
> This bug is the same in case of both 1.666 and 1.9 IWADs.

You should verify using the engines, not the IWADs. This bug was probably also in v1.2.

**Comment by jmtd** [comment]
altdeath was only added in 1.5 :)

**Comment by AXDOOMER** [comment]
> altdeath was only added in 1.5 :)

The bug doesn't happen when altdeath is activated. The bug occurs because of how they added the feature that makes guns stay on the map, thus affecting only coop and normal deathmatch.

**Comment by Zodomaniac** [comment]
So finally,
@jmtd 
>The real question is, is this a bug which should be preserved according to the project goals?

**Comment by chungy** [comment]
I've gone through with testing DOSBox and Chocolate Doom with 1.666, 1.7a, 1.8, and 1.9. No behavioral difference was seen across versions, but:
 * Pick-up messages are not displayed in co-op
 * Pick-up messages are not displayed in deathmatch 1.0
 * Pick-up messages *are* displayed in deathmatch 2.0

I believe Chocolate Doom is behaving identically to vanilla and doesn't need to be changed.

**Comment by fragglet** [comment]
@chungy - thank you for taking the time to investigate and for the comprehensive summary. This is not a bug, then.

**Comment by fragglet** [comment]
Oh, and also huge thanks to @AXDOOMER and @jmtd for tracking down the code and figuring this out. This has been an interesting thread.
