### ISSUE TITLE
SDL2: Can't change the number of sound channels using Chocolate-Setup

### ISSUE THREAD

**Issue by AXDOOMER** [chocolate-doom/chocolate-doom#854]
It's not possible to change the number of sounds channels from Chocolate-Setup. It's also not possible to change the sound/music volume, but this is less a problem because it can be changed in-game. 

Doom's default is 3 sound channels. Users may want to change it to 8. 

I am wondering why the sound configuration window has been completely redesigned. "If it ain't broken, don't fix it". 

![2 3](https://cloud.githubusercontent.com/assets/6194072/22621444/dc3f290a-eaf1-11e6-85c7-507d4fcd8fc8.png)
![3 o](https://cloud.githubusercontent.com/assets/6194072/22621445/dcdd045e-eaf1-11e6-88bb-f420aac645f4.png)

**Comment by fragglet** [comment]
Thanks for the report. This is by design.

**Comment by AXDOOMER** [comment]
What's the reason for this decision?

**Comment by fragglet** [comment]
You're asking the wrong question. What's the reason for wanting this setting in the UI? We've always actively excluded useless settings and hidden them away in the configuration file. This is just another example of one.

If this sounds unreasonable then here's a way of thinking about it. You're probably one of Chocolate Doom's most dedicated users (and I'm really thankful for all your continued contributions, including filing this bug!). That fact means that you've probably spent way more time than most users, including experimenting with all the various different settings, etc.

In all that time, and in all the time you've been playing Doom, have you ever felt the need to change the number of sound channels? I certainly haven't. So it makes a lot more sense to just change the default and remove it from the UI. If you really curious enough to want to experiment with it, the setting is still there in the configuration file.

Having useless settings like this in the setup tool isn't free. There's a cost to having them, in the form of clutter that prevents people from finding the real thing they want to change. I don't agree that this is a case of "if it ain't broken, don't fix it". The sound dialog was a mess, and the new version is an improvement.

**Comment by AXDOOMER** [comment]
I didn't think from the perspective of a programmer who has to deal with messy code. This is an obvious reason to want to simplify it, I agree. Although you don't have to add new feature to this window every week or even every month, I'm aware that your time may be precious and that this is a free software project. 

Sure I can change this setting in the config file, I have been changing this setting myself for test purposes only in the past. 

I am thinking from the perspective of a regular user who goes in the sound configuration window for the first time and may want to change this setting to make sure sounds don't get chopped off in-game. (e.g. when there are a lot of imps throwing fireballs)

Of course, Chocolate-Doom must remain faithful to Doom's default settings, but everyone today has the hardware that allows to use 8 sound channels without performance loss. It's like the settings that you change one time and leave it like that forever, just like the settings that you find in "Advanced display options" or "Compatibility". 

A regular user shouldn't have to open the config file. You probably added the F1 help key for those same people who are all the opposite of power users.

**Comment by fragglet** [comment]
> I didn't think from the perspective of a programmer who has to deal with messy code. 

I'm not arguing from that perspective. I'm arguing from the perspective of a regular user who is trying to find the thing they want to configure. I don't believe that such users are likely to ever want to change this option. The default is already 8 sound channels.

**Comment by AXDOOMER** [comment]
I thought you had fixed it when you fixed the default volume for sound and music, but I found your older comment: https://github.com/chocolate-doom/chocolate-doom/issues/347#issuecomment-38881261

No reason to argue then! I already got my answer two years ago.
