### ISSUE TITLE
SDL2: Game's window tries to resize itself to be 4:3 while the user resizes it and goes crazy (Fedora)

### ISSUE THREAD

**Issue by AXDOOMER** [chocolate-doom/chocolate-doom#856]
If you try to resize Chocolate-Doom's window while the game is running, the window will try to resize itself to always be a factor of 4:3 (I'm using 'Fix aspect ratio') and it will just go crazy. 

If you try to stretch it too much horizontally for example, it will try to resize itself vertically and fill the screen until it can't. 

I would have liked to provide a video, but Fedora doesn't have any screen capture software that works.

I tested on Fedora 25. On Windows 7, I don't have this issue, because the window's content is not being updated while I'm resizing. Fedora + Gnome3 does and I guess it is what causes the issue. 

I don't know if there is anything we can do about it or if it's a SDL bug.

**Comment by fabiangreffrath** [comment]
I can confirm this, the same happens on Debian with Gnome-Shell. :/

Maybe we should only call `AdjustWindowSize()` when the mouse button has been released again.

**Comment by linguica** [comment]
Surely there must be a way in SDL to disable horizontal / vertical window resizing and enforce only diagonal resizing with the proper aspect ratio?

**Comment by jmtd** [comment]
> Maybe we should only call AdjustWindowSize() when the mouse button has been released again. That is, once the resize event is over, not before.

Hmm.

> Surely there must be a way in SDL to disable horizontal / vertical window resizing and enforce only diagonal resizing with the proper aspect ratio?

I don't think we should try to force the window size at all, if the OS or the user has tried to set it to something else. We should just add/remove borders/letterboxes as necessary.

**Comment by JNechaevsky** [comment]
Not sure that this is a same bug, but checking today's latest build (20170206-win32) I have noticed very wierd graphical glitch, similar to "HOM effect". It happens only when game is started in full screen mode.

- If game started in full screen mode and changed to windowed mode, while resizing appears HOM effect.
- If game started in windowed mode, everything is okay with resizing.

https://youtu.be/WZs8SuL4j44

Maybe this can explain #836 somehow, i.e. created windows slightly different, depending on started mode.

Note: doubled cursor while resizing game window started in windowed mode - just a graphical glitch of screen recording.

**Comment by AXDOOMER** [comment]
It's the same bug, it just doesn't act the same and I must be because it's not the same window manager.

**Comment by fabiangreffrath** [comment]
I think @jmtd is right. We should remove the extra code in the `case SDL_WINDOWEVENT_RESIZED:` statement altogether and let people resize their windows as they wish. SDL2 adds black borders on its own anyway.

**Comment by fragglet** [comment]
The SDL1 version of the code waits for a delay with no 'resized' events and then does the resize. Might be best to just switch back to that approach.

**Comment by AXDOOMER** [comment]
Here's a video of what happens on my Fedora PC: https://sendvid.com/1abbuizd

It's different from @JNechaevsky, but the bug that causes this must be the same.

**Comment by fabiangreffrath** [comment]
Please try this, does it look better?
```
--- a/src/i_video.c
+++ b/src/i_video.c
@@ -324,7 +324,7 @@ static void HandleWindowEvent(SDL_WindowEvent *event)
             // When the window is resized (we're not in fullscreen mode),
             // save the new window size.
             flags = SDL_GetWindowFlags(screen);
-            if ((flags & SDL_WINDOW_FULLSCREEN_DESKTOP) == 0)
+            if (false && (flags & SDL_WINDOW_FULLSCREEN_DESKTOP) == 0)
             {
                 SDL_GetWindowSize(screen, &window_width, &window_height);
 
```

**Comment by AXDOOMER** [comment]
`if (false && (flags & SDL_WINDOW_FULLSCREEN_DESKTOP) == 0)` will always be evaluated as `false`.  What are you trying to do?

**Comment by JNechaevsky** [comment]
Here's what I god (with @fabiangreffrath 's line): https://youtu.be/19bwFzFLw8g

Looks likes, when window is resized without any apps that used GPU in background, HOM effect appears. But when there is such apps, instead of HOM, window mirrors GPU's app contents. Something like that.

**Comment by AXDOOMER** [comment]
It doesn't look good with black borders...

**Comment by fabiangreffrath** [comment]
> What are you trying to do?

Disable a whole block of code by changing only one line.

> Here's what I god (with @fabiangreffrath 's line)

Oh my, it somehow looked "just right" on Linux. :-/

> It doesn't look good with black borders...

Well, it puts black borders where you resized the windows out of aspect ratio.

**Comment by jmtd** [comment]
> The SDL call that sets the size of the window should only be called once the user is done resizing the window, else the window tries to keep its aspect ratio while resizing and this is what causes the problem.

We can't be sure that the window resize events we get are when the user is done or not -- some environments will send them with every drag, or after a certain period of time, or only once the user stops dragging.

In the aspect-correct case, IMHO, what we should do is let the window size be whatever is asked of us by the user/window manager/etc., and fit the nearest aspect-correct rectangle within that. If we get an adjustment, re-calculate the best-fit.

Not sure what to do in the not-aspect-correct case. We might get some very odd window dimensions after all, that would make the game unviewable. Do a best-fit for a 16:10 aspect? Seems weird to work hard to draw something incorrect.

**Comment by fragglet** [comment]
> Not sure what to do in the not-aspect-correct case.

Same in either case. It's just a different aspect ratio; the behavior doesn't need to be any different.

Jon's right that it's not possible to tell when resize has "finished". What do people think about my idea to just bring back the old behavior (delay before resize)? That's what we've been doing for ages and nobody seems to have really complained. I think I only changed it because I thought it wasn't needed any more with SDL2 (resizing works okay on Mac, but apparently not on other systems).

**Comment by AXDOOMER** [comment]
> What do people think about my idea to just bring back the old behavior (delay before resize)? 

I never noticed that there was some kind of behavior while resizing before. If it works, I think that's the way to go.

**Comment by jmtd** [comment]
You don't get any of the artefacts on OSX, but I imagine the stretch/resize behaviour is the same. But I haven't seen the craziness that @AXDOOMER mentions; it's hard to describe but it "works" just not necessarily intuitively (e.g. most resizes in one dimension only are basically ignored).

**Comment by jmtd** [comment]
On Linux (X/XFCE),I don't get ugly artefacts when resizing a window, but you can get into a situation where additional borders are drawn more on one side than the other, so the game viewport is not centred within the window. Sometimes a resize is "denied" an the window snaps back to its existing size, which I think could cause problems in some other environments (as previously mentioned). So I think some behaviour changes I'd recommend

 * always put the viewport in the middle of the window, we may need more hooks to figure out if that moves
 * don't fight a window resize that doesn't match the desired viewport/aspect ratio; just make the best of it.
 * since we get weird artifacting on several platforms when resizing, pause updating the viewport until the resize is finished.

**Comment by AXDOOMER** [comment]
Crazy was maybe a pretty big word, but it's like you describe. It fights the window resize because it wants the exact 4:3 aspect ratio, so a bug occurs and the window resizes weirdly if you don't release your cursor. 

https://sendvid.com/1abbuizd

**Comment by fabiangreffrath** [comment]
> don't fight a window resize that doesn't match the desired viewport/aspect ratio; just make the best of it.

I think this would mean to remove the call to `SDL_SetWindowSize()` from `case SDL_WINDOWEVENT_RESIZED` in `HandleWindowEvent()`.

> since we get weird artifacting on several platforms when resizing, pause updating the viewport until the resize is finished.

Unfortunetaly there dosen't seem to be an API that distinguishes between "window is currently resizing" and "window in finished resizing".

**Comment by fabiangreffrath** [comment]
Does this help? It does for me with Gnome Shell!
```
--- a/src/i_video.c
+++ b/src/i_video.c
@@ -339,8 +339,8 @@ static void HandleWindowEvent(SDL_WindowEvent *event)
 
                 // Adjust the window by resizing again so that the window
                 // is the right aspect ratio.
-                AdjustWindowSize();
-                SDL_SetWindowSize(screen, window_width, window_height);
+//              AdjustWindowSize();
+//              SDL_SetWindowSize(screen, window_width, window_height);
             }
             break;
 
```

**Comment by fabiangreffrath** [comment]
Could we please stop second-guessing the player's choice regarding the windows size, no matter if it fits the framebuffer's aspect ratio or not? It causes a mess to auto-resize the window as long as the mouse cursor is still in resize handle mode - at least on Linux. This is a real show-stopper for me and another five weeks have passed since this has last been discussed.

**Comment by jmtd** [comment]
I think I need to summarize (or someone else to summarize for me) exactly what the current behaviour is, and what the proposed behaviour is, to make a judgement call.

**Comment by AXDOOMER** [comment]
Current behavior: https://sendvid.com/1abbuizd

Correct behavior: Behave like the SDL1 version of Chocolate-Doom

**Comment by fabiangreffrath** [comment]
`git checkout sdl2-branch; make; ./src/chocolate-doom -window` ;)

One day, when I tried to resize a Choco window with Gnome Shell it was arbitrarily pushed off the screen and remained unreachable until I closed the game. Not cool.

**Comment by jmtd** [comment]
> Correct behavior: Behave like the SDL1 version of Chocolate-Doom
> git checkout sdl2-branch; make; ./src/chocolate-doom -window ;)

So the reason I phrased things the way I did is I don't have (right now) the time to actually do that on multiple platforms. But I could participate in a discussion about the behaviour we want, textually.

**Comment by fabiangreffrath** [comment]
I just stumbled upon this bug report of Inkscape playing badly with a tiling window manager (Awesome in this case):

```
My suspicion is that Inkscape and Awesome are fighting over window
sizes when originally creating the window and Inkscape is holding on to
the assumption that it got the size it requested.
```

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=861763

Has anyone ever tested Choco's sdl2-branch with such a tiling window manager?

**Comment by JNechaevsky** [comment]
Briefly tried Awesome + Chocolate Doom on VM. Not very good. In fullscreen everything is fine, but after returning to windowed mode, despite of Chocolate window is properly aligned as declared tile of Awesome, it is blinking.

But if it's started as windowed, everything seems to be fine, until it game windows is changed to full screen and back to windowed.

I can make a video record if necessary.

**Comment by fabiangreffrath** [comment]
So, the behaviour is about as broken as reported for Inkscape. This seems to be the case for programs that attempt to second-guess the window manager regarding the proper window size. Let's pelase stop this, at least on Linux.

> I can make a video record if necessary.

This would be great!

**Comment by JNechaevsky** [comment]
Here we go: https://youtu.be/4M6ypgkYIMk

I'm changing different tile modes it the top-right corner of the screen. 
Also note: 2D/3D acceleration is enabled on VM, it makes a huge sense for perfomance and possibly importmant for dialogue windows behaviour.

**Comment by jmtd** [comment]
Sounds like we are gradually agreeing with https://github.com/chocolate-doom/chocolate-doom/issues/856#issuecomment-287784114

**Comment by fabiangreffrath** [comment]
> Sounds like we are gradually agreeing with #856 (comment)

Yep, at least with point 2. Not sure what we can do about point 1 though.

**Comment by AXDOOMER** [comment]
> always put the viewport in the middle of the window, we may need more hooks to figure out if that moves

What's different from SDL1 that would require us to do this? The viewport should always be the optimum size (i.e. there must never be black borders in the window). Seriously, it would look awful.  

Fraggle previously said: 

> The SDL1 version of the code waits for a delay with no 'resized' events and then does the resize. Might be best to just switch back to that approach.

I infer from this that the resize code was modified and that it broke the correct behavior. Is the current behavior a result of something that was changed because it was impossible to do with SDL2? If not, then we can go back to the previous approach.

**Comment by fabiangreffrath** [comment]
> What's different from SDL1 that would require us to do this? The viewport should always be the optimum size (i.e. there must never be black borders in the window). Seriously, it would look awful.

No, we should not change the window size after a resize to get rid of the black borders. Instead, we should live with the windows size the user (or window manager) has chosen. This is what this entire issue is about, actually.

Again, by disabling the whole code in the `case SDL_WINDOWEVENT_RESIZED` branch in `HandleWindowEvent()` (except for `need_resize = true;` that is) I already achive this and a centered viewport with Linux window managers.

> If not, then we can go back to the previous approach.

With SDL1, there was no seamless scaling. Instead, the viewport could only be resized to integer multiples of 320x200 (or 320x240, respectively), so the code had to wait a few milliseconds to decide for which target resolution to snap to. This shouldn't be necessary with SDL2's hardware-based scaling anymore.

**Comment by fabiangreffrath** [comment]
NB: What happens if you slam e.g. Alt+Left on Windows (>= 7) to align the windows to cover the left side of the screen. Will it resize itself to *not* cover half of the screen and adhere to the game's aspect ratio instead?

**Comment by JNechaevsky** [comment]
@fabiangreffrath, I will make a record tomorrow on 7/8.1/10 OSes. I will not be in time today, sorry.

**Comment by JNechaevsky** [comment]
Sorry for delay, here we go: https://youtu.be/g0TWtUqXaF0
This feature called "Aero Snap". I'm doing it using mouse and Win+Arrows.

Line-up:
1. Windows 7 (Simple theme)
2. Windows 7 (Aero)
3. Windows 8.1
4. Windows 10

Everything seems to be fine with Chocolate executable, only two notable moments, and both of them seems to be Windows-specific:

- There is notable delay with window redrawing in Classic theme. This must be because of this theme is not using GPU at all. Definitely not critical.
- In Windows 10 Aero Snap working a little bit different, don't be surprised. Everyting fine with Chocolate window, though.

**Comment by fabiangreffrath** [comment]
Thank you very much for your investigations!

I don't like the fact that the windows reduces its own size after it has been told to occupy either the left or right half of the screen. There is a shaded area marking either half of the screen if the window if moved to one of the borders, this is the expected new window size. But our game window second-guesses this and reduces its size autonomously.

Apart from this, things seem to work fine already on Windows. **Is it possible that on Windows the `SDL_WINDOWEVENT_RESIZED` event is really only emerged after the resizing has been finished (whereas on Unix it is emerged even during resize)?**

**Comment by AXDOOMER** [comment]
@fabiangreffrath  I think you accidentally closed the issue.

**Comment by fabiangreffrath** [comment]
Indeed, sorry!

**Comment by fabiangreffrath** [comment]
Just tested with Gnome Shell in a Wayland session and the results of resizing were just as bad (maybe even worse) than in a X11 session. I'll add a check for the active display server that the game runs on and only call the self-resizing code conditionally if it's neither X11 nor Wayland.
