### ISSUE TITLE
Default location for Music Packs

### ISSUE THREAD

**Issue by Vaporeon** [chocolate-doom/chocolate-doom#857]
Currently in the SDL2 branch music recordings are configured by setting a path to the config files pointing to the music tracks and nothing is set by default.

Would it be a good idea to have a default location set? For example on unix-like systems it could be /usr/share/games/doom so the music packs can be installed.

**Comment by fragglet** [comment]
Thanks for the suggestion. This is already the case. If you don't set a path it will check `~/.local/share/chocolate-doom/music`.
