### ISSUE TITLE
Mac launcher has funny-colored command line arguments text field

### ISSUE THREAD

**Issue by linguica** [chocolate-doom/chocolate-doom#858]
See attached. I seem to recall it was black-on-white before?

![screen shot 2017-02-05 at 10 43 04 am](https://cloud.githubusercontent.com/assets/5770757/22628852/500dfdb8-eb90-11e6-8ed0-eed5e10a0ae6.png)

**Comment by fragglet** [comment]
This is deliberate. Looks a bit more like a DOS window.

**Comment by chungy** [comment]
While cute, should the imitation of DOS windows be limited to libtextscreen?

I think native launchers might as well do their best to fit in entirely with the native environment.

**Comment by fragglet** [comment]
Maybe.

**Comment by linguica** [comment]
I'm not against it per se, but while the combination of 10-point Courier and a light-to-medium gray background looks fine on a retina display, on a, uh, "legacy" display the subpixel antialiasing makes it kind of hard to read easily.

retina: http://i.imgur.com/2S550vv.png
non-retina: http://i.imgur.com/K8GSX8G.png

**Comment by fragglet** [comment]
Guess which one of those I have :) Okay, I'm convinced.
