### ISSUE TITLE
Separately controllable MIDI volume on Windows Vista+

### ISSUE THREAD

**Issue by AlexMax** [chocolate-doom/chocolate-doom#862]
Since Windows Vista, the Windows sound stack has been rewritten, and as a side-effect you can no longer independently control the MIDI volume.  Eternity Engine's solution is to farm MIDI playing out to a separate process, and send music data over RPC, so I figured that would be a good place to start.

Unfortunately, my initial research turned out to be inadequate.  In order to communicate with the midirpc process over RPC, bindings must be generated with Microsoft's Interface Definition Language Compiler, called `midl`.  Thankfully, there appears to be a Wine-wrapped version of the compiler called `widl`, however such a tool would need to be integrated into the build system.

If RPC is not a solution Chocolate Doom would be willing to roll with, or if there are problems encountered with the implementation, there is also the possibility of using [some other form of IPC](https://msdn.microsoft.com/en-us/library/aa365574%28v=vs.85%29.aspx).  Whatever method we use, it would have to be fast enough to handle the music we're throwing at it.

**Comment by AlexMax** [comment]
And immediately I run into problems.

In order to use RPC, the full `windows.h` must be used by the TU, not the "Lean and Mean" variant.  This has the unfortunate side effect of bringing in typedefs that actually blow away typedefs that Chocolate Doom defines, which wouldn't be so bad except that some of these functions need to be exposed to the rest of Chocolate Doom.

This is just a small problem that could be hacked around, but over the past day or two I've had a realization - Chocolate Doom already comes with a mechanism for RPC that is something I can actually comprehend and have worked with before.  Sockets.  Specifically, SDL_net.  Why can't I just stream the MIDI data over a localhost socket?  I'll have to marshall and unmarshall the data myself, but that's not THAT big of a deal with such a small API surface.  I also believe that Windows Firewall won't be a problem if I limit the server to only listen on localhost.

**Comment by AlexMax** [comment]
I have been working on the socket-driven implementation for a few days and have run into a slightly different sort of road-block.

The trouble is that the sub-process that handles playing music is its own program, and thus sharing code between the main Doom process and the music-playing process is tricky.  Notably, I can not reuse any of the **NET_*** functionality that exposes high-level routines over UDP that already exists in Chocolate Doom, because they have other dependencies elsewhere in Doom's code that are not satisfied when I just pull in bits and pieces for the subprocess - for example, I can't pull in those routines without also pulling in **Z_Malloc** and **I_Error** and so on.

The other option is to simply forgo Chocolate Doom's high-level functionality and use raw SDL_net to communicate.  However, while working with the **NET_*** functionality, I discovered that it was incredibly modular, with modules such as `net_sdl_module` containing function pointers to their appropriate functions.  I'm not quite sure if I'm supposed to supply something similar, and if so, what sort of interface I need to present.  After all, this is supposed to be a work-around for a problem specific to windows, so I'm not exactly sure that "modular" is the appropriate approach here.

**Comment by jmtd** [comment]
Hi @AlexMax , I'm not an expert on this kind of thing but if I were designing this from a UNIX perspective, here's what I'd do: I'd not write a completely distinct program, instead I'd have all this stuff be subroutines in chocolate-doom itself, and when creating the sub-process, just `fork()`. Then, I'd have the parent and child process communicate over a pipe.

From my (very limited) understanding of windows, it doesn't have a `fork`, or at least, it's not built on having a `fork` like that, but perhaps there is something similar. It means you don't need to worry about building a minimal separate program, unwinding the dependencies as you describe, we wouldn't need to worry about shipping a separate binary and having it available at all times (finding it relative to the executed binary, what if the user moves stuff about, etc.), and communicating over a pipe is simple enough that you don't need to worry about sockets etc. Quite similar to how the linux sound server worked in fact.

**Comment by fragglet** [comment]
I wouldn't try to add a dependency on `net_sdl.c` to communicate with the separate server. The code in there is quite specialized - it's intended for the network engine to use. You'd be better off using the plain SDL_net APIs to achieve the same.

Re: `windows.h`: includes are on a per-file basis. So can't you just have a particular .c file that #includes `windows.h` without the `WIN32_LEAN_AND_MEAN` #define?

**Comment by AlexMax** [comment]
> So can't you just have a particular .c file that #includes windows.h without the WIN32_LEAN_AND_MEAN #define?

I can, but then if I expose any functions via the associated .h file, they can't use any of the conflicting types.

**Comment by jmtd** [comment]
seems windows has `zwCreateProcess`to do something fork-like: http://stackoverflow.com/questions/985281/what-is-the-closest-thing-windows-has-to-fork/985525#985525

**Comment by AlexMax** [comment]
SDL_net does not support a TCP listening socket on anything other than `0.0.0.0`.  The upshot is that I cannot open a TCP listening socket with SDL_net without seeing an ugly firewall popup notification, which is unacceptable.

A couple of ways forwards:

* Using local UDP sockets via SDL_net.  This opens me up to the unreliability of UDP.
* Another is communicating with the subprocess through a [named pipe](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365590(v=vs.85).aspx).
* Or, maybe I could try [communicating over stdin/stdout](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682499(v=vs.85).aspx) of the launched process.

**Comment by jmtd** [comment]
> A couple of ways forwards:
...
> Or maybe I could cut the middleman and try communicating over stdin/stdout of the launched process.

That's how I would approach it with the fork-like method I was outlining.

**Comment by nukeykt** [comment]
I would use Vanilla Doom approach here: write MUS/MIDI player and change volume at MIDI event level. I see these advantages of this approach:
- Vanilla accurate MIDI music. DMX actually clips MIDI channel volume with music volume.
- Platform independent.
- Allows to introduce MUS format limitations.

But it has following disadvantages:
- Huge sound code rewrite.
- Possibly breaks Timidity (and GUS) support.

**Comment by AlexMax** [comment]
@jmtd I actually messed around with that approach tonight, but I'm having second thoughts about it.  Using Win32 pipes results in a considerable amount of Win32 word salad, and I'm not sure if @fragglet wants that sort of thing in Chocolate Doom on principle 😜 .

**Comment by jmtd** [comment]
> lso, another downside I've discovered is that since stdin/stdout are being used for IPC, I cannot use them to print-debug what's going on with the server.

You've still got stderr though, right?

**Comment by fragglet** [comment]
As it's a Windows-only feature anyway, it's fine to use Win32 pipes if that's easier. It's not like we're going to use this on other OSes?

**Comment by AlexMax** [comment]
@jmtd Of course, how silly of me to forget.

Good news!  I was able to get communication over stdin working!

Better news, Chocolate Doom is sending data and the subprocess is making sense of it!  If you want to glance at my in-progress branch, [feel free](https://github.com/chocolate-doom/chocolate-doom/compare/sdl2-branch...AlexMax:chocolate-midivolume).

Bad news, the integration is currently incredibly messy and unfinished and there are a few bugs.  Such as not actually being able to hear anything.  And crashes as soon as another song is attempted to be played.  So I have a long road in front of me yet.

More bad news - due to the way I worked on this branch, my TCP dead-end is currently enshrined in the history of the branch.  I started work on the TCP implementation, then I implemented some data structures for the subprocess before I realized the problem with SDL_net.  I can try and generate some cleaner history free of the TCP dead-end if that's desirable, but if you don't care that's fine too.

**Comment by jmtd** [comment]
Don't consider that yet: get something working to your satisfaction first :) I don't know how important a clean history is for Fraggle, but long lived branches like sdl2-branch have a very messy history and aren't going to get cleaned up.

**Comment by AlexMax** [comment]
Speaking of working, the [branch is now in a working state](https://github.com/chocolate-doom/chocolate-doom/compare/sdl2-branch...AlexMax:chocolate-midivolume).  You can launch Chocolate Doom with Native MIDI and separately control the volume of the music and SFX.

**Comment by AlexMax** [comment]
I'm getting close to a point where I can share this with the world.  However, something I might need a little help with is setting up automake correctly - I wasn't able to get Chocolate Doom built with cygwin last time I tried, and my MSVC project is upgraded and not in condition to commit.

**Comment by chungy** [comment]
I added autoconf/automake support to the branch here: https://github.com/chungy/chocolate-doom/tree/chocolate-midivolume

I do see the following warnings and errors, using i686-w64-mingw32-gcc 6.3.1:
```
buffer.c: In function ‘Buffer_Push’:
buffer.c:65:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
     ptrdiff_t space_begin = buf->data - buf->buffer;
     ^~~~~~~~~
buffer.c: In function ‘Buffer_Shift’:
buffer.c:102:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
     ptrdiff_t max_shift = buf->data_end - buf->data;
     ^~~~~~~~~
main.c: In function ‘MidiPipe_RegisterSong’:
main.c:167:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
     unsigned int i = NET_MIDIPIPE_PACKET_TYPE_REGISTER_SONG_ACK;
     ^~~~~~~~
main.c: In function ‘ParseMessage’:
main.c:267:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
     int bytes_read = Reader_BytesRead(reader);
     ^~~
At top level:
main.c:44:18: warning: ‘midi_buffer’ defined but not used [-Wunused-variable]
 static buffer_t *midi_buffer;      // Data from client.
                  ^~~~~~~~~~~
```

```
i_midipipe.c: In function ‘ExpectPipe’:
i_midipipe.c:158:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
     int start = I_GetTimeMS();
     ^~~
i_midipipe.c: In function ‘I_MidiPipe_RegisterSong’:
i_midipipe.c:217:29: warning: passing argument 2 of ‘NET_WriteString’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
     NET_WriteString(packet, filename);
                             ^~~~~~~~
In file included from i_midipipe.c:30:0:
net_packet.h:41:6: note: expected ‘char *’ but argument is of type ‘const char *’
 void NET_WriteString(net_packet_t *packet, char *string);
      ^~~~~~~~~~~~~~~
i_midipipe.c: In function ‘I_MidiPipe_InitServer’:
i_midipipe.c:360:17: error: storage size of ‘sbuf’ isn’t known
     struct stat sbuf;
                 ^~~~
i_midipipe.c:373:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
     size_t filename_len = GetModuleFileName(NULL, filename, MAX_PATH);
     ^~~~~~
i_midipipe.c:387:8: warning: implicit declaration of function ‘stat’ [-Wimplicit-function-declaration]
     if(stat(module, &sbuf))
        ^~~~
i_midipipe.c:394:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
     SECURITY_ATTRIBUTES sec_attrs;
     ^~~~~~~~~~~~~~~~~~~
i_midipipe.c:425:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
     PROCESS_INFORMATION proc_info;
     ^~~~~~~~~~~~~~~~~~~
i_midipipe.c:428:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
     STARTUPINFO startup_info;
     ^~~~~~~~~~~
i_midipipe.c:435:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
     BOOL ok = CreateProcess(TEXT(module), TEXT(cmdline), NULL, NULL, TRUE,
     ^~~~
i_midipipe.c:360:17: warning: unused variable ‘sbuf’ [-Wunused-variable]
     struct stat sbuf;
                 ^~~~
```

**Comment by AlexMax** [comment]
I finally managed to get cygwin up and running, and have ferreted out all of the GCC warning/errors.
