### ISSUE TITLE
Vsync doesn't seem to be active

### ISSUE THREAD

**Issue by linguica** [chocolate-doom/chocolate-doom#868]
From testing out @jmtd 's VGA porch emulation code, I think I've discovered a bug with the SDL2 code: vsync isn't enabled, so there's screen tearing.

Slow motion video of sdl2-branch (with the porch emulation pull request - this made it much more obvious at least):

![tearing 1](https://cloud.githubusercontent.com/assets/5770757/23138721/cfae1354-f75d-11e6-944b-b8b542d81127.gif)

Editing SetVideoMode() to add `renderer_flags |= SDL_RENDERER_PRESENTVSYNC;`

![vsync](https://cloud.githubusercontent.com/assets/5770757/23138863/958eadae-f75e-11e6-8d88-ec51b604de50.gif)

I would submit a pull request with a one-line change but I don't know if there's any possible reason someone might want vsync turned off or if it should be an option in some way.

**Comment by fabiangreffrath** [comment]
> I would submit a pull request with a one-line change but I don't know if there's any possible reason someone might want vsync turned off or if it should be an option in some way

It will make a difference for Crispy's uncapped rendering, so I'll add an option to turn it on or off. For Choco, I think you are right and we should enable this unconditionally.

**Comment by jmtd** [comment]
This is a great bug report!

**Comment by fabiangreffrath** [comment]
> For Choco, I think you are right and we should enable this unconditionally.

Oh, wait! How about `-timedemo`, is this now capped at the screen's refresh rate?

**Comment by chungy** [comment]
> Oh, wait! How about -timedemo, is this now capped at the screen's refresh rate?

Yeah, it is.
