### ISSUE TITLE
Strife: Different behavior when a demo is specified with the file extension

### ISSUE THREAD

**Issue by AXDOOMER** [chocolate-doom/chocolate-doom#870]
When I try to play a demo and specify the name with the extension (which is bad just like with Doom), I get this error message in Strife: 

![untitled](https://cloud.githubusercontent.com/assets/6194072/23242162/6568c41e-f945-11e6-95f1-e439f2a19a92.gif)

Chocolate-Strife does some magic trick that accepts the .lmp extension thus to achieve the same bug I would need to do "-playdemo c:\dos\strife\testing.lmp.lmp" and instead this gives the error "W_GetNumForName: c:\dos\s not found" which is also wrong.

So it's wrong for two reasons: First, the error message seems to let know that the error is triggered at a different place internally, that means the game is not behaving the same on the inside. Second, the error displayed by Choco Strife contains a 8 character path that's obviously no fine. Was it looking to display the 8 character name of the file like if I was in DOS? Modern OS have long file names and huge paths.

**Comment by chungy** [comment]
This is related to it falling back to searching for a demo lump with the specified name in any of the loaded IWAD or PWAD files. Lumps in WADs have an 8-character limit.

**Comment by haleyjd** [comment]
"Z_CT" is indicative of heap corruption; I highly doubt this is something that Chocolate should be emulating accurately.

**Comment by fragglet** [comment]
This is by design. We're deliberately more forgiving about the paths we exist, so that the following are all valid:

    chocolate-doom -playdemo foo
    chocolate-doom -playdemo foo.lmp
    chocolate-doom -playdemo $PWD/foo.lmp

**Comment by AXDOOMER** [comment]
I'm  not asking to emulated the `Z_CT` error, but at least display an error message with the correct path rather than "W_GetNumForName: c:\dos\s not found". This is confusing and it's wrong to put a long path into a 8 char string. If only the name of the file was displayed, it would already be better than displaying the first 8 chars of the path.
