### ISSUE TITLE
[Feature request] Add "force_software_renderer" to setup program

### ISSUE THREAD

**Issue by JNechaevsky** [chocolate-doom/chocolate-doom#871]
Since force software rendering is present in config file as variable, maybe it also should be placed in setup executable (Display options/Advanced)? There is no awful necessary to do this, but I think it might be useful by following reasons:

1. Software rendering may prevent from some additional little noise/heat on notebooks with discrete graphic cards, when even minimal GPU using starts cooling fan spins faster. This is a rare case of course, because of overall CPU/GPU usage of Chocolate Doom is very small.
2. May help someone, who don't like frame changing interpolation and loves SDL1 movement feeling.
3. May be interesting from technical POW.
4. At last, it's one of Chocolate Doom features.

**Comment by fragglet** [comment]
We deliberately don't expose every config file option in the setup UI and I actually think we've gone too far recently in adding some mostly-useless options. I'd rather just tell people, "you need a GPU and the ability to do hardware rendering to use this software" than clutter the UI. The software rendering option is a hack anyway.

**Comment by jmtd** [comment]
> I actually think we've gone too far recently in adding some mostly-useless options. 

Please elaborate so we can fix this:)
