### ISSUE TITLE
CMake Build System

### ISSUE THREAD

**Issue by AlexMax** [chocolate-doom/chocolate-doom#877]
This issue is for the CMake build system that I am in the process of creating for Chocolate Doom.  [The link to the branch is here](https://github.com/AlexMax/crispy-doom/tree/cmake).

There was a discussion about CMake on Doomworld recently, and there was a challenge that it replace the Code::Blocks build system.  Here what has been accomplished so far:

* All of the targets are built.  This includes incorporating things such as resource files and manifests.
* MinGW Makefile and Ninja targets work on Windows.  This includes Code::Blocks, which can use either system to drive the build.  The Visual Studio target works as well.
* A cursory check of compiling on Linux reveals that it works too.  I didn't look too deeply into this, since autotools already exists.
* There is a single extra non-CMakeLists.txt file that is necessary for the build to run.  **config.h.in** is used to template out the **config.h** file, as CMake has no autoheader equivalent.  All of the other .in files are used as-is.

Stuff in progress:

* libpng and libsamplerate optional dependencies are part of the build system, and work on Linux, but I have not yet come up with a nice way of integrating them into a Windows build yet.
* Work on documentation is ongoing, and my work so far can be found in **README.CMake.md**.
* Mac builds with XCode.  Hasn't even begun actually, hopefully won't be too much of a bother.

Weird stuff I found out:

* I have not yet been able to figure out how to use the version of GDB included with TDM-GCC on Chocolate Doom, there are unknown exceptions raised.  This isn't a CMake issue, but it's something I ran into while testing the Code::Blocks project.

I am pleased to report that I was able to walk @JNechaevsky through creating the project file for Code::Blocks.  He did find it a little...inconvenient, and uncovered several trouble spots where I needed to improve the functionality and make things less confusing.

**Comment by chungy** [comment]
Looking pretty good, only testing with make and ninja targets myself, but seems to competently build the engine and setup program!

> A cursory check of compiling on Linux reveals that it works too. I didn't look too deeply into this, since autotools already exists.

Seems to work fine. There is no install target, but as the autotools system would be preferred on Unix anyway, I can't convince myself that it's a real issue at all.

> libpng and libsamplerate optional dependencies are part of the build system, and work on Linux, but I have not yet come up with a nice way of integrating them into a Windows build yet.

These seem to work doing a crossbuild on Arch Linux and mingw-w64. I suspect Cygwin would be similar. I can't provide advice about more native Windows environments though (MSVC, CodeBlocks, etc)

> Work on documentation is ongoing, and my work so far can be found in README.CMake.md.

This file is annoying to read on a terminal. Can you break the lines at 72-wide?

**Comment by jmtd** [comment]
> Mac builds with XCode. Hasn't even begun actually, hopefully won't be too much of a bother.

Just as a data point, I build on Mac but never use Xcode. I think Fraggle is the same. I personally wouldn't care if that worked or not, but perhaps it's useful for someone?

**Comment by jmtd** [comment]
Earlier today I tried

```
$ mkdir build
$ cd build
$ cmake ..
$ make -j
... # errors
```

I thought I'd try just a "make" next to get the error output isolated, but it actually worked! So the issue might be to do with parallelism. Looking over the `make -j` output, I'm seeing something pretty weird!

```
ccache: error: Failed to fork: Resource temporarily unavailable
ccache: error: Failed to fork: Resource temporarily unavailable
ccache: error: Failed to fork: Resource temporarily unavailable
clang: error: unable to execute command: posix_spawn failed: Resource temporarily unavailable
ccache: error: Failed to fork: Resource temporarily unavailable
```

**Comment by jmtd** [comment]
`make clean; make -j32` worked.

**Comment by JNechaevsky** [comment]
@AlexMax, sorry for late reply. As I promised, I have tested your update - everything configures, generates and works fine: http://i.imgur.com/UptLw6y.png

Now it's much more comfortable to have all SDL2_* stuff in one SDL2 section :)
However, I have not touched SAMPLERATE and ZLIB stuff.

**Comment by jmtd** [comment]
Getting  `Unknown CMake command "check_library_exists".` Fix seems to be

   +INCLUDE(CheckLibraryExists)

Could we have this as a PR? It's easier to find code discussions there than the issues.

**Comment by chungy** [comment]
CMake support was merged quite a while ago. Closing.
