### ISSUE TITLE
Configurable button for respawning

### ISSUE THREAD

**Issue by Zodomaniac** [chocolate-doom/chocolate-doom#880]
For about 20 years it's already been common in FPS games to respawn/restart level after death by clicking the "fire" button, the newer players like me can get a bit confused after death in Doom DM that they should hit Use to respawn. I suggest to enable binding the respawn button to different actions: use or fire (and maybe another, speed on etc.).

**Comment by fragglet** [comment]
Thanks for the suggestion. I think this is out of scope for the project, though maybe Crispy Doom will take it.

**Comment by fabiangreffrath** [comment]
I have sent him here, because I hoped that the possibility to rebind the respawn action to a different button would get accepted. :/

**Comment by fragglet** [comment]
Understood. As mentioned in previous comments, I've been relatively liberal about expanding the range of input controls, but this situation seems like a fairly clear case of "that's just how Vanilla behaves".
