### ISSUE TITLE
Suggestion: Mark the DLL files with the hidden attribute

### ISSUE THREAD

**Issue by chungy** [chocolate-doom/chocolate-doom#883]
Presently, all the files in the Windows zip distribution have no file attributes attached to them. One attribute possible, however, is the hidden attribute, that hides files from normal Windows Explorer or `dir` command listings (both have overrides to display hidden files).

The *.dll files are not files that should normally be interacted with directly, and as such it just clutters the display.

Currently, everything's on full display:
![DLLs Not Hidden](https://chungy.keybase.pub/chocolate-doom/windows_no-hidden-files.png)

It could alternatively look like this:
![DLLs Hidden](https://chungy.keybase.pub/chocolate-doom/windows_hidden-files.png)
(In this example that includes `chocolate-midiproc.exe`, that would actually be another candidate for being hidden: It's not meant to be run directly...)

---

Two people on IRC did come up with a couple points against this idea
 * It is not typical convention to set the hidden attribute on DLLs
 * If somebody tried to move Chocolate Doom by dragging the files instead of the whole folder, the DLLs won't be selected/moved with it (assuming hidden files aren't displayed)

On the first point, it's also not really convention to be interacting with programs so directly. Windows programs usually install to `Program Files` and you're not really expected to browse it manually anyway (heh... try looking at the MS Office directory, they dump hundreds of files in the same folder, trying to pick out one of the applications to run is a real trick). Chocolate Doom is already breaking a bit of conventions by distributing as a zip file (I don't believe it's an issue, but it's just how it is). Also mind that the hidden attribute is only relevant for UI display, program functionality is completely unaffected.

The second point might have more merit, but I kind of struggle to think whether this is really a common enough action to worry about...

I can come up with a third point too: Since the zip files are created from Unix systems (even under cygwin!), the `zip` program has no way to force Windows attributes such as the hidden attribute on them. We might be able to have a program to take more control over the zip creation and do this ourselves (something written in Python, perhaps). Certainly the lazy route of not doing anything is the easiest. :-)

**Comment by JNechaevsky** [comment]
I'm not sure that hiding DLLs is a good idea, this can make some confusion. 
But may I recommend some restructuring by adding folders? 
Something like this: http://i.imgur.com/QFJEajS.png

I.e., `dlls` folder for any libraries and `docs` folder for text files and license.

But I honestly don't know, is it possible for Windows to have DLLs placed in other folder than executable, without declaration any system-wide PATH variable.

**Comment by fragglet** [comment]
Sounds needlessly confusing - I understand that there's clutter but on it potentially leads to more confusing situations - for example, `chocolate-doom.exe` "works" from one directory, but if moved to another, mysteriously stops working because of a dependency on files that the user can't see.

**Comment by chungy** [comment]
> I.e., dlls folder for any libraries and docs folder for text files and license.
>
> But I honestly don't know, is it possible for Windows to have DLLs placed in other folder than executable, without declaration any system-wide PATH variable.

They just have to be in the PATH, but to do that before the EXEs are run, there would need to be `.cmd` files to load the engine instead of allowing to run directly. I think the idea is even worse than mine.

> `chocolate-doom.exe` "works" from one directory, but if moved to another, mysteriously stops working because of a dependency on files that the user can't see.

Aye, this was brought up on IRC.  Okay, so four people think this is a bad idea, shall we close this? :)

**Comment by fragglet** [comment]
Okay, closing. Thanks for suggesting though.

**Comment by fx02** [comment]
Installer/launcher is solution to resolve "issues" like this.
