### ISSUE TITLE
SDL2: DPI Aware manifest isn't actually applied

### ISSUE THREAD

**Issue by AlexMax** [chocolate-doom/chocolate-doom#885]
Chocolate Doom appears to ignore the manifest and scales itself up at higher DPI's.  If I enable the DPI-awareness compatibility setting, for Chocolate Doom, the resolution is set to the proper size.

This is something I can verify happens with my 3.0 beta that I downloaded, as well as the almost-up-to-date branches I'm currently working on that use the autotools build system.

The manifest itself is fine, because if I add it by hand using Visual Studio using project properties, I get a DPI-aware program that doesn't scale itself up.

**Comment by AlexMax** [comment]
The solution turned out to be simple.  Change the manifest invocation in the resource file to:

    1 24 "../src/manifest.xml"

**Comment by jmtd** [comment]
> I'm not sure it's worth a pull request when somebody can just go in and fix it in two seconds.

Make one yourself in the github UI and you'll at least get the commit credited to you!
