### ISSUE TITLE
SDL2: Running headless appears to be impossible

### ISSUE THREAD

**Issue by AlexMax** [chocolate-doom/chocolate-doom#891]
I have been running into issues when trying to run the SDL2 version of Chocolate Doom on a headless Linux box.  It appears that the code as it stands doesn't play well with the `dummy` video driver.

1. `Error creating renderer for screen window: Couldn't find matching render driver`.  I eventually tracked this error down to the use of `SDL_RENDERER_PRESENTVSYNC` when creating the renderer - use of that flag prevents the creation of the renderer.  Passing `-timedemo` appears to avoid setting this flag, but then I run into another problem...
2. `CreateUpscaledTexture: Can't create a texture big enough for the whole screen! Maximum texture size 0x0`.  This error message is due to the fact that `max_texture_width` and `max_texture_height` don't appear to have any value with the dummy video driver.  I think another developer ran into a similar issue when attempting to run Chocolate Doom in a virtual machine.  I was able to bypass this error message by hard-coding values for the texture width and height.

As this issue shows, I have figured out ways to bypass these issues.  However, I only know workarounds - I am unsure as to what the correct way to fix this problem is.

**Comment by fragglet** [comment]
Interesting. I wonder if this also breaks statcheck - I think that uses the dummy driver too.

**Comment by fabiangreffrath** [comment]
Couldn't statcheck just use `-nodraw`?

**Comment by fragglet** [comment]
It does use `-nodraw` but it still has to initialize the video backend.
