### ISSUE TITLE
crashes when config references a (now unattached) display

### ISSUE THREAD

**Issue by jmtd** [chocolate-doom/chocolate-doom#898]
Run or configure chocolate-doom with two or more displays; put choco on the second display; remove second display try running choco. Result

```
Could not get display mode for video display #1: displayIndex must be in the range 0 - 0
```

**Comment by fabiangreffrath** [comment]
Hm, maybe we should run `CenterWindow()` if `SDL_GetCurrentDisplayMode()` fails and try again.
