### ISSUE TITLE
build error with MingW-W64: undefined reference to `_imp__GetDeviceCaps@8'

### ISSUE THREAD

**Issue by fabiangreffrath** [chocolate-doom/chocolate-doom#899]
I don't know when this started, because I haven't build sdl2-branch on Windows for ages, but this is what currently happens to me (on Win7 64-bit, MSYS2, gcc.exe (Rev2, Built by MSYS2 project) 6.3.0)

```
  CCLD     chocolate-doom.exe
../textscreen/libtextscreen.a(txt_sdl.o): In function `Win32_UseLargeFont':
D:\msys32\home\greffrath\chd\textscreen/txt_sdl.c:125: undefined reference to `_imp__GetDeviceCaps@8'
collect2.exe: error: ld returned 1 exit status
```

Forcefully adding `-mwindows` to `LDFLAGS` fixes this, but I am hesitant, because AFAIR this was not necessary before:

```
--- a/configure.ac
+++ b/configure.ac
@@ -94,6 +94,7 @@ AC_ARG_WITH([bashcompletiondir],
 case "$host" in
   *-*-mingw* | *-*-cygwin* | *-*-msvc* )
     AC_CHECK_TOOL(WINDRES, windres, )
+    LDFLAGS="$LDFLAGS -mwindows"
     ;;
   *)
     WINDRES=
```

**Comment by fabiangreffrath** [comment]
So, any opinions?

**Comment by AXDOOMER** [comment]
I got the exact same error when I tried to build it by myself using cmake. 

Use [chocpkg](https://github.com/chocolate-doom/chocpkg) instead, it's easier. I have successfully cross-compiled Chocolate-Doom with it.

**Comment by AXDOOMER** [comment]
If you want to build it for Windows, you have to go in the script `buildenv.sh` and uncomment the line `BUILD_HOST=i686-w64-mingw32`.

**Comment by fabiangreffrath** [comment]
I am not going to cross-build it. This happens when I do a native build with MSYS2 on an actual Windows 7 system.

**Comment by AXDOOMER** [comment]
So my understanding is that you want to build for Windows on Windows using MSYS2 which is a kind of Linux distro. Then you can still use chocpkg. 

What is you current way of building it that gave you an error?

**Comment by fabiangreffrath** [comment]
I use the usual
```
autoreconf -vif
./configure
make
```

**Comment by AXDOOMER** [comment]
I don't build like that on GNU/Linux. I usually do:
```
./autogen.sh
make -j 4
```
On MSYS2, I don't know if it would build Linux or Wind0ws binaries.

**Comment by fabiangreffrath** [comment]
Have a look at `autogen.sh`: It's basically the same as calling `autoreconf -vif && ./configure` and the `-j 4` parameter to `make` merely complies up to 4 filea at once. So, we are building the same way.

Also, MSYS2 is a "unix-like" environment for Windows (i.e. basically a bash which allows to run the `./configure` script and some other tools) which allows for building *native* Win32-applications using MinGW-W64.

**Comment by AXDOOMER** [comment]
`undefined reference to` could mean it's a linking error and `GetDeviceCaps` is found in `gdi32.dll`. Maybe add `gdi32` as an import lib? I think it's `libgdi32.a` in the MinGW lib folder. I hope this helps.

**Comment by fabiangreffrath** [comment]
Yep, adding `-lgdi32` to LIBS could serve as an alternative approach. But I think it makes more sense to tell the compiler that we are actually building a windowed application, it seems to fall back to `-mconsole` recently if not told differently. Any Win32 experts around here?

**Comment by fabiangreffrath** [comment]
Hm, there is a mismatch between the linker flags returned by `sdl2-config` and `pkg-config`:

```
greffrath@WS615 MINGW32 ~/chd
(sdl2-branch) $ pkg-config --libs SDL2
-LD:/msys32/mingw32/lib -lmingw32 -lSDL2main -lSDL2

greffrath@WS615 MINGW32 ~/chd
(sdl2-branch) $ sdl2-config --libs
-L/mingw32/lib -lmingw32 -lSDL2main -lSDL2 -mwindows
```

There is one flag missing in the latter (which is what Choco currently uses) and that is, surprise, `-mwindows`. So, I guess that SDL2 using applications are supposed to get built with this linker flag on Windows, but this has somehow missed its way into the pkg-config file.

I am thus sure that it is safe to add this flag if we detect we are building natively on Windows using Autotools.

**Comment by fabiangreffrath** [comment]
Sorry, guys! Forget everything I said, this seems to be a problem introduced by MSYS2:

https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-SDL2/PKGBUILD#L36

**Comment by fabiangreffrath** [comment]
https://github.com/Alexpux/MINGW-packages/issues/2413
