### ISSUE TITLE
The startup will appear frozen if NET_ValidGameSettings returns false

### ISSUE THREAD

**Issue by AXDOOMER** [chocolate-doom/chocolate-doom#905]
If somehow this function returns `false`, then the game will get stuck at `D_CheckNetGame: Checking network game status.` at startup. There is no error message about the invalid game setting(s) and nothing will happen. I believe there should be feedback for the user, else what's the purpose of this function if it doesn't let the user start the game with invalid settings, but instead prevent the program from exiting and making it appear frozen? Some settings such as deathmatch can only be made invalid if there are changes to Setup (for example: a third deathmatch mode) and the developer forgets to do the changes, but a user can trigger this bug by using the command line parameter `-skill 6`, which is an invalid skill level. Other game settings can also trigger this. See the function. 

NET_ValidGameSettings: https://github.com/chocolate-doom/chocolate-doom/blob/30f853b65820280931e06e07fd5f624313670305/src/net_common.c#L511

**Comment by fabiangreffrath** [comment]
This appears to be the same issue as https://github.com/chocolate-doom/chocolate-doom/issues/875

**Comment by AXDOOMER** [comment]
Yes, it must be the same.
