### ISSUE TITLE
Few suggestions for Find Internet server

### ISSUE THREAD

**Issue by JNechaevsky** [chocolate-doom/chocolate-doom#907]
There is no critical necessity for all of these, so please consider them only as ideas.

- Capitalize the word "internet" to get "Find **I**nternet server" title in the server selection window.
- Add current players column. Just to know how server is loaded before connecting to it. Maybe only one digit will be good enough, since there are strict limitations for all games (4 and 8). From another hand, just digit 2 may looks confusing, rather than proper 2/4.
- Add server's version indicator. It may prevent some confusion of different Chocolate / Crispy versions, when they are registered on Master Server.

**Comment by chungy** [comment]
> Capitalize the word "internet" to get "Find Internet server" title in the server selection window.

It is becoming widely accepted (for example, the Associated Press style guidelines) to keep the word lowercase except at the beginning of a sentence, since internet is not a trademark or brandname of any sort. I think I'd prefer lowercasing the option that pulls up this dialog, actually.

**Comment by jmtd** [comment]
It's a proper noun, and needs distinguishing from the regular noun "internet"

**Comment by fragglet** [comment]
Fixed - thanks. I didn't do the third suggestion because recent changes to network protocol versioning would make the label misleading. If a server is listed, we have some confidence that we're able to connect to it in a compatible way.

**Comment by AXDOOMER** [comment]
Could it be possible to display if the game has already started? An idea would be to display `2/4` when there are two players connected and we are waiting for other players, but when the game has started, `2/2` could be displayed to indicate that no more players can join.
