### ISSUE TITLE
File chooser on Linux searches for files with a lower case extension only

### ISSUE THREAD

**Issue by AXDOOMER** [chocolate-doom/chocolate-doom#908]
When browsing for WADs. 

The file filters are for .deh, .wad, .lmp, but there is no * filter. On Linux, there needs to be uppercase file filters for extensions so users can select uppercase files.

**Comment by AXDOOMER** [comment]
Also, why not add extensions `.mid` or `.mus` which Doom supports? I also believe Doom supports `.wav` files. 

For the files filters, I don't know if you can do like Java. For example, for the file chooser in Java, you give it a category (DeHackEd for example) and you give the accepted files extensions (`.deh` and `.DEH`). 

What I would consider a fix for this bug is having both uppercase and lowercase file extensions. No mixed case, not even for `.Wad`.

**Comment by jmtd** [comment]
So you're talking about the zenity file chooser (if you don't have zenity installed, you don't get that pop-up and instead have to type a path).

The file chooser gets called in a few different places and it makes sense to have different extension filters in each place.

For multiplayer add WAD, I agree with adding all-caps versions of wad,lmp,deh.

I'm not sure about .mid or .mus or .wav; did that really work in vanilla?

**Comment by jmtd** [comment]
the fix needs to be in libtextscreen, we need to convert an extension like wad into a pattern like *.[Ww][Aa][Dd]; just adding uppercase equivalents to the filter list is not sufficient.

**Comment by fabiangreffrath** [comment]
> I'm not sure about .mid or .mus or .wav; did that really work in vanilla?

I don't think DOOM.EXE was ever able to directly handle such files do I don't see how it makes sense to pass them to Choco?

**Comment by AXDOOMER** [comment]
Yes it can handle such files. The sounds in vanilla are 8-bit wave files at 11025Hz. You can also `-file .mid` files and it handles them correctly. If they can't be selected using the file chooser, then the user will have to rename them with a `.lmp` extension. This is why I suggest you add a `.*` filter that accepts any extensions, so that a different extension doesn't have to be added for every file type supported by vanilla.

**Comment by jmtd** [comment]
> Yes it can handle such files. The sounds in vanilla are 8-bit wave files at 11025Hz. You can also -file .mid files and it handles them correctly.

The .mid I can believe, but the sounds are not *exactly* WAV files (they lack the whole RIFF header and have sample padding on either side). I suspect Doom ignores the extension and loads any non-wad extension as a raw lump replacement based on the short name before the extension. Thus using -file dsslop.wav (for example) will "work" but the sound will be corrupted in some way I imagine. I'll have to try it :>

> This is why I suggest you add a * or .* filter that accepts any extensions

Yes that is a good idea, essentially a filter that disables filtering. The default would still be .wad (or similar) but you could turn it off if you wanted.

I half coded this yesterday and might PR it today.

**Comment by jmtd** [comment]
Was resolved by merging #909
