### ISSUE TITLE
Mono downmix

### ISSUE THREAD

**Issue by PorscheMonty** [chocolate-doom/chocolate-doom#910]
Greetings.

I've found myself using this piece of hardware that couldn't handle stereo sound because of a missing speaker. Then I figured I would set up CD to downmix to mono and get it over with, just to find out there's no such thing available.

This must be virtually at the very bottom of the feature suggestion list, and rightfully so, but it couldn't hurt to have it there just as a fallback option (yes, I'd know how to circumvent it with third party software but that's kind of besides the point)

Thanks for listening and thanks for this excellent port (3.0 working mighty well here stability-wise, plus the libsamplerate issue appears to have been fixed for good).

Regards.

**Comment by fragglet** [comment]
It's a pretty obscure feature to request. If there's already third-party software that can achieve the same result then I suggest that's probably the best solution. Thanks for the suggestion though.
