### ISSUE TITLE
Heretic Expansion

### ISSUE THREAD

**Issue by symbios24** [chocolate-doom/chocolate-doom#914]
Hello i been trying chocolate doom on the Raspberry Pi in Retropie and everything work fine except the Heretic  Shadow of the Serpent Riders Expansion is there a way to make it work?

Thanks

**Comment by JNechaevsky** [comment]
Hello @symbios24 

How exactly you are loading Serpent Riders wad? Since this is a standalone game, not an addition, it should be loaded by simple running `chocolate-heretic.exe`, while heretic.wad must be the Serpent Riders version.

**Comment by symbios24** [comment]
Im using a raspberry and the Retropie OS not windows
I putted all doom/hexen/strife/heretic wad in a doom folder in ports and i run the chocolate doom setup that creates shortcuts in ports section of retropie for everything except the expansion both heretic and the expansion share the same name this is the launching script of heretic:

#!/bin/bash
"/opt/retropie/supplementary/runcommand/runcommand.sh" 0 _PORT_ "chocolate-heretic" ""

how do i make the launching script for the expansion? eg i have change the wad name to hereticex.wad

Thanks

**Comment by fabiangreffrath** [comment]
Try to add `-iwad /path/to/heretic.wad` into the empty set of quotation marks at the end of the line.

**Comment by symbios24** [comment]
It did not work it launching the normal heretic not the expansion i did the file like this: 
#!/bin/bash
"/opt/retropie/supplementary/runcommand/runcommand.sh" 0 _PORT_ "chocolate-heretic" "-iwad /home/pi/RetroPie/roms/ports/doom/hereticex/heretic.wad"

is it correct?

**Comment by jmtd** [comment]
Here's a suggested workaround: just put the SOTSW heretic IWAD in the Ports directory as Heretic.wad, and always play the expansion. The only real difference is it adds episodes 4 and 5, episodes 1-3 are essentially identical in any case, so there's very little reason to play heretic without the expansion.

**Comment by CapnClever** [comment]
In addition to what @jmtd wrote, v1.0 and v1.1 aren't emulated in any significant way (v1.2 being Shadows of the Serpent Riders). The demos still desync in Chocolate Heretic using the v1.0 IWAD, for example. Closest thing to support is that HHE patches were written with v1.0 in mind, and Chocolate Heretic converts the necessary components in those patches so they'll work correctly in v1.2. You're safe using Heretic: Shadows of the Serpent Riders as "the only Heretic", even moreso than Ultimate Doom can be considered "the only Doom1".

If you're really nitpicky with version differences (like I am) then name them differently and type out the `-iwad` parameter so it references that exact IWAD as necessary. In your case I suppose it would be something like this:
```
Heretic v1.0:
"/opt/retropie/supplementary/runcommand/runcommand.sh" 0 PORT "chocolate-heretic" "-iwad /home/pi/RetroPie/roms/ports/doom/heretic/heretic.wad"

Heretic Serpent Riders (v1.2):
"/opt/retropie/supplementary/runcommand/runcommand.sh" 0 PORT "chocolate-heretic" "-iwad /home/pi/RetroPie/roms/ports/doom/hereticex/hereticex.wad"
```

You might be able to do better syntactically (unfamiliar with the language) but hopefully that adequately describes the details.

**Comment by symbios24** [comment]
Thanks but i have v1.3

**Comment by symbios24** [comment]
I have v1.3 that seems to includes both heretic and the expansion it has all 5 episodes.

another thing now i have some doom mods in pk3 is it possible to play them with chocolate doom?

Thanks

**Comment by AXDOOMER** [comment]
> another thing now i have some doom mods in pk3 eg: brutalv20b.pk3 is it possible to play them with chocolate doom?

No

**Comment by JNechaevsky** [comment]
> another thing now i have some doom mods in pk3 eg: brutalv20b.pk3 is it possible to play them with chocolate doom?

Nope, Chocolate Doom supports only classical WAD format. Also, it does not support any kind of *ZDoom specifics and scripts. But you still can play vanilla-like custom maps, using `-file`.

**Comment by symbios24** [comment]
Hello again i`m trying to install chocolate doom through the Retropie-Extra Scripts (https://github.com/zerojay/RetroPie-Extra) as i did it several times before with success, but today the install keeps failing im getting an error about that it can not find strife,is the chocolate doom github having any problems?

Thanks
