### ISSUE TITLE
[SDL2] SFX not playing after recent commit

### ISSUE THREAD

**Issue by Zodomaniac** [chocolate-doom/chocolate-doom#922]
After the commit https://github.com/chocolate-doom/chocolate-doom/commit/5383fa67ab4ddcd01c9352b47a3ad34f2ebf9da7 the SFX don't play at all.

**Comment by jmtd** [comment]
Thanks for the report: sound, music, or both?

**Comment by chungy** [comment]
Also post your OS version. It'd be particularly interesting if versions older than Vista are affected.

**Comment by Zodomaniac** [comment]
@chungy @jmtd 
My OS is Win7. Music (in case it's Native MIDI, not OPL ) plays, but game sounds never do.

**Comment by fabiangreffrath** [comment]
Cannot confirm on Windows 7 (64-bit) with a binary compiled with`gcc.exe (Rev2, Built by MSYS2 project) 7.1.0`.

**Comment by Zodomaniac** [comment]
@fabiangreffrath I meant the build from latest.chocolate-doom.org

**Comment by chungy** [comment]
I'm unable to reproduce either, neither on a self-compiled build (using mingw-w64-gcc 7.1.1), nor the latest.c-d.org build. Using Windows 7 in a VM for testing.

Are you able to provide more details about your system and configuration?

**Comment by Zodomaniac** [comment]
This has fixed itself some way :)
