### ISSUE TITLE
(SDL2 branch) Command line parameters (-fast, -respawn, -nomonsters) don't apply at all

### ISSUE THREAD

**Issue by Zodomaniac** [chocolate-doom/chocolate-doom#924]
When launching SDL2 C.D. with command line parameters like -fast and starting the game immediately (so that in-game demos don't tamper with the parameters) the parameters are still not applied.

**Comment by fabiangreffrath** [comment]
That's how Vanilla works: The parameters are reset when you start the game through the New Game menu. You have to pass a `-warp` parameter on the command line to immediately start the game from a map.
