### ISSUE TITLE
Please someone help in explaining this error to me that I got during my experiment. please explain in simple words because i am new to this area. thanks #

### ISSUE THREAD

**Issue by adil25** [chocolate-doom/chocolate-doom#934]
/home/adil/.local/lib/python3.5/site-packages/numpy/core/_methods.py:127: RuntimeWarning: invalid value encountered in double_scalars
ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
File "/media/adil/Research Work/In process VizDoom Research/mwydmuch_ViZDoom-master/examples/python/pr_Training and Testing.py", line 247, in 
"min: %.1f," % train_scores.min(), "max: %.1f," % train_scores.max())
File "/home/adil/.local/lib/python3.5/site-packages/numpy/core/_methods.py", line 29, in _amin
return umr_minimum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity

**Comment by chungy** [comment]
Not related to Chocolate Doom, closing.

**Comment by fragglet** [comment]
I suggest you post on StackOverflow.

**Comment by adil25** [comment]
@fragglet....ok thanks
