### ISSUE TITLE
SDL2: 1066x667 resolution disappears if de-selected

### ISSUE THREAD

**Issue by Zodomaniac** [chocolate-doom/chocolate-doom#935]
When launching SDL2 Choco for the first time, for Windowed mode Setup has the following uncorrected aspect ratio resolutions: integer from 320x200 to 1600x1000 and 1066x667 which is the default one. If I de-select the 1066x667 (choose any other resolution), the 1066x667 disappears from the possible options on the subsequent Setup tool launches.
![1066x667](https://user-images.githubusercontent.com/15119473/29283740-a84c8202-8130-11e7-9fca-7b80d8d55fdc.png)

**Comment by chungy** [comment]
Did you run the SDL2 version with an existing config file? 1066x667 shouldn't ever be the _default_, but it'll display any arbitrary resolution that your `chocolate-doom.cfg` already has set as the window size.

The default list of resolutions comes from [src/setup/display.c](https://github.com/chocolate-doom/chocolate-doom/blob/e334de61580e02c7fce892dd185b5c3fd7ff6e5d/src/setup/display.c).

**Comment by Zodomaniac** [comment]
>Did you run the SDL2 version with an existing config file?

Yes, I did. I updated the daily build afther the latest today's commit and ran it.

**Comment by chungy** [comment]
Yeah, that'll be why. Your window size was 1066x667 so it showed that option so you can return to it after you selected another, but if you close the program, it has no way of remembering that.

**Comment by Zodomaniac** [comment]
The question remains how I got that resolution value recorded into the config file before, I wonder?

**Comment by chungy** [comment]
Resizing your window, perhaps?

I think this is solved now, closing :)

**Comment by Zodomaniac** [comment]
Yes, I may have dragged the window corner, really.

**Comment by fragglet** [comment]
Yeah, it's just there to represent the fact that you're using a "non-standard" window size. Otherwise the alternative would be a list of the "standard" resolutions with none of them selected.
