### ISSUE TITLE
Top-level Makefile does not know how to build convenience libraries

### ISSUE THREAD

**Issue by fabiangreffrath** [chocolate-doom/chocolate-doom#938]
Unfortunately, this is where my Automake-foo ends, but I think that this should be possible:
```
$ cd chocolate-doom/src
$ make chocolate-heretic
make: *** No rule to make target 'heretic/libheretic.a', needed by 'chocolate-heretic'.  Stop.
```

**Comment by fragglet** [comment]
Sadly it's not possible - you just have to build from the top level.

An alternative does exist in the form of non-recursive automake, eg. https://autotools.io/automake/nonrecursive.html

**Comment by fabiangreffrath** [comment]
> An alternative does exist in the form of non-recursive automake

Wait a minute, please. Does this mean that "we" would accept a patch that does this?

**Comment by jmtd** [comment]
This reminds me of [recursive make considered harmful](http://aegis.sourceforge.net/auug97.pdf)

**Comment by jmtd** [comment]
oh, and of course there's a [non-recursive make considered harmful](https://www.microsoft.com/en-us/research/wp-content/uploads/2016/03/hadrian.pdf), but look at the author list, SPJ... and a certain Dr. Mokhov from my old stomping grounds.

**Comment by bb010g** [comment]
There's also [Meson](http://mesonbuild.com/) if we're talking about "exotic" (a.k.a. non-Autotools/CMake/pure Make) build systems, since I have a feeling we wouldn't want people having to go through installing Stack to build. [wlroots](https://github.com/SirCmpwn/wlroots) just switched over from CMake if you want a nice example repo.

**Comment by fabiangreffrath** [comment]
> This reminds me of recursive make considered harmful

I'll reopen this so I won't forget to post a pull-request in which we can discuss the pros and cons.

**Comment by fragglet** [comment]
> Wait a minute, please. Does this mean that "we" would accept a patch that does this?

I think this would be fine so long as it's done in a "maintainable"/scalable way. That is, we shouldn't have one gigantic Makefile where all targets are defined - I'd like to see targets defined in the directory where they belong.

The exception is Makefiles like the ones in `pkg` which are kind of separate/specialized and don't really need to be part of the main build (indeed, they aren't).

**Comment by fabiangreffrath** [comment]
A rule like this in `src/Makefile.am` will help here:

```
heretic/libheretic.a :
       $(MAKE) -C heretic
```

Unfortunately, I have no idea how to formulate this more sophisticated with wildcards...
