### ISSUE TITLE
Textscreen library should include extern "C" declarations

### ISSUE THREAD

**Issue by Altazimuth** [chocolate-doom/chocolate-doom#941]
Repositories that use Textscreen and are C++ have to do this themselves. For example Eternity puts the follow code at the given places in txt_main.h:
https://github.com/chocolate-doom/chocolate-doom/blob/sdl2-branch/textscreen/txt_main.h#L124
```cpp
#ifdef __cplusplus
extern "C" {
#endif
```

https://github.com/chocolate-doom/chocolate-doom/blob/sdl2-branch/textscreen/txt_main.h#L185
```cpp
#ifdef __cplusplus
}
#endif
```

This doesn't intrude on C compilation, and benefits those who want Chocolate Doom's ENDOOM support in a C++ project.

**Comment by fragglet** [comment]
Sounds reasonable. Several ports (Eternity, PrBoom+, others?) use libtextscreen; it would make sense to check their revision histories to see if there are other things also worth importing.

**Comment by Altazimuth** [comment]
The only other modifications I needed to make was importing doomkeys.h, and adjusting includes of it to reference the new placement (within the "textscreen" folder in EE's case).
