### ISSUE TITLE
Notable delay while changing windowed/fullscreen mode

### ISSUE THREAD

**Issue by JNechaevsky** [chocolate-doom/chocolate-doom#949]
There is seems to be a notable delay (about 1 sec.) while changing windowed/fullscreen mode, which was not happening earlier. It is not critical, just a little bit uncomfortable. Video example:

- https://www.youtube.com/watch?v=fx5_0VJA7nI

Suggestion: probably it's start to happening after one of commits that affect SDL window system/mode, sorry, can't say for sure what exactly. I'm showing my project as an example how fast switching was "before".

Tested on latest dev builds of Chocolate & Crispy Doom.

**Comment by fabiangreffrath** [comment]
Does it help if you scale the window up to nearly-fullscreen size before (I am asking because of the regeneration of the intermediate texture)? Also, is there a difference if you play with SDL 2.0.5 and 2.0.6?

**Comment by JNechaevsky** [comment]
Nope, does not much. Even if window is stretched to near fullscreen size, changing to fullscreen mode still have delay. By the way, resizing window also have this delay.

All tests were made with 2.0.5, since 2.0.6 isn't working properly at the moment (no sound issue, see https://github.com/chocolate-doom/chocolate-doom/issues/945#issuecomment-333650648). Just checked this case with 2.0.6 - same problem, delay is still notable.

**Comment by fabiangreffrath** [comment]
> By the way, resizing window also have this delay.

Aha, then you are experiencing this 500 ms delay which was introduced here on purpose in order to mitigate https://github.com/chocolate-doom/chocolate-doom/issues/856 :

https://github.com/chocolate-doom/chocolate-doom/blob/sdl2-branch/src/i_video.c#L716

**Comment by JNechaevsky** [comment]
Note: Link now is slightly broken because of changed lines in the code, however, we are speaking about `RESIZE_DELAY`.

@fabiangreffrath, maybe it's worth to don't apply this delay on Windows? There is no real necessity for it there, and frankly, this delay is a little bit annoying.

**Comment by JNechaevsky** [comment]
Excuse me, I should explain more correctly what actually "annoying" is.

For common playing this delay is okay. You run the game normally, you playing it, you exiting it when you are done. You have no necessity to switch fullscreen/windowed mode often.

But for development and mapping needs this delay is annoying. For example: you starting the game in full screen mode to get a bigger, better and closer view of some things, and when you need to switch to the code or Doom Builder, you have to suffer this little delay, do some things there and suffer delay again on getting back to the game in full screen.

Well, have to admit that `ALT+TAB` is a thing, but... Some people may be really mode happy or more familiar with screen mode changing by `ALT+ENTER`. And needles to say that Doom Builder is created primary _(and only?)_ for Windows.

**Comment by JNechaevsky** [comment]
@fabiangreffrath, ping again ⏰ (about window behavior on Windows).

**Comment by fabiangreffrath** [comment]
As this is windows specific, I doubt I am the right person to fix this.

**Comment by JNechaevsky** [comment]
Guess we have to ask @haleyjd then. Seriously, for Windows this delay is just annoying...

**Comment by JNechaevsky** [comment]
@haleyjd, ping. :alarm_clock:

**Comment by JNechaevsky** [comment]
@haleyjd, ping - ping - ping. :boom:

**Comment by haleyjd** [comment]
That delay was originally added to "let the screen settle down" before the game would start running again, because a lot of monitors had issues with still displaying a blank screen well after control had returned to games using SDL from the system video mode changing functions.

500ms is only half a second though. If you are experiencing "long" delays, it's naught to do with this call.
