### ISSUE TITLE
Chocolate Doom crash with digital SFX on SDL 2.0.6

### ISSUE THREAD

**Issue by MindfulProtons** [chocolate-doom/chocolate-doom#950]
So, on Chocolate Doom 3.0.0beta1.r16.64ad6083-1 on Arch Linux, I get a segfault every time that the digital sound effects in either Doom 1 or Doom 2 play, or I get a malloc.c error which looks like this:

chocolate-doom: malloc.c:2427: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
Aborted (core dumped)

**Comment by fabiangreffrath** [comment]
Did Arch happen to switch the SDL2 libraries to version 2.0.6 recently?

**Comment by MindfulProtons** [comment]
Yes, it did. Strangely, Chocolate Doom 2.3.0 works fine, but I want the music pack feature, since I don't have a real SC-55.

**Comment by chungy** [comment]
Yeah, definiately sdl 2.0.6 related. You can try downgrading your package back to 2.0.5.

Chocolate Doom 2.3.0 also supports music packs on Linux though, for what it's worth.

**Comment by fragglet** [comment]
Dupe of #945 - please upgrade to SDL 2.0.7.

**Comment by chungy** [comment]
We'll have to wait for 2.0.7 to get released first.

**Comment by ndrchvzz** [comment]
Arch Linux has just updated to 2.0.7 but it is still crashing. =(
