### ISSUE TITLE
Feature request: command-line MUS player

### ISSUE THREAD

**Issue by krozett** [chocolate-doom/chocolate-doom#951]
This might be more appropriate for Crispy Doom, but figured I would suggest it here first.

I would love to see a command-line option that accepts a MUS lump name, plays it using the configured driver, but outputs the PCM sound to a file (or STDOUT) without actually launching the game. Chocolate/Crispy has the best (maybe only?) true OPL emulation for MUS files. Come to think of it, MIDI output in other Doom ports can be pretty lousy as well. The only standalone players I've seen are either for DOS or rely on MUS2MIDI, which isn't very accurate.

I've been using DOSBox to run MUSPLAY, and outputting that to DRO files... because at least DRO is supported in a few modern players. MUS players are almost non-existent.

**Comment by fabiangreffrath** [comment]
I guess you are asking because there is already a "similar" feature in Crispy Doom in the `-mergedump` parameter. As such, I am not opposed to such a request, although Doom isn't primarily a MIDI synthesizer. ;)

However, I am not familiar with the sound code at all. Do you have any idea where I could hook into the code to write the PCM data to disk instead of paying it back?

**Comment by krozett** [comment]
It's going to differ depending on the driver, it looks like.

For example, it seems like for OPL the place to hook into would be the end of the OPL3_Generate function:
https://github.com/chocolate-doom/chocolate-doom/blob/30f853b65820280931e06e07fd5f624313670305/opl/opl3.c#L1090

But then you have to do that for each individual driver.

However, I found a workflow to get what I want:

1. Convert to MIDI using wildmidi
1. Use a command-line tool called ADLMIDI (https://github.com/Wohlstand/ADLMIDI) to convert that MIDI file into a WAV.

ADLMIDI understands how to use the GENMIDI lump, and even has both the Doom 1 and Doom 2 versions built-in! Plus its OPL3 emulation uses the Nuked library, the same one used by Chocolate Doom. The only reason I wasn't using it before is that ADLMIDI's MUS parsing totally screws up the tempo. But it can handle regular MIDI just fine.

I hesitated to use wildmidi at first, due to me misunderstanding that the MUS2MID library is not flawed. Apparently the MID2MUS utility is the flawed one. I tried a few files and the output sounds nearly identical to Chocolate!

Now to try to find a MIDI player that understands DMXGUS lumps...

**Comment by fragglet** [comment]
I think this is out of scope for Chocolate Doom, but maybe someone can reuse Chocolate Doom's MIDI and OPL code to build this for you.
