### ISSUE TITLE
does not play ConC.E.R.Ned's intro music in MIDI format with OPL emulation

### ISSUE THREAD

**Issue by fabiangreffrath** [chocolate-doom/chocolate-doom#954]
Hi guys,

the ConC.E.R.Ned PWAD contains replacement levels and music for Doom1:

https://www.doomworld.com/idgames/levels/doom/megawads/concern

While some of the music tracks are in MUS format, others are in MIDI format, e.g. after extracting with deutex:
```
$ file musics/d_intro.mid 
musics/d_intro.mid: Standard MIDI data (format 1) using 9 tracks at 1/192
```

However, when loading the PWAD with chocolate-doom, the replacement intro music is not played back, instead Doom's own regular intro music is played. When switching from OPL emulation to "native MIDI" the music is replaced as expected. Also, the music is replaced as expected when using OPL emulation in PrBoom+.

**Comment by nukeykt** [comment]
Vanilla Doom uses D_INTROA for OPL synthesis and D_INTRO for other devices.

**Comment by fabiangreffrath** [comment]
Ah, thanks, so this is not a bug but an accuracy feature. Now, I think I will add a check to Crispy Doom to see if D_INTRO is from a PWAD and D_INTROA is not and then play the former nevertheless.
