### ISSUE TITLE
Letterboxing in high resolutions in fullscreen

### ISSUE THREAD

**Issue by Zanmato27** [chocolate-doom/chocolate-doom#956]
This is been something of annoyance for me with using Chocolate Doom since the source port always puts in letterboxes when trying to play Doom in high-resolutions. I don't mind the pillarboxes (vertical bars) when playing the game in 4:3 with aspect-ratio correction in fullscreen, but when I play the game using high-resolutions (in my case, 1920x1080) I get letterboxes (horizontal bars) on top of that, and I don't think the source port is properly upscaling the game screen to cover the top and bottom portions of the screen in fullscreen mode while maintaining a 4:3 ratio. I have here some screenshot comparisons of playing Doom II using Chocolate Doom's fullscreen scaling issues with and without aspect-ratio correction versus DOSBox with aspect-ratio correction. Although some lower-resolutions like 1280x920 doesn't seem to have this issue with letterboxing, but the overall picture doesn't look as crisp and sharp when playing on my desktop's native resolution, and there might be other resolutions that could be affected by this letterboxing issue as well.

• Chocolate Doom with aspect-ratio correction: [https://i.imgur.com/i853hQZ.png](url)
• Chocolate Doom without aspect-ratio correction: [https://i.imgur.com/5uwAJuV.png](url)
• Doom II with the proper aspect-ratio under DOSBox: [https://i.imgur.com/lfV8AFT.png](url)

I'm hoping this upscaling issue can be addressed in the v3.0 release of Chocolate Doom.

**Comment by fragglet** [comment]
Hi,

Thanks for the report. This has been resolved in Chocolate Doom v3.0 through the use of hardware scaling that allows scaling to arbitrary sizes. If you'd like to give the current beta a try (available on the Downloads page on the website) we'd love to hear any feedback you have.

**Comment by Zanmato27** [comment]
I am trying the 3.0 beta and I'm noticing a potential issue with upscaling. Without using the "force_software_renderer" setting, the image is somewhat blurry though runs fine, and if I do use the forced software renderer setting, the image is much cleaner but the frame-rate is more choppier than usual, and sadly I have tried changing the video driver with the "video_driver" setting to settings such as "directx", "opengl", and "direct3d", none of these worked at all since I get a failed to initialize video driver setting.

**Comment by fragglet** [comment]
In general I don't recommend using `force_software_renderer`.

> Without using the "force_software_renderer" setting, the image is somewhat blurry though runs fine

Can you describe what you mean by "somewhat blurry"? And what is the resolution of your monitor?

**Comment by Zanmato27** [comment]
By somewhat blurry, it looks like some kind of Bilinear filter is being applied over the game screen, and my display's resolution is 1920x1080.

Image quality when not using force_software_renderer:
![chocolatedoom_noforcedsoftware](https://user-images.githubusercontent.com/10169555/33523030-4bb3645c-d7ca-11e7-86d6-b2be2e43adcf.png)

After using force_software_renderer:
![chocolatedoom_forcedsoftware](https://user-images.githubusercontent.com/10169555/33523033-536a9850-d7ca-11e7-8dab-f96fe43f5582.png)

**Comment by jmtd** [comment]
It can't be pixel perfect. The first resolution that can be achieved perfectly is 1600x1200, so at 1080p some interpolation must be happening in both cases.

**Comment by JNechaevsky** [comment]
Following @fabiangreffrath's recent idea (sorry, can't find #issue id), I've also would like to suggest making a SDL hinting optional. Maybe not even as hidden option, but as a visible menu item in Setup executable.

It's worth it.

**Comment by fabiangreffrath** [comment]
This is the corresponding commit in Crispy:
https://github.com/fabiangreffrath/crispy-doom/commit/95ee837a3487d1b153d2c72153a0c3d019a13e7f#diff-7e61dc47251785545445d15441b9a87f

**Comment by fragglet** [comment]
I [previously commented](https://github.com/chocolate-doom/chocolate-doom/issues/859#issuecomment-336233272) on this in #859. I'd rather not include it.

@Zanmato27 If the screen is excessively blurry, I recommend setting `integer_scaling` to 1 in `chocolate-doom.cfg`; this can alleviate a lot of the blurriness, although it brings back some of the letterboxing. Unfortunately there aren't really many other options. You'll probably need to use [one of the latest autobuilds](http://latest.chocolate-doom.org) to get the option.
