### ISSUE TITLE
parameterize setup program name in manpages

### ISSUE THREAD

**Issue by jmtd** [chocolate-doom/chocolate-doom#959]
See https://github.com/fabiangreffrath/crispy-doom/issues/235

I plan to address this, but if/when I start on it I'll assign myself this issue, so anyone who might want to work on it please feel free if I haven't done that yet.

**Comment by jmtd** [comment]
Hm. We need the program name (autofoo's `@PROGRAM_PREFIX@`) substituted in all manpages. I wonder whether to achieve that with autofoo (introduce another layer of templating/indirection in the manpage files that is resolved at autofoo time) or just pass PROGRAM_PREFIX through to docgen and have it handle that too.

**Comment by jmtd** [comment]
We also need `@PACKAGE_SHORTNAME@`, and possibly others. So I'm going to explore the autofoo route first.

**Comment by fabiangreffrath** [comment]
It will be easier, but "quick and dirty", to just call a substitution command with e.g. `sed` over the generated manpages?

**Comment by jmtd** [comment]
My WIP basically does this by extending `docgen` (which does this in one case already)

**Comment by jmtd** [comment]
My work in progress: https://github.com/chocolate-doom/chocolate-doom/issues/959
