### ISSUE TITLE
Cannot hear any sounds when pausing the game

### ISSUE THREAD

**Issue by Paar86** [chocolate-doom/chocolate-doom#960]
If you pause the game and then open the ingame menu you cannot hear any sounds when moving the cursor. If you exit the game while paused the game will still be muted when you start it again. The pause key seemingly mutes the entire application in the Windows volume control menu. Tested in Windows 10 Pro. Chocolate Doom 3.0.0-beta1.

**Comment by fragglet** [comment]
Thanks for the report. I believe this is the same as #195; the recent midipipe feature should fix this.
