### ISSUE TITLE
"final2" iwad's are not beign automatically detected

### ISSUE THREAD

**Issue by PorscheMonty** [chocolate-doom/chocolate-doom#970]
I'm not sure this is the intended behavior, but it  would be nice to have CD do this without user intervention so to avoid the extra -gameversion parameter required to prevent the demo playback crash.

Tested on 32-bit WinXP with chocolate-doom-sdl2-branch-20171214-win32.zip.

Thanks for your time.

**Comment by fragglet** [comment]
Yeah, this is intended behavior; there's no easy way to tell the difference between IWADs.

crash = desync, correct?

**Comment by PorscheMonty** [comment]
Hmm, not exactly. I was talking about the "W_GetNumForName: demo4 not found!" crash that occurs right after the last demos in both tnt and plutonia iwads are done playing back, which doesn't happen with final2 on.

Now, given the inconvenience of telling iwads apart, I'd suggest, if at all appropriate, that a "final2" boolean option may be added to chocolate-doom.cfg so that final2 behavior is enabled automatically whenever "-iwad tnt.wad" or "-iwad plutonia.wad" are used.

This is practically a cosmetic issue if an issue at all, so I'm not contending your judgment to declare it closed.

**Comment by fragglet** [comment]
Yeah, it's a difficult choice - we previously tried `final2` as a default since it seems more sensible to not have the game crash. But most demos have been recorded with the original `final` and desync if you use `final2`, so we switched it back. 71d316afb2ae7191a4ef6fac2d757238ae3616e1 has some history.
