### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by PorscheMonty** [chocolate-doom/chocolate-doom#972]
https://github.com/chocolate-doom/chocolate-doom/blob/master/README.Music (which's mentioned in https://www.chocolate-doom.org/wiki/index.php/OPL_MIDI), appears to be down. Not much of a problem for me since the file comes bundled with CD, but it shouldn't be hard to update either.

Best regards.

**Comment by fragglet** [comment]
Thanks, fixed.
