### ISSUE TITLE
Where's ioperm.sys?

### ISSUE THREAD

**Issue by PorscheMonty** [chocolate-doom/chocolate-doom#973]
According to "README.Music.txt". it can be downloaded from http://openwince.sourceforge.net/ioperm/, but all I'm seeing is the source code, which I wouldn't really know how to compile. Maybe it was integrated into CD at some point and doesn't need to be downloaded anymore? yet it's hard to tell what's going on because I'm not getting any stdout.txt whasoever with chocolate-doom-sdl2-branch-20171229-win32.zip and there isn't some sort of "Hardware OPL" option available from the setup tool either just to be a bit more sure.

I suppose I could lower the sample rate to something ridiculous like 8khz so to make the two of them more discernible (can't do it right now), because the current implementation of OPL is already so exceptionally good I can hardly tell it apart from a real SB's under ideal circumstances (this meaning using an external filter with similar properties to make the sound more "punchy" or so to speak)

Anyways, just trying to get the OPL passthrough thing going the VOGON's way, which appears to work for some people.

Thanks for your time and sorry for the inconveniences.

**Comment by fragglet** [comment]
I had trouble finding it too, but I think this is it:

<https://sourceforge.net/projects/openwince/files/ioperm/0.2.1/iopermsys-0.2.1.tar.bz2/download>

Let me know if this works or not. I'm sure you're aware already but you'll need a sound card with hardware OPL support.

**Comment by PorscheMonty** [comment]
Thank you.

Now, I do indeed have not one but two cards with hardware OPL support, and both of them perform correctly in DOS: https://www.doomworld.com/forum/topic/51412-chocolate-doom-and-opl-passthrough-for-cmi8738-sound-cards/

(currently using the genius one)

But here's the thing; CD will crash at startup upon ioperm.sys being loaded, and it won't quit crashing until I have rebooted the system. There's no stdout, neither do I get anything from command line by forcing a log via "chocolate-doom > whatever".

It makes no matter whether or not the poking has been been performed before attempting to run CD (with ioperm.sys in the same directory as the main exe's, of course) as instructed in the appertaining vogons' thread; CD will without fail, crash.

I'm completely at loss at what could be happening here :/

**Comment by fragglet** [comment]
Sorry to hear that - in all honesty I think it's going to be very difficult and involved to debug this, so I'm kind of lost too.

Based on the thread you've linked it looks like you had it working in the past, so what's changed since then? Is it the same Windows version?

**Comment by PorscheMonty** [comment]
Alright. To put things in the proper perspective; OPL passthrough is working just fine here with the DosBox daum build, which thing I was never able to get going before the peekpoke trick from the vogons' thread referenced by CD's documentation was made available.

The computer I'm using right now is the exact same computer I was using when I posted that; nothing's changed hardware-wise, only the OS, which was 32-bit WinXP Pro SP3 at the time, has now been upgraded to PosReady 2009 (yes, that's an upgrade from my perspective, but I spare anybody contentious).

The sad thing is, OPL passthrough officially works on this computer now, but ioperm will not have any of it apparently.
