### ISSUE TITLE
Suggestion: add W_GenerateHashTable also for Heretic and Hexen

### ISSUE THREAD

**Issue by JNechaevsky** [chocolate-doom/chocolate-doom#976]
At the moment, `W_GenerateHashTable` is called only in Doom and Strife, but maybe it is worth to add it also for Heretic and Hexen?

On any modern CPUs it probably will not give any bits of performance (maybe just a few microseconds while loading levels), but it seems to be safe for use and not violating Chocolate Phylosophy.

Also, Heretic and Hexen aren't using hash-tables for textures, but it's a different thing that does not related to `W_GenerateHashTable` and of course, I'm not suggesting to add it.

**Comment by fragglet** [comment]
Wow, I'm a bit surprised that Heretic/Hexen aren't calling this already!
