### ISSUE TITLE
Allow user to continue playing even if they have SDL 2.0.6

### ISSUE THREAD

**Issue by mfrancis95** [chocolate-doom/chocolate-doom#977]
On Ubuntu with SDL 2.0.6, I haven't come across the bug that supposedly makes the game crash yet. I'm wondering what your thoughts are on giving the user a choice to continue playing in spite of the bug warning.

I have an example of this change [here](https://github.com/mfrancis95/chocolate-doom/commit/34a672ca8c95d3b00c89a775dfcbb6945fb60e88).

**Comment by fabiangreffrath** [comment]
We should probably rather entirely remove this check and demand SDL2 (>= 2.0.7) in configure.ac.

**Comment by fragglet** [comment]
Ubuntu/Debian have probably patched the fix in to their SDL2 package; they can easily apply a patch that removes the 2.0.6 check from the Chocolate Doom package too.
