### ISSUE TITLE
Support native midi loop points

### ISSUE THREAD

**Issue by buvk** [chocolate-doom/chocolate-doom#980]
Would it be possible to support loop points when using native midi?  When using flac, ogg or mp3, after a track ends, it'll start over at the beginning.

**Comment by fragglet** [comment]
I'm not sure what you mean:

1. Native MIDI just means that we use the system's built-in MIDI playback, so no FLAC, Ogg or MP3 is being used.
1. Are you actually referring to [digital music packs](https://www.chocolate-doom.org/wiki/index.php/Digital_music_packs)? If so, then loop point metadata is already supported for Ogg and FLAC.

I'm going to assume you mean (2) in which case this bug should be working as intended. Feel free to reopen if I'm wrong.
