### ISSUE TITLE
Loop point metadata doesn't work on Windows

### ISSUE THREAD

**Issue by buvk** [chocolate-doom/chocolate-doom#982]
I am using Windows build v3.0.0, and have configured Chocolate Doom to use the Roland SC-55 FLAC and OGG music packs.  When a song ends, it starts over at the beginning.  There is no seamless looping.

**Comment by fragglet** [comment]
Can you confirm it's the packs from this page you're using?

http://sc55.duke4.net/games.php#doom

Can you give an example of a specific track that doesn't loop as intended?

**Comment by buvk** [comment]
Yep, those are the packs I am using.  I re-downloaded them as well to ensure I had the latest versions.

Example tracks:
Doom E1M1 - d_e1m1.flac
Doom E1M6 - d_e1m6.flac

**Comment by fragglet** [comment]
Tried both the raw and boosted versions on macOS and they work fine. Maybe it's a Windows-specific bug.

**Comment by fragglet** [comment]
Fixed I believe. Can you test [the latest autobuild](http://latest.chocolate-doom.org/) and confirm?

**Comment by buvk** [comment]
Music loops seamlessly now!  Thank you very much.
