### ISSUE TITLE
Unable to build due to missing configure script

### ISSUE THREAD

**Issue by fabiensanglard** [chocolate-doom/chocolate-doom#989]
### Background

Version of Chocolate Doom: github source code

Operating System and version: MacOS X High Sierra

Game:  All

### Bug description

Observed behavior: 

1/ Download source code
2/ attempt to run ./configure. There is no such file.
3/  Attempted to run: curl http://www.chocolate-doom.org/build-chocolate-doom | sh
4/ Got same issue "./build-chocolate-doom: line 173: ./configure: No such file or directory"

Expected behavior: Build executable

**Comment by fabiangreffrath** [comment]
You will have to run `autoreconf -fiv` in the source tree before calling the `configure` script.

**Comment by jmtd** [comment]
Perhaps we should fix that shell script then

**Comment by chungy** [comment]
That shell script is `autogen.sh`!

Release tarballs always have the autoconf/automake files pre-generated, but such generated files are not (and should not be) in the Git tree.

**Comment by fabiensanglard** [comment]
Just for the record, I tried to run autoreconf and I did not have it.
OK.

$brew install automake
Error: You must `brew link xz` before automake can be installed

Arg.

$ brew link xz
Linking /usr/local/Cellar/xz/5.2.2... 
Error: Could not symlink bin/lzcmp
To force the link and overwrite all conflicting files:
  brew link --overwrite xz

OOOOOK.

brew link --overwrite xz
Linking /usr/local/Cellar/xz/5.2.2... 
Error: Could not symlink bin/lzcat
/usr/local/bin is not writable.

I give up. For now. 

I am not going to complain about people working for free but I feel the build system could help being  easier. Has the CMake port been abandonned?

**Comment by chungy** [comment]
@fragglet uses Mac OS X, he might be able to chime in on how to get things successfully set up.

> Has the CMake port been abandonned?

Yes, there was little interest when neither the Code::Blocks nor MSVC users were willing to change their workflows in favor of CMake.

**Comment by jmtd** [comment]
Oh I hadn't noticed it was @fabiensanglard who filed this! *waves* (Did you get my mail re your black book(s)?:))

Since you are using brew anyway, IMHO we should just get the brew formula updated for v3.

**Comment by fabiensanglard** [comment]
Hi Jonathan. No I did not receive your email.

**Comment by jmtd** [comment]
Ok I'll resend.

I'm going to try and submit an updated brew formula, probably next week (don't have regular access to a Mac anymore!)

**Comment by linguica** [comment]
Did you try chocpkg as detailed here: https://www.chocolate-doom.org/wiki/index.php/Chocpkg ? I just git cloned into a new directory and ran the command and it built everything for me with no problems.

**Comment by fabiensanglard** [comment]
@linguica chocpkg worked flawlessly. Thank you so much :) !

**Comment by jmtd** [comment]
Glad you're sorted. Update brew formula PR is here, fwiw: https://github.com/Homebrew/homebrew-core/pull/24293
