### ISSUE TITLE
Crash when trying to load a non-existent savegame from the command line

### ISSUE THREAD

**Issue by Zodomaniac** [chocolate-doom/chocolate-doom#990]
### Background

Version of Chocolate Doom: Any

Operating System and version: Windows 7

Game: (Doom/Heretic/Hexen/Strife/other): Any

Any loaded WADs and mods (please include full command line): `chocolate-doom -loadgame (i)` when doomsav(i) file doesn't exist.

### Bug description

Observed behavior: When trying to load a non-existent savegame (empty slot) from the command line, the executable crashes.
E.g. chocolate-doom -loadgame (i) when doomsav(i) file doesn't exist.

Expected behavior:
I think the program should error out by code
`'Savegame %ssav%d does not exist', game_name, i`
where game_name is substituted based on the loaded IWAD: 'doom' for Doom series, 'chex' for Chex/Chex2, 'hacx' for Hacx...

**Comment by chungy** [comment]
Thanks, I've added a simple error message to all the affected games (Strife seemed to already handle it).

**Comment by Zodomaniac** [comment]
Tested with daily build, what's the problem?
I didn't experience this in Crispy Doom 5.1 with EXEs from the daily build
![could not load](https://user-images.githubusercontent.com/15119473/36342969-e1f0f0f0-1416-11e8-8b45-4635c0bd01b2.png)

**Comment by chungy** [comment]
I don't have the same issue in Wine:

![screenshot from 2018-02-17 11-48-18](https://user-images.githubusercontent.com/1094821/36345030-9badf608-13d8-11e8-8909-192a4cfe4196.png)

This doesn't necessarily mean that it's not a real issue on Windows, but are you sure you have the latest commit?

I'll upload my own build (the one that works in Wine) for you to test that: https://chungy.keybase.pub/chocolate-doom-3.0.0-60-g0b50fbde-win32.zip

**Comment by Zodomaniac** [comment]
@chungy 
>but are you sure you have the latest commit?

Your build shows this window correctly :+1: but the daily autobuild from http://latest.chocolate-doom.org/ doesn't, there's some issue in the auto-builder.
