### ISSUE TITLE
Daily build does not display the name of the savegame that could not be loaded

### ISSUE THREAD

**Issue by Zodomaniac** [chocolate-doom/chocolate-doom#992]
### Background

Version of Chocolate Doom: Feb 17, 2018 daily build from http://latest.chocolate-doom.org/ 

Operating System and version: Windows 7, Windows 10

Game: (Doom/Heretic/Hexen/Strife/other) 

Any loaded WADs and mods (please include full command line):

### Bug description

Observed behavior: The name of the savegame that could not be loaded is not displayed
![could not load](https://user-images.githubusercontent.com/15119473/36350253-8eeb9bae-14a6-11e8-9fbc-911c74c7057f.png)

Expected behavior:
![git](https://user-images.githubusercontent.com/15119473/36350278-fa4b1820-14a6-11e8-895d-17a275d8606c.png)
The build uploaded by @chungy https://chungy.keybase.pub/chocolate-doom-3.0.0-60-g0b50fbde-win32.zip displays the message correctly but the daily autobuild doesn't.
I also tried Crispy Doom 5.1 with EXEs from the daily build, and the message displays correctly, that makes me think it's some issue in the auto-built SDL.

**Comment by mfrancis95** [comment]
Is this still an issue?

**Comment by Zodomaniac** [comment]
@mfrancis95 No, I checked the latest daily build and it fixed itself.
